### ISSUE TITLE
[Bug] configure: error: in `/root/apache-doris-1.0.0-incubating-src/thirdparty/src/unixODBC-2.3.7'

### ISSUE THREAD

**Issue by alangui** [apache/incubator-doris#10020]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

docker build env: apache/incubator-doris:build-env-for-1.0.0
code tag: 1.0.0-rc3

### What's Wrong?

===== begin build unixODBC-2.3.7
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gawk... (cached) gawk
checking for bison... bison -y
checking for style of include used by make... GNU
checking for gcc... /var/local/ldb-toolchain/bin/../bin/gcc
checking whether the C compiler works... no
configure: error: in `/root/incubator-doris-1.0.0-rc03/thirdparty/src/unixODBC-2.3.7':
configure: error: C compiler cannot create executables
See `config.log' for more details

### What You Expected?

Build success

### How to Reproduce?

unset DORIS_THIRDPARTY
sh build.sh --clean --be --fe --ui

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by alangui** [comment]
nothing

**Comment by WuZezhang** [comment]
Have you solved your problem? I have the same problem. Do you have a solution?

**Comment by zhaofei1193** [comment]
同样的问题，有解决方案吗？
open-source/doris-2.0.2-rc05/thirdparty/src/unixODBC-2.3.7':
configure: error: C compiler cannot create executables

**Comment by SailNow** [comment]
有同样的问题，有人找到解决方案了吗

**Comment by AcKing-Sam** [comment]
Hi, I have encountered the same question in Ubuntu 22.04.
You can check the file `doris/thirdparty/src/unixODBC-2.3.7/config.log` to see the detailed problem.
I believe in this way you can fix it!
