### ISSUE TITLE
[Bug] When the 1.0.5-no-avx2 version queries data, the program crashes on the BE node

### ISSUE THREAD

**Issue by gitbbrid** [apache/incubator-doris#10100]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

all version  of no-avx2 
Tested version:0.15.5-no-avx2
,1.0.0-preview2-no-avx2
,1.0.5-no-avx2

所有no-avx2发行的版本
已测试版本：0.15.5-no-avx2
,1.0.0-preview2-no-avx2
,1.0.5-no-avx2

### What's Wrong?

When we use the No-Avx2 version for data query, the BE node crashes directly
当我们使用No-Avx2版本进行数据查询时，BE节点直接崩溃

> Query example：

MYQL [fintell_poc]> select * from apply_info_v3;
ERROR 1064 (HY000): errCode = 2, detailMessage = there is no scanNode Backend. [10003: in black list(io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason)]`

> The log shows:

start time: Mon Jun 13 18:45:28 CST 2022
*** Aborted at 1655117413 (unix time) try "date -d @1655117413" if you are using GNU date ***
PC: @          0x352bf06 _avx2_run_container_cardinality.isra.0
*** SIGILL (@0x352bf06) received by PID 16929 (TID 0x7fae159fb700) from PID 55754502; stack trace: ***
    @          0x2f43f62 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fae19442630 (unknown)
    @          0x352bf06 _avx2_run_container_cardinality.isra.0
    @          0x3513a95 roaring_bitmap_get_cardinality
    @          0x1fe52d8 doris::segment_v2::SegmentIterator::_get_row_ranges_by_keys()
    @          0x1fe6cf1 doris::segment_v2::SegmentIterator::_init()
    @          0x1fe751e doris::segment_v2::SegmentIterator::next_batch()
    @          0x1805d34 doris::BetaRowsetReader::next_block()
    @          0x1764571 doris::CollectIterator::Level0Iterator::_refresh_current_row_v2()
    @          0x1765633 doris::CollectIterator::add_child()
    @          0x173a90f doris::Reader::_capture_rs_readers()
    @          0x1743d54 doris::Reader::init()
    @          0x1ea083e doris::OlapScanner::open()
    @          0x1e5ab9f doris::OlapScanNode::scanner_thread()
    @          0x18681af doris::PriorityThreadPool::work_thread()
    @          0x2f10737 thread_proxy
    @     0x7fae1943aea5 start_thread
    @     0x7fae18e61b0d __clone
    @                0x0 (unknown)
Connection closed`

### What You Expected?

A quick fix as we are planning to put it into production use.
快速的到解决，因为我们正在计划投入生产使用。

### Anything Else?

no

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by cambyzju** [comment]
Please give schema of table apply_info_v3, and some test data to reproduce the problem is better.

**Comment by gitbbrid** [comment]
> Please give schema of table apply_info_v3, and some test data to reproduce the problem is better.

Table of apply_info_v3

create table apply_info_v3
(
id bigint default '0' comment '自增',
apply_no varchar(64) default '' comment '申请编号',
customer_no varchar(64) default '' comment '客户编号',
apply_amt bigint default '0' comment '授信额度',
apply_status tinyint default '0' comment '申请状态 0/1/2/3 1-通过',
rs_status tinyint default '0' comment '人工审核状态 1/2/3/4 4-完成',
refuse_code varchar(64) default '' comment '拒绝原因码',
channel_code varchar(16) default '' comment '渠道编码',
create_time datetime default '1000-01-01 00:00:00' comment '创建时间',
update_time datetime default '1000-01-01 00:00:00' comment '更新时间',
update_year char(4) default '' comment '更新时间所在年',
update_month char(7) default '' comment '更新时间所在月',
update_week char(8) default '' comment '更新时间所在周',
update_day char(10) default '' comment '更新时间所在天',
create_week char(8) default '' comment '创建时间所在周',
create_month char(7) default '' comment '创建时间所在月份',
create_day char(10) default '' comment '创建时间所在天',
create_year char(4) default '' comment '创建时间所在年份'
)
COMMENT "额度申请"
DISTRIBUTED BY HASH(id) BUCKETS 3
PROPERTIES (
"replication_num" = "1"
);

test data of apply_info_v3

http://101.43.23.40/fintell_asset_data_show_apply_info_v3.json
> Table of apply_info_v3

create table apply_info_v3
(
    id           bigint default '0' comment '自增',
    apply_no     varchar(64) default ''                    comment '申请编号',
    customer_no  varchar(64) default ''                    comment '客户编号',
    apply_amt    bigint      default '0'                   comment '授信额度',
    apply_status tinyint     default '0'                   comment '申请状态 0/1/2/3 1-通过',
    rs_status    tinyint     default '0'                   comment '人工审核状态 1/2/3/4 4-完成',
    refuse_code  varchar(64) default ''                    comment '拒绝原因码',
    channel_code varchar(16) default ''                    comment '渠道编码',
    create_time  datetime    default '1000-01-01 00:00:00' comment '创建时间',
    update_time  datetime    default '1000-01-01 00:00:00' comment '更新时间',
    update_year  char(4)     default ''                    comment '更新时间所在年',
    update_month char(7)     default ''                    comment '更新时间所在月',
    update_week  char(8)     default ''                    comment '更新时间所在周',
    update_day   char(10)    default ''                    comment '更新时间所在天',
    create_week  char(8)     default ''                    comment '创建时间所在周',
    create_month char(7)     default ''                    comment '创建时间所在月份',
    create_day   char(10)    default ''                    comment '创建时间所在天',
    create_year  char(4)     default ''                    comment '创建时间所在年份'
) 
COMMENT "额度申请"
DISTRIBUTED BY HASH(id) BUCKETS 3
PROPERTIES (
    "replication_num" = "1"
);


> test data of apply_info_v3

[http://101.43.23.40/fintell_asset_data_show_apply_info_v3.json](http://101.43.23.40/fintell_asset_data_show_apply_info_v3.json)

> CPU info
![image](https://user-images.githubusercontent.com/1452870/173559476-b8abd04f-2c9b-4156-99a4-822bb1da82c5.png)

**Comment by gitbbrid** [comment]
> Please give schema of table apply_info_v3, and some test data to reproduce the problem is better.

> Table of apply_info_v3

create table apply_info_v3
(
    id           bigint default '0' comment '自增',
    apply_no     varchar(64) default ''                    comment '申请编号',
    customer_no  varchar(64) default ''                    comment '客户编号',
    apply_amt    bigint      default '0'                   comment '授信额度',
    apply_status tinyint     default '0'                   comment '申请状态 0/1/2/3 1-通过',
    rs_status    tinyint     default '0'                   comment '人工审核状态 1/2/3/4 4-完成',
    refuse_code  varchar(64) default ''                    comment '拒绝原因码',
    channel_code varchar(16) default ''                    comment '渠道编码',
    create_time  datetime    default '1000-01-01 00:00:00' comment '创建时间',
    update_time  datetime    default '1000-01-01 00:00:00' comment '更新时间',
    update_year  char(4)     default ''                    comment '更新时间所在年',
    update_month char(7)     default ''                    comment '更新时间所在月',
    update_week  char(8)     default ''                    comment '更新时间所在周',
    update_day   char(10)    default ''                    comment '更新时间所在天',
    create_week  char(8)     default ''                    comment '创建时间所在周',
    create_month char(7)     default ''                    comment '创建时间所在月份',
    create_day   char(10)    default ''                    comment '创建时间所在天',
    create_year  char(4)     default ''                    comment '创建时间所在年份'
) 
COMMENT "额度申请"
DISTRIBUTED BY HASH(id) BUCKETS 3
PROPERTIES (
    "replication_num" = "1"
);


> test data of apply_info_v3

[http://101.43.23.40/fintell_asset_data_show_apply_info_v3.json](http://101.43.23.40/fintell_asset_data_show_apply_info_v3.json)

> CPU info
![image](https://user-images.githubusercontent.com/1452870/173559476-b8abd04f-2c9b-4156-99a4-822bb1da82c5.png)

**Comment by cambyzju** [comment]
```
@ 0x352bf06 _avx2_run_container_cardinality.isra.0
@ 0x3513a95 roaring_bitmap_get_cardinality
```
it looks like third party library `roaringbitmap` inside image `1.0.5-no-avx2 ` still use AVX2.
we need recompile `roaringbitmap` without AVX2 and then release another image.

**Comment by Toms1999** [comment]
let me see see
