### ISSUE TITLE
[Enhancement] stream load in publish version step may delay for along time

### ISSUE THREAD

**Issue by chenlinzhong** [apache/incubator-doris#10158]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

1.publish version  step  may delay for along time ,seriously affect the speed of import

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by miranquil** [comment]
How did you fix this issue?
