### ISSUE TITLE
Null value is not correctly handled when it is a partition column

### ISSUE THREAD

**Issue by morningman** [apache/incubator-doris#1038]
1. Should we have to support null value in range partition column.
    Which range of partition should we put this null value? The first one? or the smallest one?

2. the partition select behavior for null value is different in BE load process and FE query process. which cause uncertain results

**Comment by imay** [comment]
> 1. Should we have to support null value in range partition column.
>    Which range of partition should we put this null value? The first one? or the smallest one?

I think we should support null value in range partition column. And can you give an example, I am not very clear the difference between 'first one' and 'smallest one'

> 2. the partition select behavior for null value is different in BE load process and FE query process. which cause uncertain results

we can unify the process of both FE and BE

**Comment by morningman** [comment]
For now, we loaded the null value into the partition which range includes MIN VALUE.
For example, a table with following partitions (k1 as partition column with type INT)

partition p1 values less than("10"),
partition p2 values less than("20");

Null value will be loaded into partition p1. 

And if we drop the partition p1, NULL value can not be loaded anymore.
