### ISSUE TITLE
No rule to make target

### ISSUE THREAD

**Issue by lvdelu** [apache/incubator-doris#1073]
![image](https://user-images.githubusercontent.com/16470271/56882434-2337aa00-6a96-11e9-885d-a6e403fb9d6f.png)

**Comment by imay** [comment]
from the error message, it looks like that there is 'libthriftnm.a' in your thirdparty libraries. 

How do you get your thirdparty libraries? You build it?

**Comment by lvdelu** [comment]
yes,I build it ,but it doesn't exist there

**Comment by morningman** [comment]
It does not reproduce in my environment, may be rebuild thrift can solve this problem.
