### ISSUE TITLE
whether there is an QQ group or wechat group?

### ISSUE THREAD

**Issue by vkingnew** [apache/incubator-doris#1074]
I have some questions ,is there have a channel to communication?eg QQ group or wechat Group?
And where could i get some offline meetup files.

**Comment by imay** [comment]
@vkingnew 
we have wechat group, you can add me through wexin, my id is ApacheZhaoc

**Comment by vkingnew** [comment]
Advice to public the wechat group.It's convenient for more people join Doris and spread it.

**Comment by imay** [comment]
When the number of group members exceed 100,  new member must be invited by members

**Comment by vkingnew** [comment]
OK,I know.QQ group is better.

**Comment by morningman** [comment]
Currently Wechat  is enough, because there isn't much people of our age using QQ ...
