### ISSUE TITLE
ERROR 5036 (HY000): exec rpc errorUNKONWN

### ISSUE THREAD

**Issue by alexliu5678** [apache/incubator-doris#109]
select * from ssb.lineorder;
ERROR 5036 (HY000): exec rpc errorUNKONWN

**Comment by Leehom001** [comment]
补充：
    多BE部署情况下，导入数据没有问题，查询数据，查询到与fe在同一主机的be时，可正常查询，查询到其它主机的be时，报错：
        mysql> select * from table1;
        ERROR 1064 (HY000): exec rpc errorUNKONWN

**Comment by morningman** [comment]
Reopen it if happening again
