### ISSUE TITLE
 fatal error: json2pb/json_to_pb.h: No such file or directory

### ISSUE THREAD

**Issue by ykPrograWorld** [apache/incubator-doris#1103]
![图片](https://user-images.githubusercontent.com/26919124/57278712-d7aa7f00-70d9-11e9-9612-bfa406fbd674.png)
what's the problem?
How can I fix it?

**Comment by imay** [comment]
Do you have `thirdparty/installed/include/json2pb` directory?

**Comment by ykPrograWorld** [comment]
> 
> 
> Do you have `thirdparty/installed/include/json2pb` directory?

No  
Do I need to create this folder myself?

**Comment by imay** [comment]
If you build `thirdparty` successfully there will be a directory here.

and can you execute `find thirdparty/installed/include -name "json2pb"` to see if there is one?

**Comment by ykPrograWorld** [comment]
> 
> 
> If you build `thirdparty` successfully there will be a directory here.
> 
> and can you execute `find thirdparty/installed/include -name "json2pb"` to see if there is one?

I'm sure there is no such folder
I downloaded the mater packages, and running the build. sh command, the result is such
how can I fix it?

**Comment by imay** [comment]
> > If you build `thirdparty` successfully there will be a directory here.
> > and can you execute `find thirdparty/installed/include -name "json2pb"` to see if there is one?
> 
> I'm sure there is no such folder
> I downloaded the master package, and running the build. sh command, the result is such
> how can I fix it?

It seems that your thirdparty didn't produce successfully. Do you have `thirdparty/installed/include/brpc`?

**Comment by ykPrograWorld** [comment]
> 
> 
> > > If you build `thirdparty` successfully there will be a directory here.
> > > and can you execute `find thirdparty/installed/include -name "json2pb"` to see if there is one?
> > 
> > 
> > I'm sure there is no such folder
> > I downloaded the master package, and running the build. sh command, the result is such
> > how can I fix it?
> 
> It seems that your thirdparty didn't produce successfully. Do you have `thirdparty/installed/include/brpc`?

I deleted all these folders and tried to recompile
Where can I find the compiled package?

**Comment by imay** [comment]
> > > > If you build `thirdparty` successfully there will be a directory here.
> > > > and can you execute `find thirdparty/installed/include -name "json2pb"` to see if there is one?
> > > 
> > > 
> > > I'm sure there is no such folder
> > > I downloaded the master package, and running the build. sh command, the result is such
> > > how can I fix it?
> > 
> > 
> > It seems that your thirdparty didn't produce successfully. Do you have `thirdparty/installed/include/brpc`?
> 
> I deleted all these folders and tried to recompile
> Where can I find the compiled package?

You have two options

1. you can build Doris use Docker image, [here](https://github.com/apache/incubator-doris#4-compile-and-install) is the guide
2. you can use Baidu's release which is maintained by Baidu doris's user. [here](https://github.com/baidu-doris/incubator-doris/releases/download/DORIS-0.9.11-release/DORIS-0.9.11-release-output.tar.gz) is a compiled package

**Comment by ykPrograWorld** [comment]
> 
> 
> > > > > If you build `thirdparty` successfully there will be a directory here.
> > > > > and can you execute `find thirdparty/installed/include -name "json2pb"` to see if there is one?
> > > > 
> > > > 
> > > > I'm sure there is no such folder
> > > > I downloaded the master package, and running the build. sh command, the result is such
> > > > how can I fix it?
> > > 
> > > 
> > > It seems that your thirdparty didn't produce successfully. Do you have `thirdparty/installed/include/brpc`?
> > 
> > 
> > I deleted all these folders and tried to recompile
> > Where can I find the compiled package?
> 
> You have two options
> 
>     1. you can build Doris use Docker image, [here](https://github.com/apache/incubator-doris#4-compile-and-install) is the guide
> 
>     2. you can use Baidu's release which is maintained by Baidu doris's user. [here](https://github.com/baidu-doris/incubator-doris/releases/download/DORIS-0.9.11-release/DORIS-0.9.11-release-output.tar.gz) is a compiled package

I tried to compile several more times, but still failed. Thank you very much for providing the compiled package, and finally I used it.

**Comment by imay** [comment]
> > > > > > If you build `thirdparty` successfully there will be a directory here.
> > > > > > and can you execute `find thirdparty/installed/include -name "json2pb"` to see if there is one?
> > > > > 
> > > > > 
> > > > > I'm sure there is no such folder
> > > > > I downloaded the master package, and running the build. sh command, the result is such
> > > > > how can I fix it?
> > > > 
> > > > 
> > > > It seems that your thirdparty didn't produce successfully. Do you have `thirdparty/installed/include/brpc`?
> > > 
> > > 
> > > I deleted all these folders and tried to recompile
> > > Where can I find the compiled package?
> > 
> > 
> > You have two options
> > ```
> > 1. you can build Doris use Docker image, [here](https://github.com/apache/incubator-doris#4-compile-and-install) is the guide
> > 
> > 2. you can use Baidu's release which is maintained by Baidu doris's user. [here](https://github.com/baidu-doris/incubator-doris/releases/download/DORIS-0.9.11-release/DORIS-0.9.11-release-output.tar.gz) is a compiled package
> > ```
> 
> I tried to compile several more times, but still failed. Thank you very much for providing the compiled package, and finally I used it.

OK, you can add me through wechat to see what the problem is in your environment. My wechat id is ApacheZhaoc

**Comment by cleverpig** [comment]
> > > > > If you build `thirdparty` successfully there will be a directory here.
> > > > > and can you execute `find thirdparty/installed/include -name "json2pb"` to see if there is one?
> > > > 
> > > > 
> > > > I'm sure there is no such folder
> > > > I downloaded the master package, and running the build. sh command, the result is such
> > > > how can I fix it?
> > > 
> > > 
> > > It seems that your thirdparty didn't produce successfully. Do you have `thirdparty/installed/include/brpc`?
> > 
> > 
> > I deleted all these folders and tried to recompile
> > Where can I find the compiled package?
> 
> You have two options
> 
> 1. you can build Doris use Docker image, [here](https://github.com/apache/incubator-doris#4-compile-and-install) is the guide
> 2. you can use Baidu's release which is maintained by Baidu doris's user. [here](https://github.com/baidu-doris/incubator-doris/releases/download/DORIS-0.9.11-release/DORIS-0.9.11-release-output.tar.gz) is a compiled package

@imay This does not effect for the question.
