### ISSUE TITLE
Drop table causes be crash

### ISSUE THREAD

**Issue by HangyuanLiu** [apache/incubator-doris#1114]
**Describe the bug**
Drop table causes be crash after schema change

**To Reproduce**
1. schema change 
2. drop table
3. create table again

error log :
F0507 10:25:01.622939 19737 utils.cpp:1098] fail to destroy mutex. err=Device or resource busy

**Comment by kangpinghuang** [comment]
hi, the reason of this problem is the schema change lock is not released when drop tablet.
This is a bug of BE, it will be solved in release 0.10 soon.
