### ISSUE TITLE
The download link for doris-incubating-thirdparty-20190414 is broken

### ISSUE THREAD

**Issue by gaodayue** [apache/incubator-doris#1168]
When I am trying to download https://doris-incubating-repo.bj.bcebos.com/doris-incubating-thirdparty-20190414.tar.gz in [Doris-Install](https://github.com/apache/incubator-doris/wiki/Doris-Install), it says

```
{
"code": "NoSuchKey",
"message": "The specified key does not exist.",
"requestId": "cb2fcf45-f5d0-429c-a0cd-9e72b635c25c"
}
```

**Comment by morningman** [comment]
We no longer provide this package. You can set REPOSITORY_URL and download it by running
`sh download-thirdparty.sh`

Wiki is just updated.
https://github.com/apache/incubator-doris/wiki/Doris-Install

**Comment by gaodayue** [comment]
Got it, thanks!
