### ISSUE TITLE
compile be error using docker image

### ISSUE THREAD

**Issue by skyler-tao** [apache/incubator-doris#1203]
**Describe the bug**
On my Mac, I have installed docker, so I use the docker image apachedoris/doris-dev:build-env to compile the source code.
fe is ok, but be failed:
![image](https://user-images.githubusercontent.com/8034498/58365194-1ec6ab80-7ef3-11e9-84ab-05d271bad3af.png)
the source code is pull from master, commit id: b132f4ac0c0ee54ad9b5e9d86b7a9fb00548978b

**Comment by imay** [comment]
Hi it seems like you meet a GCC error not a Doris problem.

Maybe there is no enough memory for compilation. 
You can change `PARALLEL` in build.sh to 1 and retry to build.

**Comment by skyler-tao** [comment]
Yes, you're right.
