### ISSUE TITLE
bin/start_fe.sh: line 59: /home/doris/run/fe/conf/fe.conf: No such file or directory

### ISSUE THREAD

**Issue by wengad82** [apache/incubator-doris#1212]
Dockerfile:

FROM centos:7.2.1511

RUN mkdir /home/doris/run/ -p

COPY jdk1.8.0_92 /home/doris/run/jdk1.8.0_92/
COPY fe/ /home/doris/run/fe/

ENV JAVA_HOME /home/doris/run/jdk1.8.0_92/ 
ENV DORIS_HOME /home/doris/run/fe

EXPOSE 8030 9020 9030 9010

VOLUME ["/home/doris/run/fe/conf","/home/doris/run/fe/log","/home/doris/run/fe/doris-meta"]

WORKDIR /home/doris/run/fe/

RUN pwd;find . -iname "*"

CMD "bin/start_fe.sh"

为什么使用如下创建容器都会报错
docker run -d -p 8030:8030 -p 9020:9020 -p 9030:9030  -p 9010:9010 \
 -v /home/doris/ferun/log:/home/doris/run/fe/log \
 -v /home/doris/ferun/conf:/home/doris/run/fe/conf \
 -v /home/doris/ferun/doris-meta:/home/doris/run/fe/doris-meta \
 -e TZ=Asia/Shanghai --privileged=true --name fe mathings.com/doris-fe:0.9 

 错误内容
bin/start_fe.sh: line 59: /home/doris/run/fe/conf/fe.conf: No such file or directory

把conf目录不做映射，就没问题？

**Comment by morningman** [comment]
You can first attach to the container, and see if there has file: `/home/doris/run/fe/conf/fe.conf`

**Comment by wengad82** [comment]
yes，theres is a fe.conf under /home/doris/run/fe/conf

[root@study conf]# docker exec -it fe /bin/bash
[root@7b86c049c22e fe]# ls -l /home/doris/run/fe/conf/fe.conf 
-rwxrwxrwx. 1 root root 1758 May 29 10:20 /home/doris/run/fe/conf/fe.conf

**Comment by EmmyMiao87** [comment]
Do you still have this problem?

**Comment by jackwener** [comment]
Old problem, close.👀
