### ISSUE TITLE
cannot find symbol when compile FE with JDK 12

### ISSUE THREAD

**Issue by kangkaisen** [apache/incubator-doris#1214]
**Describe the bug**
The following error will occur when compile FE with JDK 12:
```
[ERROR] /home/kangkaisen/palo/fe/src/main/java/org/apache/doris/catalog/EsTable.java:[43,22] package javax.xml.soap does not exist
[ERROR] /home/kangkaisen/palo/fe/src/main/java/org/apache/doris/task/LoadPendingTask.java:[41,24] cannot find symbol
  symbol:   class Debug
  location: package sun.security.ssl
```

I found the `sun.security.ssl.Debug` is unnecessary. So we could remove it.

Besides, **I think we should add a [maven-checkstyle-plugin](https://maven.apache.org/plugins/maven-checkstyle-plugin/) to check FE code style.**

**Comment by imay** [comment]
> Besides, **I think we should add a [maven-checkstyle-plugin](https://maven.apache.org/plugins/maven-checkstyle-plugin/) to check FE code style.**

It's a good idea. Can you help us to add this plugin?

And I think we should discuss about how to use it. For example, what should be checked first.

I'm afraid there will be too many problems if we enable this checker

**Comment by kangkaisen** [comment]
OK. I could do this work, but I am busy recently.  I will do this work when I have time.  
Before I do it, I will discuss the detail with you.
