### ISSUE TITLE
Use multi condition cost much more time to return?

### ISSUE THREAD

**Issue by qdore** [apache/incubator-doris#1221]
**Describe the bug**
![image](https://user-images.githubusercontent.com/6831829/58563786-5a000c00-825e-11e9-883b-c589a3c5951a.png)

Condition b has no data in datasource, it should has no effect in the third sql statements, but in fact it cost triple time to run.

**Comment by imay** [comment]
It is bad for Doris to handle OR predicate. For your query, Doris would read all data and do OR operation. It is bad when event_day is a partition column or index column, which can be used to avoid too much scan.

And you can rewrite your query to `event_day` in ("20190526", "20190926"), which should be better
