### ISSUE TITLE
The version 0.10 already supports kafka string load. Where can I find relevant documentation

### ISSUE THREAD

**Issue by luoyafei** [apache/incubator-doris#1253]
I have upgraded to 0.10, but not find 'kafka load example' in 'help stream load' doc.

**Comment by imay** [comment]
you can " help routine", " help routine load"

and you can reference here [manual](https://github.com/apache/incubator-doris/blob/master/docs/documentation/cn/administrator-guide/load-data/routine-load-manual.md)

**Comment by luoyafei** [comment]
perfect
