### ISSUE TITLE
failed to initialize storage reader. tablet=322844.1094272791, res=-214, backend=10.90.239.23

### ISSUE THREAD

**Issue by qdore** [apache/incubator-doris#1256]
A normal sql trigger doris return this:

```
ERROR 1064 (HY000): failed to initialize storage reader. tablet=322844.1094272791, res=-214, backend=10.90.239.23
```

**Comment by qdore** [comment]
And why palo open many deleted file fd? Does it has fd leak?
![image](https://user-images.githubusercontent.com/6831829/58946799-3df9ee80-87b9-11e9-90b6-68edd4e0a7f9.png)

**Comment by imay** [comment]
No, this is not a fd leak. we have a cache for all open files. When we delete a file, for example when this file is compacted, we don't disable its FD cache. So you see a lot of FD opened for a deleted file. 

After FD cache is full, default 30000, we will close unused FD, and these FD will be closed then.

Of course, there is room for improvement. We can do this later

**Comment by qdore** [comment]
initialize storage reader failed:
be warning log:
```
W0606 10:21:45.183228  4247 olap_header.cpp:686] fail to find version in version list. [s
tart_version_id=0 end_version_id=1201 tmp_start=-1 tmp_end=1]

```

**Comment by HawickMason** [comment]
any idea why this hanppened @imay  I got the same error with "failed to initialize storage reader." but have no clue on how to deal with it

**Comment by chaoyli** [comment]
Query may lasts so long. During this period, compaction has done and remove compacted versions.
In new master, this bug has already addressed.

**Comment by chaoyli** [comment]
You can compare the exec/olap_scanner.cpp, which call capture_rs_readers() in advance to get rid of data to be removed.
