### ISSUE TITLE
Support S3 as the persistent storage

### ISSUE THREAD

**Issue by yingfeng** [apache/incubator-doris#126]
Some OLAPs, such as [Snowflake](http://info.snowflake.net/rs/252-RFO-227/images/Snowflake_SIGMOD.pdf), directly use S3 as their table storage, even the temporary data. It has the benefit to save money for cloud users, additionally, it saves time for data ETL.  From this [benchmark](https://blog.fivetran.com/warehouse-benchmark-dce9f4c529c1) could we see that S3 based OLAP(Snowflake) does not have a remarkable performance difference with local storage based one(Redshift). There also exists similar projects as [Rocksdb-cloud](https://github.com/rockset/rocksdb-cloud ) which uses S3 as the Rocksdb's persistent storage, it could save some time to deliver such feature.

**Comment by EmmyMiao87** [comment]
From the perspective of cost performance, we have indeed thought about using S3 as storage on the architecture of separation of storage and computing.
The work of separating storage and computing is still under design discussion. After the framework is implemented, support for S3 as storage can be carried out.
