### ISSUE TITLE
eliminate predicate which is pushed to storage engine

### ISSUE THREAD

**Issue by imay** [apache/incubator-doris#1261]
Currently, although we push down predicates to StorageEngine, but we do it in OlapScanner again. This is a waste for query which will read too many rows from Engine.

we should reduce this eval operation, which need us to eliminate the predicates which can be done in Storage Engine. 

It is difficult that we has normalize user predicates, and there is no relation between user predicates and Storage filter.

**Comment by EmmyMiao87** [comment]
Are we not doing this because we don’t trust the filtering of the storage engine?
