### ISSUE TITLE
建议添加dayofweek函数

### ISSUE THREAD

**Issue by ltylty** [apache/incubator-doris#1336]
0.9版本不支持dayofweek函数，建议添加。
还有dayofyear函数已经可用，但是在[文档](https://github.com/apache/incubator-doris/wiki/Sql-Reference)中没有说明，建议更新文档

**Comment by imay** [comment]
you can use `select date_format("2019-06-19", "%w");` to get day of week

Yes, we should improve our documents, and you can reference some in [here](https://github.com/apache/incubator-doris/tree/master/docs/documentation/cn/sql-reference)

**Comment by HangyuanLiu** [comment]
I will add a dayofweek function for doris.
