### ISSUE TITLE
Wrong query result with constant 

### ISSUE THREAD

**Issue by kangkaisen** [apache/incubator-doris#1356]
**Describe the bug**
1 create a view with constant
```
CREATE VIEW `app_brand_ka_analysis_flow_entry_m_kks4` AS
SELECT `t`.`brand_id` AS `bigchain_brand_id`,
       `t`.`city_id` AS `poi_second_city_id`,
       `t`.`mo` AS `mo`
FROM `default_cluster:mart_waimai`.`app_ka_brand_list_m` t
UNION ALL
SELECT `t`.`brand_id` AS `bigchain_brand_id`,
       -1 AS `poi_second_city_id`,
       `t`.`mo` AS `mo`
FROM `default_cluster:mart_waimai`.`app_ka_brand_list_m` t;
```
2 query

SQL1 :

```
SELECT
poi_second_city_id
FROM
app_brand_ka_analysis_flow_entry_m_kks4
WHERE
mo = 24233
AND poi_second_city_id = -1
AND bigchain_brand_id = 437;
```
the result is:

```
|                 -1 |
|                 -1 |
|                 -1 |
|                 -1 |
|                 -1 |
|                 -1 |
|                 -1 |
|                 -1 |
+--------------------+
5714 rows in set (27.65 sec)
```
SQL 2:
```
SELECT
poi_second_city_id
FROM
app_brand_ka_analysis_flow_entry_m_kks4
WHERE
mo = 24233
AND poi_second_city_id IN (-1)
AND bigchain_brand_id = 437;
```
the result is empty.

the SQL 2 result is wrong. because in `RangePartitionPruner.prune`, the code will run into
```
        Set<Long> resultSet = Sets.newHashSet();
        int childrenNum = inPredicate.getChildren().size();
        int newComplex = inPredicate.getChildren().size() * complex;
        for (int i = 1; i < childrenNum; ++i) {
            LiteralExpr expr = (LiteralExpr) inPredicate.getChild(i);
            minKey.pushColumn(expr, keyColumn.getDataType());
            maxKey.pushColumn(expr, keyColumn.getDataType());
            Collection<Long> subList = prune(rangeMap, columnIdx + 1, minKey, maxKey, newComplex);
            for (long partId : subList) {
                resultSet.add(partId);
            }
            minKey.popColumn();
            maxKey.popColumn();
        }
```
**and get the wrong partition id.**

we could fix the bug by computing `-1 in (-1)`  to `BoolLiteral(true)`.

**Comment by imay** [comment]
Even this patch can make this query work in a proper way. however I think the root reason won't be fixed.

For second operand of the union query

```
SELECT `t`.`brand_id` AS `bigchain_brand_id`,
       -1 AS `poi_second_city_id`,
       `t`.`mo` AS `mo`
FROM `default_cluster:mart_waimai`.`app_ka_brand_list_m` t;
```

I don't know why the `poi_second_city_id IN (-1)` predicate is used to prune partition.  Maybe there is some problem?

**Comment by kangkaisen** [comment]
why the poi_second_city_id IN (-1) predicate is used to prune partition?

1 poi_second_city_id IN (-1) is -1 in (-1)

2 In `SingleNodePlanner`,    List<Expr> conjuncts = analyzer.getUnassignedConjuncts(scanNode), conjuncts will contain  -1 in (-1);

3  In `PartitionColumnFilter keyFilter = createPartitionFilter(slotDesc, conjuncts);` -1 in (-1) will set setInPredicate `partitionColumnFilter.setInPredicate(inPredicate);`

4 So the `RangePartitionPruner.partitionColumnFilters` will contain -1 in (-1) inPredicate.

I think the root cause is  -1 in (-1) shouldn't be contained analyzer.getUnassignedConjuncts(scanNode). So I think simplify -1 in (-1)  to BoolLiteral(true) will fix this issue and reasonable.

**Comment by imay** [comment]
I think the problem located in step `3`. `-1 in (-1)` can not be used to prune partition. What we want to use to prune partition is in predicate like `partitionColumn in (1, 2, 3)`. So besides this patch, we'd better to have another patch to check if the in predicate can match this pattern.

**Comment by kangkaisen** [comment]
Yes. I see And I agree with you.

The issue should be here:

```
            if (!expr.isBound(desc.getId())) {
                continue;
            }
```

If we think conjunct -1 in (-1) could get here,  we will need change `expr.isBound` method, change the `expr.isBound` value to false for `LiteralExpr`.  

If we think conjunct -1 in (-1) could not get here, we should simplify constant Expr earlier.

I don't know the origin design, but I guess  conjunct -1 in (-1)  should simplify earlier.
