### ISSUE TITLE
Casting float string to int will return null

### ISSUE THREAD

**Issue by chenhao7253886** [apache/incubator-doris#1369]
Because StringParser does't support cast float string to int,  as following:
mysql> select cast("11.22" as int);
+----------------------+
| CAST('11.22' AS INT) |
+----------------------+
|                 NULL |
+----------------------+
1 row in set (0.01 sec)
so we will have to change SQL to this:
mysql> select cast(cast("11.22" as double) as int);
+--------------------------------------+
| CAST(CAST('11.22' AS DOUBLE) AS INT) |
+--------------------------------------+
|                                   11 |
+--------------------------------------+
1 row in set (0.00 sec)

**Comment by EmmyMiao87** [comment]
There is currently no plan to support the conversion of float to int
