### ISSUE TITLE
Support bloom filter in new format segment

### ISSUE THREAD

**Issue by imay** [apache/incubator-doris#1389]
We should support bloom filter in new format segment, so we can convert old data into new format without impact query's performance.

This will add BloomFilterPageBuilder which will create a bloom filter page. BloomFilterPageDecoder which will decode bloom filter page and provide test interface. And we should use bloom filter to avoid unused data load in SegmentIterator. And the detail will be fixed in future.

#1305

**Comment by kangpinghuang** [comment]
I will solve this issue. Here is my basic design:
1. use BlockedBloomFilter to realize the bloom filter format, ref: https://github.com/apache/parquet-format/blob/master/BloomFilter.md
2. use the IndexPage to add ordinal index for bloom filter index to load the required bf page and boost the query performance

**Comment by compasses** [comment]
@kangpinghuang Hi, maybe it's long time ago, I dig the bloom filter code recently, and there are some optimize direction todo.
Here I just curious during write, why we just calculate the bf, instead of keep the distinct values? I think that's can reduce the memory footprint.
