### ISSUE TITLE
llvm 无法编译

### ISSUE THREAD

**Issue by zhaomingzhu** [apache/incubator-doris#1399]
环境：
1)OS centos7.2
2)gcc --version
gcc (GCC) 5.4.0
3)cmake --version
cmake version 3.4.3
3)rpm -qa|grep libstdc
**libstdc++-devel-4.8.5-36.el7.x86_64
libstdc++-4.8.5-36.el7.x86_64
libstdc++-static-4.8.5-36.el7.x86_64**
4)rpm -qa|grep libatomic
**libatomic-4.8.5-36.el7.x86_64**
5）llvm-3.4.2.src 

问题：编译报错：
 1） /usr/bin/g++
  -L/export/apache-doris-0.9.0.rc02-incubating-src/thirdparty/installed/lib
  -static-libstdc++ -static-libgcc
  CMakeFiles/cmTC_390a5.dir/testCXXCompiler.cxx.o -o cmTC_390a5

  /usr/bin/ld: 找不到 -lstdc++

  collect2: 错误：ld 返回 1

  gmake[1]: *** [cmTC_390a5] 错误 1

2)去掉#LDFLAGS="-L${TP_LIB_DIR} -static-libstdc++ -static-libgcc"   -static-libstdc++编译报错
CMake Error at cmake/modules/CheckAtomic.cmake:53 (message):
  Host compiler appears to require libatomic, but cannot find it.

**Comment by imay** [comment]
0.9.0是老版本了，建议使用0.10版本。

还有就是建议使用我们的Docker环境进行编译

**Comment by zhaomingzhu** [comment]
使用最新版本编译还是报错，不知道问题出在哪
1）  In file included from /export/incubator-doris-0.10.0-rc04/be/src/util/bfd_parser.cpp:18:0:
/export/incubator-doris-0.10.0-rc04/be/src/util/bfd_parser.h:33:17: 致命错误：bfd.h：没有那个文件或目录
编译中断。
[ 16%] Linking CXX static library libExprs.a
make[2]: *** [src/util/CMakeFiles/Util.dir/bfd_parser.cpp.o] 错误 1
make[2]: *** 正在等待未完成的任务....
[ 17%] Building CXX object src/gen_cpp/CMakeFiles/DorisGen.dir/export/incubator-doris-0.10.0-rc04/gensrc/build/gen_cpp/DataSinks_constants.cpp.o
[ 17%] Building CXX object src/gen_cpp/CMakeFiles/DorisGen.dir/export/incubator-doris-0.10.0-rc04/gensrc/build/gen_cpp/DataSinks_types.cpp.o
[ 18%] Building CXX object src/olap/CMakeFiles/Olap.dir/schema_change.cpp.o
[ 27%] Built target Exprs
[ 27%] Building CXX object src/olap/CMakeFiles/Olap.dir/segment_reader.cpp.o
In file included from /export/incubator-doris-0.10.0-rc04/be/src/http/action/pprof_actions.cpp:37:0:
/export/incubator-doris-0.10.0-rc04/be/src/util/bfd_parser.h:33:17: 致命错误：bfd.h：没有那个文件或目录
编译中断。
make[2]: *** [src/http/CMakeFiles/Webserver.dir/action/pprof_actions.cpp.o] 错误 1

**Comment by imay** [comment]
You can install libbfd with `yum install elfutils-devel`

**Comment by zhaomingzhu** [comment]
sorry 依然报错。 使用你们docker 环境编译fe和自己设置环境编译FE，出现同样错误。
网络可以通，但是maven依赖包无法下载。

[ERROR] Plugin net.sourceforge.czt.dev:cup-maven-plugin:1.6-cdh or one of its dependencies could not be resolved: Failed to read artifact descriptor for net.sourceforge.czt.dev:cup-maven-plugin:jar:1.6-cdh: Could not transfer artifact net.sourceforge.czt.dev:cup-maven-plugin:pom:1.6-cdh from/to spring-plugins (http://repo.spring.io/plugins-release/): 没有到主机的路由 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

**Comment by zhaomingzhu** [comment]
Thanks ，this problem has been solved by adding proxies for mvn config。 but compile BE code is error。
Question 3：
../olap/libOlap.a(utils.cpp.o)：在函数‘boost::cpp_regex_traits<char>::transform_primary[abi:cxx11](char const*, char const*) const’中：
/export/incubator-doris-0.10.0-rc04/thirdparty/installed/include/boost/regex/v4/cpp_regex_traits.hpp:966：对‘boost::re_detail_106400::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const’未定义的引用
../olap/libOlap.a(utils.cpp.o)：在函数‘boost::cpp_regex_traits<char>::transform[abi:cxx11](char const*, char const*) const’中：
/export/incubator-doris-0.10.0-rc04/thirdparty/installed/include/boost/regex/v4/cpp_regex_traits.hpp:962：对‘boost::re_detail_106400::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const’未定义的引用
collect2: 错误：ld 返回 1
make[2]: *** [src/tools/meta_tool] 错误 1
make[1]: *** [src/tools/CMakeFiles/meta_tool.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
../olap/libOlap.a(utils.cpp.o)：在函数‘boost::cpp_regex_traits<char>::transform_primary[abi:cxx11](char const*, char const*) const’中：
/export/incubator-doris-0.10.0-rc04/thirdparty/installed/include/boost/regex/v4/cpp_regex_traits.hpp:966：对‘boost::re_detail_106400::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const’未定义的引用
../olap/libOlap.a(utils.cpp.o)：在函数‘boost::cpp_regex_traits<char>::transform[abi:cxx11](char const*, char const*) const’中：
/export/incubator-doris-0.10.0-rc04/thirdparty/installed/include/boost/regex/v4/cpp_regex_traits.hpp:962：对‘boost::re_detail_106400::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const’未定义的引用
collect2: 错误：ld 返回 1
make[2]: *** [src/service/palo_be] 错误 1
make[1]: *** [src/service/CMakeFiles/palo_be.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by zhaomingzhu** [comment]
重新安装环境编译成功。
