### ISSUE TITLE
can't connect doris by metabse

### ISSUE THREAD

**Issue by ChaimCode** [apache/incubator-doris#1411]
**Describe the bug**
can't connect doris by metabse

**To Reproduce**
1. add a new database in metabse
2.  you will see:  java.sql.SQLException: Syntax error at:

**Expected behavior**
can connect doris by metabse.

**Screenshots**
![image](https://user-images.githubusercontent.com/12760278/60333457-a9f00100-99cb-11e9-8eab-55e625516587.png)

**Comment by chenhao7253886** [comment]
Fixed in https://github.com/apache/incubator-doris/pull/1418/files
