### ISSUE TITLE
ETL_SUBMIT_FAIL problem

### ISSUE THREAD

**Issue by zttaotao2013** [apache/incubator-doris#1416]
我搭建了3fe + 3be + 3broker的doris测试环境，计划对存储于hdfs目录中的数据使用Broker进行批量入库，我定义了一个任务：
load label data_load_1
data infile
(
  "hdfs://192.168.0.2:8020/doris/data/*.nb"
   into table test
)
....
在/doris/data/目录下，有300个数据文件，每个文件1G左右，当我提交一个入库任务时，报 ETL_SUBMIT_FAIL; msg:create job request fail. scan bytes per broker scanner limit: 3221225472.
当单个文件导入时能够顺利导入。doris对这种场景的批量导入有数据量限制？如果是这样，感觉批量入库不太友好，300个文件我需要设置300个Load任务。

**Comment by imay** [comment]
当前broker导入需要把数据都加载到内存中，然后完成排序操作再写入到磁盘中。
我们新版本的导入已经可以不需要全部加载到内存中了，这个值是可以改大的。你可以修改max_bytes_per_broker_scanner的值

**Comment by zttaotao2013** [comment]
是在fe或be的配置文件中改么？我用mysql set 命令提示没有这个变量

**Comment by imay** [comment]
> 是在fe或be的配置文件中改么？我用mysql set 命令提示没有这个变量

fe.conf 
max_bytes_per_broker_scanner = xxxxx

**Comment by zttaotao2013** [comment]
改完后不再报上面那个错误了，但报了Broker etl failed：Memory limit exceeded的错误。

**Comment by imay** [comment]
set exec_mem_limit = xxx 
xxx's unit is in bytes whose default value is 2GB

**Comment by zttaotao2013** [comment]
我用的是0.10.0-rc04版本，该版本支持“不需要全部加载到内存中”特性么？

**Comment by imay** [comment]
> 我用的是0.10.0-rc04版本，该版本支持“不需要全部加载到内存中”特性么？

This is supported in current master branch. not in 0.10.0

**Comment by zttaotao2013** [comment]
ok，3q

**Comment by zttaotao2013** [comment]
测试过程我我发现Load的性能不高，我在hdfs的一个目录下放了20G数据，22个文件，表字段150个，入库使用了1小时17分钟，这个性能对于一个MPP入库来说，感觉性能不太好。硬件配置上，doris使用万兆网，hadoop使用千兆网，SSD磁盘。性能有调优的空间吗？

**Comment by zttaotao2013** [comment]
磁盘是HDD

**Comment by morningman** [comment]
> 测试过程我我发现Load的性能不高，我在hdfs的一个目录下放了20G数据，22个文件，表字段150个，入库使用了1小时17分钟，这个性能对于一个MPP入库来说，感觉性能不太好。硬件配置上，doris使用万兆网，hadoop使用千兆网，SSD磁盘。性能有调优的空间吗？

这个测试你使用的是哪个doris 版本？

**Comment by zttaotao2013** [comment]
master上的版本
