### ISSUE TITLE
使用Power BI连接到doris时提示：MySQL: No matching function with signature:utc_timestamp().

### ISSUE THREAD

**Issue by bd7ce** [apache/incubator-doris#1428]
如题。貌似为缺乏 utc_timestamp()函数。

Power BI Desktop是个人免费使用的BI工具，建议增加支持。

**Comment by morningman** [comment]
Could you offer the full SQL?
You may find it in fe.audit.log

**Comment by HangyuanLiu** [comment]
我可以帮组增加utc_timestamp()函数功能

**Comment by morningman** [comment]
> 我可以帮组增加utc_timestamp()函数功能

Nice! But notice that Doris does not support setting timezone, so you may think more about it

**Comment by HangyuanLiu** [comment]
This new utc_timestamp function does not support timezone as usual, 
but I will modify all time zone related code and time zone related functions in the next PR to make Doris support settting timezone.

**Comment by bd7ce** [comment]
更新后验证，utc_timestamp()函数已经正常了，但连接时继续报错:
“从提供程序读取数据时出错：输入字符串的格式不正确”。

检查fe.audio.log，最后一句是：
select timediff(now(),utc_timestamp());

在mysql命令行执行该命令，发现结果中有秒与毫秒之间有乱码。
而直接执行
select now();
select utc_timestamp();
均没有毫秒。
貌似为timediff()的精度有问题？
