### ISSUE TITLE
如何比较方便地按天分区建表

### ISSUE THREAD

**Issue by ltylty** [apache/incubator-doris#1452]
在文档中看到如下建表语句
 CREATE TABLE example_db.table_range
    (
    k1 DATE,
    k2 INT,
    k3 SMALLINT,
    v1 VARCHAR(2048),
    v2 DATETIME DEFAULT "2014-02-04 15:36:00"
    )
    ENGINE=olap
    DUPLICATE KEY(k1, k2, k3)
    PARTITION BY RANGE (k1)
    (
    PARTITION p1 VALUES LESS THAN ("2014-01-01"),
    PARTITION p2 VALUES LESS THAN ("2014-06-01"),
    PARTITION p3 VALUES LESS THAN ("2014-12-01")
    )
    DISTRIBUTED BY HASH(k2) BUCKETS 32
    PROPERTIES(
    "storage_medium" = "SSD", "storage_cooldown_time" = "2015-06-04 00:00:00"
    );

这个语句会将数据划分成如下3个分区：
    ( {    MIN     },   {"2014-01-01"} )
    [ {"2014-01-01"},   {"2014-06-01"} )
    [ {"2014-06-01"},   {"2014-12-01"} )

如果我想按天或者按月分区，不是要写很多 PARTITION p3 VALUES LESS THAN ("2014-12-01") 这样地语句？有没有比较方便地做法？

**Comment by morningman** [comment]
目前只能手动添加或者通过add partition 来添加。
你期望能够以什么样的形式呢？

**Comment by ltylty** [comment]
比如类似click house的语法， PARTITION BY toYYYYMM(FlightDate)

**Comment by dzzgml** [comment]
hive的分区方式就比较不错
