### ISSUE TITLE
This code whether only limit operations are supported and offset operations are not supported？

### ISSUE THREAD

**Issue by zhuyuncheng** [apache/incubator-doris#1509]
🌹🌹

**Comment by imay** [comment]
We support both limit and offset. When there is an order by clause, offset will effect. However if there is no order by clause, data is not ordered, and offset is useless, so we ignore offset.

**Comment by zhuyuncheng** [comment]
> We support both limit and offset. When there is an order by clause, offset will effect. However if there is no order by clause, data is not ordered, and offset is useless, so we ignore offset.

`SHOW LOAD FROM xx ORDER BY CreateTime DESC LIMIT 3,2`  This query offet is not supported.

**Comment by zhuyuncheng** [comment]
https://github.com/apache/incubator-doris/blob/master/fe/src/main/java/org/apache/doris/analysis/ShowLoadStmt.java#L259

**Comment by imay** [comment]
@zhuyuncheng 
I think you are right. Currently, we don't support offset in `SHOW LOAD` statement.

**Comment by zhuyuncheng** [comment]
> @zhuyuncheng
> I think you are right. Currently, we don't support offset in `SHOW LOAD` statement.
> 
> And can you give us a PR to support it?

Let me try.

**Comment by zhuyuncheng** [comment]
Let me try. @imay
