### ISSUE TITLE
Parquet导入问题

### ISSUE THREAD

**Issue by zhangy5** [apache/incubator-doris#1534]
1. help文档中说：
导入Parquet文件中数据  指定FORMAT 为parquet， 默认是通过文件后缀判断
我执行导入时，导入文件为
hdfs://host:port/data/d1.parquet 或 hdfs://host:port/data/d1.Parquet
导入该文件时，不指定format as，导入失败。看上去并不能通过文件的后缀名判断导入的文件是parquet文件。

2. 导入时，导入语句如：
LOAD LABEL test.label_1 (DATA INFILE("hdfs://host:port/data/null.Parquet") INTO TABLE `null_b` format as 'parqut' ) WITH BROKER "hdfs" ("username"="xx");
format as指定了错误的file_type，没有相应的错误提示，只看到最后导入失败。是否应该检查语法，当format as遇到不支持的格式时，直接提示错误。

3. 创建parquet外部表，如：
create external table t(
  `k1` tinyint(4) NULL COMMENT "",
   `v1` date NULL COMMENT ""
)
ENGINE=broker
properties("broker_name" ="hdfs","path" ="hdfs://host:port/data/d.parquet")
BROKER PROPERTIES ("username"="xxx");
创建成功，但是select结果为empty。且无任何错误提示。创建外部表时，是否需要指定format？具体有语法帮助么？

**Comment by worker24h** [comment]
**Create External Table：**
create external table t(
k1 tinyint(4) NULL COMMENT "",
v1 date NULL COMMENT ""
)
ENGINE=broker
properties("broker_name" ="hdfs","path" ="hdfs://host:port/data/d.parquet",**"format"="parquet"**)
BROKER PROPERTIES ("username"="xxx");

**Comment by worker24h** [comment]
Problem-1 and Problem-2，I had fix
