### ISSUE TITLE
Support multiple time zone

### ISSUE THREAD

**Issue by HangyuanLiu** [apache/incubator-doris#1583]
**Is your feature request related to a problem? Please describe.**
Support multiple time zone

**Solution:**

1. Setting of time zone related parameters: 
    mainly involves two parameters "system_time_zone" and "time_zone".
    "system_time_zone" is obtained by calling the system interface and cannot be modified. 
    "time_zone" parameter can be modified. To be compatible with historical logic, the default setting is CST.
Time zone values ​​can be given in several formats, no case sensitive:
* "SYSTEM", indicating that the server time zone is the same as the system time zone
* A string representing the UTC offset, such as '+10:00' or '-06:00'
* Standard time zone format such as "Asia/Shanghai", "America/Los_Angeles"
* Abbreviated time zone formats such as "MET", "CTT" are not supported. Because the abbreviated time zone is ambiguous in different scenarios, it is not recommended.
* In order to be compatible with Doris, support CST abbreviated time zone, internally transfer CST to "China/Shanghai" Chinese standard time zone

2. Time zone in BE: Perceive the time zone by Fe, and then pass two parameters to be. One is the UTC timestamp, and the other is the time zone information.

3.  the time recorded in the fe: such as "show backends", "show load". These time fields should be modified according to the time zone. Fe internally stores timestamps. The timestamp can be converted to a date literal by calling the TimeUtils.longToTimeString function. Inside the function, get the time zone configuration through Session variabled

**Comment by imay** [comment]
@HangyuanLiu 

I have a question. How can we get `system_time_zone`? How to keep the values on each node consistent.

And I think this can be split into some small patches.

For example:
1. support related user function aware of time zone.
2. Support time zone for our system usage.

**Comment by HangyuanLiu** [comment]
@imay 
I think system_time_zone is a parameter that represents the time zone of the machine, but the other variable "time_zone" is really takes effect. 
So system_time_zone is fetched according to the machine's time zone and cannot be modified. The time_zone function is customizable in doris cluster.

And I will split this feature as three commit
