### ISSUE TITLE
when  Executing sql, mysql command line scrambling

### ISSUE THREAD

**Issue by manannan2017** [apache/incubator-doris#1603]
steps：
1、Connect doris
2、select ST_Point(3,3);
![image](https://user-images.githubusercontent.com/33174388/62623045-6ab1ba00-b952-11e9-9ad9-ae28e27d8c9a.png)

mysql is：
![image](https://user-images.githubusercontent.com/33174388/62623581-c6c90e00-b953-11e9-96d8-f0d0ee86af36.png)

3、mysql command line scrambling， only can be closed

**Comment by imay** [comment]
Yes, point will return a binary, which may cause command line scrambling.
You can use `ST_AsText()` function to see the content of it.

For Example `select ST_AsText(POINT(3,3))`

**Comment by manannan2017** [comment]
Can we add this information in the document?When the user accidentally entered this command，user experience is not good
