### ISSUE TITLE
Backend's disks statistics (UsedPct and MaxDiskUsedPct) is incorrect

### ISSUE THREAD

**Issue by MLikeWater** [apache/incubator-doris#1608]
**Describe the bug**

When executing the command "show backends; "，the UsedPct metric is found to have a negative value, such as -148.01 %, while the MaxDiskUsedPct value is 0.00%.

**To Reproduce**
1. Install FE and BE software
2. Configure FE(conf/fe.conf) and BE(conf/be.conf)
a parameter of the configuration file, conf/be.conf:
```
storage_root_path = /disk/disk1/doris, 500;/disk/disk2/doris, 500;/disk/disk3/doris, 500;
or
storage_root_path=/doris/be/palo-data
```
3. start FE nodes
4. add BE nodes
5. start BE nodes
6. execute the command "show backends; "

**Expected behavior**
The correct result should be:
* UsedPct: shows the utilization of the entire disk of the current backend node
* MaxDiskUsedPct: shows the highest disk utilization of the current backend node

**Comment by jiangshouzhuang** [comment]
I will modify this issue.
