### ISSUE TITLE
ST_Circle function：when radius is too large，the result is 20015118.2119

### ISSUE THREAD

**Issue by manannan2017** [apache/incubator-doris#1620]
1、execute sql，Numbers of radius exceed 8 digits
SELECT ST_AsText(ST_Circle(111, 64, 123456789));
![image](https://user-images.githubusercontent.com/33174388/62768755-23e6d000-baca-11e9-8ece-71a5f7252b0a.png)

except：the result is NULL

**Comment by yangzhg** [comment]
i will check this

**Comment by yangzhg** [comment]
this is not  a bug, when the radius is larger than  half of circumference of earth, it will be zoomed to this scale
