### ISSUE TITLE
建议增加Value列的聚合方式(append、按位与)

### ISSUE THREAD

**Issue by gdmmx** [apache/incubator-doris#165]
建议给Value列的聚合增加以下方式：

- append聚合：用于指定分隔符(通常是\n)的多行追加
- &聚合：用于flag或tag用途的bitmap数据。 `例如row1 value=(1<<2)与 row2 value=(1<<4)按&的方式聚合`

append和&的计算是数据处理常见需求，请RD考虑增加这两种聚合能力。

**Comment by EmmyMiao87** [comment]
Now, we already support agg type `Bitmap_union`. 
If you have some business data related to tags, you can use the global dictionary function to map the tags to integers, and then use bitmap type to store them.
If you want to calculate the union, you can use the `bitmap_union` function directly. 
I don't know if this kind of meets your needs.

**Comment by EmmyMiao87** [comment]
You can get help by command `help create table`
