### ISSUE TITLE
the sql-reference doc review，i have some doubts

### ISSUE THREAD

**Issue by manannan2017** [apache/incubator-doris#1656]
一、github上sql-reference
1、dayofweek(DATETIME date)描述不清晰
原来：参数为Date或者Datetime类型； 纠正信息：可cast到date的数字也可以
地址：https://github.com/apache/incubator-doris/blob/master/docs/documentation/cn/sql-reference/sql-functions/date-time-functions/dayofweek.md

2、ST_Polygon建议补充信息：多边形不能交叉
关键字不能用：
![image](https://user-images.githubusercontent.com/33174388/63094043-d8d12f00-bf99-11e9-923c-69cf377e93a4.png)
地址：https://github.com/apache/incubator-doris/blob/master/docs/documentation/cn/sql-reference/sql-functions/spatial-functions/st_polygon.md

3、建议补充圆的半径最大值信息【超过8位数，就不准了】
SELECT ST_AsText(ST_Circle(111, -64, 123456789));
地址：https://github.com/apache/incubator-doris/blob/master/docs/documentation/cn/sql-reference/sql-functions/spatial-functions/st_circle.md

二、doris官网
1、导入，分隔符与描述的不一致
![image](https://user-images.githubusercontent.com/33174388/63094093-03bb8300-bf9a-11e9-86d8-7cf539d4935f.png)

地址：http://doris.apache.org/Docs/cn/getting-started/basic-usage.html#id10

2、描述错误：int 类型占4字节
![image](https://user-images.githubusercontent.com/33174388/63094111-103fdb80-bf9a-11e9-9275-c204d44a86c8.png)
地址：http://doris.apache.org/Docs/cn/getting-started/data-model-rollup.html

3、错别字
![image](https://user-images.githubusercontent.com/33174388/63094137-2352ab80-bf9a-11e9-8d3a-42e9d977a5dd.png)

地址：http://doris.apache.org/Docs/cn/getting-started/data-model-rollup.html

4、序号有误
![image](https://user-images.githubusercontent.com/33174388/63094165-32395e00-bf9a-11e9-94ee-40ad09caf061.png)

地址：http://doris.apache.org/Docs/cn/getting-started/best-practice.html

5、数据划分 错别字
![image](https://user-images.githubusercontent.com/33174388/63094180-3ebdb680-bf9a-11e9-8f93-27794cd8e61d.png)

三、命令行里help文档
1、help create table：
![image](https://user-images.githubusercontent.com/33174388/63094206-4aa97880-bf9a-11e9-9636-5845574d8d6b.png)

2、范围是否正确
![image](https://user-images.githubusercontent.com/33174388/63094222-572dd100-bf9a-11e9-9192-6618af764e58.png)

3、help mini load
![image](https://user-images.githubusercontent.com/33174388/63094243-6280fc80-bf9a-11e9-9e05-313e81740feb.png)

4、help largeint
![image](https://user-images.githubusercontent.com/33174388/63094251-69a80a80-bf9a-11e9-96f0-ab6a69576f5f.png)

5、help create file
![image](https://user-images.githubusercontent.com/33174388/63094266-7167af00-bf9a-11e9-8fd3-3dda7f5b80c7.png)

**Comment by imay** [comment]
Can you change it for us, and give PR to fix it?
