### ISSUE TITLE
NumberTotalRows in stream load result is double

### ISSUE THREAD

**Issue by kangkaisen** [apache/incubator-doris#1663]
**Describe the bug**
https://github.com/apache/incubator-doris/pull/1597 introduce a minor bug:

The NumberTotalRows and NumberLoadedRows in stream load result is double.

**To Reproduce**

```
seq 11 20 | awk '{OFS="\t"}{print $1, $1 * 10, $1 * 100}' | curl -v --location-trusted -u xxx:xxx   -T - http://xxx:8410/api/test/table/_stream_load
```
the result is :
```
    "TxnId": 9041,
    "Label": "ebf35996-b51a-435d-b48d-0c38c6f7d6fc",
    "Status": "Success",
    "Message": "OK",
    "NumberTotalRows": 20,
    "NumberLoadedRows": 20,
    "NumberFilteredRows": 0,
    "NumberUnselectedRows": 0,
    "LoadBytes": 126,
    "LoadTimeMs": 489
```

**Comment by morningman** [comment]
You mean NumberTotalRows is same as NumberLoadedRows, so NumberTotalRows is redundant?

**Comment by kangkaisen** [comment]
> You mean NumberTotalRows is same as NumberLoadedRows, so NumberTotalRows is redundant?

No. Update the issue description.
