### ISSUE TITLE
Remove author tag in our code

### ISSUE THREAD

**Issue by imay** [apache/incubator-doris#1755]
We should remove author tag in our code

[Here](http://www.apache.org/foundation/records/minutes/2004/board_minutes_2004_09_22.txt) and [Here](https://lists.apache.org/thread.html/7eec9fa00bec3ac6f818c937bac32aae9fcf1463e5096fc2c0ab0c59@%3Cgeneral.incubator.apache.org%3E) is reference.

**Comment by xy720** [comment]
ok.I 'll do it.
