### ISSUE TITLE
在CentOS上直接编译报错：‘char* strncpy(char*, const char*, size_t)’

### ISSUE THREAD

**Issue by nick-yangg** [apache/incubator-doris#1781]
我在使用sh build.sh 编译的时候报错，致使编译失败。
![image](https://user-images.githubusercontent.com/55170104/64662776-31ea9080-d47c-11e9-8716-c8019b033f57.png)

**Comment by imay** [comment]
centos的版本是？gcc的版本是？你这个应该是在编译三方库RocksDB出的问题？

如果想快速尝试Doris，建议可以直接使用Doris的docker镜像进行编译

**Comment by nick-yangg** [comment]
CentOS的的版本是7 ，gcc 8 的版本，如果是RocksDB出的问题需要怎么去解决它

**Comment by nick-yangg** [comment]
@imay

**Comment by imay** [comment]
你可以尝试export CXXFLAGS="-Wno-error=stringop-truncation"之后在编译试试

**Comment by nick-yangg** [comment]
@imay 我在编译的过程中出现了这些，应该没什么问题吧？
![image](https://user-images.githubusercontent.com/55170104/64665946-15a02100-d487-11e9-8809-0e9ca92179c1.png)

**Comment by nick-yangg** [comment]
@imay 这个必须要编译吗，有编译好的版本（直接用的版本）吗？

**Comment by nick-yangg** [comment]
好的我在尝试编译中，这个必须要编译吗，有编译好的可以直接使用的吗？

ZHAO Chun <notifications@github.com> 于2019年9月11日周三 上午10:43写道：
