### ISSUE TITLE
doris对于实时流处理的支持

### ISSUE THREAD

**Issue by yan-yunfeng** [apache/incubator-doris#1790]
我在尝试用flink接入doris进行实时数据的存储，发现单条数据的存入非常慢。
doris是否不太支持这种实时数据的逐条插入呢？如果不太支持，后续是否会实现实时数据快速逐条插入？

**Comment by chaoyli** [comment]
doris的导入支持的micro-batch，每秒支持的导入在100次左右，对于这种单条导入，目前框架有限制。
我理解micro-batch对于分析场景，能够覆盖大部分的场景。
你这边是什么场景需要单条实时导入呢?

**Comment by morningman** [comment]
Do not use `INSERT INTO VALUES` stmt in product environment. It's throughput is very low.
You can use `stream load` via http to meet load latency within seconds.
see here: `http://doris.incubator.apache.org/documentation/cn/administrator-guide/load-data/stream-load-manual.html`

**Comment by yan-yunfeng** [comment]
最后采用http的方式在flink流程中缓存后再定时或定量批量进行导入总算打通流程了

**Comment by z-Dapor** [comment]
> 最后采用http的方式在flink流程中缓存后再定时或定量批量进行导入总算打通流程了

大概缓存的数量和占用的内存大概多少呢？一批多少数据？

**Comment by yan-yunfeng** [comment]
这里可以直接将数据写入kafka，然后doris订阅那个主题进行存储就行了，我们刚开始用的时候没有注意有这么个功能
















在 2020-03-09 14:12:41，"z-Dapor" <notifications@github.com> 写道：

最后采用http的方式在flink流程中缓存后再定时或定量批量进行导入总算打通流程了

大概缓存的数量和占用的内存大概多少呢？一批多少数据？

**Comment by hww123** [comment]
> 这里可以直接将数据写入kafka，然后doris订阅那个主题进行存储就行了，我们刚开始用的时候没有注意有这么个功能 在 2020-03-09 14:12:41，"z-Dapor" <notifications@github.com> 写道： 最后采用http的方式在flink流程中缓存后再定时或定量批量进行导入总算打通流程了 大概缓存的数量和占用的内存大概多少呢？一批多少数据？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，想问一下 你用kafka订阅的方式，那么kafka发消息的api是怎么写的？ 
官方说csv格式，我用new ProducerRecord(topic, partition, timestamp, key,value)
 然后 value 是  xx,xx,xx,xx 对应表的4个字段按顺序.但是SHOW ROUTINE LOAD TASK WHERE JobName =topic 没有报错日志  表也没有数据导入进去，topic是有消息数据的。

**Comment by hww123** [comment]
@yan-yunfeng 

> 这里可以直接将数据写入kafka，然后doris订阅那个主题进行存储就行了，我们刚开始用的时候没有注意有这么个功能 在 2020-03-09 14:12:41，"z-Dapor" <notifications@github.com> 写道： 最后采用http的方式在flink流程中缓存后再定时或定量批量进行导入总算打通流程了 大概缓存的数量和占用的内存大概多少呢？一批多少数据？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，想问一下 你用kafka订阅的方式，那么kafka发消息的api是怎么写的？
官方说csv格式，我用new ProducerRecord(topic, partition, timestamp, key,value)
然后 value 是 xx,xx,xx,xx 对应表的4个字段按顺序.但是SHOW ROUTINE LOAD TASK WHERE JobName =topic 没有报错日志 表也没有数据导入进去，topic是有消息数据的。

**Comment by yan-yunfeng** [comment]
@hww123 
写入kafka的时候设置好分隔符，doris消费的时候设置好同样的分隔符，具体可以参考官方文档
http://doris.apache.org/documentation/cn/administrator-guide/load-data/routine-load-manual.html
