### ISSUE TITLE
doris 进行count(*) 操作是有时候会出现下面的错误

### ISSUE THREAD

**Issue by nick-yangg** [apache/incubator-doris#1794]
```
failed to initialize storage reader. tablet=12301.1548401152, res=-105, backend=xx.xxx.xx.xx
```
这个问题是bug还是那里操作配置的有问题？

**Comment by imay** [comment]
可以把内存适当调整大一些，`set exec_mem_limit = `

**Comment by morningman** [comment]
You can search `exec_mem_limit` here:

`http://doris.incubator.apache.org/documentation/cn/getting-started/advance-usage.html?highlight=exec_mem_limit`

**Comment by nick-yangg** [comment]
![image](https://user-images.githubusercontent.com/55170104/64907894-4acc9d80-d72b-11e9-92e0-925390696764.png)
我set exec_mem_limit 内存适当调整大了，但是问题依旧，日志中信息如上，我通过ulimit -n 8048 修改了配置之后问题消失了，希望对其他人有用。
