### ISSUE TITLE
建议尝试把这个项目向Apache推，争取成为Apache顶级项目

### ISSUE THREAD

**Issue by fengnex** [apache/incubator-doris#180]
GitHub上的项目非常多，相对而言Apache上的项目质量、知名度要好得多。
成为Apache顶级项目之后，方便推广、方便吸收更多人员，能够更好的证明palo。
强烈建议！

**Comment by interma** [comment]
https://lists.apache.org/thread.html/74a3f3f945403b50515c658047d3284955288a637207e4f97ecc15d1@%3Cgeneral.incubator.apache.org%3E

**Comment by imay** [comment]
Now Apache doris(incubating) has already a ASF project. I will close this issue.
