### ISSUE TITLE
be启动时日志文件显示报错

### ISSUE THREAD

**Issue by nick-yangg** [apache/incubator-doris#1804]
![image](https://user-images.githubusercontent.com/55170104/64842995-73bf3680-d636-11e9-8399-49ad39f55826.png)

这个问题是什么原因引起的，需要怎么去解决呢

**Comment by morningman** [comment]
The main error is `Doris Be http service did not start correctly. exiting`.
Other warnings can be ignore.

This error means the BE's http port(default is 8040, configured in be.conf) is already used by some other process. You need to try your port using `netstat` command.
