### ISSUE TITLE
doris 误删表之后有什么操作能够恢复吗？

### ISSUE THREAD

**Issue by nick-yangg** [apache/incubator-doris#1805]
doris 有提供关于数据恢复相关的操作吗

**Comment by morningman** [comment]
If you drop the table or partition by using `DROP table` or `ALTER table drop partition`, you can recover it by using "RECOVER ...";

see `help recover;` for more help;

the default retention time is 1 day, which is set in `fe.conf` as `catalog_trash_expire_second`
