### ISSUE TITLE
doris报错Error preloading the connection pool

### ISSUE THREAD

**Issue by nick-yangg** [apache/incubator-doris#1806]
doris 同时连接数据在100左右时，连接会出现这个错误Error preloading the connection pool，我已经配置了max_conn_per_user 为1000并重启了FE，但是错误依旧存在，请问这个需要怎么解决呢。

**Comment by imay** [comment]
The max number of connection for each user is 100. You can change it with `SET PROPERTY` command. You can execute `help SET PROPERTY` to get detail information.
