### ISSUE TITLE
服务器重启后FE启动一直失败

### ISSUE THREAD

**Issue by nick-yangg** [apache/incubator-doris#1807]
![image](https://user-images.githubusercontent.com/55170104/64904782-63c05900-d701-11e9-94c9-07c58e28a9fb.png)
服务器重新之后，FE节点启动不起来，这个问题需要怎么解决呢

**Comment by morningman** [comment]
Your FE config is wrong, or your starting procedure is incorrect.
Plz follow the document `http://doris.incubator.apache.org/documentation/cn/installing/install-deploy.html` to check your step.
Or you may simply clean up the `palo-meta` dir and start it again, but this may lose data if this FE is your only master FE.

**Comment by nick-yangg** [comment]
好的
