### ISSUE TITLE
doris FE扩容失败问题

### ISSUE THREAD

**Issue by nick-yangg** [apache/incubator-doris#1808]
![image](https://user-images.githubusercontent.com/55170104/64906319-9b3a0000-d717-11e9-96de-0d9291d2f869.png)

这个FE节点启动不起来是什么问题

**Comment by morningman** [comment]
Please describe the way to reproduce this case

**Comment by nick-yangg** [comment]
我的测试环境是一台FE和3台BE，在此基础上进行扩容FE操作，按照下面的步骤操作的
![image](https://user-images.githubusercontent.com/55170104/64931667-9470d180-d86c-11e9-8af8-0aaae017f500.png)
但是会出现上面的报错，并且FE image 中元数据丢失了，请问我要怎么解决这个问题呢？

**Comment by nick-yangg** [comment]
@imay  @morningman

**Comment by nick-yangg** [comment]
![image](https://user-images.githubusercontent.com/55170104/64943873-6c4e9600-d89f-11e9-8672-84a12839a98c.png)
我是这样启动其他fe节点的

**Comment by nick-yangg** [comment]
> ![image](https://user-images.githubusercontent.com/55170104/64943873-6c4e9600-d89f-11e9-8672-84a12839a98c.png)
> 我是这样启动其他fe节点的

启动之后主节点就连不上了

**Comment by nick-yangg** [comment]
![image](https://user-images.githubusercontent.com/55170104/64944082-06164300-d8a0-11e9-874c-3dea25d0c623.png)
这是我其中一台FE  log 日志的错误信息
