### ISSUE TITLE
support udtf：user defined table generation function

### ISSUE THREAD

**Issue by xionglei0** [apache/incubator-doris#1809]
we need to explode one line to multi lines,like json string or array string
this is what udtf do， like table test_udtf:
**select * from test_udtf;**
+-------------+------------+--+
|   pageid    | adid_list  |
+-------------+------------+--+
| front_page  | [1,2,3]    |
| end_page    | [4,3,6]    |
+-------------+------------+--+

hive implements udtf  like this:
grammer one: **select pageid, score from test_udtf1 lateral view explode(adid_list) scores as score;**
Grammer two: **select pageid, explode(adid_list)  as score from test_udtf ;**
+-------------+--------+--+
|   pageid    | score  |
+-------------+--------+--+
| front_page  | 1      |
| front_page  | 2      |
| front_page  | 3      |
| end_page    | 4      |
| end_page    | 3      |
| end_page    | 6      |
+-------------+--------+--+

**Comment by xionglei0** [comment]
https://github.com/apache/incubator-doris/issues/1809

**Comment by wguangliang** [comment]
hi,have you found the solution to the problem.I have the same problem too. How to write the doris sql?

**Comment by caiconghui** [comment]
@wguangliang now, Doris doesn't support udtf, but we can use other method to work around  https://xie.infoq.cn/article/f7a2d9fd093d4f80bf8480db6

**Comment by wguangliang** [comment]
@caiconghui thanks~
