### ISSUE TITLE
这种FE扩容状态是正常的吗

### ISSUE THREAD

**Issue by nick-yangg** [apache/incubator-doris#1814]
![image](https://user-images.githubusercontent.com/55170104/64963364-b51c4400-d8cb-11e9-99ad-daee917fe7a6.png)
这种FE扩容状态是正常的吗？

**Comment by morningman** [comment]
It not right, the `Join` status is false, means those 2 Frontends does not join the cluster.
You need to check fe.log for more information.

**Comment by nick-yangg** [comment]
非常感谢您的回复，我司已经解决了此问题，并修复了此bug。

Mingyu Chen <notifications@github.com> 于2019年9月17日周二 下午2:26写道：
