### ISSUE TITLE
mini load：too many filtered rows

### ISSUE THREAD

**Issue by DarrenChanChenChi** [apache/incubator-doris#1815]
when I do the mini load，it has the issue：too many filtered rows.
the file to load is as follows:
20190915        1       1584928185071026        爱奇艺  1       6       1       50      300     62532   2       2       null    1568300733      0       0       0       4514    6800090 222     23000
20190915        1       1584928185071026        爱奇艺  1       6       2       null    300     62532   5       2       null    1568211354      0       0       0       4514    6800090 222     23000
20190915        1       1582378849591818        新华社  1       3       1       50      null    39856179        2       null    null    1568211707      0       0       0       356724  null    1854    14
20190915        2       1570168231568259        央视新闻        2       7       1       30      null    41722422        2       null    null    1568213647      0       0       0       2208015 966592602       10468   71328834
20190915        1       1570168231568259        央视新闻        2       3       1       10      null    41722422        2       null    null    1568212541      0       0       0       2208015 966592602       10468   71328834
20190915        1       1570168231568259        央视新闻        2       1       2       100     null    41722422        5       null    null    1568211272      0       0       0       2208015 966592602       10468   71328834

when I just has one row data，it succeed.
the content of create table is:

CREATE TABLE `bjh_showx_baoliang_author` (
`base_day` date COMMENT "",
`type` tinyint DEFAULT "1" COMMENT "短期-1,长期-2",
`app_id` varchar(32) DEFAULT "" COMMENT "",
`name` varchar(32) DEFAULT "" COMMENT "",
`level` varchar(32) DEFAULT "" COMMENT "",
`business_line_id` varchar(32) DEFAULT "" COMMENT "",
`status` tinyint DEFAULT "2" COMMENT "1-保量中,2-已释出",
`quota` varchar(32) DEFAULT "" COMMENT "",
`real_flow` varchar(32) DEFAULT "" COMMENT "",
`real_show` varchar(32) DEFAULT "" COMMENT "",
`article_num` varchar(32) DEFAULT "" COMMENT "",
`baoliang_num` varchar(32) DEFAULT "" COMMENT "",
`baoliang_finish_num` varchar(32) DEFAULT "" COMMENT "",
`begin_time` varchar(32) DEFAULT "" COMMENT "",
`end_time` varchar(32) DEFAULT "" COMMENT "",
`fawen_num_bjh` bigint DEFAULT "0" COMMENT "",
`fawen_num_tth` bigint DEFAULT "0" COMMENT "",
`fenfa_num_bjh` bigint DEFAULT "0" COMMENT "",
`fenfa_num_tth` bigint DEFAULT "0" COMMENT "",
`fensi_num_bjh` bigint DEFAULT "0" COMMENT "",
`fensi_num_tth` bigint DEFAULT "0" COMMENT ""
) ENGINE=OLAP
UNIQUE KEY(`base_day`,`type`,`app_id`,`name`,`level`,`business_line_id`,`status`)
DISTRIBUTED BY HASH(`base_day`) BUCKETS 32;

Thank you!

**Comment by imay** [comment]
@DarrenChanChenChi 

Data has been filtered because of some reason. You can visit the URL returned by `SHOW LOAD` command. In this URL, there will be detail error information.
