### ISSUE TITLE
be core down when add partition with buckets=0

### ISSUE THREAD

**Issue by xionglei0** [apache/incubator-doris#1856]
doris support buckets = 0 while execute add partition statment like below:
![image](https://user-images.githubusercontent.com/55084968/65496587-4c485380-deeb-11e9-9d66-cf2a6b2a606e.png)

then the be core down when loading data into the partition:
look at line 590, partition->num_buckets=0 and then core down
![image](https://user-images.githubusercontent.com/55084968/65496994-0d66cd80-deec-11e9-991a-0917b9a0cb2e.png)

core like below:
![image](https://user-images.githubusercontent.com/55084968/65497632-1efca500-deed-11e9-8f0c-ea59ec90defd.png)

so add bucket limit, and not support set buckets=0 while add partition:
![image](https://user-images.githubusercontent.com/55084968/65496735-96313980-deeb-11e9-989e-2a95122798e5.png)

**Comment by xionglei0** [comment]
https://github.com/apache/incubator-doris/pull/1855

**Comment by imay** [comment]
@xionglei0 
We should close issue after PR is merged in master.
