### ISSUE TITLE
complie failed when using direct compilation

### ISSUE THREAD

**Issue by yangzhg** [apache/incubator-doris#1862]
complie failed when using direct compilation in ubuntu 16.04 according to https://doris.apache.org/documentation/cn/installing/compilation.html#centos-ubuntu
because of:
1. the minimum version of gcc is 7.3.0 not 5.3.1
2. the minimum version of cmake is 3.11 not 3.4.3+（building arrow from source requires 3.11 or higher）
3. thirdparty lib libarrow.a and libparquet.a shoud in lib64 not lib dir

**Comment by imay** [comment]
> complie failed when using direct compilation in ubuntu 16.04 according to https://doris.apache.org/documentation/cn/installing/compilation.html#centos-ubuntu
> because of:
> 
> 1. the minimum version of gcc is 7.3.0 not 5.3.1

what's the problem compiling with GCC 5.3.1

> 2. the minimum version of cmake is 3.11 not 3.4.3+（building arrow from source requires 3.11 or higher）
> 3. thirdparty lib libarrow.a and libparquet.a shoud in lib64 not lib dir

**Comment by imay** [comment]
This will affect users using Doris, I think we should close this before we release 0.11.0. @yangzhg can you please give us a PR to fix it ASAP?

**Comment by yangzhg** [comment]
finally i found the reason of why cannot complie in gcc5. becaue of c++11 before gcc 6.1 can't use enum class as unordered_map key, ref https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60970
so it  need to provide a specialization of std::hash
I will fix it today
