### ISSUE TITLE
hll_hash function used in column mapping of broker load does not support nested expression parameter

### ISSUE THREAD

**Issue by yuanlihan** [apache/incubator-doris#1870]
_hll_hash_ function used in column mapping of broker load does not support nested expression parameter.
eg, _hll_hash(coalesce(userid, deviceid))_ will get error:
`ERROR 1064 (HY000): Mapping function args error, arg: coalesce(`userid`, `deviceid`)`

**Comment by EmmyMiao87** [comment]
https://github.com/apache/incubator-doris/pull/1873
