### ISSUE TITLE
direct Compile failed

### ISSUE THREAD

**Issue by fengzhizi2005** [apache/incubator-doris#1893]
/home/doris/incubator-doris-master/be/src/geo/wkt_yacc.y:37 parser name defined to default :"parse"
"/home/doris/incubator-doris-master/be/src/geo/wkt_yacc.y", line 39: junk after `%%' in definition section
"/home/doris/incubator-doris-master/be/src/geo/wkt_yacc.y", line 39: no input grammar
double free or corruption (top)
Aborted (core dumped)
src/geo/CMakeFiles/Geo.dir/build.make:69: recipe for target '/home/doris/incubator-doris-master/gensrc/build/geo/wkt_yacc.y.cpp' failed
make[2]: *** [/home/doris/incubator-doris-master/gensrc/build/geo/wkt_yacc.y.cpp] Error 134
CMakeFiles/Makefile2:581: recipe for target 'src/geo/CMakeFiles/Geo.dir/all' failed
make[1]: *** [src/geo/CMakeFiles/Geo.dir/all] Error 2

os:Ubuntu 18.04.2 LTS (GNU/Linux 5.0.0-29-generic x86_64)
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
cmake version 3.11.0-rc4

**Comment by imay** [comment]
what's the output of `bison --version`

**Comment by fengzhizi2005** [comment]
$ bison --version
bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>

Thank you for your timely reply.

**Comment by imay** [comment]
it works under bison (GNU Bison) 3.0, can you change the bison to this version?

**Comment by fengzhizi2005** [comment]
Thank you. I'll try.

**Comment by fengzhizi2005** [comment]
bison is OK，May I ask another question?

/usr/bin/ld: cannot find -liberty
collect2: error: ld returned 1 exit status
src/tools/CMakeFiles/meta_tool.dir/build.make:171: recipe for target 'src/tools/meta_tool' failed
make[2]: *** [src/tools/meta_tool] Error 1
CMakeFiles/Makefile2:1188: recipe for target 'src/tools/CMakeFiles/meta_tool.dir/all' failed
make[1]: *** [src/tools/CMakeFiles/meta_tool.dir/all] Error 2

**Comment by fengzhizi2005** [comment]
Solutions have been found ，Thanks
sudo apt-get install libiberty-dev
