### ISSUE TITLE
HLL column may store null value

### ISSUE THREAD

**Issue by HangyuanLiu** [apache/incubator-doris#1897]
**Describe the bug**
HLL column may store null value
**To Reproduce**
1、
CREATE TABLE `test_uv_13` (
  `pin_id` bigint(20) NOT NULL COMMENT "",
  `id` bigint(20) NULL COMMENT "",
  `uv1` hll HLL_UNION NOT NULL COMMENT "",
  `uv2` hll HLL_UNION NOT NULL COMMENT ""
) ENGINE=OLAP
AGGREGATE KEY(`pin_id`, `id`)
DISTRIBUTED BY HASH(`pin_id`) BUCKETS 16
PROPERTIES (
"storage_type" = "COLUMN"
)
2、
insert into test_uv_13 (pin_id,id) values(1,2);
3、select hll_union_agg(uv1) from test_uv_13;

This select statement may result in crash

MySQL [test]> desc test_uv_13;
+--------+--------+------+-------+---------+-----------+
| Field  | Type   | Null | Key   | Default | Extra     |
+--------+--------+------+-------+---------+-----------+
| pin_id | BIGINT | No   | true  | N/A     |           |
| id     | BIGINT | Yes  | true  | N/A     |           |
| uv1    | HLL    | No   | false | 0       | HLL_UNION |
| uv2    | HLL    | No   | false | 0       | HLL_UNION |
+--------+--------+------+-------+---------+-----------+

There are several problems with this scenario
**1. Why does the created table have default value in HLL
2. Why can the import succeed when the default value is 0
3. Why be crash when select**

**Comment by imay** [comment]
After I looked into backend code, I found
1. HLL column default column is "0". This should be fixed to no default value for HLL Column
2. InsertStmt consider that this default value can be ingested into Doris. This should be fixed to not allow varchar is casted to HLL column.
3. OLAPTableSink will send string "0" as serialized HLL column, which is invalid. This should be checked and filtered before sending.
4. "0" will serialized into an empty string. This should be serialized to a HLL empty set.
5. empty string is a nullptr when reading HLL column. we will handle nullptr as HLL empty set.
6. nullptr will cause backend process crash.

I will fix backend in following ways.
1. I will add simple check for HLL column when data loading, this can avoid dirty data being ingested in our storage.
2. we will add some branch to let dirty data can be handler without causing backend process crash.

@HangyuanLiu 
Can you improve our process in Frontend?

**Comment by HangyuanLiu** [comment]
@imay OK, I will improve process in Frontend
