### ISSUE TITLE
palo对ANSI SQL支持度

### ISSUE THREAD

**Issue by meolu** [apache/incubator-doris#191]
palo非常惊艳，有想调研应用到某业务线上，特提前了解以下问题：
- ANSI SQL支持到哪个版本？SQL-92、SQL-99、SQL-2003
- 有没有TPC-H/TPC-DS测试结果？

**Comment by cyongli** [comment]
支持SQL-92,TPC-H的内部跑过，但是是在新版本是发布的，过段时间新版本上会一起发布到github上。

**Comment by EmmyMiao87** [comment]
Version 0.11 supports the TPC-H
