### ISSUE TITLE
Think about replacing RE with hyperscan

### ISSUE THREAD

**Issue by imay** [apache/incubator-doris#1929]
According to [this](https://rust-leipzig.github.io/regex/2017/03/28/comparison-of-regex-engines/) article, [hyperscan](https://github.com/intel/hyperscan) has the better performance than RE2. I think we can investigate hyperscan and to see if it can replace RE2 and get better performance.

**Comment by yangzhg** [comment]
HyperScan does not support capturing group  base on issus https://github.com/intel/hyperscan/issues/64
![image](https://user-images.githubusercontent.com/9098473/67270306-fc10e100-f4ea-11e9-9276-176d202b4b8c.png)


in our project most use of RE2::FullMatch  is used to extract the sub-match data from regex string, so we cannot use HyperScan replace RE2
