### ISSUE TITLE
Palo的使用场景问题-对明细数据的查询支持好吗

### ISSUE THREAD

**Issue by peiss** [apache/incubator-doris#198]
目前得到的信息，是PALO通过ROLL UP的预计算+自动路由的方式，实现了对于聚合类数据查询的场景支持的很好，毕竟BASE数据经过聚合之后能大幅减少数据行数；

然而我们有个场景就是想要存储明细数据，请问PALO对于明细数据的支持怎么样？如果使用明细数据存储到PALO，需要注意哪些地方？

**Comment by morningman** [comment]
可以参考这个 https://github.com/baidu/palo/issues/197

**Comment by EmmyMiao87** [comment]
明细模型也有很多业务线在使用，而且在0.12版本之后明细模型上也支持创建物化视图，来通过预聚合的方式加快查询。
