### ISSUE TITLE
Palo导入数据问题

### ISSUE THREAD

**Issue by saga1015** [apache/incubator-doris#199]
Hi，百度Palo的大拿：
咨询下Palo支持导入mysqldump出来的SQL文件吗？
另外如果要持续的从MySQL导出数据到Palo是不是需要自己开发一个同步工具，将语法转换为Palo后写入Palo中？

**Comment by morningman** [comment]
不支持，目前只能将mysql中的数据 dump 成文本文件进行导入

**Comment by saga1015** [comment]
@morningman 大神，如果我用canal+mq的方式做增量导入palo是否可以？

**Comment by morningman** [comment]
目前我们提供了流式导入的接口，外层需要适配。详细情况可以见wiki

**Comment by clay4444** [comment]
@morningman  流式导入的接口指的是java  api的接口？？ wiki地址可以发下吗？？

**Comment by clay4444** [comment]
@saga1015   我也在做canal+mq的方式做增量导入，请教一下，你们用的哪种方式导入的呀

**Comment by HangyuanLiu** [comment]
> @saga1015 我也在做canal+mq的方式做增量导入，请教一下，你们用的哪种方式导入的呀

有kafka load ,可直接从kafka 中读取数据：http://doris.incubator.apache.org/documentation/cn/administrator-guide/load-data/routine-load-manual.html

> @morningman 流式导入的接口指的是java api的接口？？ wiki地址可以发下吗？？

https://github.com/apache/incubator-doris/tree/master/samples/stream_load/java
