### ISSUE TITLE
[Proposal] Limit the memory usage of Compaction

### ISSUE THREAD

**Issue by morningman** [apache/incubator-doris#2016]
With the widespread use of the new load framework, existing compaction strategies are no longer work in some scenarios. This document focuses on the problems that the new load framework brings to the compaction logic and how to improve it.

## Problem

In the new load framework, the load data forms a serial of `Memtables` in memory. When the size of a memtable reaches the threshold (default is 100MB), it will be written to the disk to form a `Segment`. A batch of load is corresponding ti a `Version`. When a batch of loaded data is relatively large, or a row of a table is large, a batch of load may generate thousands of segments.

In the compaction logic, at least one version is selected for one compaction. Compaction is an external sorting that will open a `RowBlock` for each segment, with 1024 rows per RowBlock. So a RowBlock occupies a memory size of (1024 * row size).

Assuming that a Compaction has 1000 Segments and each row is 4K in size, RowBlock will take up 4G memory. When multiple Compactions are running at the same time, the system OOM may be caused.

## Solution

This proposal is to ensure that Compaction can run stably with less memory by estimating and limiting the amount of memory used by Compaction. This work is divided into the following three steps.

### Compaction ratio statistic

To estimate the amount of memory used by a Compaction, it is mainly to estimate the size of a row in memory. We can simply use the ratio of the size of a memtable in memory to the size of file it is written on disk as the compaction ratio. With this ratio, the size of the data file on the disk, and the number of rows in file, we can calculate the approximate occupancy of a single row of data in memory.

### Supported compaction within a version

Currently only Compaction with at least one version is supported. And if there are too many Segments in a single version, it still consumes a lot of memory. So we need to support compaction with a subset of segments with a single version. 

### Limiting Compaction memory usage

With the previous two steps, it has been possible to estimate and limit the memory usage of a single Compaction. Finally, we need an overall limit to ensure that the memory overhead can be within a reasonable range when multiple Compactions are running at the same time.

**Comment by imay** [comment]
# Compaction ratio statistic
> To estimate the amount of memory used by a Compaction, it is mainly to estimate the size of a row in memory. We can simply use the ratio of the size of a memtable in memory to the size of file it is written on disk as the compaction ratio. With this ratio, the size of the data file on the disk, and the number of rows in file, we can calculate the approximate occupancy of a single row of data in memory.
> 

Why not estimate average row length by computing ratio of write bytes to number of rows when generating a rowset. And this value can be recorded in rowset meta.

> ### Supported compaction within a version
> Currently only Compaction with at least one version is supported. And if there are too many Segments in a single version, it still consumes a lot of memory. So we need to support compaction with a subset of segments with a single version.
> 

It will be better to merge enough segments into a bigger segment when loading other than leaving it when compaction. 1. This is simple for compaction logic; 2. this is good for read. Even if we have 1000 segments for a rowset, it will lead to terrible read performance.

**Comment by morningman** [comment]
> Why not estimate average row length by computing ratio of write bytes to number of rows when generating a rowset. And this value can be recorded in rowset meta.

Do you mean the `memtable size / num of rows`?

**Comment by morningman** [comment]
> It will be better to merge enough segments into a bigger segment when loading other than leaving it when compaction

I am afraid it will increase the mem consumption of a load process. And the concurrence of loading is much larger than compaction. If doing this when loading, we need to rethink about how to limit the memory of loading.

**Comment by imay** [comment]
> > Why not estimate average row length by computing ratio of write bytes to number of rows when generating a rowset. And this value can be recorded in rowset meta.
> 
> Do you mean the `memtable size / num of rows`?

No. Now when write a rowset, RowsetWriter will estimate how how many bytes to decide if it will generate a segment. We can use this value divided by row count as average row size.


> I am afraid it will increase the mem consumption of a load process. And the concurrence of loading is much larger than compaction. If doing this when loading, we need to rethink about how to limit the memory of loading.

what I want to do has no effect for current load process. It will be done before we add this rowset to StorageEngine. If we found there are too many number of rowsets, we can try to merge some of them to a bigger rowset. Actually we can do it for all load operation, because it will improve our read performance. 

Even though we can do this, but I think it is not very urgent. For you example, when a segment has 1000 segment, the rowset size will be 100GB(1000 * 100MB), it will lead to other serious problem. Such as tablet balance, read performance. So I think for this proposal, you can leave this case aside.

**Comment by gaodayue** [comment]
> what I want to do has no effect for current load process. It will be done before we add this rowset to StorageEngine. If we found there are too many number of rowsets, we can try to merge some of them to a bigger rowset. Actually we can do it for all load operation, because it will improve our read performance.

I think the motivation for compaction within a rowset is to reduce the number of overlapped segments and improve query performance.  However when the number of segments is large, single round of compaction would consume too much memory. So we need to decide how many number of segments to compact at a time based on estimated RowBlock size and available memory.

My question is the previous compaction strategy will generate a rowset with a new version (like 0-6) to replace input rowsets with overlapped version, but when doing compaction within a rowset, you end up with two rowset with the same version. Is it a problem? And if it is, how do you plan to solve it?

**Comment by imay** [comment]
> > what I want to do has no effect for current load process. It will be done before we add this rowset to StorageEngine. If we found there are too many number of rowsets, we can try to merge some of them to a bigger rowset. Actually we can do it for all load operation, because it will improve our read performance.
> 
> I think the motivation for compaction within a rowset is to reduce the number of overlapped segments and improve query performance. However when the number of segments is large, single round of compaction would consume too much memory. So we need to decide how many number of segments to compact at a time based on estimated RowBlock size and available memory.
> 
> My question is the previous compaction strategy will generate a rowset with a new version (like 0-6) to replace input rowsets with overlapped version, but when doing compaction within a rowset, you end up with two rowset with the same version. Is it a problem? And if it is, how do you plan to solve it?

In my point of view, we should create another type of operation to generate a new rowset from rowset with many segments other than compaction. And this operation's input and output are segments, then this will works fine, because Doris already have many segments which are not sorted in one rowset.

**Comment by morningman** [comment]
After the research, most of the memory overhead was concentrated on opening the segments(RowBlock) and creating the Readers(StreamBuffer). And this part of the memory overhead is strongly related to the number of columns of data and the column type. And we can't accurately estimate the size of a row of data in memory at this time, so we can't estimate the memory required for a compaction.

Compaction within a rowset is a way to reduce the memory, but the root cause still exists, which is: How many segments should we selected for a compaction by given certain amount of memory. And this requires the statistic of size of a row of data in memory.

I will leave this Issue opened and try to resolve it sometimes later.
