### ISSUE TITLE
when the tdigest compression param for pencentile_approx is small，such as 1-100，the result will go to jump

### ISSUE THREAD

**Issue by manannan2017** [apache/incubator-doris#2024]
1、table data， k4 BIGINT：
![image](https://user-images.githubusercontent.com/33174388/67188724-87bd3b80-f41f-11e9-9c9f-dd0f6ca43817.png)

2、when the tdigest compression param for pencentile_approx is small，such as 1-100，the result will go to jump.
![image](https://user-images.githubusercontent.com/33174388/67188690-77a55c00-f41f-11e9-96b9-b9f06a6d2ae7.png)

![image](https://user-images.githubusercontent.com/33174388/67188663-68261300-f41f-11e9-93c3-f0c2b8fa41e8.png)

**Comment by shengyunyao** [comment]
I will fix this by limiting the compression param to [2048, 10000].
