### ISSUE TITLE
unexpected UDF deduction

### ISSUE THREAD

**Issue by KevinLinGit** [apache/incubator-doris#2027]
**Describe the bug**
I have two udaf functions as follow:

- STRING  topk(STRING, INT, INT, BIGINT)
- STRING  topk(STRING, INT, INT, DOUBLE)

Then, just explain sql "explain select topk(province_, 0, 5, 1) from test", you will get something as follow:
![image](https://user-images.githubusercontent.com/6179135/67253295-820c3800-f4a9-11e9-86d4-9b8ba25bc4bc.png)

**Comment by EmmyMiao87** [comment]
So, the expect answer is String topk(String,int,int,bigint) ?

**Comment by KevinLinGit** [comment]
the expect answer is String topk(String,int,int,bigint). YES

**Comment by KevinLinGit** [comment]
The other case,  two udaf functions as follow:
percentile(BIGINT,DOUBLE)
percentile(DOUBLE,DOUBLE)
Then sql like percentile(0.1, 0.5) will use percentile(BIGINT,DOUBLE), but percentile(DOUBLE,DOUBLE) is expected
