### ISSUE TITLE
Make License of gutil more clear

### ISSUE THREAD

**Issue by imay** [apache/incubator-doris#2030]
The license for some of the files copied from Apache Impala particularly in be/src/gutil are a little unclear. Following the way that Impala does its License might be an improvement.

**Comment by yangzhg** [comment]
be/src/gutil/utf/LICENSE and be/src/gutil/utf/rune.c  under a personal without fee is granted, so they  are not in CATEGORY X, and we put the license in out source code.
be/src/util/coding.cpp and be/src/util/coding.cpp are both under the GPLv2 and Apache 2.0 License, so  they are not in CATEGORY X
our rocksdb version is  5.14.2  and it under Apache 2.0 License and LevelDB License
