### ISSUE TITLE
Segment V2 core dump when schema change

### ISSUE THREAD

**Issue by zhangy5** [apache/incubator-doris#2038]
**Describe the bug**
Segment V2 core dump when schema change

**core file**
#0  doris::segment_v2::ColumnReader::read_page (this=0xcedf860, pp=..., stats=0x0, handle=handle@entry=0xcedf5f0)
    at /home/palo-ci/CI/workspace/doris_local_qacitool_compile/core/be/src/olap/rowset/segment_v2/column_reader.cpp:114
#1  0x00000000015acdd7 in doris::segment_v2::FileColumnIterator::_read_page (this=this@entry=0xc4217a0, iter=..., page=0xcedf5e0)
    at /home/palo-ci/CI/workspace/doris_local_qacitool_compile/core/be/src/olap/rowset/segment_v2/column_reader.cpp:426
#2  0x00000000015ad915 in doris::segment_v2::FileColumnIterator::seek_to_ordinal (this=0xc4217a0, rid=0)
    at /home/palo-ci/CI/workspace/doris_local_qacitool_compile/core/be/src/olap/rowset/segment_v2/column_reader.cpp:313
#3  0x0000000001579f91 in doris::segment_v2::SegmentIterator::_seek_columns (this=this@entry=0xbdb8ea0, column_ids=std::vector of length 11, capacity 11 = {...}, pos=0)
    at /home/palo-ci/CI/workspace/doris_local_qacitool_compile/core/be/src/olap/rowset/segment_v2/segment_iterator.cpp:310
#4  0x000000000157a131 in doris::segment_v2::SegmentIterator::_init_column_iterators (this=this@entry=0xbdb8ea0)
    at /home/palo-ci/CI/workspace/doris_local_qacitool_compile/core/be/src/olap/rowset/segment_v2/segment_iterator.cpp:195
#5  0x000000000157cbaf in doris::segment_v2::SegmentIterator::_init (this=this@entry=0xbdb8ea0)
    at /home/palo-ci/CI/workspace/doris_local_qacitool_compile/core/be/src/olap/rowset/segment_v2/segment_iterator.cpp:61
#6  0x000000000157d03f in doris::segment_v2::SegmentIterator::next_batch (this=0xbdb8ea0, block=0xb3878c0)
    at /home/palo-ci/CI/workspace/doris_local_qacitool_compile/core/be/src/olap/rowset/segment_v2/segment_iterator.cpp:318
#7  0x0000000000f4556b in doris::BetaRowsetReader::next_block (this=0xa4b8380, block=0x7f9b0c9180a8)
    at /home/palo-ci/CI/workspace/doris_local_qacitool_compile/core/be/src/olap/rowset/beta_rowset_reader.cpp:113
#8  0x000000000155d64d in doris::SchemaChangeDirectly::process (this=0xe4ef650, rowset_reader=std::shared_ptr (count 3, weak 0) 0xa4b8380, rowset_writer=0xdc6f0e0, new_tablet=
    std::shared_ptr (count 5, weak 1) 0xc31fb10, base_tablet=...) at /home/palo-ci/CI/workspace/doris_local_qacitool_compile/core/be/src/olap/schema_change.cpp:769
#9  0x0000000001564b01 in doris::SchemaChangeHandler::_convert_historical_rowsets (sc_params=...)
    at /home/palo-ci/CI/workspace/doris_local_qacitool_compile/core/be/src/olap/schema_change.cpp:1682
#10 0x0000000001566f69 in doris::SchemaChangeHandler::_do_process_alter_tablet_v2 (this=this@entry=0x7f9b0c9185c0, request=...)
    at /home/palo-ci/CI/workspace/doris_local_qacitool_compile/core/be/src/olap/schema_change.cpp:1337
#11 0x0000000001568006 in doris::SchemaChangeHandler::process_alter_tablet_v2 (this=this@entry=0x7f9b0c9185c0, request=...)
    at /home/palo-ci/CI/workspace/doris_local_qacitool_compile/core/be/src/olap/schema_change.cpp:1162
#12 0x000000000159aca9 in doris::EngineAlterTabletTask::execute (this=0x7f9b0c918800)
    at /home/palo-ci/CI/workspace/doris_local_qacitool_compile/core/be/src/olap/task/engine_alter_tablet_task.cpp:39
#13 0x0000000000e5ac95 in doris::StorageEngine::execute_task (this=0x5860580, task=task@entry=0x7f9b0c918800)
    at /home/palo-ci/CI/workspace/doris_local_qacitool_compile/core/be/src/olap/storage_engine.cpp:928
#14 0x00000000013b1391 in doris::TaskWorkerPool::_alter_tablet (this=this@entry=0x742e120, worker_pool_this=worker_pool_this@entry=0x742e120, agent_task_req=...,
    signature=signature@entry=17242, task_type=task_type@entry=doris::TTaskType::ALTER, finish_task_request=finish_task_request@entry=0x7f9b0c9188d0)
    at /home/palo-ci/CI/workspace/doris_local_qacitool_compile/core/be/src/agent/task_worker_pool.cpp:619
#15 0x00000000013bb46a in doris::TaskWorkerPool::_alter_tablet_worker_thread_callback (arg_this=0x742e120)
    at /home/palo-ci/CI/workspace/doris_local_qacitool_compile/core/be/src/agent/task_worker_pool.cpp:567
#16 0x00007f9b8dd111c3 in start_thread () from /opt/compiler/gcc-4.8.2/lib64/libpthread.so.0
#17 0x00007f9b8e00e12d in clone () from /opt/compiler/gcc-4.8.2/lib64/libc.so.6

**Comment by wangbo** [comment]
Is there a way to reproduce the case stablely?
Such as create a arbitrary table and doing a arbitrary alter operation will cause, or just some specific table desc and specific alter operation

**Comment by kangpinghuang** [comment]
I have locate the bug. I will fix it.

**Comment by zhangy5** [comment]
Fixed
