### ISSUE TITLE
sql count 统计值为0时，结果返回 Empty set 

### ISSUE THREAD

**Issue by jinyishu** [apache/incubator-doris#2059]
现象：
mysql> select count(1) from test2 a  inner join test b  on a.did = b.did group by a.did;
Empty set (1 min 27.16 sec)
期望：返回值为 0

**Comment by xy720** [comment]
There is a problem in this sql statement. When the result set of table a inner join table b is empty, it is not reasonable to group by a.did. You should remove the **group by a.did** clause then the return value is 0.
