### ISSUE TITLE
load支持parquet 文件数据导入

### ISSUE THREAD

**Issue by melin** [apache/incubator-doris#207]
hive 表中存储数据为parquet 格式，建议load支持parquet 文件数据导入数据

**Comment by yanchaoguo** [comment]
> hive 表中存储数据为parquet 格式，建议load支持parquet 文件数据导入数据

+1 请兼容hadoop生态

**Comment by imay** [comment]
@yanchaoguo 

parquet格式已经在支持中了。

#1173 这个patch已经处于基本可用状态，着急的可以先试试
