### ISSUE TITLE
删除分区之后，紧接着执行创建分区的命令，但是不导入数据，顺序连续执行3次这样的操作，有没有可能出现第3次创建分区的命令早于第1次创建分区的命令先完成 (maybe not a bug)

### ISSUE THREAD

**Issue by pangjianfei** [apache/incubator-doris#2070]
**Describe the bug**
我在使用palo的时候，有一个流程是：我会获取最近一周的需要导入palo的数据，在palo中的分区是按照天为单位，我在执行导入数据的时候，会循环执行先删除分区，再创建分区（分区是从小到大进行操作），最后执行load数据的命令，但是出现了异常，就是创建分区的时候出现了分区的区间范围在已经存在的分区区间范围内。

**推测**
在官方文档中对drop partition命令有说明：drop partition 删除分区命令是同步命令，执行成功即生效。而后台数据真正删除的时间可能会延迟10分钟左右。
所以我想请教2个问题：

1. 删除分区之后，紧接着执行创建分区的命令，但是不导入数据，顺序连续执行3次这样的操作，有没有可能出现第3次创建分区的命令早于第1次创建分区的命令先完成？

2. 创建分区是不是必须要在之前已经存在的分区的后台数据完全删除的情况下才能真正创建成功？

以上，望得到答复，谢谢

**Comment by imay** [comment]
> **推测**
> 在官方文档中对drop partition命令有说明：drop partition 删除分区命令是同步命令，执行成功即生效。而后台数据真正删除的时间可能会延迟10分钟左右。
> 所以我想请教2个问题：
> 
>     1. 删除分区之后，紧接着执行创建分区的命令，但是不导入数据，顺序连续执行3次这样的操作，有没有可能出现第3次创建分区的命令早于第1次创建分区的命令先完成？
> 

如果你是用同一个session执行的，那么一定是按照顺序执行的，先执行完一个，再执行下一个。不会出现你说的这种。

>     2. 创建分区是不是必须要在之前已经存在的分区的后台数据完全删除的情况下才能真正创建成功？
> 

不会，即使后台数据没删除完毕，也不影响创建分区成功。会为新的分区创建tablet，与老的数据没有关系

**Comment by pangjianfei** [comment]
> 如果你是用同一个session执行的，那么一定是按照顺序执行的，先执行完一个，再执行下一个。不会出现你说的这种。

还有一点点疑惑，如果不是同一个session呢？还有同一台机器连续curl n次url算同一个session吗？

**Comment by imay** [comment]
> > 如果你是用同一个session执行的，那么一定是按照顺序执行的，先执行完一个，再执行下一个。不会出现你说的这种。
> 
> 还有一点点疑惑，如果不是同一个session呢？还有同一台机器连续curl n次url算同一个session吗？

如果不是一个session，那么你怎么能够定义先后呢？一个session是说使用客户端链接上来，到这个客户端退出之前。

**Comment by pangjianfei** [comment]
👌，明白了多谢
