### ISSUE TITLE
【predicate push down】When there is an operation, predicate push down fails

### ISSUE THREAD

**Issue by manannan2017** [apache/incubator-doris#2095]
1、【When there is an operation, predicate push down fails】
1> select s.k1, s.k2, s.ss from (select k1, k2, sum(k2) over (partition by k1) as ss from baseall)s  where s.k1 + s.k2 > 10 group by s.k1, s.k2, s.ss;---no push down
2> select k1, k2, sum(k2) over (partition by k1) as ss from baseall  where k1 + k2 > 10 ;---ok push down

2、【Subquery ？】
1> select * from (select s.k1, s.k3, s.ss from (select k1, k3, sum(k2) over (partition by k3) as ss from baseall)s  where s.k3 > 1 group by s.k1, s.k3, s.ss)s2 where s2.k1 > 10 and s2.k3 > 8;
2> select * from (select s.k1, s.k3, s.ss from (select k1, k3, sum(k2) over (partition by k1) as ss from baseall)s  where s.k3 > 1 group by s.k1, s.k3, s.ss)s2 where s2.k1 > 10 and s2.k3 > 8;

**Comment by EmmyMiao87** [comment]
Answer1: 
The predicate in query 1 `s.k1 + s.k2 > 10 ` could not be pushed down. The slot k2 of predicate is not a group by slot. 
The predicate in query 2 `s.k1 + s.k2 > 10 ` do not need to be pushed down. The predicate in where is in front of the window function according to sql grammar.

Answer2:
Only the predicate which slot is related to group by could be push down. 
For the query1: the group by slot is k3 in window function. So the predicates `s2.k3 > 8` and `s.k3 > 1` could be pushed down to the tuple named ss.
For the query2: the group by slot is k1 in window function. So the predicate `s2.k1 > 10` could be pushed down to the tuple hamed ss while the predicates `s2.k3 > 8` and `s.k3 > 1` belongs to the tuple named s
