### ISSUE TITLE
bazel support?

### ISSUE THREAD

**Issue by zhouhaibing089** [apache/incubator-doris#2099]
**Is your feature request related to a problem? Please describe.**

This project consists of java/cpp/python/bash, it looks like that bazel is good fit as the build system for this project.

**Describe the solution you'd like**

Bazel is fast, and serves as the unified build system. (the more tools needed, the harder to manage developer productivity). Without too much investigation, it seems that cmake and maven can be avoided.

Just a suggestion by the way. :)

**Comment by morningman** [comment]
Good suggestion. We may look into it later
