### ISSUE TITLE
postman stream load failed

### ISSUE THREAD

**Issue by HiwayChe** [apache/incubator-doris#2108]
I have read this manual: https://github.com/apache/incubator-doris/blob/master/docs/documentation/cn/administrator-guide/load-data/stream-load-manual.md, it says doris support loading data by stream load using http,  in this manual it use `curl`, I tried and succeed, but it failed in postman, here is my `curl` command and postman configuration.

`curl` command:
![image](https://user-images.githubusercontent.com/5837440/67919923-4d9d2800-fbdd-11e9-880e-9aa6c1ed91cd.png)

postman configuration:
![image](https://user-images.githubusercontent.com/5837440/67919975-71f90480-fbdd-11e9-8af6-a6c92bb7cb63.png)
![image](https://user-images.githubusercontent.com/5837440/67919982-77eee580-fbdd-11e9-8c62-d97495d648c5.png)
![image](https://user-images.githubusercontent.com/5837440/67919989-7de4c680-fbdd-11e9-8399-440a149a273c.png)

As you see, it failed in postman, doris server return 501(Not Implemented), do I miss something?

**Comment by imay** [comment]
What HTTP method do you specify? StreamLoad should be under HTTP **PUT** method

**Comment by HiwayChe** [comment]
I use POST in the above screenshot,  change to PUT, it returns 200 with  `{"status":"FAILED","msg":"There is no 100-continue header"}`
![image](https://user-images.githubusercontent.com/5837440/67922907-159ae280-fbe7-11e9-81a4-428001f0dcb4.png)

**Comment by imay** [comment]
You should add a header `Expect: 100-continue`
