### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [apache/incubator-doris#211]
Would you like to [wrap any pointer data members](https://github.com/baidu/palo/blob/19997510a69c24c22bd2e59e213ed8531e3058c7/be/src/agent/task_worker_pool.cpp#L78 "Update candidate: TaskWorkerPool class") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by morningman** [comment]
Yes, we already change some ptr to smart pointer like shared_ptr or unique_ptr.
Just close this issue.

**Comment by elfring** [comment]
How are the chances to [fix the class “TaskWorkerPool”](https://github.com/apache/incubator-doris/blob/a08170fd501c9a41aa0ce5a7811bbf2f64483308/be/src/agent/task_worker_pool.cpp#L91 "Update candidate")?
