### ISSUE TITLE
bitmap_union_int cause 'be' node hang

### ISSUE THREAD

**Issue by XShun** [apache/incubator-doris#2115]
When I use bitmap_union_int() to replace count(distinct ) for a test, I found that it would cause be nodes hang. So, how can I slove this problem?
ErrMsg: 
    > 1064 - there is no scanNode Backend
SQL：
    select bitmap_union_int(id) from table1;
The type of `id` is int, and rows of table1 is about 70 million, and the model of table is Agg.
Looking forward to reply! thx!

**Comment by XShun** [comment]
Yes, all Backend are down.
There is nothing output in the be.WARAING, and this is be.INFO of one of Backends: 
![beINFO](https://user-images.githubusercontent.com/34292183/67938331-3aed1800-fc0a-11e9-9665-4e870cb8b727.png)
I had tried to trun up the `exec_mem_limit` to 8GB, but it doesn't work.
This is be.out of one of Backends: 
![beout](https://user-images.githubusercontent.com/34292183/67938393-56582300-fc0a-11e9-954c-f7168de259c7.png)

**Comment by XShun** [comment]
@kangkaisen This is fe.warn.log:
![feWarnLog](https://user-images.githubusercontent.com/34292183/67939673-062e9000-fc0d-11e9-8871-d3ec497e5d46.png)

**Comment by kangkaisen** [comment]
@XShun Hi，What's the last commit of your code?

Please give me the create table sql and some raw data(dozens of line is enough)，thanks.

I will try reproducing and solving this issue.

**Comment by kangkaisen** [comment]
@XShun Hi. How do you load the data to table1?
All bitmap_union_int query will make BE down,  or only `select bitmap_union_int(id) from table1` will make BE down ;

**Comment by XShun** [comment]
@kangkaisen Hi, I just saw your message. I also met the 'be could not start' problem yesterday, so I pulled the latest code this morning and rebuilt it. I load data to table1 through `load label ... with broker ...` , and the source data is on the HDFS. All bitmap_union_int query will make BE down. 
Here are the create table sql and some rows:
`CREATE TABLE table1 (
  k1 date NOT NULL COMMENT "key1",
  k2 varchar(20) NOT NULL COMMENT "key2",
  k3 varchar(100) NOT NULL COMMENT "key3",
  k4 int(11) NOT NULL COMMENT "key4",
  id int(11) NOT NULL COMMENT "id",
  flag bigint(20) SUM NOT NULL DEFAULT "1" COMMENT "flag"
) ENGINE=OLAP
AGGREGATE KEY(k1, k2, k3, k4, id)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`) BUCKETS 6
PROPERTIES (
"storage_type" = "COLUMN"
);`
Rows:
`2018-01-01,主键二,主键三,10000001,1000001,1
2018-01-02,主键二,主键三,10000002,1000002,1
2018-01-03,主键二,主键三,10000001,1000003,2`
The last column is used to calculate `count(1)`.
THX!

**Comment by kangkaisen** [comment]
@XShun I just tried reproducing this issue, but bitmap_union_int work well. 
So I want to be confirm again,  If you only load dozens of line raw data to `table1`, the `select bitmap_union_int(id) from table1` will make BE down?

**Comment by XShun** [comment]
@kangkaisen I just insert into `table2` 10 rows from `table1`, the structure of `table2` is the
same to  `table1`. When use `bitmap_union_int` function, it made BE down. Then I tried the other three bitmap functions, `TO_BITMAP` and `BITMAP_COUNT` functions worked well, but `BITMAP_UNION` function also made BE down.

**Comment by imay** [comment]
> @kangkaisen I just insert into `table2` 10 rows from `table1`, the structure of `table2` is the
> same to `table1`. When use `bitmap_union_int` function, it made BE down. Then I tried the other three bitmap functions, `TO_BITMAP` and `BITMAP_COUNT` functions worked well, but `BITMAP_UNION` function also made BE down.

@XShun

I have tried your case, and be works fine. Can you give more detail about your test? Your Query? And you can create a table with only one column `id`, then you retry your query on it to see if BE will crash

**Comment by XShun** [comment]
@imay Only one column `id` also occurred the problem. Maybe the problem caused by my BE environment, I will rebuild Doris cluster for a try. THX!

**Comment by kangkaisen** [comment]
> @imay Only one column `id` also occurred the problem. Maybe the problem caused by my BE environment, I will rebuild Doris cluster for a try. THX!

@XShun  Hi, If this issue still exist. please generate the core dump file and show me this `bt full`stack.

**Comment by XShun** [comment]
> > @imay Only one column `id` also occurred the problem. Maybe the problem caused by my BE environment, I will rebuild Doris cluster for a try. THX!
> 
> @XShun Hi, If this issue still exist. please generate the core dump file and show me this `bt full`stack.

OK

**Comment by XShun** [comment]
> > @imay Only one column `id` also occurred the problem. Maybe the problem caused by my BE environment, I will rebuild Doris cluster for a try. THX!
> 
> @XShun Hi, If this issue still exist. please generate the core dump file and show me this `bt full`stack.

@kangkaisen OK
