### ISSUE TITLE
[PROPOSAL] Supporting aggregate method of REPLACE_IF_NOT_NULL

### ISSUE THREAD

**Issue by imay** [apache/incubator-doris#2117]
## Motivation

Many users have proposed a usage scenario to Doris. There are multiple data sources in a table. When a data source needs to be imported, it is often unable to obtain all the columns' value. However Doris requires that all columns should be included in one import, in this way, in order to import data into Doris, users can only join the load data with already existed data in Doris to generate all columns data, and then load it into Doris. Or user should keep a copy of data other place, and generate data with all columns when ETL stage. This makes user very cumbersome and inefficient.

So in order to facilitate data import for users in this case, I intend to support a new aggregate method REPLACE_IF_NOT_NULL. In this way, users can change some columns' value without changing the other columns' value.

## Design

> original value: value of column already in Doris
> added value: newly added value from load data
> new value: after apply added value, the value of column in Doris

REPLACE_IF_NOT_NULL: the semantics of this aggregation method is to replace the origin value if and only if the added value is a non-NULL value.

We currently support the aggregate method of REPLACE. The semantics of REPLACE is that no matter what the added value is, the original value will be replaced by the added value. Then REPLACE_IF_NOT_NULL is to replace the original value if and only if the added value is not NULL. If the added value is NULL, the original value will be maintained with no change. When the user imports data, he can use NULL to represent the column with no value, then the original value can be still retained.

The following two tables compare the difference between REPLACE and REPLACE_IF_NOT_NULL behavior

REPLACE_IF_NOT_NULL: 

| original value | added value | new value |
| --- | --- | --- |
| NULL | NULL | null |
| NULL | 1 | 1 |
| 1 | NULL | 1 |
| 1 | 2 | 2 |

REPLACE:

| original value | added value | new value |
| --- | --- | --- |
| NULL | NULL | NULL |
| NULL | 1 | 1 |
| 1 | NULL | NULL |
| 1 | 2 | 2 |

The work does not require too much change.

1. Add a new aggregation method in Frontend. Columns of this aggregation type can be created when tables are created.
2. Support the corresponding operators of this aggregation method on the engine side.

## Defect

Besides both the orignal value and added value are NULL, there is no way to make a value of column NULL. So once a user sets a column value to a non-NULL value, there is no way to change the value to NULL.

**Comment by imay** [comment]
<img width="468" alt="图片" src="https://user-images.githubusercontent.com/1249159/68013235-5bc77300-fcc7-11e9-8ca6-66d54ddd389b.png">

Above picture is a demo.

**Comment by kangkaisen** [comment]
could we use `replace(true)`, `replace(false)` replace `replace`, `replace_if_not_null` ?

**Comment by imay** [comment]
> could we use `replace(true)`, `replace(false)` replace `replace`, `replace_if_not_null` ?

what do the `ture` and `false` in bracket mean?

**Comment by kangkaisen** [comment]
> > could we use `replace(true)`, `replace(false)` replace `replace`, `replace_if_not_null` ?
> 
> what do the `ture` and `false` in bracket mean?

`ture` and `false` means when the new value is `null`, whether we will use `null` replace the old value.

**Comment by kangkaisen** [comment]
besides `replace_if_not_null`, I think there should also have `replace_if_larger`,  `replace_if_lower`. So I think we should support  replace(args),  the args type and meaning could further discuss.

**Comment by imay** [comment]
> besides `replace_if_not_null`, I think there should also have `replace_if_larger`, `replace_if_lower`. So I think we should support replace(args), the args type and meaning could further discuss.

This is a good suggestion. I think `replace_if_larger` equals `max` method and `replace_if_lower` equals `min` method?

**Comment by kangkaisen** [comment]
> > besides `replace_if_not_null`, I think there should also have `replace_if_larger`, `replace_if_lower`. So I think we should support replace(args), the args type and meaning could further discuss.
> 
> This is a good suggestion. I think `replace_if_larger` equals `max` method and `replace_if_lower` equals `min` method?

Yes. I just want to illustrate the replace condition maybe various.

**Comment by imay** [comment]
I think the comman way is that we support a `merge(original_value, added_value)` function. 

All aggregate function can be included in this funcion

`sum: orignal + added`
`min: added < original ? added : original`
`max: added > original ? added : original`
`replace: added`
`replace_if_not_null: added is null ? original : added`

If we do this, I think it will a very very huge work to change already exist work. And I think we can support `replace_if_not_null` first, if we change later, we can unify this to that one.

The reason why I choose `replace_if_not_null` is more direct.

**Comment by kangkaisen** [comment]
OK.

**Comment by alenfive** [comment]
1. REPLACE_IF_NOT_NULL 很好的解决了聚合模式下的末次的需求
2. 现在我还有一个首次的需求，如用户首次访问了哪篇文章,期待有REPALCE_IF_NULL 的函数，对库中已经存在的数据进行判断，如果为NULL,则替换
3. min函数能够获得最早的时间，但无法对文本类型作首次判断，或者你有更好的建议

首次访问[最早的一条记录]的需求在数据分析场景中蛮常见和重要的
