### ISSUE TITLE
If the parameter of ifnull is datetime, return wrong type

### ISSUE THREAD

**Issue by zhangy5** [apache/incubator-doris#2123]
**Describe the bug**
If the parameter of ifnull is datetime, return wrong type.

**To Reproduce**
query is: select ifnull(b.k10, cast("2017-06-06" as date)) k, b.k1 from baseall a left join bigtable b on a.k1 = b.k1 + 5 order by k
k returns a long type as  follows.

![image](https://user-images.githubusercontent.com/10826066/68102607-76d7f400-ff0e-11e9-88d7-a750c96ebad0.png)

table schema:
CREATE TABLE `baseall` (
  `k1` tinyint(4) NOT NULL COMMENT "",
  `k2` smallint(6) NOT NULL COMMENT "",
  `k3` int(11) NOT NULL COMMENT "",
  `k4` bigint(20) NOT NULL COMMENT "",
  `k5` decimal(9, 3) NOT NULL COMMENT "",
  `k6` char(5) NOT NULL COMMENT "",
  `k10` date NOT NULL COMMENT "",
  `k11` datetime NOT NULL COMMENT "",
  `k7` varchar(20) NOT NULL COMMENT "",
  `k8` double MAX NOT NULL COMMENT "",
  `k9` float SUM NOT NULL COMMENT ""
) ENGINE=OLAP
AGGREGATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`, `k6`, `k10`, `k11`, `k7`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`) BUCKETS 5
PROPERTIES (
"storage_type" = "COLUMN"
);
baseall table is same with bigtable.

**Expected behavior**
expected result:
![image](https://user-images.githubusercontent.com/10826066/68102633-953def80-ff0e-11e9-8305-035ccf4c8c3b.png)

**Comment by Seaven** [comment]
I'm following the question

**Comment by Seaven** [comment]
There are several reasons for the question：
1.The ifnull method does not support check for date type
2.If the parameter type of ifnull method is different, maybe will return unpredictable result, such as ifnull(b.k10, b.k9), ifnull(b.k10, b.k11).....

**Comment by Seaven** [comment]
The reasons for the question is IFFULL syntax does not support date type. 

And IFNULL sytax maybe will return unpredictable result if the parameters type is different, such as ifnull(b.k10, b.k9) return (2017-06-06), ifnull(b.k10, b.k1) return (20170606). The reason is Implicaity-Cast method find a unsuitable superclass of two different types, maybe we should optimize the Implicaity-Cast method later.

**Comment by zhangy5** [comment]
it's ok now
