### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [apache/incubator-doris#213]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [BrokerScanner::open_file_reader](https://github.com/baidu/palo/blob/6486be64c319fe0beb8c6b4430c1662de54f182e/be/src/exec/broker_scanner.cpp#L229 "BrokerScanner::open_file_reader function")
- [DppWriter](https://github.com/baidu/palo/blob/6486be64c319fe0beb8c6b4430c1662de54f182e/be/src/runtime/dpp_writer.cpp#L52 "Destructor for DppWriter")
- [ReloadTabletAction](https://github.com/baidu/palo/blob/19997510a69c24c22bd2e59e213ed8531e3058c7/be/src/http/action/reload_tablet_action.h#L33 "Destructor for ReloadTabletAction")

**Comment by elfring** [comment]
How do you think about to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by imay** [comment]
> How do you think about to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html)?

It is a good idea. Could you please provide a PR to fix it?
