### ISSUE TITLE
Cross join with <=>

### ISSUE THREAD

**Issue by morningman** [apache/incubator-doris#2136]
**Describe the bug**
When join with operator `<=>`, there will be a cross join node, which is inefficient.

Actually, join with `<=>` can be treated as equal join, and a hash join node should be 
generated for this.

[what is `<=>`](https://stackoverflow.com/questions/21927117/what-is-this-operator-in-mysql)

**Comment by EmmyMiao87** [comment]
#2156

**Comment by EmmyMiao87** [comment]
#2155

**Comment by EmmyMiao87** [comment]
#2164

**Comment by EmmyMiao87** [comment]
Already change the <=> from cross join to hash join
