### ISSUE TITLE
when desc and asc，the result order of ‘’inf and nan‘’ is the same

### ISSUE THREAD

**Issue by manannan2017** [apache/incubator-doris#2145]
1、table
![image](https://user-images.githubusercontent.com/33174388/68295285-05926f80-00cd-11ea-9f67-fad0f64e3084.png)

table data:
![image](https://user-images.githubusercontent.com/33174388/68295326-1d69f380-00cd-11ea-9521-d12932c86bf4.png)

2、problems？ when desc and asc，the result order of ‘’inf and nan‘’ is the same
1>  desc
![image](https://user-images.githubusercontent.com/33174388/68295161-be0be380-00cc-11ea-8252-95001907bd83.png)

2> asc
![image](https://user-images.githubusercontent.com/33174388/68295194-d1b74a00-00cc-11ea-9abd-4b1bf3330ff3.png)

3、excepted
when desc and asc，the result order of ‘’inf and nan‘’ is not the same，the order is the opposite

**Comment by yangzhg** [comment]
i will check this

**Comment by yangzhg** [comment]
the same with issue #2142
