### ISSUE TITLE
Spark date result is 1970-01-01 when doris date is before 1970-01-01 or after 2038-01-19

### ISSUE THREAD

**Issue by zhangy5** [apache/incubator-doris#2157]
When spark query Doris data, spark date/datetime result is different with doris date/datetime. For example, Doris date/datetime before 1970-01-01 or ater 2038-01-19，spark result is 1970-01-01
![image](https://user-images.githubusercontent.com/10826066/68387692-d72e9600-0199-11ea-8643-3419c7cb460c.png)

It  will cause different SQL result.
SQL like: select k10 from baseall where k10 < '1970-01-01' . k10 is date type.
Spark result is empty, doris result is 1 row as follows.
![image](https://user-images.githubusercontent.com/10826066/68387167-a732c300-0198-11ea-9dfb-3ca17ca2edcf.png)

SQL like: select * from baseall where k10 < '1970-01-02'
Spark result is 3 rows, doris result is 1 row.
spark result:
![image](https://user-images.githubusercontent.com/10826066/68387280-f1b43f80-0198-11ea-9a8a-fa067fbde4e9.png)

All data in doris is:
![image](https://user-images.githubusercontent.com/10826066/68387356-18727600-0199-11ea-96af-5525c78436b6.png)

I think when there is data before 1970-01-01 or ater 2038-01-19 in doris, the query result executed on spark may be different from doris that may be a wrong result.

**Comment by zhangy5** [comment]
#2106

**Comment by wuyunfeng** [comment]
resolved

**Comment by zhangy5** [comment]
date/datetime column in doris will convert to string in spark, largeint too.

**Comment by wuyunfeng** [comment]
@zhangy5  em...

**Comment by zhangy5** [comment]
For now no problem has been found, and this issue is closed temporarily. You can repon it if there is any questions.

**Comment by wuyunfeng** [comment]
feel free to reopen this if you have any question.
