### ISSUE TITLE
when int column union date column， is the system not supported？

### ISSUE THREAD

**Issue by manannan2017** [apache/incubator-doris#2180]
1、table，k1 TINYINT, k10 date
![image](https://user-images.githubusercontent.com/33174388/68659561-68bf4e80-0572-11ea-8189-350ced9ab4be.png)

2、sql：
select k1 from baseall union all select k10 from bigtable limit 3;
![image](https://user-images.githubusercontent.com/33174388/68659610-7ffe3c00-0572-11ea-918a-f6deb048142c.png)

3、excepted：
mysql is support
![image](https://user-images.githubusercontent.com/33174388/68659649-960bfc80-0572-11ea-9d2a-86639f83fb55.png)

**Comment by xy720** [comment]
work in progress
