### ISSUE TITLE
why storage medium setting only supports the path extension?

### ISSUE THREAD

**Issue by vagetablechicken** [apache/incubator-doris#2195]
When setting storage_root_path,  doris uses the path extension (.ssd/.hdd) to define the storage medium. Why not just add the medium at the end of each root path, seperate by ',', like 'capacity limit'?
e.g.
storage_root_path = /home/disk1/palo **,** HDD,50

**Comment by imay** [comment]
That's a historical reason, there is no special purpose

**Comment by vagetablechicken** [comment]
> That's a historical reason, there is no special purpose

OK. For my part, I can't rename the storage paths.  I'll fix it.

**Comment by imay** [comment]
> > That's a historical reason, there is no special purpose
> 
> OK. For my part, I can't rename the storage paths. I'll fix it.

I think you should provide some details about the format which you want to change to. Because it should be kept compatible with old format.

**Comment by vagetablechicken** [comment]
How about "storage_root_path = <path>, <capacity>, <medium> "?
We can set medium after the capacity limit, it's optional. So we can still use "storage_root_path = /home/disk1/palo.HDD,50;/home/disk2/palo.SSD,1;/home/disk2/palo" to set root path.
I'd prefer to delete reading medium from the extension. But if you want to keep it, that's no problem.
Who has the greater priority, extension or medium parameter?

**Comment by imay** [comment]
> @imay How about "storage_root_path = < path >, < capacity >, < medium > "?

If this format is used, if `capacity` or `medium` is not specified, what does the final path look like? like"< path >, , < medium >" or "< path >, < capacity >,". And if other property is added to this path later, the what will the format be? 
How about the format like "path,medium=xxx,capacity=xxx". If user don't specify medium and capacity we use the default option.

> We can set medium after the capacity limit, it's optional. So we can still use "storage_root_path = /home/disk1/palo.HDD,50;/home/disk2/palo.SSD,1;/home/disk2/palo" to set root path.
> I'd prefer to delete reading medium from the extension. But if you want to keep it, that's no problem.

Even we support new format of path, we should be compatible with old format. Because there are already many instances running now, we should make them happy.

> Who has the greater priority, extension or medium parameter?

**Comment by vagetablechicken** [comment]
> And if other property is added to this path later, the what will the format be?

It's a good question.  The format like "path,medium=xxx,capacity=xxx" looks like the best choice.
But now, config's pattern is "key = value", so it'll look like:

`storage_root_path = /home/disk1/palo.HDD,capacity=50,medium=HDD;/home/disk2/palo.SSD,capacity=1;/home/disk2/palo, medium=SSD`

It's difficult to punctuate. And it's difficult to discriminate one pattern from another.

How about support one more pattern? We can set a obvious format marker '('. If we read '(', that means we use the new pattern to parse path. Otherwise, we use the old pattern "< path.extension >, < capacity >;< path.extension >".
The new pattern can be:
`storage_root_path = ( { path  = < path >;capacity = < capacity >;medium = < medium >;},{ path = <  
 path >;} );`

We don't need to mix the patterns up, right?

**Comment by imay** [comment]
@vagetablechicken 

> > And if other property is added to this path later, the what will the format be?
> 
> It's a good question. The format like "path,medium=xxx,capacity=xxx" looks like the best choice.
> But now, config's pattern is "key = value", so it'll look like:
> 
> `storage_root_path = /home/disk1/palo.HDD,capacity=50,medium=HDD;/home/disk2/palo.SSD,capacity=1;/home/disk2/palo, medium=SSD`
> 
> It's difficult to punctuate. And it's difficult to discriminate one pattern from another.
> 

If `=` is difficult to punctuate, how about `:`, like `storage_root_path = /home/disk1/palo.HDD,capacity:50,medium:HDD`

> How about support one more pattern? We can set a obvious format marker '('. If we read '(', that means we use the new pattern to parse path. Otherwise, we use the old pattern "< path.extension >, < capacity >;< path.extension >".
> The new pattern can be:
> `storage_root_path = ( { path = < path >;capacity = < capacity >;medium = < medium >;},{ path = < path >;} );`
> 
> We don't need to mix the patterns up, right?

Unless one format is not suitable, otherwise it is better not to introduce anthor format.

**Comment by vagetablechicken** [comment]
OK, `:` is good.
So we can handle `/home/disk1/palo.HDD, 50`,`/home/disk1/palo, capacity:50, medium: HDD`.
But how to do with `/home/disk1/palo.HDD, capacity:50, medium:SSD`?

**Comment by imay** [comment]
@vagetablechicken 

> But how to do with `/home/disk1/palo.HDD, capacity:50, medium:SSD`?

For this case, property `medium` has a higher priority. Otherwise, the medium can not be specified except changing directory name.
