### ISSUE TITLE
be节点偶发down

### ISSUE THREAD

**Issue by yuanfeng0905** [apache/incubator-doris#223]
be奔溃堆栈：

*** Aborted at 1534568958 (unix time) try "date -d @1534568958" if you are using GNU date ***
PC: @           0xcab427 palo::ClientCacheHelper::get_client()
*** SIGSEGV (@0x10) received by PID 222 (TID 0x7f49103e2700) from PID 16; stack trace: ***
    @     0x7f49783cb100 (unknown)
    @           0xcab427 palo::ClientCacheHelper::get_client()
    @           0xb59b17 palo::ClientConnection<>::ClientConnection()
    @           0xf3a820 palo::MiniLoadAction::load()
    @           0xf3b814 palo::MiniLoadAction::handle()
    @           0xf2905b palo::Webserver::mongoose_callback()
    @           0xf298e0 palo::Webserver::mongoose_callback_static()
    @           0xf490dd handle_request()
    @           0xf4b238 worker_thread()
    @     0x7f49783c3dc5 start_thread
    @     0x7f4977def21d __clone
==============================================
OS: centos7.2
palo version: 0.8.1

**Comment by morningman** [comment]
We already abandoned mongoose. The new http server on Backends is implemented by libevent.
Please update to our newest release version.
This bug may not be produced again
