### ISSUE TITLE
When create table with unique key using replace type for non key column encounter error

### ISSUE THREAD

**Issue by caiconghui** [apache/incubator-doris#2232]
when use show create table, we get statement like
CREATE TABLE `doris_test` (
`id` varchar(100) NOT NULL COMMENT "",
`time` bigint(20) REPLACE NOT NULL COMMENT "",
`datatype` int(11) REPLACE NOT NULL COMMENT ""
) ENGINE=OLAP
UNIQUE KEY(`id`)
COMMENT "my sink doris table"
DISTRIBUTED BY HASH(`id`) BUCKETS 5
PROPERTIES (
"storage_type" = "COLUMN"
);
and we execute it, such error occur:
UNIQUE_KEYS table should not specify aggregate type for non-key column[time]

**Comment by caiconghui** [comment]
#2231

**Comment by caiconghui** [comment]
it seems that only show create table statement from no range partition table can produce replace keyword, so fix show create table is also work well.

**Comment by imay** [comment]
@caiconghui 

I have see your PR for this patch. This is one way to make thing work.
And is it easy to let show create table return column defination without REPLACE?

**Comment by caiconghui** [comment]
@imay 
yes, but for unique key table  there is nothing wrong for create table with replace keyword. After deep thinking, I think the real bug is create table statement not the show create table statement, because the create table is nothing wrong, so we should fix create table statement.

**Comment by imay** [comment]
@caiconghui 
Actually, value column of unique column has no aggregate method. REPLACE is unnecessary, there is no other choice for it. We just use REPLACE method internally to implement unique key, which should not be exposed to Doris user. So I think it is better to fix show create table's result if it is easy.

**Comment by caiconghui** [comment]
@imay 
ok, I see. I will fix it
