### ISSUE TITLE
Fix some bugs about load label

### ISSUE THREAD

**Issue by morningman** [apache/incubator-doris#2240]
1. `dbIdToTxnLabels` in `GlobalTransactionMgr` should be consistent with `idToTransactionState`, not only contains running or finished transactions' labels.

2. callback id should be removed when replaying transaction abort or visible edit log. Or there will be lots of unused callback id in non-master FE's memory.

3. `LabelAlreadyUsed` exception should be thrown before adding load job. Otherwise, there will be lots of CANCELLED load jobs when reason "label already used".

4. LoadTimeoutChecker should check txn's status before deciding weather to cancel the job, instead of only checking job' state. This is a bad case now:

    1. txn A committed on master, and replayed on follower X, but load job' state is still LOADING.
    2. master down, follower X become master, and starting LoadTimeoutChecker thread.
    3. because the load job' state is still LOADING, and isCommitting is false, the cancel will be done, and result in job' state as CANCELLED but txn' status is COMMITTED.

**Comment by morningman** [comment]
There still remaining a bug that load job's state is not consistent with transaction status.
It looks like the job' state is LOADING but transactions state is COMMITTED of VISIBLE.

**Comment by imay** [comment]
@morningman 
Can you add more explain about why old version code will cause problem?

**Comment by morningman** [comment]
> @morningman
> Can you add more explain about why old version code will cause problem?

updated
