### ISSUE TITLE
Is that will be better create table with column default enable to be null?

### ISSUE THREAD

**Issue by caiconghui** [apache/incubator-doris#2242]
on production enviroment, create table usually with so many nullable columns, i think except key column, other column can be nullable for default? or not nullable column for default is for special purpose?

**Comment by imay** [comment]
Yes, I aggre with you. Column is created nullable is easy for user, but some impact for performance.
I think we can make a column nullable as default.

**Comment by caiconghui** [comment]
@imay is it ok for table with nullable key ??
MySQL [doris_test]> show columns from doris_test212;
+-------+----------+------+------+---------+---------+
| Field | Type     | Null | Key  | Default | Extra   |
+-------+----------+------+------+---------+---------+
| id    | INT      | YES  | YES  | 10      |         |
| name  | SMALLINT | NO   | YES  | NULL    |         |
| tt    | INT      | NO   | NO   | NULL    | REPLACE |
+-------+----------+------+------+---------+---------+
3 rows in set (0.00 sec)

**Comment by caiconghui** [comment]
or it will be better nullable default for normal column and not nullable default for key column?

**Comment by imay** [comment]
@caiconghui 

Now we have no restrict on key columns and value columns. So it is OK to make all columns nullable default.
And if we support primary key in the future, then we should make key not nullable.

**Comment by morningman** [comment]
I am not sure it is a good idea to change the default behavior of a system back and forth.
We just change the default column type to NOT NULL not long ago(which is a not good, I admitted, but for performance, we did it).
And now, changing it back will confuse all current users...

**Comment by caiconghui** [comment]
Maybe default nullable column may confuse users except hadoop users. In many database system, such as kudu, hive, mysql, the default nullable column is a common use case, we get data from hdfs, kafka, which cannot ensure that column data not null, actually, null value for many columns  is very common in production enviroment. And kudu, parquet, orc file also process with nullable column well. It is also ok for us to mark every non key column nullable explicitly if column not nullable default feature is so much important for doris on scan performance. But the specail design should be noted in the document, because normal users may not think too much when create table, and may load data failed because of data not allowed null default.

**Comment by imay** [comment]
For me, I think it is OK to change default from not null to NULL. Because it will not bring more discomfort, nullable is superset of not null. And most database default is null, such as MySQL and Postgresql. If the default is NULL, it will make load easier for beginners.
So I will vote +1 for default NULL.

**Comment by morningman** [comment]
OK, then you'd better modify the CREATE TABLE document to tell the user what is the default behavior.
