### ISSUE TITLE
add a mechanism for FE to collect the table's format statistics

### ISSUE THREAD

**Issue by kangpinghuang** [apache/incubator-doris#2249]
For issue #2245 , in order to be aware of the convert process from AlphaRowset to BetaRowset, we need a mechanism to know the process of convert.
here is my basic design:
1. when BE report to FE, add fields to indicate how many AlphaRowset and BetaRowset there are.
2. FE collect the total statistics from all BEs, and calcute the the total process of convert, and should also provide a api to get the convert process of single table.
3. http api or show proc can be the apis to get the statistics.
like:
curl -x GET http://fe_host:fe_http_port/api/format/convert/progress
curl -x GET http://fe_host:fe_http_port/api/format/convert/progress/cluster/db/table_name

show proc "/convert/process";
show proc "/convert/cluster/db/table_name"

**Comment by lingbin** [comment]
This is a one-time job, which means that the tool is no longer needed after the feature is fully online, so we only need to add an external tool.
This tool should be able to view the status of the segment from the following three dimensions
1.  cluster(i.e. total summary)
2. table
3. be
