### ISSUE TITLE
Does routine load will make oom?

### ISSUE THREAD

**Issue by hxianshun** [apache/incubator-doris#2271]
These days, I tried to load data to doris from kafka. I created a routine load and I wrote some data to kafka. Then I saw the status of load is RUNNING, and I can execute query from the destination table. Because it is just test, so I just wrote about 200,000 rows, and I didn't stop the routine load. Actually, when 200,000 rows load finished, there is no other data for 'routine load job' to consume, and I didn't stop the 'routine load job'. 
The next day, I found BE down. Then I looked over the BE log and I saw a lot of 'kafka consume timeout: xxxxxxxx-xxxxxxxx', and there is an oom error in dmesg, and BE was killed because of oom. 
So, does routine load will make oom when there is no other data in kafka for 'routine load job' to consume? Should I stop the routine load when there is no data to kafka to avoid this error?

**Comment by imay** [comment]
What's the version of your Doris BE? 
And there should be no memory leak even if you didn't stop your routine load job.
Can you provide more information? And if you start BE again, does its memory increase?

**Comment by morningman** [comment]
`kafka consume timeout: xxxxxxxx-xxxxxxxx` will apear when there is no data to consume, and that is normal.

It should not make OOM exception. Can you reproduce it ?

**Comment by XShun** [comment]
@imay @morningman Hi, thanks for reply. I just saw your message. I had restarted BE and started a new ROUTINE LOAD and reset the properties of ROUTINE LOAD. Until now the memory is normal, I will observe it for a while.

**Comment by imay** [comment]
@XShun If you find memory is abnormal, you can refer [this page](doris.apache.org/documentation/cn/developer-guide/debug-tool.html) to look into memory usage.

**Comment by XShun** [comment]
@imay Hi, the page is 404.

**Comment by imay** [comment]
> @imay Hi, the page is 404.

update
