### ISSUE TITLE
be crashes when the storage data locate in nas

### ISSUE THREAD

**Issue by lenmom** [apache/incubator-doris#2280]
**Describe the bug**
Deploy doris-0.11.5 and set the data storage to **nas**. and it would crash then the io operation is huge.

**crash stack:**
start time: Sat Nov 23 02:18:53 CST 2019
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::remove: Device or resource busy: "/opt/user/lenmom/doris-0.11.5/data/data/6/24112/1184626908/clone/.nfs000000002db61b010035ef58"
*** Aborted at 1574446754 (unix time) try "date -d @1574446754" if you are using GNU date ***
PC: @     0x7ffa22a861d7 __GI_raise
*** SIGABRT (@0x3e800005bfd) received by PID 23549 (TID 0x7ff9c163f700) from PID 23549; stack trace: ***
    @     0x7ffa22a86250 (unknown)
    @     0x7ffa22a861d7 __GI_raise
    @     0x7ffa22a878c8 __GI_abort
    @          0x2ca1745 __gnu_cxx::__verbose_terminate_handler()
    @          0x2c0d806 __cxxabiv1::__terminate()
    @          0x2c0d851 std::terminate()
    @          0x2c0bfb3 __cxa_throw
    @          0x19feca7 (anonymous namespace)::remove_all_aux()
    @          0x19fe9d2 (anonymous namespace)::remove_all_aux()
    @          0x19fedd4 boost::filesystem::detail::remove_all()
    @          0x14df4e4 doris::EngineCloneTask::_finish_clone()
    @          0x14e46cb doris::EngineCloneTask::execute()
    @           0xdfe5f5 doris::StorageEngine::execute_task()
    @          0x13153aa doris::TaskWorkerPool::_clone_worker_thread_callback()
    @     0x7ffa2283cdc5 start_thread
    @     0x7ffa22b4876d __clone
start time: Sat Nov 23 02:19:17 CST 2019
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::remove: Device or resource busy: "/opt/user/lenmom/doris-0.11.5/data/data/2/24088/1184626908/clone/.nfs000000002db61c920035ef73"
*** Aborted at 1574446769 (unix time) try "date -d @1574446769" if you are using GNU date ***
PC: @     0x7ff6aef511d7 __GI_raise
*** SIGABRT (@0x3e80000659e) received by PID 26014 (TID 0x7ff64e240700) from PID 26014; stack trace: ***
    @     0x7ff6aef51250 (unknown)
    @     0x7ff6aef511d7 __GI_raise
    @     0x7ff6aef528c8 __GI_abort
    @          0x2ca1745 __gnu_cxx::__verbose_terminate_handler()
    @          0x2c0d806 __cxxabiv1::__terminate()
    @          0x2c0d851 std::terminate()
    @          0x2c0bfb3 __cxa_throw
    @          0x19feca7 (anonymous namespace)::remove_all_aux()
    @          0x19fe9d2 (anonymous namespace)::remove_all_aux()
    @          0x19fedd4 boost::filesystem::detail::remove_all()
    @          0x14df4e4 doris::EngineCloneTask::_finish_clone()
    @          0x14e46cb doris::EngineCloneTask::execute()
    @           0xdfe5f5 doris::StorageEngine::execute_task()
    @          0x13153aa doris::TaskWorkerPool::_clone_worker_thread_callback()
    @     0x7ff6aed07dc5 start_thread
    @     0x7ff6af01376d __clone
start time: Sat Nov 23 02:19:31 CST 2019

I have encounted 10 times crash in 5 min:
-rw------- 1 lenmom lenmom  2380038144 Nov 23 02:17 core.12117
-rw------- 1 lenmom lenmom 10471809024 Nov 23 02:12 core.14854
-rw------- 1 lenmom lenmom  2389475328 Nov 23 02:17 core.15551
-rw------- 1 lenmom lenmom  2384236544 Nov 23 02:18 core.19004
-rw------- 1 lenmom lenmom  2375839744 Nov 23 02:18 core.22358
-rw------- 1 lenmom lenmom  2378997760 Nov 23 02:19 core.23549
-rw------- 1 lenmom lenmom  2372698112 Nov 23 02:19 core.26014
-rw------- 1 lenmom lenmom  2380967936 Nov 23 02:13 core.27010
-rw------- 1 lenmom lenmom  2378989568 Nov 23 02:13 core.28710
-rw------- 1 lenmom lenmom  2409410560 Nov 23 02:16 core.30312

**Comment by imay** [comment]
This problem is because that we want to delete an `.nfs` file. About this type of file, we can refer to [silly rename](http://nfs.sourceforge.net/#faq_d2).

BE crash becuase of boost's exception. However there should be some problems

1. Why the file is opened when the files is going to be deleted
2. What can we do about these `.nfs` files
