### ISSUE TITLE
建表出错

### ISSUE THREAD

**Issue by freedomme** [apache/incubator-doris#229]
MySQL [test]> CREATE TABLE table1
    -> (
    ->     siteid INT DEFAULT '10',
    ->     citycode SMALLINT,
    ->     username VARCHAR(32) DEFAULT '',
    ->     pv BIGINT SUM DEFAULT '0'
    -> )
    -> AGGREGATE KEY(siteid, citycode, username)
    -> DISTRIBUTED BY HASH(siteid) BUCKETS 10
    -> PROPERTIES("replication_num" = "1");

**ERROR 1064 (HY000): Failed to create partition[table1]. Timeout**
MySQL [test]>

安装 文档中说明，进行建表，相关错误信息见上。集群信息，一个前端，两个后端。后端是active.应该如何排错？

**Comment by morningman** [comment]
https://github.com/apache/incubator-doris/wiki/Palo-Create%2C-Load-and-Delete

**Comment by morningman** [comment]
Search 'Failed to create partition'

**Comment by freedomme** [comment]
谢谢，我先看看
