### ISSUE TITLE
Doris ON ES，错误log不友好

### ISSUE THREAD

**Issue by blackfox1983** [apache/incubator-doris#2295]
**Describe the bug**
Doris on ES.当select某一列时，如果该列实际的类型和预期类型（varchar）不一致，会提示：
Data source returned inconsistent column data. Expected value of type VARCHAR based on column metadata. This likely indicates a problem with the data source library.

**To Reproduce**
1. 构建ES。field的type为keyword
2、在doris中建表。field类型为varchar
3、向ES写入数据。如field：2（int）
4、在doris中查询，则提示上述错误日志

**Expected behavior**
1、sql返回的提示：实际doris看到的是什么类型，值是什么多少。而用户希望是什么类型。更方便追查根因。

**Comment by wuyunfeng** [comment]
https://github.com/apache/incubator-doris/pull/2297

**Comment by wuyunfeng** [comment]
resolved
