### ISSUE TITLE
后端连接前端心跳出错

### ISSUE THREAD

**Issue by freedomme** [apache/incubator-doris#230]
出错信息见下面日志，我查看相关文档，发现文档只是在dock安装方式中提到前端 后端连接时IP设置。不是dock运行方式情况下，只是提到启动前端命令 将后端加入集群命令。从下面日志，我知道后端连接前端出错是因为 IP是错误的，要怎样在后端设置 前端的IP？
W0919 11:11:05.690816  6218 utils.cpp:183] **master client, get client from cache failed.host:** 192.168.122.1, port: 9020, code: 7
W0919 11:11:05.690943  6218 task_worker_pool.cpp:1508] **finish report task failed. status: -1**
I0919 11:11:09.724184 23950 heartbeat_server.cpp:54] **get heartbeat, host: 192.168.122.1, port: 9020**, cluster id: 820443017
I0919 11:11:14.724381 23950 heartbeat_server.cpp:54] get heartbeat, host: 192.168.122.1, port: 9020, cluster id: 820443017
I0919 11:11:15.691087  6218 task_worker_pool.cpp:1500] master host: 192.168.122.1, port: 9020
W0919 11:11:15.691735  6218 utils.cpp:183] master client, get client from cache failed.host: 192.168.122.1, port: 9020, code: 7
W0919 11:11:15.691799  6218 task_worker_pool.cpp:1508] finish report task failed. status: -1
I0919 11:11:19.724525 23950 heartbeat_server.cpp:54] get heartbeat, host: 192.168.122.1, port: 9020, cluster id: 820443017
I0919 11:11:24.724730 23950 heartbeat_server.cpp:54] get heartbeat, host: 192.168.122.1, port: 9020, cluster id: 820443017
I0919 11:11:25.691926  6218 task_worker_pool.cpp:1500] master host: 192.168.122.1, port: 9020
W0919 11:11:25.692313  6218 utils.cpp:183] master client, get client from cache failed.host: 192.168.122.1, port: 9020, code: 7
W0919 11:11:25.692442  6218 task_worker_pool.cpp:1508] finish report task failed. status: -1
I0919 11:11:29.724932 23950 heartbeat_server.cpp:54] get heartbeat, host: 192.168.122.1, port: 9020, cluster id: 820443017
I0919 11:11:34.725127 23950 heartbeat_server.cpp:54] get heartbeat, host: 192.168.122.1, port: 9020, cluster id: 820443017
I0919 11:11:35.692571  6218 task_worker_pool.cpp:1500] master host: 192.168.122.1, port: 9020

**Comment by morningman** [comment]
https://github.com/apache/incubator-doris/wiki/Palo-Deploy-%26-Upgrade

**Comment by morningman** [comment]
You can search 'priority_network'

**Comment by freedomme** [comment]
谢谢，我也看到，不过 它位列与 docker 之内，一般会理解为docker专用

**Comment by morningman** [comment]
这个是在 常见问题 一节中的：https://github.com/apache/incubator-doris/wiki/Palo-Deploy-%26-Upgrade#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by morningman** [comment]
目前不支持，您目前的情况是be可以正确的接收到fe的心跳，并获取fe ip，但是be无法正确发送汇报信息？

**Comment by morningman** [comment]
需要确认be自己获得的自己的ip，是否和 show backends 得到的be 的ip 一致

**Comment by freedomme** [comment]
be可以正确的接收到fe的心跳，并获取fe ip，但是be无法正确发送汇报信息 ,
==============================
是的，就是这样

**Comment by freedomme** [comment]
需要确认be自己获得的自己的ip 
==============
这个要怎样确认？感谢你告知

**Comment by freedomme** [comment]
比较奇怪的是，设置 priority_network  后，fe 的mysql客户端没有办法登录了

**Comment by morningman** [comment]
https://github.com/apache/incubator-doris/wiki/Palo-Deploy-&-Upgrade#ip-%E7%BB%91%E5%AE%9A
