### ISSUE TITLE
Optimization: Reduce the number of segments generated in one import and ensure they do not overlap

### ISSUE THREAD

**Issue by lingbin** [apache/incubator-doris#2341]
**Problem Description:**  
When the amount of loaded data is huge, especially when the number of string values ​​is very large, or when the length of some of the string columns is very long, a large number of segments will be generated, but **these segment files are very small**, in extreme cases only a few MiB.

In one load job, the ranges of the rows contained in these newly generated MemTable (segment) are **overlapped with each other**, which will cause some problems: when the query request is processed subsequently, all files need to be opened and merged when querying. On the one hand, it mail fails because of too many open file descriptors, and on the other hand, it will cause performance problems.

**Problem Analysis:**  
Because each segment comes from a MemTable, which means that the MemTables flush the disk too often.

**The First Problem To Optimize:**
At present, because the data row (`Tuple`) generated by the upper layer is different from the data row (` Row`) internally represented by the engine, when inserting `MemTable`, the data row is copied and the occupied memory size will be calculated in the memory occupied by MemTable.

But for the aggregation model, under certain aggregation methods, these new data may be discarded (for example: the aggregation model of a column is `MIN`, but in the new data row, the value of the column is bigger than the existing value in the MemTable), the memory occupied by the data that may be discarded is not included in the memory statistics of Memtable.

But for the aggregation model, under certain aggregation methods, these new data may be discarded (for example: the aggregation model of a column is `MIN`, but in the new data row, the value of the column is greater than the existing value in the MemTable), the memory occupied by the discarded data should not be included in Memtable's memory statistics.

**The Second Problem To Optimize:**
The value range of segments generated in one import is overlapping. If the amount of data imported at one time is very large, there will inevitably be multiple flushes of the MemTable, which will result in multiple segments. As described earlier, the value ranges of these segments overlap each other, which will cause many problems. Before the import is completed, we must organize the data of these segments to make sure their ranges do not overlap.

This will increases the latency of an import job because of the "organizing" phase, but it is acceptable. Because this organizing work is just a merge operation, the workload in the entire import process is relatively small.
+ For a relatively large amount of data loading, the user's expected import time will naturally be longer, then adding a small delay, the user's intuitive feeling is not great.
+ For imports with a small amount of imported data, the finishing time must also be very small (there may also be no delay, such as when only one MemTable is generated), so it has almost no impact on the user's experience.

**Comment by kangkaisen** [comment]
Nice job！
