### ISSUE TITLE
REPALCE聚合类型的字段的数据导入只支持导入第一条吗？

### ISSUE THREAD

**Issue by gunli** [apache/incubator-doris#237]
**Describe the bug**
REPLACE聚合类型的字段导入多条数据时只导入了第一条。

**To Reproduce**
1. 用Palo v0.8.2版本搭建单FE和单BE的测试环境；
2. 创建testDb.testTable表如下：
```sql

CREATE TABLE `testTable` (
  `k1` bigint(20) COMMENT "",
  `k2` varchar(100) COMMENT "",
  `v` bigint(20) REPLACE COMMENT ""
) ENGINE=OLAP
AGGREGATE KEY(`k1`, `k2`)
DISTRIBUTED BY HASH(`k1`) BUCKETS 8
PROPERTIES (
"storage_type" = "COLUMN"
); 
```
3. 导入如下数据curl --location-trusted -u root: -T palo_test_data.log "http://x.x.x.x:yyyy/api/testDb/testTable/_load?label=7_label&column_separator=%2c"
```txt
100,t1,80000
200,t2,300
300,t3,5000
400,t4,2000
500,t5,1000000
600,t6,60000
100,t1,900000
100,t1,20000
```
4. 查询数据，key为100,t1的数据只有第一条80000
```sql
mysql> select * from testTable;
+------+------+---------+
| k1   | k2   | v       |
+------+------+---------+
|  200 | t2   |     300 |
|  600 | t6   |   60000 |
|  300 | t3   |    5000 |
|  400 | t4   |    2000 |
|  100 | t1   |   80000 |
|  500 | t5   | 1000000 |
+------+------+---------+
6 rows in set (0.13 sec)
```

**Expected behavior**
期望是最后一条记录（100,t1,20000）覆盖前面的。

**Comment by gunli** [comment]
但是如果我把聚合类型改成sum，就能把所有相同key的求和，这让我的点困惑，有没有文档描述这些区别，或者这样设计的原因。

**Comment by imay** [comment]
@gunli sum是满足交换率的，replace是不满足交换率的。在我们进行数据处理的过程中，会对数据进行排序，但是我们处理可能会引入分布式处理这样没有办法保证顺序一定与输入的数据的顺序是一致的。

所以，最后的结果可能是不稳定的

**Comment by gunli** [comment]
好的，谢谢你的热心解答。
