### ISSUE TITLE
some ut will occasionally fail

### ISSUE THREAD

**Issue by jmk1011** [apache/incubator-doris#2370]
some ut will occasionally fail
ie.
be:
1. be/test/util/system_metrics_test.cpp:SystemMetricsTest.normal
2. be/test/http/http_client_test.cpp
![image](https://user-images.githubusercontent.com/18320438/70151264-4ee2d880-16e6-11ea-9df6-f94b23edcb12.png)
4.
![image](https://user-images.githubusercontent.com/18320438/70695523-e0f96b00-1cfc-11ea-98bd-fe3a31768431.png)

fe:
1. TableQueryPlanActionTest.testQueryPlanAction
2. Running org.apache.doris.http.TableRowCountActionTest
![image](https://user-images.githubusercontent.com/18320438/70150798-8a30d780-16e5-11ea-94e4-6533a3450379.png)
3.
![image](https://user-images.githubusercontent.com/18320438/70198135-f2fd6b80-1748-11ea-8ca0-634ab8aece88.png)

**Comment by yangzhg** [comment]
be 2 and 3 I have fixed
