### ISSUE TITLE
debug mode in doris on es

### ISSUE THREAD

**Issue by BabySid** [apache/incubator-doris#2371]
**Is your feature request related to a problem? Please describe.**
when use doris on es, often need to view the corresponding DSL on a server according to SQL。iI need to scan all be'logs. It's very inefficient

**Describe the solution you'd like**
1、Simple mode. On Doris'Web site, create a tab named debug。input a sql，then output the dsl。it's very useful for trace
2、Detail mode. input a sql，output data in every stage，e.g. dsl/some dataset scrolled from ES

**Comment by wuyunfeng** [comment]
For now，translate the sql to  queyDSL maybe difficult，But I need to think about how to achieve it
