### ISSUE TITLE
Dockerfile: download URL for maven is outdated 

### ISSUE THREAD

**Issue by vagetablechicken** [apache/incubator-doris#2388]
In Dockerfile, the maven version is 3.6.0. But in https://apache.osuosl.org/maven/maven-3 , it only has 3.6.1/3.6.2/3.6.3. How about use version 3.6.3 instead?

**Comment by imay** [comment]
@vagetablechicken 
Could you please verify it and bump it up to 3.6.3 if it works fun?

**Comment by vagetablechicken** [comment]
OK，I'll fix it
