### ISSUE TITLE
[DISCUSS] Remove the `readFields()` method from the Writable interface class.

### ISSUE THREAD

**Issue by morningman** [apache/incubator-doris#2389]
I decided to remove the `readField()` method from the `Writable` interface class.

All classes that implement the `Wriable` interface need only implement the `write()` method and implement a read method in it self:

`public static T read (DataInput in) throws IOException`

First of all, wherever the `readFields()` method is called, the class type is already known. So we can directly replace the calling `readFields()` method with `Class instance = Class.read ();`

Secondly, in the future we want to introduce JSON serialization to persist the data. Its usage likes:

```
public void write (DataOutput output) {
     String json = instance.toJson ();
     Text.writeString (json, outputStream);
}

public static Class read (DataInput in) throws IOException {
     String json = Text.readString (inputStream);
     Class instance = gson.fromJson (json, Class.class);
     return instance;
}
```

If we continue to use the `readFields()` method, we cannot implement the above usage.

**Comment by morningman** [comment]
Removing the `readFields()` interface won't change too much code.
We can only remove the `@Overwrite` annotation of the `readFields()` method.

And most classes that require persistence have implemented the `static read()` method.

**Comment by imay** [comment]
@morningman 
How can we avoid someone forget implement the read function?
