### ISSUE TITLE
【sql mode】there is a problem in  operator priority 

### ISSUE THREAD

**Issue by manannan2017** [apache/incubator-doris#2396]
1、set sql mode
 set sql_mode=PIPES_AS_CONCAT;

2、problems
2.1 
doris：
![image](https://user-images.githubusercontent.com/33174388/70292963-bdc14e00-181a-11ea-909b-948ee96afe37.png)
mysql：
![image](https://user-images.githubusercontent.com/33174388/70292974-c7e34c80-181a-11ea-9549-cd82fcceda25.png)

2.2 
select (1||'a'>0) || 1;
ERROR 1064 (HY000): Unexpected exception: null
excepted NULL or  #below：
![image](https://user-images.githubusercontent.com/33174388/70293051-05e07080-181b-11ea-9b66-ec266493627e.png)

#2252

**Comment by xy720** [comment]
work in progress

**Comment by xy720** [comment]
These two problems have been fixed.
