### ISSUE TITLE
【sql mode】|| ‘-’ Symbol in expression，doris return NULL，mysql  process by first value

### ISSUE THREAD

**Issue by manannan2017** [apache/incubator-doris#2399]
1、first num is negative 

![image](https://user-images.githubusercontent.com/33174388/70304108-22d96b80-183c-11ea-9600-354857bc6c12.png)

excepted（mysql）：
![image](https://user-images.githubusercontent.com/33174388/70304135-31c01e00-183c-11ea-939a-050f283d4517.png)

2、first num is Positive 
![image](https://user-images.githubusercontent.com/33174388/70303994-ddb53980-183b-11ea-93da-c957e286517b.png)

excepted（mysql）
![image](https://user-images.githubusercontent.com/33174388/70304031-ef96dc80-183b-11ea-8b52-c247afa67dc9.png)
#2252

**Comment by xy720** [comment]
work in progress

**Comment by xy720** [comment]
I think this bug is very similar with issue #2142 
This bug is not cause by PIPES_AS_CONCAT mode, but the Arithmetic operation processing logic of Doris.
In Mysql, we can get result between numeric and non-numeric that:

```
1 + "10xy" = 11
1 + "10-1" = 11
1 + "xy10" = 1
```

But in Doris, our logic will get null.

**Comment by xy720** [comment]
I think this bug is very similar with issue #2142 
This bug is not cause by PIPES_AS_CONCAT mode, but the Arithmetic operation processing logic of Doris.
In Mysql, we can get result between numeric and non-numeric that:

```
1 + "10xy" = 11
1 + "10-1" = 11
1 + "xy10" = 1
```

But in Doris, our logic will get null.
