### ISSUE TITLE
KAFKA ROUTINE LOAD导入Doris数据丢失

### ISSUE THREAD

**Issue by ty1972873004** [apache/incubator-doris#2408]
所有的ROUTINE LOAD任务导入的数据都会丢失一部分
SHOW查看状态没有任何错误信息，一直处于RUNNING状态，但是Task被aborted

{"receivedBytes":4936663,"errorRows":0,"committedTaskNum":1,"loadedRows":5033,"loadRowsRate":0,"abortedTaskNum":20,"totalRows":5033,"unselectedRows":0,"receivedBytesRate":233000,"taskExecuteTimeMs":21171}

**Comment by morningman** [comment]
Most of aborted task means the kafka consumer does not receiving any data from kafka.
And the aborted task will not update the current offset of kafka.

What it is your Doris version? And how did you find the data lost?

**Comment by ty1972873004** [comment]
Doris Version:0.11.0
I extract data to kafka through datax,maybe 90w 
Then i create ROUTINE LOAD job
Actually write to doris only 40w，the task is always running

![image](https://user-images.githubusercontent.com/11625309/70487606-d9856680-1b30-11ea-9525-519f199b6611.png)

![image](https://user-images.githubusercontent.com/11625309/70487576-bf4b8880-1b30-11ea-93fb-fa50c3c88f70.png)

![image](https://user-images.githubusercontent.com/11625309/70487922-d8a10480-1b31-11ea-9f68-8f2c0397280e.png)

![image](https://user-images.githubusercontent.com/11625309/70487960-038b5880-1b32-11ea-85ec-10d7f39ead50.png)

**Comment by imay** [comment]
@ty1972873004 
What's the type of your table. Aggregate? Duplicate? or Unique?
If it is Aggregate or unique, it may happens because rows with the same key will be merged into one row. As a reuslt, the count() result will be less than the number of loaded rows.

**Comment by ty1972873004** [comment]
@imay  Unique
UNIQUE KEY(`id`) 
id is’t duplicated

**Comment by imay** [comment]
It says that you have about 900,000 ids, but after loadind, there are only 400,000 ids. If so, something bad may have happened. Can you provide the detail information about this 900,000 rows routine load?

**Comment by ty1972873004** [comment]
I found some error logs 

be.WARNING

W1210 14:07:28.034574 16183 data_dir.cpp:771] could not find tablet id: 28950, schema hash: 1909488096, for rowset: 020000000025aba9474d77e1f14c1a92f29ce2d7f8fc19ac, skip this rowset
W1210 14:07:28.034581 16183 data_dir.cpp:771] could not find tablet id: 28950, schema hash: 1909488096, for rowset: 020000000025abb1474d77e1f14c1a92f29ce2d7f8fc19ac, skip this rowset
W1210 14:07:28.034587 16183 data_dir.cpp:771] could not find tablet id: 28727, schema hash: 1076216222, for rowset: 02000000000004ab8149b01614778a9c9539b0e6639315bf, skip this rowset
W1210 14:07:28.034593 16183 data_dir.cpp:771] could not find tablet id: 26880, schema hash: 361831285, for rowset: 02000000002598ac474d77e1f14c1a92f29ce2d7f8fc19ac, skip this rowset
W1210 14:07:28.034600 16183 data_dir.cpp:771] could not find tablet id: 28800, schema hash: 686457861, for rowset: 0200000000259ec4474d77e1f14c1a92f29ce2d7f8fc19ac, skip this rowset
W1210 14:07:28.034605 16183 data_dir.cpp:771] could not find tablet id: 28800, schema hash: 686457861, for rowset: 0200000000259ecc474d77e1f14c1a92f29ce2d7f8fc19ac, skip this rowset
E1210 14:07:28.062312 16108 cgroups_mgr.cpp:350] Could not find a valid cgroups path for resource isolation,current value is 
W1210 14:07:28.062840 16108 exec_env_init.cpp:191] Config storage_page_cache_limit is greater than memory size, config=20G, memory=8201179136
W1210 14:07:28.081041 16364 utils.cpp:184] master client, get client from cache failed.host: , port: 0, code: 7
W1210 14:07:28.081094 16364 task_worker_pool.cpp:1248] finish report task failed. status:-1, master host:port:0
W1210 14:10:33.431669 16320 routine_load_task_executor.cpp:277] consuming failed
W1210 14:10:33.431731 17476 broker_scan_node.cpp:414] Scanner[0] prcess failed. status=cancelled
W1210 14:10:33.432528 16265 stream_load_executor.cpp:83] fragment execute failed, query_id=52545139565d4c5b-b15180235e7f2d88, errmsg=cancelledid=52545139565d4c5b-b15180235e7f2d88, job id=32036, txn id=182005, label=fj_test_mcs_p_delivery_goods-32036-52545139565d4c5b-b15180235e7f2d88-182005
W1210 14:10:54.446434 16321 routine_load_task_executor.cpp:277] consuming failed
W1210 14:10:54.446511 17558 broker_scan_node.cpp:414] Scanner[0] prcess failed. status=cancelled
W1210 14:10:54.447072 16297 stream_load_executor.cpp:83] fragment execute failed, query_id=84d6052ed225491f-84e0dcfbc7cbb462, errmsg=cancelledid=84d6052ed225491f-84e0dcfbc7cbb462, job id=32036, txn id=182006, label=fj_test_mcs_p_delivery_goods-32036-84d6052ed225491f-84e0dcfbc7cbb462-182006
W1210 14:11:14.452834 16322 routine_load_task_executor.cpp:277] consuming failed
W1210 14:11:14.452911 17678 broker_scan_node.cpp:414] Scanner[0] prcess failed. status=cancelled
W1210 14:11:14.453999 16258 stream_load_executor.cpp:83] fragment execute failed, query_id=7f0f3a58c5ba445e-ab66a9012af6d85f, errmsg=cancelledid=7f0f3a58c5ba445e-ab66a9012af6d85f, job id=32036, txn id=182007, label=fj_test_mcs_p_delivery_goods-32036-7f0f3a58c5ba445e-ab66a9012af6d85f-182007
W1210 14:11:34.462235 16323 routine_load_task_executor.cpp:277] consuming failed
W1210 14:11:34.462314 17793 broker_scan_node.cpp:414] Scanner[0] prcess failed. status=cancelled
W1210 14:11:34.462914 16308 stream_load_executor.cpp:83] fragment execute failed, query_id=1e776b5857b44610-8d890b0091701e36, errmsg=cancelledid=1e776b5857b44610-8d890b0091701e36, job id=32036, txn id=182008, label=fj_test_mcs_p_delivery_goods-32036-1e776b5857b44610-8d890b0091701e36-182008
W1210 14:11:55.467751 16324 routine_load_task_executor.cpp:277] consuming failed
W1210 14:11:55.467823 17915 broker_scan_node.cpp:414] Scanner[0] prcess failed. status=cancelled
W1210 14:11:55.468518 16313 stream_load_executor.cpp:83] fragment execute failed, query_id=8c2cd3126a474d03-af98c6ee5d7467e9, errmsg=cancelledid=8c2cd3126a474d03-af98c6ee5d7467e9, job id=32036, txn id=182009, label=fj_test_mcs_p_delivery_goods-32036-8c2cd3126a474d03-af98c6ee5d7467e9-182009

**Comment by ty1972873004** [comment]
问题已解决 部署的kafka问题
