### ISSUE TITLE
Invalid metric type error for Prometheus 2.4.x

### ISSUE THREAD

**Issue by liuerfire** [apache/incubator-doris#241]
palo's metrics output is like:
```
# TYPE palo_fe_job GAUGE
palo_fe_job{job="load", type="HADOOP", state="PENDING"} 0
```

this is not allowed in Prometheus 2.4.x

See: https://github.com/prometheus/prometheus/issues/4602

**Comment by morningman** [comment]
Yes it is.
We already fixed it, and will pull it later.

prometheus 2.3.1 works for now, you can download it here:

http://bj-test-cmy.bj.bcebos.com/prometheus-2.3.1.linux-amd64.tar.gz?authorization=bce-auth-v1/069fc2786e464e63a5f1183824ddb522/2018-10-18T07:31:32Z/-1/host/6e2c3ad9e60256258b0f68c9bc51413ff73ed8a4b07959088f2dd79f54a3ac0e

**Comment by liuerfire** [comment]
Thanks
