### ISSUE TITLE
Export job cancelled with ErrorMsg 'make_snapshot failed. status: -234'

### ISSUE THREAD

**Issue by zhangy5** [apache/incubator-doris#2432]
**Describe the bug**
export job failed.
![image](https://user-images.githubusercontent.com/10826066/70620063-38da9800-1c51-11ea-88d3-914fbf57eac5.png)

**To Reproduce**
CREATE DATABASE test_sys_export_test_export_table_db

CREATE TABLE test_sys_export_test_export_table_db.test_sys_export_test_export_table_tb ( k1 tinyint NULL, k2 smallint NULL, k3 int NULL, k4 bigint NULL, k5 decimal(9, 3) NULL, k6 char(5) NULL, k10 date NULL, k11 datetime NULL, k7 varchar(20) NULL, k8 double max NULL, k9 float sum NULL ) DISTRIBUTED BY HASH(k1) BUCKETS 5

LOAD LABEL test_sys_export_test_export_table_db.label_11_19_58_27_648482_1265004945 (DATA INFILE("hdfs://ip:port/user/palo/test/data/qe/baseall.txt") INTO TABLE `test_sys_export_test_export_table_tb`) WITH BROKER "hdfs" ("username"="root", "password"="")

EXPORT TABLE test_sys_export_test_export_table_db.test_sys_export_test_export_table_tb TO "hdfs://ip:port/user/palo/test/data/export" WITH BROKER "hdfs" ("username"="root", "password"="")

**Expected behavior**
Expected export finished.

commit version: 036d7da290a66089b40bc962d9b7326a6867aab5

**Comment by morningman** [comment]
snapshot version is not set in Export Job. I will fix it

**Comment by zhangy5** [comment]
resolved
