### ISSUE TITLE
support alter view & rename view

### ISSUE THREAD

**Issue by AllenXL** [apache/incubator-doris#2456]
Suppose we have table A and a view based on table A named A_view. Then, we want to change A_view. If use drop/create，some queries during this procedure will fail. So we suggest to support alter view or rename view to avoid this drawback.

**Comment by xy720** [comment]
In Doris, the concept of view is logical. We don't store view as an concrete entity physically,
In fact, what we store is just an SQL statement. Every time a user queries the view, we will take this SQL statement out of the metadata and re-parse, re-call the analyze method, and finally get the result, which is not much difference from the ordinary query.
Therefore, the process of alter view is to replace the stored SQL statement and update the schema structure of view.

在Doris里面，view的概念是逻辑上的，我们不会将view作为实体存在物理存储上，
实际上，我们存储的只是一条sql语句，每一次用户去查询view的时候，我们都会从元数据中取出这条sql语句，重新
解析，调用analyze方法，最终得到结果，和普通的查询区别不大。
因此，Alter view的过程，就是去替换这一条被存储的sql语句，并更新view的schema结构。
