### ISSUE TITLE
Concat result error

### ISSUE THREAD

**Issue by LENAMYY** [apache/incubator-doris#2469]
**Describe the bug**
doris的执行结果：
![image](https://user-images.githubusercontent.com/58024823/70896952-ab21f280-202c-11ea-80f3-baa256c648a2.png)

mysql的执行结果：
![image](https://user-images.githubusercontent.com/58024823/70896916-96455f00-202c-11ea-8f1f-12a39e607204.png)

**To Reproduce**
select (concat(k1, k2)),(concat(k1, k2) < 1.0) from baseall;

**Comment by xy720** [comment]
I think this bug is very similar with issue #2142 and #2399  . (reference pr #2362  ).
