### ISSUE TITLE
a problem when parse column data from hdfs path 

### ISSUE THREAD

**Issue by zhangy5** [apache/incubator-doris#2478]
**To Reproduce**
create table like:
CREATE DATABASE test_sys_load_parse_from_path_test_parse_wrong_type_db;

CREATE TABLE test_sys_load_parse_from_path_test_parse_wrong_type_db.test_sys_load_parse_from_path_test_parse_wrong_type_tb ( k1 TINYINT NULL, k2 SMALLINT NULL, k3 INT NULL, k4 BIGINT NULL, k5 DATETIME NULL, v1 DATE REPLACE NULL, v2 CHAR REPLACE NULL, v3 VARCHAR(4096) REPLACE NULL, v4 FLOAT SUM NULL, v5 DOUBLE SUM NULL, v6 DECIMAL(20,7) SUM NULL ) AGGREGATE KEY (k1, k2, k3, k4, k5) PARTITION BY RANGE(k1) ( PARTITION partition_a VALUES LESS THAN ("5"), PARTITION partition_b VALUES LESS THAN ("20"), PARTITION partition_c VALUES LESS THAN ("30"), PARTITION partition_d VALUES LESS THAN MAXVALUE ) DISTRIBUTED BY HASH(k2) BUCKETS 5;

load sql is :
LOAD LABEL test_sys_load_parse_from_path_test_parse_wrong_type_db.label_17_04_39_52_077258_128914487 (DATA INFILE("hdfs://hosti:ip/user/palo/test/data/sys/broker_load/k1=-1/k2=0/k5=100.12345/partition_type") INTO TABLE `test_sys_load_parse_from_path_test_parse_wrong_type_tb` (`k1`, `k2`, `k3`, `k4`, `tmp_k5`, `v1`, `v2`, `v3`, `v4`, `v5`, `v6`) COLUMNS FROM PATH AS (k5)) WITH BROKER "hdfs" ("username"="root", "password"="");

** Problem **
k5 is datetime and the data parsed from hdfs path is 100.12345, this load job is expected to be cacenlled. But it is finished, and k5 is null. 
Broker load without strict mode property, the default strict mode is true, but it doesn’t look like it.

**Comment by morningman** [comment]
the default strict mode is now FALSE. so this is ok.

**Comment by zhangy5** [comment]
ok
