### ISSUE TITLE
[PROPOSAL] Supporting create index syntax on V2 segment

### ISSUE THREAD

**Issue by yangzhg** [apache/incubator-doris#2487]
## Motivation
Doris currently supports bitmap indexes in the v2 segment, but there is no corresponding syntax support. Therefore, we need to implement the  create index, drop index, and management index syntax support. 
The implementation is divided into two steps. The first step is to implement the front-end syntax support. The second step is to implement the index creation task and index management function.

### create table with index 
```
CREATE TABLE table1
(
    siteid INT DEFAULT '10',
    citycode SMALLINT,
    username VARCHAR(32) DEFAULT '',
    pv BIGINT SUM DEFAULT '0',
    INDEX index_name (siteid, citycode)  [USING BITMAP]  COMMENT 'balabala'
)
AGGREGATE KEY(siteid, citycode, username)
DISTRIBUTED BY HASH(siteid) BUCKETS 10
PROPERTIES("replication_num" = "1");
```
### create index 
```
CREATE INDEX index_name  ON table1 (siteid, citycod) [USING BITMAP] COMMENT 'balabala';
or 
ALTER TABLE table1 ADD  INDEX index_name (siteid, citycod)   [USING BITMAP]  COMMENT 'balabala';
```
### drop index
```
DROP INDEX index_name ON table1;
or
ALTER TABLE table1 DROP INDEX index_name 
```

### show index
```
SHOW INDEX[ES] FROM table1
```
output
```
+---------+-------------+-----------------+------------+---------+
| Table   | Index_name  | Column_name     | Index_type | Comment |
+---------+-------------+-----------------+------------+---------+
| table1  | index_name  | siteid,citycode | BITMAMP    | balabala|
+---------+-------------+-----------------+------------+---------+
```

## Compromise
Because bitmap indexes are only supported on a single column, joint indexes and expressions are not supported. Although multi-column indexes can be converted to indexes that act on a single column, in order to avoid inconvenience when creating a multi-column index, but you want to delete a column index separately. so currently each statement that creates a bitmap index can only work on a single column

**Comment by morningman** [comment]
Why there are 2 kinds of order when specifying index columns:

`ON table1 (siteid, citycod) [USING BITMAP] ` ([USING BITMAP] at the end)
`ADD  INDEX index_name  [USING BITMAP] (siteid, citycod)` ([USING BITMAP] at the begin)
