### ISSUE TITLE
insert into import cross partitions error

### ISSUE THREAD

**Issue by xinyiZzz** [apache/incubator-doris#2511]
Table partition by day, when import for more than 5 days at a time, see error:
>ERROR 1064 (HY000): For input string: "2361759245". url:  XXX

every line print error in the url:
>Reason: null value for not null column, column=partition_stat_date. src line: []; 

E.g: 
>insert into table_new partition(p20191101) select xxx from table_old WHERE stat_date >= 20191001 and stat_date <= 20191007

Bug, split the day into two sql and import twice can import succeeded
E.g: 
>insert into table_new partition(p20191101) select xxx from table_old WHERE stat_date >= 20191001 and stat_date <= 20191005

>insert into table_new partition(p20191101) select xxx from table_old WHERE stat_date >= 20191006 and stat_date <= 20191007

separate execution can succeed

**Comment by morningman** [comment]
what is your Doris version?

**Comment by xinyi-Z** [comment]
Doris version 0.11.25, sorry, I forgot
discussed with zhao,chun for Doris, error reproduce in baidu UBS-Cluster
thx ^_^

**Comment by xinyi-Z** [comment]
> what is your Doris version?

Doris version 0.11.25, sorry, I forgot
discussed with zhao,chun for Doris, error reproduce in baidu UBS-Cluster
thx ^_^
