### ISSUE TITLE
support bitmap_andnot

### ISSUE THREAD

**Issue by imay** [apache/incubator-doris#2537]
sytax
```
BITMAP bitmap_andnot(BITMAP map1, BITMAP map2)
```

this function will return the andnot result of inputs two bitmap .

#2533

**Comment by shiyi23** [comment]
@imay hello,I want to fix this, can you assign it to me?
And can you give me an example of how to use the function bitmap_andnot(BITMAP map1, BITMAP map2), Because I'm not sure I understand it correctly

**Comment by shiyi23** [comment]
![image](https://user-images.githubusercontent.com/40733762/104426657-2f8ece00-55bd-11eb-9bd0-784715f3b11f.png)
An use example just like above is enough

**Comment by morningman** [comment]
Like this：http://www.bricktou.com/include/linux/bitmapbitmap_andnot_en.html

**Comment by shiyi23** [comment]
thanks

**Comment by shiyi23** [comment]
> Like this：http://www.bricktou.com/include/linux/bitmapbitmap_andnot_en.html

thanks your reply~
