### ISSUE TITLE
Core on DorisOnES

### ISSUE THREAD

**Issue by blackfox1983** [apache/incubator-doris#2615]
start time: Wed Nov 27 16:57:23 CST 2019
*** Aborted at 1577697170 (unix time) try "date -d @1577697170" if you are using GNU date ***
PC: @          0x1433b73 doris::EsHttpScanNode::collect_scanners_status()
*** SIGSEGV (@0x8) received by PID 27689 (TID 0x7f30dc782700) from PID 8; stack trace: ***
    @     0x7f311cb225d0 (unknown)
    @          0x1433b73 doris::EsHttpScanNode::collect_scanners_status()
    @          0x1435fd8 doris::EsHttpScanNode::close()
    @          0x139db86 doris::ExecNode::close()
    @          0x13aaddb doris::HashJoinNode::close()
    @          0x139db86 doris::ExecNode::close()
    @          0x1471ba8 doris::NewPartitionedAggregationNode::close()
    @          0x1045b2a doris::PlanFragmentExecutor::close()
    @           0xfd5995 doris::FragmentExecState::execute()
    @           0xfd8886 doris::FragmentMgr::exec_actual()
    @           0xfdd972 boost::detail::function::void_function_obj_invoker0<>::invoke()
    @           0xee5f05 doris::ThreadPool::work_thread()
    @          0x19c5ecd thread_proxy
    @     0x7f311cb1add5 start_thread
    @     0x7f311bf1fead __clone

version：master (2019-11-27~)

**Comment by wuyunfeng** [comment]
@blackfox1983 

This core problem maybe related to the `EsHttpScanNode` open failure,  the size of `_scan_ranges` and `_scanners_status` are not same, `_scanners_status[_scan_ranges.index]`  return nil
