### ISSUE TITLE
Doris thirdparty compile error for Ubuntu14.04

### ISSUE THREAD

**Issue by caiconghui** [apache/incubator-doris#2648]
**Describe the bug**
bash build-thirdparty, and build apache arrow failed

**Comment by yangzhg** [comment]
first check your cmake version and other dependencies,
doris need `GCC 5.3.1+, Oracle JDK 1.8+, Python 2.7+, Apache Maven 3.5+, CMake 3.11+`
[here](https://doris.incubator.apache.org/documentation/en/installing/compilation_EN.html#direct-compilation-centos-ubuntu) is the document
