### ISSUE TITLE
[Proposal] Support partition overwrite operation

### ISSUE THREAD

**Issue by morningman** [apache/incubator-doris#2663]
# Partition Overwrite Operation

Some businesses need data backtracking, such as revising historical data or refreshing historical data. In the current version of Doris, there are only two ways to do this. One is to use the `REPLACE` aggregation model to overwrite by re-loading the data with same keys. The second way is to delete the data and then re-load the data.

The first method can guarantee that the data is overwritten atomically, but the aggregation type is limited to `REPLACE` and can only overwrite data with the same keys. In the second method, there is a gap between deleting the data and successfully loading the new data.

Therefore, we need a way that can overwrite data atomically, and without the limitations of the aggregation model.

## Two methods

There are two methods to achieve this.

1. Temporary partition

    For partitions that need to be overwritten, users can first create a temporary partition and write data to this temporary partition. After the data is written, User can replace the original partition with this temporary partition by using an atomic replacement command.

2. Overwrite directly

    Doris's underlying data is managed by MVCC. Therefore, we can add a special version, named `overwrite version` in tablet's meta, to ensure that when data is read, all data before that version can be skipped to achieve the purpose of overwriting.

Both methods have advantages and disadvantages.

The **disadvantage** of the first method is that the operation is tedious. The user needs to perform the three steps of `create temporary partition-> load data-> replace partition`. And creating temporary partitions means creating new tablets. If there are a large number of overwrite operations, a large number of temporary tablets will be generated, which is not friendly to metadata management and garbage collection mechanisms. However, the **advantage** of this method is that users can load the data in multiple batches, and then overwrite and replace them at one time through the partition replacement operation.

The **advantage** of the second method is to conform to the user's habits of overwriting write operations. Users can set any batch of load as a overwrite load. And there is no additional overhead. The **disadvantage** is that the user needs to load all the data that needs to be overwritten in a batch of load. If the amount of data to be overwritten is large, such as 100 GB or TB level, this method will lead to a higher probability of failure in the overwrite operation, and the retry cost is high.

Both methods have their own advantages and disadvantages and applicable scenarios. So I plan to support both.

### Temporary Partition (DEPRECATED, SEE BELOW)

The temporary partition method needs to consider the following:

1. How to make the load operation aware of the existence of the temporary partition? Or how to distinguish between temporary and formal partitions?
2. After the temporary partition is created, how to ensure that the formal partition will not be modified to ensure that the schema of the two partitions is exactly the same when the partition is eventually replaced?
3. How to perform partition replacement?

First of all, using this method for overwrite operations is usually a specific scenario. Therefore, the design principle is to prohibit other operations, such as `ALTER TABLE`, to ensure that there are no changes to the table schema during the entire overwrite operation to reduce functional complexity.

1. Create and delete temporary partitions

    `ALTER TABLE tbl ADD TEMPORARY PARTITION (p1, p2, p3);`

    Creates a corresponding temporary partitions for the specified partitions. The name of the temporary partition is the name of the original partition prefixed with `__doris_tmp`.

    Tables with temporary partitions cannot be altered. If you delete the original partitions, the corresponding temporary partitions will also be deleted.

    `ALTER TABLE tbl DROP TEMPORARY PARTITION (p1, p2, p3);`

    Deletes the temporary partitions.

2. Load data to temporary partition

    You must explicitly specify temporary partitions to load data.

    * broker load

        ```
        LOAD LABEL example_db.label1
        (
        DATA INFILE ("hdfs://hdfs_host:hdfs_port/user/palo/data/input/file")
        INTO TABLE `my_table`
        TEMPORARY PARTITION (p1, p2)
        )
        WITH BROKER my_hdfs_broker
        (
        "username" = "hdfs_user",
        "password" = "hdfs_passwd"
        )
        PROPERTIES
        (
        "timeout" = "3600",
        "max_filter_ratio" = "0.1"
        );
        ```

    * stream load

        ```
        curl --location-trusted -u root -H "label: l123" -H "temporary partitions: p1, p2" ....
        ```

    * insert into

        ```
        INSERT INTO TABLE TEMPORARY PARTITION (p1, p2) SELECT ...;
        ```

3. Swap temporary partitions

    `ALTER TABLE tbl SWAP TEMPORARY PARTITION (p1, p2)`

    Swap temporary and formal partitions. After the swapping, the user's query will query the exchanged partitions. Abd the temporary partition becomes a formal partition, and the formal partition becomes a temporary partition. After confirming that the data is correct, user can delete the partition by deleting the temporary partition.

### Overwrite directly

The user can specify a batch of load as an **overwrite load**. The overwrite load will proceed as normal load. But in the "publish" phase, the publish task will record an `overwrite version` in the corresponding tablet meta. The version indicates that the data before this version will be directly overwritten.

The publish task can record the `overwrite version` in the incremental rowset meta and update the tablet meta in memory. When doing the checkpoint of the tablet meta, update the `overwrite version` in the tablet meta.

1. Read operation

    The read operation will select the rowsets by specified `read version`. When the version of a rowset is less than `overwrite version`, and the `read version` is greater than or equal to `overwrite version`, the rowset will be skipped. If the `read version` is less than `overwrite version`, the` overwrite version` has no effect.

    `overwrite version` in tablet meta is actually a list. A set of `overwrite version` is recorded. The read operation will find the largest `overwrite version` that is smaller than the `read version` as **THE** overwrite version for this read.

    for example:

    ```
    0-10
    11-13
    14-14
    15-15
    16-16
    
    overwrite version: 15
    ```

    Assuming the `read version` is 14, then the [0-14] version of data is read normally, and `overwrite version(15)` does not work.

    Assuming the `read version` is 16, we find the largest overwrite version smaller than 16 is 15, and only read the two versions 15, 16.

    The `overwrite version` list is updated during compaction.
    
2. Compaction

    Compaction operation first determines the range of versions that need to be merged, the **start version** and **end version**. Then look for the largest `overwrite version` smaller than the end version. Then during compaction, skip the rowset whose version is less than `overwrite version`.
    
    The following examples illustrate some typical cases
    
    * Case 1

        ```
        0-10
        11-13
        14-14
        15-15
        16-16
        
        overwrite version: 15
        ```

        If we want to merge the [14-16] version, the 14 version will be skipped, and the resulting rowset version will still be [14-16], but only contains data of the 15 and 16 versions. And the `overwrite version` will be changed from 15 to 14. If it is not changed, the `overwrite version` will be 15, but there is a rowset with the [14-16] version, which is weird.

        ```
        0-10
        11-13
        14-16
        
        overwrite version: 14
        ```

        After that, the base compaction of versions 0 to 16 is continued, and the versions [0-10], [11-13] will be skipped, and eventually the data of version [0-16] will be generated, and the overwrite version will become 0. When overwrite version becomes 0, we can delete the overwrite version.

    * Case 2
        
        ```
        0-10
        11-13
        14-14
        15-15
        16-16
        
        overwrite version: 14, 16
        ```

        If we want to merge the [14-16] version, the 14 and 15 versions will be skipped, and the resulting rowset version is still [14-16], but only contains the data of the 16 version. And overwrite version 14 is removed and 16 becomes 14.

        ```
        0-10
        11-13
        14-16
        
        overwrite version: 14
        ```

## Schedule

I will implement the temporary partitioning method first, and then develop directly overwrite method.

**Comment by morningman** [comment]
Redesign according to new requirements

We hope that the Temporary Partition feature can be more flexible. While supporting overwrite, it can also support the modification of existing partitions, such as supporting partition splitting or merging, or modifying the number of buckets.

## Add Temp Partition

```
ALTER TABLE tbl
ADD TEMP PARTITION tp1 values ​​[(lower), (high)) BUCKETS 10,
ADD TEMP PARTITION tp2 values ​​((lower), (high)) BUCKETS 20,
ADD TEMP PARTITION tp3 values ​​[(lower), (high));
```

Temporary partitions can also specify partition ranges and number of buckets. If no bucket number is specified, the default bucket number is used. There is no limit on the range of the temporary partition. However, all ranges of the temporary partitions of a table must not conflict.

## Delete Temp Partition

```
ALTER TABLE tbl DROP TEMP PARTITION (tp1, tp2);
```

## Replace Temp Partition

```
ALTER TABLE tbl REPLACE PARTITION (p1, p2) WITH TEMP PARTITION (tp1, tp2, tp3);
```

The above statement replaces the existing partitions `p1, p2` with `tp1, tp2, tp3`. In the replace partition operation, as long as after deleting original partitions and replaced with the temp partitions, the range of the entire table does not conflict, then the replace operation will be allowed.

Replacement is an atomic operation.

## Load/Read/ to Temp Partitions

1. BROKER LOAD

    ```
    LOAD LABEL db1.label1
    DATA INFILE ("hdfs: // files")
    INTO TABLE `my_table`
    TEMP PARTITION (p1, p2)
    ...
    ```

2. STREAM LOAD

    ```
    curl -H "temp partition: p1, p2" ...
    ```

3. INSERT INTO

    ```
    INSERT INTO tbl TEMP PARTITION (p1, p2) ...
    ```

4. SELECT

    ```
    SELECT * FROM tbl TEMP PARTITION (p1, p2) ...
    ```

## Usage

* Overwrite

    First create a temporary partition with the same range as the partition to be overwritten. Then load the data to the temporary partition, and finally replace the partition with the temporary partition by the replace command to complete the overwrite.

* Partition split and merge

    First create two temporary partitions whose range is the splitted range. Use the insert into statement to load data from the original partition into two temporary partitions. Finally, use the replace command to replace the partition with temporary partitions to complete the partition split.

    Merging partitions is to create a temporary partition whose range covers multiple partitions' ranges, and then perform the same operation as split.

**Comment by kangkaisen** [comment]
> We hope that the Temporary Partition feature can be more flexible. While supporting overwrite, it can also support the modification of existing partitions, such as supporting partition splitting or merging, or modifying the number of buckets.

If the Temporary Partition is not binding with the original Partition, we will need to support Temporary Partition set partition properties. such as `replication_num`,  `in_memory`.

**Comment by imay** [comment]
> ```
> ALTER TABLE tbl
> ADD TEMP PARTITION tp1 values ​​[(lower), (high)) BUCKETS 10,
> ADD TEMP PARTITION tp2 values ​​((lower), (high)) BUCKETS 20,
> ADD TEMP PARTITION tp3 values ​​[(lower), (high));
> ```

Prefer using keyword TEMPORARY 

> However, all ranges of the temporary partitions of a table must not conflict.

Is this necessary?

 > In the replace partition operation, as long as after deleting original partitions and replaced with the temp partitions, the range of the entire table does not conflict, then the replace operation will be allowed.

Besides the ranges don't conflict, the new partitions' range should be exactly the same with old partitions'. For example in the situation that the old partitions ranges are [1,3), [3,5) the new partition is [1,2) [3,5), there will be a hole [2,3) in the table. I'm not sure if this will work fine.

> ```
> LOAD LABEL db1.label1
> DATA INFILE ("hdfs: // files")
> INTO TABLE `my_table`
> TEMP PARTITION (p1, p2)
> ...
> ```

I think the TEMP keyword here isn't necessary, and should be removed.

**Comment by morningman** [comment]
> If the Temporary Partition is not binding with the original Partition, we will need to support Temporary Partition set partition properties. such as `replication_num`, `in_memory`.

Is it necessary to make this `temporary` thing much complexity? As you said, this is just a `short life time` partition and will not exist long time.

**Comment by morningman** [comment]
> > However, all ranges of the temporary partitions of a table must not conflict.
> 
> Is this necessary?

Yes, to make things simple. And use can load data to temp partition just like the formal partition.

**Comment by morningman** [comment]
> Besides the ranges don't conflict, the new partitions' range should be exactly the same with old partitions'. For example in the situation that the old partitions ranges are [1,3), [3,5) the new partition is [1,2) [3,5), there will be a hole [2,3) in the table. I'm not sure if this will work fine.

If so, we also need to be able to specify the name of corresponding formal partition for the temporary partition in the statement. This makes the statement more complicated. 

Maybe we can create a separate syntax for split and merge scenarios? Or simply use this flexible method directly and leave it to the user to judge and handle.

**Comment by morningman** [comment]
> I think the TEMP keyword here isn't necessary, and should be removed.

It is not easy to guarantee that the name of the temporary partition and the name of the formal partition do not conflict. So we use the `temp` keyword to distinguish. In this way, users only need to ensure that the names in different partition types do not conflict.

At the same time, we want users to be aware of their behavior and realize that temporary partitions are only temporary. Because I don't even implement the replica's balacne and repair of the temporary partition.

**Comment by imay** [comment]
> If so, we also need to be able to specify the name of corresponding formal partition for the temporary partition in the statement. This makes the statement more complicated.

In the statement the replaced partition is already specified.

```
ALTER TABLE tbl REPLACE PARTITION (p1, p2) WITH TEMPORARY PARTITION (tp1, tp2, tp3);
```

We must keep the range of partition p1 p2 is the same with the range of partition tp1, tp2 and tp3.

**Comment by morningman** [comment]
> In the statement the replaced partition is already specified.

No, I mean we have to specify the name of corresponding formal partition in `CREATE TEMP PARTITION` stmt. Otherwise we can control the range of a temp partition user created.

And I think this is OK, just leave it to user how to use it. And in `REPLACE` operation, I will only check after replacing, the new ranges are not conflict.

**Comment by imay** [comment]
> > I think the TEMP keyword here isn't necessary, and should be removed.
> 
> It is not easy to guarantee that the name of the temporary partition and the name of the formal partition do not conflict. 

Why it is not easy? when the new partition temporary or not is added, the name is checked. Then the name can be guaranteed not conflict.

> 
> At the same time, we want users to be aware of their behavior and realize that temporary partitions are only temporary.

> Because I don't even implement the replica's balacne and repair of the temporary partition.

I think it is not a good idea not to do this. Better to treat temp partition like normal partition, otherwise when the temp partition is converted to a normal partition, additional check will be done.

**Comment by imay** [comment]
> > In the statement the replaced partition is already specified.
> 
> No, I mean we have to specify the name of corresponding formal partition in `CREATE TEMP PARTITION` stmt. Otherwise we can control the range of a temp partition user created.

I don't quite understand why you should indicate the name of the associated partition when creating the partition?
 
> And I think this is OK, just leave it to user how to use it. And in `REPLACE` operation, I will only check after replacing, the new ranges are not conflict.

I want to emphasize that it is not enough to just check for conflicts. You need to check if the two partitions replaced before and after are exactly enough to cover. The conflict just says that the partitions overlap, and there is another case where there are holes between the partitions

**Comment by morningman** [comment]
> I think it is not a good idea not to do this. Better to treat temp partition like normal partition, otherwise when the temp partition is converted to a normal partition, additional check will be done.

I agree with this

**Comment by morningman** [comment]
> > > In the statement the replaced partition is already specified.
> > 
> > 
> > No, I mean we have to specify the name of corresponding formal partition in `CREATE TEMP PARTITION` stmt. Otherwise we can control the range of a temp partition user created.
> 
> I don't quite understand why you should indicate the name of the associated partition when creating the partition?
> 
> > And I think this is OK, just leave it to user how to use it. And in `REPLACE` operation, I will only check after replacing, the new ranges are not conflict.
> 
> I want to emphasize that it is not enough to just check for conflicts. You need to check if the two partitions replaced before and after are exactly enough to cover. The conflict just says that the partitions overlap, and there is another case where there are holes between the partitions

I mean, for example, the origin partition(p1, p2) ranges are:
[0, 10)
[10, 20)

And user create 2 temp partitions (tp1, tp2) with range:
[10, 11) and [15, 18)

And user replace the (p1, p2) with (tp1, tp2), should we allow this operation?

Two options. First, we check strictly. The range must be covered and equal. But if user really want to new range of tp1 and tp2? So the second option is, we only check for conflicts and not for coverage.

**Comment by imay** [comment]
> I mean, for example, the origin partition(p1, p2) ranges are:
> [0, 10)
> [10, 20)
> 
> And user create 2 temp partitions (tp1, tp2) with range:
> [10, 11) and [15, 18)
> 
> And user replace the (p1, p2) with (tp1, tp2), should we allow this operation?
> 
> Two options. First, we check strictly. The range must be covered and equal. But if user really want to new range of tp1 and tp2? So the second option is, we only check for conflicts and not for coverage.

Oh I see.

My concern is that Doris should not allow the existence of holes at this time. If there is a hole, it may cause problems in other modules. So I am more inclined to check if it is covered. For the problem you said, then you need the user to create another 3 placeholders partition tp3 [0, 10), tp4 [11, 15), tp5 [18, 20). In this case, we can make the user operate successfully.

**Comment by morningman** [comment]
> My concern is that Doris should not allow the existence of holes at this time. If there is a hole, it may cause problems in other modules. So I am more inclined to check if it is covered. For the problem you said, then you need the user to create another 3 placeholders partition tp3 [0, 10), tp4 [11, 15), tp5 [18, 20). In this case, we can make the user operate successfully.

Actually, Doris do support holes in partition range, and it will not cause any problem.(It is same as user drop a partition in the middle of the ranges).

I think let user create the placeholders is not friendly, so may be we can give an option to user, the default behavior is to check strictly. But if user insist, he can set an option to allow replacing partitions with holes.

**Comment by imay** [comment]
> Actually, Doris do support holes in partition range, and it will not cause any problem.(It is same as user drop a partition in the middle of the ranges).

If it will work fine, it is OK to leave a hole after swap partitions.
 
> I think let user create the placeholders is not friendly, so may be we can give an option to user, the default behavior is to check strictly. But if user insist, he can set an option to allow replacing partitions with holes.

That will be great.
