### ISSUE TITLE
insert select into bitmap column with negative number may be filtered

### ISSUE THREAD

**Issue by jmk1011** [apache/incubator-doris#2699]
**Describe the bug**
insert select into bitmap column with negative number may be filtered
filter reson:
Reason: The to_bitmap function argument: -2147483647 type isn't integer family or exceed unsigned integer max value 4294967295. src line: [bitmap_set]; 

this is different from https://github.com/apache/incubator-doris/issues/2678 .the column in baseall is more than baseall table in 2678

**To Reproduce**
1. CREATE TABLE `baseall` (
  `k1` tinyint(4) NULL COMMENT "",
  `k2` smallint(6) NULL COMMENT "",
  `k3` int(11) NULL COMMENT "",
  `k4` bigint(20) NULL COMMENT "",
  `k5` decimal(9, 3) NULL COMMENT "",
  `k6` char(5) NULL COMMENT "",
  `k10` date NULL COMMENT "",
  `k11` datetime NULL COMMENT "",
  `k7` varchar(20) NULL COMMENT "",
  `k8` double MAX NULL COMMENT "",
  `k9` float SUM NULL COMMENT ""
) ENGINE=OLAP
AGGREGATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`, `k6`, `k10`, `k11`, `k7`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`) BUCKETS 5
PROPERTIES (
"storage_type" = "COLUMN"
);

2. insert into baseall values (12,32767,-2147483647,9223372036854775807,243.325,'false','1991-08-11','2013-04-02 15:16:52','l',-564.898,3.1415927);
insert into baseall values (3,1989,1002,11011905,24453.325,'false','2012-03-14','2000-01-01 00:00:00','y',78945,3654);
insert into baseall values (10,1991,5014,9223372036854775807,-258.369,'false','2015-04-02','2013-04-02 15:16:52','w',-123456.54,0.235);
insert into baseall values (8,255,2147483647,11011920,-0.123,'true','1989-03-21','9999-11-11 12:12:00','w',987456.123,12.14);
insert into baseall values (9,1991,-2147483647,11011902,-654.654,'true','1991-08-11','1989-03-21 13:11:00','w',0,69.123);
insert into baseall values (11,1989,25699,-9223372036854775807,0.666,'true','2015-04-02','1989-03-21 13:11:00','y',-987.001,4.336);
insert into baseall values (13,-32767,2147483647,-9223372036854775807,100.001,'false','2015-04-02','2015-04-02 00:00:00','w',123.456,3.1415927);
insert into baseall values (14,255,103,11011902,0,'false','2015-04-02','2015-04-02 00:00:00','',3.141592654,2.036);
insert into baseall values (7,-32767,1002,7210457,3.141,'false','1988-03-21','1901-01-01 00:00:00','j',0,6058);
insert into baseall values (6,32767,3021,123456,604587,'true','2014-11-11','2015-03-13 12:36:38','y',0.1,80699);
insert into baseall values (4,1991,3021,-11011907,243243.325,'false','3124-10-10','2015-03-13 10:30:00','y',2.06,-0.001);
insert into baseall values (5,1985,5014,-11011903,243.325,'true','2015-01-01','2015-03-13 12:36:38','d',-0,-365);
insert into baseall values (1,1989,1001,11011902,123.123,'true','1989-03-21','1989-03-21 13:00:00','w',0.1,6.333);
insert into baseall values (2,1986,1001,11011903,1243.5,'false','1901-12-31','1989-03-21 13:00:00','w',20.268,789.25);
insert into baseall values (15,1992,3021,11011920,0,'true','9999-12-12','2015-04-02 00:00:00','',3.141592653,20.456);

3. CREATE TABLE test_bitmap_tb ( id int COMMENT "", id1 tinyint COMMENT "", c_float float SUM COMMENT "", bitmap_set bitmap BITMAP_UNION COMMENT "" ) ENGINE=OLAP DISTRIBUTED BY HASH(id, id1) BUCKETS 5 PROPERTIES ( "storage_type" = "COLUMN" );

4. insert into test_bitmap_tb select k3, k1, k9, TO_BITMAP(k3) from baseall;
(This phenomenon does not recur stably, you can try step-4 a few more times)

**Screenshots**
![image](https://user-images.githubusercontent.com/18320438/71953410-14a4b380-321d-11ea-9240-36df807487e1.png)
![image](https://user-images.githubusercontent.com/18320438/71953420-1ff7df00-321d-11ea-9926-1318d4fbd019.png)
![image](https://user-images.githubusercontent.com/18320438/71953484-50d81400-321d-11ea-8fc0-bab9bb87ed4f.png)

**Code Version**
https://github.com/apache/incubator-doris/commit/72fd74508607aab85be5f390579de4d7300383c8

**Comment by kangkaisen** [comment]
`The to_bitmap function argument: -2147483647 type isn't integer family or exceed unsigned integer max value 4294967295. src line: [bitmap_set];`

This is reasonable and not a issue.

**Comment by jmk1011** [comment]
but be will core. and in https://github.com/apache/incubator-doris/issues/2678, insert with the same value -2147483647 will return success.

**Comment by kangkaisen** [comment]
> #2678

Be core is bug, I will fix it.

to_bitmap only support int value from 0 to 4294967295 currently.
