### ISSUE TITLE
Reducing the duplication of code with Apache Impala

### ISSUE THREAD

**Issue by lide-reed** [apache/incubator-doris#270]
1. Find out the code, modules, components which duplicates of Impala;
2. Determine the features which could be merged to Impala under Impala
community support.
3. Define clearly the interface between the query engine and other
components, such as the storage engine, metadata management, mysql server,
load and export modules, web server and so on.
4. Separate the Impala query engine from Palo.

**Comment by EmmyMiao87** [comment]
This is a big renovation project. What is the main purpose of implantation?

**Comment by stiga-huang** [comment]
For the purpose, there is a discussion in the email thread: https://lists.apache.org/thread.html/efe1151ebb50ec64f9b674dea8923f92ff118590f25e2d1663782f28%40%3Cdev.doris.apache.org%3E

It's a pity that now Doris diverges a lot from Impala. We've seen both the Impala and Doris communities did some duplicated works, e.g. support for set operations(INTERSET, EXCEPT).

It'd save a lot of time and efforts if we can work together and concentrate on each other's domain.
