### ISSUE TITLE
The date function cannot calculate the month in which the two dates differ

### ISSUE THREAD

**Issue by chorylee001** [apache/incubator-doris#2703]
The date function cannot calculate the MONTH in which there is a difference between two dates, such as in mysql  TIMESTAMPDIFF(MONTH,'2018-10-01','2019-10-01 '),the result is 12.
What should I do?

**Comment by HangyuanLiu** [comment]
There is no function that directly supports calculating the monthly difference. Wd need support TIMESTAMPDIFF  function for Doris.

**Comment by chorylee001** [comment]
> There is no function that directly supports calculating the monthly difference. Wd need support TIMESTAMPDIFF function for Doris.

ok,thanks.
we neet it.I don't think it's just me.

**Comment by HangyuanLiu** [comment]
Hi, we have add timestampdiff function in master branch

**Comment by chorylee001** [comment]
Thank you very much,we will use it.


在 2020年1月21日，下午12:00，HangyuanLiu <notifications@github.com> 写道：

﻿

Hi, we have add timestampdiff function in master branch
