### ISSUE TITLE
load orc format file failed, because of decimal type

### ISSUE THREAD

**Issue by zhangy5** [apache/incubator-doris#2741]
**Describe the bug**
Broker load error msg:
The field name(decimal_key) type not support.

In doris table decimal_key is DECIMAL(27,9).
In orc file, decimal_key is DECIMAL, like
      {
        "columnId": 8,
        "count": 59210,
        "hasNull": false,
        "min": "-999995094.612564",
        "max": "9999856396.221593",
        "sum": "267010084965029.953989",
        "type": "DECIMAL"
      },

**To Reproduce**
1. create table:
REATE TABLE test_sys_pull_load_hdfs_test_all_types_orc_tb ( tinyint_key TINYINT NULL, smallint_key SMALLINT NULL, int_key INT NULL, bigint_key BIGINT NULL, largeint_key LARGEINT NULL, char_key CHAR(50) NULL, varchar_key VARCHAR(65533) NULL, decimal_key DECIMAL(27, 9) NULL, date_key DATE NULL, datetime_key DATETIME NULL, tinyint_value_max TINYINT MAX NULL, smallint_value_min SMALLINT MIN NULL, int_value_sum INT SUM NULL, bigint_value_sum BIGINT SUM NULL, largeint_value_sum LARGEINT SUM NULL, largeint_value_replace LARGEINT replace NULL, char_value_replace CHAR(50) REPLACE NULL, varchar_value_replace VARCHAR(65533) REPLACE NULL, decimal_value_replace DECIMAL(27, 9) REPLACE NULL, date_value_replace DATE REPLACE NULL, datetime_value_replace DATETIME REPLACE NULL, float_value_sum FLOAT SUM NULL, double_value_sum DOUBLE SUM NULL ) AGGREGATE KEY(tinyint_key,smallint_key,int_key,bigint_key,largeint_key,char_key,varchar_key,decimal_key,date_key,datetime_key) PARTITION BY RANGE(tinyint_key) ( PARTITION partition_a VALUES LESS THAN ("5"), PARTITION partition_b VALUES LESS THAN ("20"), PARTITION partition_c VALUES LESS THAN ("30"), PARTITION partition_d VALUES LESS THAN MAXVALUE ) DISTRIBUTED BY HASH(largeint_key, decimal_key) BUCKETS 13

2. load orc file:
LOAD LABEL label_13_10_55_58_337056_2031711585 (DATA INFILE("hdfs://host:port/user/palo/test/data/sys/pull_load/pull_load_data.orc") INTO TABLE `test_sys_pull_load_hdfs_test_all_types_orc_tb` FORMAT AS "orc") WITH BROKER "hdfs" ("username"="xx", "password"="xx")

#2491

**Comment by HangyuanLiu** [comment]
Hi，currently decimal types and timestamp types are not supported, I will provide them on the next PR as soon as possible

**Comment by zhangy5** [comment]
ok
