### ISSUE TITLE
create table error:  Timeout. Unfinished mark

### ISSUE THREAD

**Issue by crazyleeyang** [apache/incubator-doris#2745]
**Describe the bug**
when i use the following sql to create table:
```sql
CREATE TABLE `test` (
  `d1` datetime NULL COMMENT "aaa",
  `t1` bigint(20) NULL COMMENT "aaa",
  `s1` varchar(256) NULL COMMENT "aaa",
  `s2` varchar(256) REPLACE NULL COMMENT "aaa",
  `a1` int(11) REPLACE NULL COMMENT "aaa",
  `i1` int(11) REPLACE NULL COMMENT "aaa",
  `d11` varchar(128) REPLACE NULL COMMENT "aaa"
) ENGINE=OLAP
AGGREGATE KEY(`d1`, `t1`, `s1`)
DISTRIBUTED BY HASH(`s1`) BUCKETS 8
PROPERTIES (
"storage_type" = "COLUMN"
);
```

**error info**
"ERROR 1064 (HY000): Failed to create partition[test]. Timeout. Unfinished mark: 10016=467190, 10017=467194, 10017=467206"

**other info**
- Version: [Doris version 0.11.16-release]
- OS: [centos]
- when "show backends", all be are alive.

**Comment by morningman** [comment]
http://doris.incubator.apache.org/documentation/cn/getting-started/data-partition.html
See "常见问题" here
