### ISSUE TITLE
Doris could not 'select' or 'insert' by presto

### ISSUE THREAD

**Issue by IanWatsons** [apache/incubator-doris#2757]
**Describe the bug**
Doris could not return the correct result when connected with presto and excute select or insert,  it will throw the error "Table '$tablename' not found".

**To Reproduce**
1. Use presto java client, version 0.230
2. "select * from tablename" or insert into tablename values()
3. Error: Table '$tablename' not found"

**Expected behavior**
Get table data

**Screenshots**
![image](https://user-images.githubusercontent.com/10363706/72322003-3e0f8480-36e0-11ea-933d-65c28ba4b06d.png)
![image](https://user-images.githubusercontent.com/10363706/72322042-5384ae80-36e0-11ea-82fc-f572b6b2144c.png)

**Comment by greeenSY** [comment]
I get the same error.
My presto client version is 0.223

**Comment by lfyzjck** [comment]
Presto raise TableNotFoundException because it could not found any valid columns from Doris.

I just found that the way Doris stored dataType is different with MySQL in `information_schema.columns` where Presto get table schema from.

Doris:
![image](https://user-images.githubusercontent.com/800042/84974187-56833f80-b155-11ea-98d5-e4447f146905.png)

MySQL:
![image](https://user-images.githubusercontent.com/800042/84974203-60a53e00-b155-11ea-9251-107ea5420012.png)

The key is that dataType size is stored in other columns in MySQL.

in Presto BaseJdbcClient.java
```
public List<JdbcColumnHandle> getColumns(ConnectorSession session, JdbcTableHandle tableHandle)
    {
        try (Connection connection = connectionFactory.openConnection(JdbcIdentity.from(session))) {
            try (ResultSet resultSet = getColumns(tableHandle, connection.getMetaData())) {
                List<JdbcColumnHandle> columns = new ArrayList<>();
                while (resultSet.next()) {
                    JdbcTypeHandle typeHandle = new JdbcTypeHandle(
                            resultSet.getInt("DATA_TYPE"),
                            resultSet.getInt("COLUMN_SIZE"),
                            resultSet.getInt("DECIMAL_DIGITS"));
                    Optional<ReadMapping> columnMapping = toPrestoType(session, typeHandle);
                    // skip unsupported column types
                    if (columnMapping.isPresent()) {
                        String columnName = resultSet.getString("COLUMN_NAME");
                        boolean nullable = columnNullable == resultSet.getInt("NULLABLE");
                        columns.add(new JdbcColumnHandle(connectorId, columnName, typeHandle, columnMapping.get().getType(), nullable));
                    }
                }
                if (columns.isEmpty()) {
                    // In rare cases (e.g. PostgreSQL) a table might have no columns.
                    throw new TableNotFoundException(tableHandle.getSchemaTableName());
                }
                return ImmutableList.copyOf(columns);
            }
        }
        catch (SQLException e) {
            throw new PrestoException(JDBC_ERROR, e);
        }
    }
```
