### ISSUE TITLE
Can Doris support fe and be without binding dead IP

### ISSUE THREAD

**Issue by wkhappy1** [apache/incubator-doris#2770]
In k8s, if the pod in k8s is restarted, the IP corresponding to this pod is changed, but the hostname remains the same. Can  not bind to IP but hook with hostname

**Comment by EmmyMiao87** [comment]
If you deploy doris in K8S, the better way is use host network which ip is stable.

**Comment by liangyongz** [comment]
You can try hostNetwork.
spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

https://github.com/liangyongz/doris-on-k8s
