### ISSUE TITLE
sh build.sh执行报错

### ISSUE THREAD

**Issue by itzzy** [apache/incubator-doris#2785]
[WARNING:/root/incubator-doris/gensrc/thrift/PaloInternalService.thrift:103] 64-bit constant "107374182400" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PaloInternalService.thrift:105] 64-bit constant "2147483648" may not work in all languages.

touch /root/incubator-doris/gensrc/thrift/../build//java/.MetaStoreService.tm
/var/local/thirdparty/installed/bin/thrift -I /root/incubator-doris/gensrc/thrift -I /root/incubator-doris/gensrc/thrift/../build//thrift/ --gen java -out /root/incubator-doris/gensrc/thrift/../build//java /root/incubator-doris/gensrc/thrift/HeartbeatService.thrift
touch /root/incubator-doris/gensrc/thrift/../build//java/.HeartbeatService.tm
/var/local/thirdparty/installed/bin/thrift -I /root/incubator-doris/gensrc/thrift -I /root/incubator-doris/gensrc/thrift/../build//thrift/ --gen java -out /root/incubator-doris/gensrc/thrift/../build//java /root/incubator-doris/gensrc/thrift/Ddl.thrift
touch /root/incubator-doris/gensrc/thrift/../build//java/.Ddl.tm
/var/local/thirdparty/installed/bin/thrift -I /root/incubator-doris/gensrc/thrift -I /root/incubator-doris/gensrc/thrift/../build//thrift/ --gen java -out /root/incubator-doris/gensrc/thrift/../build//java /root/incubator-doris/gensrc/thrift/Partitions.thrift
touch /root/incubator-doris/gensrc/thrift/../build//java/.Partitions.tm
/var/local/thirdparty/installed/bin/thrift -I /root/incubator-doris/gensrc/thrift -I /root/incubator-doris/gensrc/thrift/../build//thrift/ --gen java -out /root/incubator-doris/gensrc/thrift/../build//java /root/incubator-doris/gensrc/thrift/Descriptors.thrift
touch /root/incubator-doris/gensrc/thrift/../build//java/.Descriptors.tm
/var/local/thirdparty/installed/bin/thrift -I /root/incubator-doris/gensrc/thrift -I /root/incubator-doris/gensrc/thrift/../build//thrift/ --gen java -out /root/incubator-doris/gensrc/thrift/../build//java /root/incubator-doris/gensrc/thrift/AgentService.thrift
[WARNING:/root/incubator-doris/gensrc/thrift/PaloInternalService.thrift:94] 64-bit constant "2147483648" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PaloInternalService.thrift:100] 64-bit constant "9223372036854775807" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PaloInternalService.thrift:103] 64-bit constant "107374182400" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PaloInternalService.thrift:105] 64-bit constant "2147483648" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PlanNodes.thrift:563] 64-bit constant "12188490189880" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PlanNodes.thrift:563] 64-bit constant "12188490189880" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PlanNodes.thrift:563] 64-bit constant "12188490189880" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PlanNodes.thrift:563] 64-bit constant "12188490189880" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PaloInternalService.thrift:94] 64-bit constant "2147483648" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PaloInternalService.thrift:100] 64-bit constant "9223372036854775807" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PaloInternalService.thrift:103] 64-bit constant "107374182400" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PaloInternalService.thrift:105] 64-bit constant "2147483648" may not work in all languages.

touch /root/incubator-doris/gensrc/thrift/../build//java/.AgentService.tm
/var/local/thirdparty/installed/bin/thrift -I /root/incubator-doris/gensrc/thrift -I /root/incubator-doris/gensrc/thrift/../build//thrift/ --gen java -out /root/incubator-doris/gensrc/thrift/../build//java /root/incubator-doris/gensrc/thrift/Status.thrift
touch /root/incubator-doris/gensrc/thrift/../build//java/.Status.tm
/var/local/thirdparty/installed/bin/thrift -I /root/incubator-doris/gensrc/thrift -I /root/incubator-doris/gensrc/thrift/../build//thrift/ --gen java -out /root/incubator-doris/gensrc/thrift/../build//java /root/incubator-doris/gensrc/thrift/RuntimeProfile.thrift
touch /root/incubator-doris/gensrc/thrift/../build//java/.RuntimeProfile.tm
/var/local/thirdparty/installed/bin/thrift -I /root/incubator-doris/gensrc/thrift -I /root/incubator-doris/gensrc/thrift/../build//thrift/ --gen java -out /root/incubator-doris/gensrc/thrift/../build//java /root/incubator-doris/gensrc/thrift/MetricDefs.thrift
touch /root/incubator-doris/gensrc/thrift/../build//java/.MetricDefs.tm
/var/local/thirdparty/installed/bin/thrift -I /root/incubator-doris/gensrc/thrift -I /root/incubator-doris/gensrc/thrift/../build//thrift/ --gen java -out /root/incubator-doris/gensrc/thrift/../build//java /root/incubator-doris/gensrc/thrift/PaloService.thrift
touch /root/incubator-doris/gensrc/thrift/../build//java/.PaloService.tm
/var/local/thirdparty/installed/bin/thrift -I /root/incubator-doris/gensrc/thrift -I /root/incubator-doris/gensrc/thrift/../build//thrift/ --gen java -out /root/incubator-doris/gensrc/thrift/../build//java /root/incubator-doris/gensrc/thrift/DorisExternalService.thrift
touch /root/incubator-doris/gensrc/thrift/../build//java/.DorisExternalService.tm
/var/local/thirdparty/installed/bin/thrift -I /root/incubator-doris/gensrc/thrift -I /root/incubator-doris/gensrc/thrift/../build//thrift/ --gen java -out /root/incubator-doris/gensrc/thrift/../build//java /root/incubator-doris/gensrc/thrift/Metrics.thrift
touch /root/incubator-doris/gensrc/thrift/../build//java/.Metrics.tm
/var/local/thirdparty/installed/bin/thrift -I /root/incubator-doris/gensrc/thrift -I /root/incubator-doris/gensrc/thrift/../build//thrift/ --gen java -out /root/incubator-doris/gensrc/thrift/../build//java /root/incubator-doris/gensrc/thrift/Planner.thrift
[WARNING:/root/incubator-doris/gensrc/thrift/PlanNodes.thrift:563] 64-bit constant "12188490189880" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PlanNodes.thrift:563] 64-bit constant "12188490189880" may not work in all languages.

touch /root/incubator-doris/gensrc/thrift/../build//java/.Planner.tm
/var/local/thirdparty/installed/bin/thrift -I /root/incubator-doris/gensrc/thrift -I /root/incubator-doris/gensrc/thrift/../build//thrift/ --gen java -out /root/incubator-doris/gensrc/thrift/../build//java /root/incubator-doris/gensrc/thrift/NetworkTest.thrift
touch /root/incubator-doris/gensrc/thrift/../build//java/.NetworkTest.tm
/var/local/thirdparty/installed/bin/thrift -I /root/incubator-doris/gensrc/thrift -I /root/incubator-doris/gensrc/thrift/../build//thrift/ --gen java -out /root/incubator-doris/gensrc/thrift/../build//java /root/incubator-doris/gensrc/thrift/BackendService.thrift
[WARNING:/root/incubator-doris/gensrc/thrift/PaloInternalService.thrift:94] 64-bit constant "2147483648" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PaloInternalService.thrift:100] 64-bit constant "9223372036854775807" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PaloInternalService.thrift:103] 64-bit constant "107374182400" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PaloInternalService.thrift:105] 64-bit constant "2147483648" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PlanNodes.thrift:563] 64-bit constant "12188490189880" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PlanNodes.thrift:563] 64-bit constant "12188490189880" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PlanNodes.thrift:563] 64-bit constant "12188490189880" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PlanNodes.thrift:563] 64-bit constant "12188490189880" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PaloInternalService.thrift:94] 64-bit constant "2147483648" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PaloInternalService.thrift:100] 64-bit constant "9223372036854775807" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PaloInternalService.thrift:103] 64-bit constant "107374182400" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PaloInternalService.thrift:105] 64-bit constant "2147483648" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PaloInternalService.thrift:94] 64-bit constant "2147483648" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PaloInternalService.thrift:100] 64-bit constant "9223372036854775807" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PaloInternalService.thrift:103] 64-bit constant "107374182400" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PaloInternalService.thrift:105] 64-bit constant "2147483648" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PlanNodes.thrift:563] 64-bit constant "12188490189880" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PlanNodes.thrift:563] 64-bit constant "12188490189880" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PlanNodes.thrift:563] 64-bit constant "12188490189880" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PlanNodes.thrift:563] 64-bit constant "12188490189880" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PaloInternalService.thrift:94] 64-bit constant "2147483648" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PaloInternalService.thrift:100] 64-bit constant "9223372036854775807" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PaloInternalService.thrift:103] 64-bit constant "107374182400" may not work in all languages.

[WARNING:/root/incubator-doris/gensrc/thrift/PaloInternalService.thrift:105] 64-bit constant "2147483648" may not work in all languages.

touch /root/incubator-doris/gensrc/thrift/../build//java/.BackendService.tm
make[1]: Leaving directory `/root/incubator-doris/gensrc/thrift'
Build Backend
-- The CXX compiler identification is GNU 7.3.0
-- The C compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /usr/bin/../bin/g++
-- Check for working CXX compiler: /usr/bin/../bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/../bin/gcc
-- Check for working C compiler: /usr/bin/../bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type is RELEASE
-- Build target arch is x86_64
-- make test: OFF
-- defined PIC_LIB_PATH
-- build gensrc if necessary
make: Entering directory `/root/incubator-doris/gensrc'
make -C script
make[1]: Entering directory `/root/incubator-doris/gensrc/script'
/root/incubator-doris/gensrc/script/gen_build_version.sh
make[1]: Leaving directory `/root/incubator-doris/gensrc/script'
make -C proto
make[1]: Entering directory `/root/incubator-doris/gensrc/proto'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/root/incubator-doris/gensrc/proto'
make -C thrift
make[1]: Entering directory `/root/incubator-doris/gensrc/thrift'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/root/incubator-doris/gensrc/thrift'
make: Leaving directory `/root/incubator-doris/gensrc'
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   thread
--   regex
--   filesystem
--   system
--   date_time
--   program_options
--   chrono
--   atomic
-- /var/local/thirdparty/installed/lib/libboost_thread.a/var/local/thirdparty/installed/lib/libboost_regex.a/var/local/thirdparty/installed/lib/libboost_filesystem.a/var/local/thirdparty/installed/lib/libboost_system.a/var/local/thirdparty/installed/lib/libboost_date_time.a/var/local/thirdparty/installed/lib/libboost_program_options.a/var/local/thirdparty/installed/lib/libboost_chrono.a/var/local/thirdparty/installed/lib/libboost_atomic.a
CMake Error at CMakeLists.txt:266 (message):
  Could not find clang++

-- Configuring incomplete, errors occurred!
See also "/root/incubator-doris/be/build/CMakeFiles/CMakeOutput.log".
See also "/root/incubator-doris/be/build/CMakeFiles/CMakeError.log".

docker环境，编译出错

**Comment by morningman** [comment]
which docker image version did you get?

**Comment by yangbiao121** [comment]
> which docker image version did you get?
USE docker got the following issue
 docker Version:      17.05.0-ce
Doris version 0.11.38

**ERROR  INFO**
build.sh: line 41: /var/local/thirdparty/build-thirdparty.sh: No such file or directory
