### ISSUE TITLE
unable to login with mysql -h xxx -uxxx after changing root password

### ISSUE THREAD

**Issue by wenbronk** [apache/incubator-doris#2797]
unable to login with terminal after changing root password;

> centos8
double network card with vmware

when i change password for root `SET PASSWORD FOR 'root' = PASSWORD('your_password');'
i can't login again, but use navicat test success

**Comment by imay** [comment]
you can try `mysql --default-auth=mysql_native_password -h host -P port`

**Comment by wenbronk** [comment]
可以登陆了, 谢谢!!!
