### ISSUE TITLE
doris can't create table according to help-manual

### ISSUE THREAD

**Issue by blackfox1983** [apache/incubator-doris#2807]
in help-manual
![image](https://user-images.githubusercontent.com/6658943/72694904-97106a00-3b71-11ea-99cb-db397e5a60d9.png)

actual
![image](https://user-images.githubusercontent.com/6658943/72694918-aabbd080-3b71-11ea-9ffe-1350ef6c2dd0.png)

**Comment by kangkaisen** [comment]
This is not a issue. 
The doc is for 0.11. bug your code should has this PR:
https://github.com/apache/incubator-doris/pull/1948/files

Because I see you could create table with `id2 bitmap bitmap_union NULL` successfully.
