### ISSUE TITLE
doris can't insert into table(bitmap) after created it

### ISSUE THREAD

**Issue by blackfox1983** [apache/incubator-doris#2810]
according the manual, i create the table.

CREATE TABLE `bitmap_test` (
  `id` int(11) NULL COMMENT "",
  `id2` bitmap bitmap_union NULL
) ENGINE=OLAP
AGGREGATE KEY(`id`)
DISTRIBUTED BY HASH(`id`) BUCKETS 10;

then insert some data. it show some errors:

> insert into bitmap_test values(1, to_bitmap(1));
ERROR 1064 (HY000): Failed to commit txn 17855. Tablet [230684] success replica num 0 is less then quorum replica num 2 while error backends 10002,10003,10005

then i check be'log:
W0120 10:32:24.639506 227768 column_writer.cpp:123] Unspported filed type. field=id2, type=25
W0120 10:32:24.639767 227768 segment_writer.cpp:72] fail to create writer
W0120 10:32:24.639818 227768 column_data_writer.cpp:264] fail to init segment writer
W0120 10:32:24.639847 227768 column_data_writer.cpp:111] fail to add segment. [res=-104]
W0120 10:32:24.639879 227768 column_data_writer.cpp:181] failed to flush data while attaching row cursor.[res=-104]

**Comment by kangkaisen** [comment]
This issue is duplicated with https://github.com/apache/incubator-doris/issues/2406 and has been fixed.
