### ISSUE TITLE
[Proposal] support spark load

### ISSUE THREAD

**Issue by kangpinghuang** [apache/incubator-doris#2855]
For many users who want to load data into doris for the first time, they have large amount of data, about 20G+，it is hard to support to load so large data into doris at one time. To resolve this problem, I proposal a new solution to load data by using spark cluster. Here is my design. please review it and give me some comments.

**Comment by kangpinghuang** [comment]
[spark_load.pdf](https://github.com/apache/incubator-doris/files/4169541/spark_load.pdf)

**Comment by imay** [comment]
@kangpinghuang 
Could you please give a PR for this design? Then others can make comment for this proposal.

**Comment by kangpinghuang** [comment]
ok, I will propose a pr
