### ISSUE TITLE
[Bitmap Index] can't create index with order"alter table add index using bitmap"

### ISSUE THREAD

**Issue by IanWatsons** [apache/incubator-doris#2873]
**Describe the bug**
Doris can't create index with order"alter table table_name add index using bitmap"

**To Reproduce**
1. create table:
CREATE TABLE table_for_bitmap
(
siteid INT DEFAULT '10',
varchar_date VARCHAR(32),
pv BIGINT SUM DEFAULT '0'
)
AGGREGATE KEY(siteid,varchar_date)
DISTRIBUTED BY HASH(siteid) BUCKETS 10;

2. add bitmap index with order:
ALTER TABLE table_for_bitmap ADD INDEX index_name USING BITMAP (siteid) COMMENT 'balabala';

3. See error
ERROR 1064 (HY000): Syntax error at:
ALTER TABLE solo ADD INDEX index_name  USING BITMAP (siteid) COMMENT 'balabala'
                                       ^
Encountered: USING
Expected

**Screenshots**
![image](https://user-images.githubusercontent.com/10363706/74130547-40042f00-4c1d-11ea-8df2-ebd824b78bf6.png)

**Additional context**
You can create bitmap index with order:
"ALTER TABLE table_for_bitmap ADD INDEX index_name (siteid) COMMENT 'balabala'; "

**Comment by yangzhg** [comment]
the syntax you using is invalid the right syntax likes `ALTER TABLE table1 ADD  INDEX index_name (siteid, citycod)  [USING BITMAP] COMMENT 'balabala';`
you can refer to https://github.com/apache/incubator-doris/pull/2573
