### ISSUE TITLE
the binary files created by executing  unit test  were too large for personal PC 

### ISSUE THREAD

**Issue by uestctxq** [apache/incubator-doris#292]
**Question**
 when I execute unit test of Doris , it will create many  too large binary files  so that my personal computer throw errors like this 
```
FragmentMgrTest. PrepareFailed 

.....

run-ut.sh: line 168: 9033 Segmentation fault    ${DORIS_TEST_BINARY_DIR}/runtime/fragment_mgr_test
```
can reduce the binary files so that I can execute the unit test on my computer

**Comment by imay** [comment]
@uestctxq Thanks for your feedback.

Now we use static link for all executable binary, which can execute anywhere whether or not there are enough suitable library. However it looks like that unit test will only executed locally, So we will try to support dynamic link for unit-test to reduce binary size.
