### ISSUE TITLE
Support for custom gcc paths

### ISSUE THREAD

**Issue by Liunus** [apache/incubator-doris#297]
After installing devtoolset-7-gcc to /opt/rh/devtoolset-7/, failed when compiling:

`thirdparty/installed//include/boost/config/select_stdlib_config.hpp:18:12: fatal error: 'cstddef' file not found # include <cstddef>`

So maybe need to better support thirdparty libraries and build toolchains.

**Comment by chalsliu** [comment]
```
cd /home/user/doris/be/build/src/codegen && /home/user/doris/thirdparty/installed/llvm/bin/clang++ -gcc-toolchain /opt/rh/devtoolset-7/root/usr -std=c++11 -c -emit-llvm -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DIR_COMPILE -DNDEBUG -DHAVE_INTTYPES_H -DHAVE_NETINET_IN_H -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG -D__GLIBCXX_BITSIZE_INT_N_0=128 -D__GLIBCXX_TYPE_INT_N_0=__int128 -U_GLIBCXX_USE_FLOAT128 -DLLVM_ON_UNIX -I/home/user/doris/thirdparty/installed//llvm/include -I/home/user/doris/be/src -I/home/user/doris/be/../gensrc/build/ -I/home/user/doris/thirdparty/installed//include -I/home/user/doris/thirdparty/installed//include/thrift/ -I/home/user/doris/thirdparty/installed//include/event/ -I/home/user/doris/thirdparty/installed//gperftools/include -I/opt/rh/devtoolset-7/root/usr/include /home/user/doris/be/src/codegen/doris_ir.cpp -o /home/user/doris/be/../gensrc/build//doris_ir/doris_no_sse_tmp.bc
```
This step caused the error because the header file could not be found.

**Comment by chalsliu** [comment]
> what path should be added to CPLUS_INCLUDE_PATH??

The correct header file path of custom GCC, by default, clang can't find them. 
So it should be set explicitly.

**Comment by imay** [comment]
> > what path should be added to CPLUS_INCLUDE_PATH??
> 
> The correct header file path of custom GCC, by default, clang can't find them.
> So it should be set explicitly.

With `-gcc-toolchain`, LLVM should find gcc's path. And what's in your `${GCCHOME}/lib/gcc/` directory?

**Comment by chalsliu** [comment]
> > > what path should be added to CPLUS_INCLUDE_PATH??
> > 
> > 
> > The correct header file path of custom GCC, by default, clang can't find them.
> > So it should be set explicitly.
> 
> With `-gcc-toolchain`, LLVM should find gcc's path. And what's in your `${GCCHOME}/lib/gcc/` directory?

/opt/rh/devtoolset-7/root/usr/bin/gcc on my server.

**Comment by imay** [comment]
What is in `/opt/rh/devtoolset-7/root/usr/bin/gcc/lib/gcc`

**Comment by chalsliu** [comment]
> What is in `/opt/rh/devtoolset-7/root/usr/bin/gcc/lib/gcc`

/opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/

**Comment by imay** [comment]
> /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/

Could you reinstall gcc with three bit version `x86_64-redhat-linux/7.3.0` other than `x86_64-redhat-linux/7`?

**Comment by chalsliu** [comment]
> > /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/
> 
> Could you reinstall gcc with three bit version `x86_64-redhat-linux/7.3.0` other than `x86_64-redhat-linux/7`?

After install gcc in this way,
```
sudo yum install centos-release-scl
sudo yum install devtoolset-7-gcc*
```
There is only one version number by default.

**Comment by chalsliu** [comment]
Another solution:
1. Find default header file paths of DORIS_GCC_HOME and set as enviroment variable CLANG_COMPATIBLE_FLAGS.
2. Explicitly add these paths to CLANG_INCLUDE_FLAGS in be/CMakeLists.txt
