### ISSUE TITLE
Support alter non-OLAP table. e.g. doris on es

### ISSUE THREAD

**Issue by BabySid** [apache/incubator-doris#2999]
i use doris on es in our production environment. and offenly i add some columns when after added some fields in es.

now i need drop table and re-create table because doris is not supporting alter non-olap table.
it maybe make service offline because it cannot run sql on the table.

can doris support alter table (add / remove column) when es-mapping modified?

or has a mechanism that can sync field from es automatic? 

thanks

**Comment by morningman** [comment]
We will consider it later.

**Comment by blackfox1983** [comment]
@wuyunfeng how is the progress?
