### ISSUE TITLE
Support bulk loading from S3 compatible distributed storage

### ISSUE THREAD

**Issue by yingfeng** [apache/incubator-doris#3]
S3 compatible is more and more prevalent especially for cloud native applications, as a result, it's reasonable to encapsulate a S3 compatible wrapper to fs_broker to make Palo more popular on multiple clouds.

**Comment by bigdata86** [comment]
good idea

**Comment by maruyue** [comment]
这个在下一个版本，我们会开发引入

**Comment by imay** [comment]
This is supported through #3003
