### ISSUE TITLE
多租户请求隔离模式

### ISSUE THREAD

**Issue by BabySid** [apache/incubator-doris#3046]
问题：
使用doris做数据存储，一般会有多个团队的请求来访问同一份数据，这个里面会有两个问题需要考虑：
1、避免各个请求在既定资源下互相影响（延迟）。如一个不重要的请求如果把集群资源打满，会影响其他重要请求的延迟
2、也方便对各个请求消耗的资源进行独立结算。如可以方便统计某一类请求消耗的cpu、mem……

从用户视角希望看到的是：
1、请求上可以打1级、2级的tag，用来区分一级分组和一级下二级分组。方便做管理和隔离（这个是必选，没有这个什么都没法做）
2、不同的tag会指定不同的资源来做查询分析
3、请求可以基于tag设置优先级，调整请求队列的执行顺序（比如请求之间任务抢占）。主要解决高优请求资源不足时可以抢占低优的请求对列（这个可以低优，主要是因为业务侧系统可以设计队列排序）
4、tag->资源的配置希望可以在doris内部配置，避免外部用户修改。tag的使用可以类似这样：
    set tag=A,B; select * from tbl where id = 100;
    使用tagA以及二级tagB对应的资源来运行后面的sql

**Comment by blackfox1983** [comment]
上述的4，主要的目的是 不希望业务侧的sql需要修改，外围的tag制定可以有一个官方的语法灵活指定即可，一般来说，在系统中，我们可以外围封装这部分逻辑对业务透明掉
