### ISSUE TITLE
[Stream Load]Invalid rollback for stream load

### ISSUE THREAD

**Issue by WingsGo** [apache/incubator-doris#3053]
**Describe the bug**
For #1998 solve the PUBLISH_TIMEOUT will cause BE rollback txn incorrect, but i found there is still some bug. As shown in following log, the txn committed succefully, but FE receive a rollback request
```
2020-03-07 20:57:31,450 INFO 7812 [GlobalTransactionMgr.commitTransaction():429] transaction:[TransactionState. transaction id: 48471692, label: xxx db id: 10005, coordinator: BE: xxx, transaction status: COMMITTED, error replicas num: 2, replica ids: 64461890,66187307, prepare time: 1583585844933, commit time: 1583585851450, finish time: -1, reason: ] successfully committed
2020-03-07 20:57:36,451 INFO 10956 [FrontendServiceImpl.loadTxnRollback():723] receive txn rollback request. db: xxx, tbl: xxx, txn id: 48471692, reason: transaction commit successfully, BUT data will be visible later, backend: xxx
```
BE's log:

```
W0307 20:55:19.606360 157168 stream_load_executor.cpp:192] commit transaction failed, errmsg=transaction commit successfully, BUT data will be visible laterid=a0481d6290973230-1fe841af6df5088b, job id=-1, txn id=48470900, label=xxx
I0307 21:25:42.506554 156973 txn_manager.cpp:496] find expire pending data.  tablet_id=64461864 schema_hash=1937251931 tablet_uid=0841acc74eba0dee-576e37036f499486 transaction_id=48470900 exist_sec=1829
```

I found the reason is that the code in following should also add judge if status is PUBLISH_TIMEOUT, if it is, we shouldn't rollback the txn
```
Status status(result.status);
    if (!status.ok()) {
        LOG(WARNING) << "commit transaction failed, errmsg=" << status.get_error_msg()
            << ctx->brief();
        return status;
    }
```

**Comment by morningman** [comment]
Are you sure the problem is here?
in `stream_load_executor->commit_txn()`, if the FE return a PUBLISH_TIMEOUT status, it return will this status directly to the caller(`_handle()` in `stream_load.cpp`).

And in `_handle()`, it will check the status' code, and only if it is NOT the PUBLISH_TIMEOUT, it will send a roll back request.

**Comment by WingsGo** [comment]
https://github.com/apache/incubator-doris/blob/c83729435f45aa6d2d93c644ba80aa10189dd962/be/src/runtime/stream_load/stream_load_executor.cpp#L177-L198

As in code,  the warning log is `W0307 20:55:19.606360 157168 stream_load_executor.cpp:192] commit transaction failed, errmsg=transaction commit successfully, BUT data will be visible laterid=a0481d6290973230-1fe841af6df5088b, job id=-1, txn id=48470900, label=xxx
` I know that _handle() will check the staus' code, but i don't konw where to call the method `handle()` I found that the warning log means that the txn is committed successfully, but there is not a check if the txn is PUBLISH_TIMEOUT， so the warning log is printed and BE try to rollback txn. I know that `handle()` method is called by http method, maybe you can point that how `commit_txn` method call the http api to help me find out the true reason?

**Comment by WingsGo** [comment]
https://github.com/apache/incubator-doris/blob/c83729435f45aa6d2d93c644ba80aa10189dd962/be/src/runtime/stream_load/stream_load_executor.cpp#L177-L198

As in code,  the warning log is `W0307 20:55:19.606360 157168 stream_load_executor.cpp:192] commit transaction failed, errmsg=transaction commit successfully, BUT data will be visible laterid=a0481d6290973230-1fe841af6df5088b, job id=-1, txn id=48470900, label=xxx
` I know that _handle() will check the staus' code, but i don't konw where to call the method `handle()` I found that the warning log means that the txn is committed successfully, but there is not a check if the txn is PUBLISH_TIMEOUT， so the warning log is printed and BE try to rollback txn. Maybe you can point that where the method `handle()` called to help me find out the true reason?

**Comment by WingsGo** [comment]
I also have another question, why ` StreamLoadExecutor::execute_plan_fragment` is called in two method `_handle` and `_process_put` ?
