### ISSUE TITLE
it is not friendly to set quota in bytes units

### ISSUE THREAD

**Issue by kangpinghuang** [apache/incubator-doris#306]
What is the problem?
now, use alter database set data quota statement to change database's quota is hard to use because the unit is byte.
when you set 1T quota, you should first change 1T to 1099511630000 byte manually.

How to solve the problem?
to support quota in other unit: B/K/M/G/T

**Comment by imay** [comment]
I agree with you, I think it's better to write 1GB than 1073741824.

Can you contribute a PR?
