### ISSUE TITLE
how I set BACKEND?

### ISSUE THREAD

**Issue by z-Dapor** [apache/incubator-doris#3071]
mysql> ALTER SYSTEM ADD BACKEND "host:port"
    -> ;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SYSTEM ADD BACKEND "host:port"' at line 1

-------------
I dont konw "ALTER SYSTEM",can u help me?
should I change the command ?

**Comment by imay** [comment]
what you connected seems like MySQL not Doris.

**Comment by z-Dapor** [comment]
> what you connected seems like MySQL not Doris.

How to connect Doris？
I see wiki talk use mysql client and command ./mysql-client -h host -P port -uroot
then I sign mysql.
wiki: https://github.com/apache/incubator-doris/wiki/Doris-Install

**Comment by imay** [comment]
Have you install and start a Doris Frontend?

**Comment by z-Dapor** [comment]
> Have you install and start a Doris Frontend?

![image](https://user-images.githubusercontent.com/21967676/76322656-9f3d8800-631e-11ea-882c-8b58a7e6c398.png)
![image](https://user-images.githubusercontent.com/21967676/76322754-bed4b080-631e-11ea-8289-7af53c75eae8.png)
![image](https://user-images.githubusercontent.com/21967676/76322791-c7c58200-631e-11ea-8fd4-158a96671bfc.png)
I build FE,BE in docker,and mount source on mac disk.
I dont konw how to set conf fe&be.conf property: priority_networks
my mac IP is  = 172.17.47.36;I just set priority_networks = 172.17.47.36
then cd output/fe/bin/ and nohup start fe.
Look at the log above ⬆️ 
It looks normal.

**Comment by z-Dapor** [comment]
![image](https://user-images.githubusercontent.com/21967676/76374236-95973d00-637d-11ea-9ab8-261a3ff6a8cb.png)
"Unrecognized option: -o" in start_fe.sh

**Comment by z-Dapor** [comment]
![image](https://user-images.githubusercontent.com/21967676/76387831-b625be00-63a2-11ea-97cd-a5472dc50515.png)
what happened ? how to fix it

**Comment by z-Dapor** [comment]
oh...f**k,
end.
I load the source and buid in Idea,then start FE And Read the source.
I fix it.
by delete fe/image and bdb.
God.
