### ISSUE TITLE
use docker build error

### ISSUE THREAD

**Issue by stalary** [apache/incubator-doris#3072]
**Describe the bug**
use docker build error
docker run -it -v  /Users/mac/incubator-doris-0.11.0-rc01:/root/incubator-doris-0.11.0-rc01 apachedoris/doris-dev:build-env-1.1

**Screenshots**
<img width="1440" alt="屏幕快照 2020-03-11 10 32 32" src="https://user-images.githubusercontent.com/24592373/76376612-b2367380-6383-11ea-8adc-c8a58cbb6d1c.png">

**Comment by imay** [comment]
This is because the bad network. You need to try more

**Comment by stalary** [comment]
I tried many times, but it didn't work. I look the return is 403. Is there something wrong with this package?

**Comment by stalary** [comment]
Where can I find the compiled executable package?

**Comment by trueeyu** [comment]
@stalary modify the fe/pom.xm add a new repository, try?

> <repositories>
                <repository>
                    <id>aliyun</id>
                    <name>aliyun maven</name>
                    <url>http://maven.aliyun.com/nexus/content/groups/public/</url>
                </repository>
               ...

**Comment by stalary** [comment]
<img width="1435" alt="屏幕快照 2020-03-11 15 42 40" src="https://user-images.githubusercontent.com/24592373/76393662-fa1ec000-63ae-11ea-9650-556946609ce9.png">
@trueeyu It still doesn't seem to work

**Comment by XShun** [comment]
vi `fe/pom.xml` change `http://repo.spring.io/plugins-release/` to `https://repo.spring.io/plugins-release/` .
http -> https

**Comment by XShun** [comment]
@stalary vi `fe/pom.xml` change `http://repo.spring.io/plugins-release/` to `https://repo.spring.io/plugins-release/`.
http -> https

**Comment by stalary** [comment]
@XShun That solved my problem. Thank you
