### ISSUE TITLE
[Proposal] create table stmt support set rowset type

### ISSUE THREAD

**Issue by trueeyu** [apache/incubator-doris#3082]
Currently, if i want't use the segment v2，i should set the global variable default_rowset_type=beta，it's not convenient and not easy to understand。

It's better the create table stmt support set rowset type;

How can i check the rowset type of table ?

**Comment by kangpinghuang** [comment]
hi, Now the meta of table do not contain the rowset type property in FE, If you think it is useful to specify the storage rowset type in create tablet statement, you can do it as the following steps:
1. add the storage rowset type into the table meta in FE
2. add the storage rowset type property in create table statement
3.set the preferred_rowset_type in tablet meta in BE

BTW, here is a PR you can reference: https://github.com/apache/incubator-doris/pull/2294/files.
preferred_rowset_type is also used in this pr.
