### ISSUE TITLE
use datagrip connect fe error

### ISSUE THREAD

**Issue by stalary** [apache/incubator-doris#3085]
**Describe the bug**
use datagrip connect fe error
`[HY000][1193] errCode = 2, detailMessage = Unknown system variable 'event_scheduler'.
errCode = 2, detailMessage = Unknown system variable 'event_scheduler'
`

**Comment by stalary** [comment]
I use mysql-driver version is 5.1.35

**Comment by stalary** [comment]
Is mysql version too low?I see it's 5.1.0

**Comment by stalary** [comment]
@kangkaisen

**Comment by kangkaisen** [comment]
@stalary This is Doris don't support this `event_scheduler ` system variable. 
We will support `event_scheduler`   system variable and  Fix this issue

**Comment by stalary** [comment]
> @stalary This Because Doris don't support this `event_scheduler ` system variable.
> We will support `event_scheduler` system variable and Fix this issue

thanks

**Comment by gengjun-git** [comment]
@stalary This error occurs when datagrip attempts to sync schemas from Doris. Connection can be established however. You can close the sync in the Options tab.
![Selection_134](https://user-images.githubusercontent.com/54172532/76923732-3b632280-690f-11ea-93ba-ae65a7818e1d.png)

**Comment by gengjun-git** [comment]
#3144 PR

**Comment by stalary** [comment]
> @stalary This error occurs when datagrip attempts to sync schemas from Doris. Connection can be established however. You can close the sync in the Options tab.
> ![Selection_134](https://user-images.githubusercontent.com/54172532/76923732-3b632280-690f-11ea-93ba-ae65a7818e1d.png)

I cannot see the database after a successful connection

**Comment by stalary** [comment]
<img width="285" alt="屏幕快照 2020-03-25 18 20 36" src="https://user-images.githubusercontent.com/24592373/77526309-56accf80-6ec5-11ea-887b-f0d238696eb0.png">

**Comment by morningman** [comment]
looks like some commands are not supported.
you can see the fe.audit.log to find it.

**Comment by stalary** [comment]
<img width="1440" alt="屏幕快照 2020-03-25 18 23 57" src="https://user-images.githubusercontent.com/24592373/77526592-ce7afa00-6ec5-11ea-9765-4ab254ec4344.png">

add schema also error
@morningman

**Comment by stalary** [comment]
<img width="1436" alt="屏幕快照 2020-03-25 18 25 28" src="https://user-images.githubusercontent.com/24592373/77526825-274a9280-6ec6-11ea-85df-0b3046c075c7.png">

**Comment by stalary** [comment]
`
2020-03-27 23:06:09,462 WARN 138 [ConnectProcessor.analyze():232] origin_stmt: /* ApplicationName=DataGrip 2019.3.4 */ select table_name from information_schema.tables
        where table_schema collate utf8_general_ci = 'information_schema'
          and table_name collate utf8_general_ci = 'parameters'; Analyze error message: Syntax error in line 2:
        where table_schema collate utf8_general_ci = 'i...
                           ^
Encountered: COLLATE
Expected: ||, COMMA
`

**Comment by funyeah** [comment]
![image](https://user-images.githubusercontent.com/19163232/86433315-fbdd0c80-bd2c-11ea-89d3-f7c7c4f80b24.png)

**Comment by Chase-Chen0110** [comment]
thanks a lot！

**Comment by SweetCarter** [comment]
it was useful 泰裤拉
