### ISSUE TITLE
How do I import the hive table in orc format

### ISSUE THREAD

**Issue by stalary** [apache/incubator-doris#3089]
How do I import orc - formatted hive tables through broker？
`
2020-03-12 15:53:28  [ pool-2-thread-4:12755168 ] - [ WARN ]  failed to pread: TBrokerFD(high:6094912196621913064, low:-6970217137392478674)
org.apache.doris.broker.hdfs.BrokerException: end of file reached
`

**Comment by imay** [comment]
Hi, ORC is only supported in master brach which is not released yet.
You can test it with master branch

**Comment by stalary** [comment]
I'm using the master now, do I need to specify the broker format?

**Comment by imay** [comment]
Yes, you can type `help broker load` to see some example

**Comment by stalary** [comment]
thanks!
