### ISSUE TITLE
Can Support ORC format in EXTERNAL TABLE?

### ISSUE THREAD

**Issue by stalary** [apache/incubator-doris#3118]
I hope support ORC format in EXTERNAL TABLE.

**Comment by imay** [comment]
@HangyuanLiu 
Has this feature been supported?

**Comment by HangyuanLiu** [comment]
Using orc as an external table is not supported currently. Support for loading orc type files into doris

**Comment by stalary** [comment]
@HangyuanLiu Could you please help to implement this function? I'm not familiar with c++.

**Comment by HangyuanLiu** [comment]
Why you need this feature？external table in hdfs not support filter and predicate push-down now.
So the select  performance is low. Could you load orc file into doris ?

**Comment by stalary** [comment]
Okay, I'll use load orc file into doris.
