### ISSUE TITLE
BUILD FAILURE

### ISSUE THREAD

**Issue by ighack** [apache/incubator-doris#3129]
Build Frontend
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------< org.apache:doris-fe >-------------------------
[INFO] Building doris-fe 3.4.0
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from spring-plugins: http://repo.spring.io/plugins-release/net/sourceforge/czt/dev/cup-maven-plugin/1.6-cdh/cup-maven-plugin-1.6-cdh.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.111 s
[INFO] Finished at: 2020-03-17T07:03:32Z
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin net.sourceforge.czt.dev:cup-maven-plugin:1.6-cdh or one of its dependencies could not be resolved: Failed to read artifact descriptor for net.sourceforge.cz
t.dev:cup-maven-plugin:jar:1.6-cdh: Could not transfer artifact net.sourceforge.czt.dev:cup-maven-plugin:pom:1.6-cdh from/to spring-plugins (http://repo.spring.io/plugins-release/): Authorization failed for http://repo.spring.io/plugins-release/net/sourceforge/czt/dev/cup-maven-plugin/1.6-cdh/cup-maven-plugin-1.6-cdh.pom 403 Forbidden -> [Help 1][ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

apachedoris/doris-dev:build-env-1.1
0.11.0

**Comment by ighack** [comment]
wget http://repo.spring.io/plugins-release/net/sourceforge/czt/dev/cup-maven-plugin/1.6-cdh/cup-maven-plugin-1.6-cd
h.pom--2020-03-17 07:11:10--  http://repo.spring.io/plugins-release/net/sourceforge/czt/dev/cup-maven-plugin/1.6-cdh/cup-maven-plugin-1.6-cdh.pom
Resolving repo.spring.io (repo.spring.io)... 35.241.58.96
Connecting to repo.spring.io (repo.spring.io)|35.241.58.96|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-03-17 07:11:13 ERROR 403: Forbidden.

**Comment by ighack** [comment]
vi fe/pom.xml 
change http://repo.spring.io/plugins-release/ 
to 
https://repo.spring.io/plugins-release/.
http -> https

**Comment by pangjianfei** [comment]
in 0.12.21  https://repo.spring.io/plugins-release/ is not work too, 
I solved this problem by replace https://repository.cloudera.com/artifactory/ext-release-local with https://repo.spring.io/plugins-release/

**Comment by mmuru** [comment]
I had the same issue with released version 0.12.0, fe-build failed with the following error 
`[ERROR] Plugin net.sourceforge.czt.dev:cup-maven-plugin:1.6-cdh or one of its dependencies could not be resolved: Could not find artifact net.sourceforge.czt.dev:cup-maven-plugin:jar:1.6-cdh in spring-plugins (https://repo.spring.io/plugins-release/) -> [Help 1]`
I had to add the following in fe/pom.xml
`<pluginRepository>
     <id>cloudera-plugins</id>
      <url>https://repository.cloudera.com/content/groups/public/</url>
</pluginRepository>
`
