### ISSUE TITLE
Unknown host repository.cloudera.com: Name or service not known 

### ISSUE THREAD

**Issue by ighack** [apache/incubator-doris#3131]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12:10 min
[INFO] Finished at: 2020-03-17T07:43:09Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project doris-fe: Could not resolve dependencies for project org.apache:doris-fe:jar:3.4.0: Failed to collect dependencies at net.sourcef
orge.czt.dev:java-cup:jar:0.11-a-czt02-cdh: Failed to read artifact descriptor for net.sourceforge.czt.dev:java-cup:jar:0.11-a-czt02-cdh: Could not transfer artifact net.sourceforge.czt.dev:java-cup:pom:0.11-a-czt02-cdh from/to cloudera-thirdparty (https://repository.cloudera.com/content/repositories/third-party/): Transfer failed for https://repository.cloudera.com/content/repositories/third-party/net/sourceforge/czt/dev/java-cup/0.11-a-czt02-cdh/java-cup-0.11-a-czt02-cdh.pom: Unknown host repository.cloudera.com: Name or service not known -> [Help 1][ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by imay** [comment]
@ighack 
Have you built Doris successfully?

**Comment by ighack** [comment]
@imay 
yes

**Comment by imay** [comment]
@ighack 
OK, I will close this issue, could you please describe how you solved it?

**Comment by ighack** [comment]
I just build it again,it works
I don't know why.

**Comment by w517424787** [comment]
use this url:
<repositories>
<repository>
  <id>cloudera</id>
  <url>https://repository.cloudera.com/artifactory/cloudera-repos/</url>
</repository>
</repositories>
