### ISSUE TITLE
[Bug] Python throw Commands out of sync; you can't run this command now

### ISSUE THREAD

**Issue by morningman** [apache/incubator-doris#3139]
**Describe the bug**
When using Python Mysqldb library to execute sql on Doris. Some time it will throw
error:
```
Commands out of sync; you can't run this command now
```

**To Reproduce**

1. Execute sql like: 

```
execute("insert into table tbl1 select * from tbl2;")
```

Notice that there is a `;` at the end of the statement.

2. If the `insert` statement has some warnings, then the error will throw.

**Comment by knightvv** [comment]
I'm hitting this same problem still. Repro code:

`    conn = mysql.connector.connect(
        host=MYSQL_HOST,
        user=MYSQL_USER,
        password=MYSQL_PSWD,
        port=MYSQL_PORT
    )

    # Create a database
    cursor = conn.cursor()

    # For mysql, need to create db first
    cursor.execute(f"CREATE DATABASE IF NOT EXISTS {MYSQL_DB_NAME} DEFAULT CHARACTER SET 'utf8mb4';\
                   USE {MYSQL_DB_NAME};SHOW DATABASES;",
                   multi=True)
    
    # fetch results
    res = cursor.fetchall()
    conn.commit() # <--- throws MySQLInterfaceError: Commands out of sync; you can't run this command now`
