### ISSUE TITLE
Support to create a slave table of Mysql through real-time update

### ISSUE THREAD

**Issue by shipengAlan** [apache/incubator-doris#3161]
In data warehouse, data transfers from multiple sources is always required. And, DB,  e.g. MySQL is one of the most important.

So, can OLAP Doris(Palo) support some abilities to create a slave table for real-time synchronization with OLTP DB?

**Comment by morningman** [comment]
Doris doesn't support update and delete, so its not easy to be a slave.
But we may think to provide some tools to do this
