### ISSUE TITLE
It's dangerous to convert from segmentV1 to v2 automatic when create bitmap index

### ISSUE THREAD

**Issue by trueeyu** [apache/incubator-doris#3183]
Current create bitmap index on table with segment v1 format，will auto convert the storage format from v1 to v2, and not notify user 。
If one table has massive data of TB or PB level，It's dangerous，because it will convert all the data。
Current the segment v1 doesn't support bitmapIndex. So i proposal restrict create bitmap index on table with v1 format;

**Comment by gaodayue** [comment]
+1 It makes sense to report error when creating bitmap index on v1 table.

**Comment by morningman** [comment]
@trueeyu Hi, are you willing to submit a PR for this?

**Comment by trueeyu** [comment]
> @trueeyu Hi, are you willing to submit a PR for this?

OK! I will fix it

**Comment by morningman** [comment]
Nice.
FE may not know the segment format of a table. So maybe you need just let the alter task send
to BE. And BE will deny to do the alter task if it find that the segment format is v1.
After the alter task failed more than 3 times, the job will be cancelled automatically.

**Comment by trueeyu** [comment]
> Nice.
> FE may not know the segment format of a table. So maybe you need just let the alter task send
> to BE. And BE will deny to do the alter task if it find that the segment format is v1.
> After the alter task failed more than 3 times, the job will be cancelled automatically.

It's better to put the storage format as a property  in the metadata of the table

**Comment by trueeyu** [comment]
> > Nice.
> > FE may not know the segment format of a table. So maybe you need just let the alter task send
> > to BE. And BE will deny to do the alter task if it find that the segment format is v1.
> > After the alter task failed more than 3 times, the job will be cancelled automatically.
> 
> It's better to put the storage format as a property in the metadata of the table

#3082

**Comment by morningman** [comment]
Yes，But currently there is a transition state and a `__doris_v2` type schema change job, so it may not be easy to make a uniform identification at the table level.

**Comment by trueeyu** [comment]
> Yes，But currently there is a transition state and a `__doris_v2` type schema change job, so it may not be easy to make a uniform identification at the table level.

This is really a problem，the FE don't know the storage format of the table already created. Let me think about it;
