### ISSUE TITLE
start_fe.sh has an error in the MAC environment

### ISSUE THREAD

**Issue by stalary** [apache/incubator-doris#3217]
`ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -o
	at org.apache.commons.cli.Parser.processOption(Parser.java:383)
	at org.apache.commons.cli.Parser.parse(Parser.java:210)
	at org.apache.commons.cli.Parser.parse(Parser.java:88)
# regarding copyright ownership.  The ASF licenses this file
	at org.apache.doris.PaloFe.parseArgs(PaloFe.java:169)
	at org.apache.doris.PaloFe.start(PaloFe.java:75)
	at org.apache.doris.PaloFe.main(PaloFe.java:59)
Failed to parse command line. exit now
`
I remove -o from OPTS, it can start

**Comment by haohao0103** [comment]
@stalary  hello ,how to fix this ? i got the same question

**Comment by ghycn** [comment]
OPTS  delete -o 
then run error like this
<img width="639" alt="image" src="https://user-images.githubusercontent.com/20291615/198885633-aa028f7a-0c00-4c54-9c60-6e6541a0e0d1.png">

**Comment by codeDing18** [comment]
I remove -o from OPTS, it can start. thx
