### ISSUE TITLE
Doris version 0.11.0 dockerfile ask maven version 3.6.0，but where is it???????

### ISSUE THREAD

**Issue by yangbiao121** [apache/incubator-doris#3229]
![image](https://user-images.githubusercontent.com/26757248/77898799-4ecaa200-72ae-11ea-95b4-8a8f04591052.png)

**Comment by imay** [comment]
@yangbiao121 
1. we have fixed mvn version to 3.6.3 in master branch.
2. It is not a good idea to build docker file yourself. we have already provided a docker image, you can use it directly.

I will close this issue.
