### ISSUE TITLE
util/core_local_test.cpp run failed

### ISSUE THREAD

**Issue by morningman** [apache/incubator-doris#323]
**Describe the bug**
`TEST_F(CoreLocalTest, CoreLocalValueNormal)` failed at `ASSERT_EQ(10000 + std::thread::hardware_concurrency(), sum);`

**To Reproduce**
if `std::thread::hardware_concurrency()` is not the power of 2 or is less than 8, this unit test will be failed.
The reason is that `CoreLocalValueController` calculate the allocator size using:

```
int num_cpus = static_cast<int>(std::thread::hardware_concurrency());
_size = 8;
while (_size < num_cpus) {
    _size << 1;
}
```

**Comment by imay** [comment]
Yes, this is a bug. I'll fix it.
