### ISSUE TITLE
PTabletWriterOpenRequest should be independently configured

### ISSUE THREAD

**Issue by vagetablechicken** [apache/incubator-doris#3243]
We use `config::tablet_writer_rpc_timeout_sec` to set the rpc timeout in OlapTableSink. But sink node contains two rpc request types, `PTabletWriterOpenRequest` and `PTabletWriterAddBatchRequest`.

For example:
1. the default rpc is 10min. And the whole plan_fragment_executor timeout is 10min.
1. When I do sink->open(), if one be can't response to me, I will be blocked in NodeChannel::open_wait() for 10min. 
1. I want to execute the plan(the loop of get_next() & sink->send()). But the plan fragment has timed out(10min).

It's only one channel open failed, won't break the plan execution. And we can finish the plan before the plan_fragment_executor timeout(10min). But we waste time in waiting`PTabletWriterOpenResult`.

So I think it's better to separate TabletWriterOpen timeout from TabletWriterAddBatch timeout.

**Comment by chaoyli** [comment]
I think you can use config:: tablet_writer_rpc_timeout_sec / 10 set PTabletWriterOpenRequest timeout.

**Comment by vagetablechicken** [comment]
> I think you can use config:: tablet_writer_rpc_timeout_sec / 10 set PTabletWriterOpenRequest timeout.
It can be the suggestion value. But I think it's more flexible to add a `config::tablet_writer_open_rpc_timeout_sec`.

**Comment by imay** [comment]
@vagetablechicken 
I agree with you on the new config. However I think it will be better if we can find the root cause of open timeout.

**Comment by vagetablechicken** [comment]
> @vagetablechicken
> I agree with you on the new config. However I think it will be better if we can find the root cause of open timeout.

I think "open timeout" should be treated as a routine problem. About the open timeout case we found, it's probably because the connected BE is overload. Actually the whole cluster is overload. :sob:
I will keep an eye on it.

**Comment by imay** [comment]
> I think "open timeout" should be treated as a routine problem.

OK, looking forward to you PR to make it better.

> About the open timeout case we found, it's probably because the connected BE is overload. Actually the whole cluster is overload. 😭
> I will keep an eye on it.

Looking forward to your feedback

**Comment by vagetablechicken** [comment]
Oh, my bad. I debuged in old branch, so I missed this commit 8eb413fa699fe4c981e1e0e01be7eb781e2ed56f.

https://github.com/apache/incubator-doris/blob/3f247b0d2dc424335c0b81259733cc8cbc2fcc1f/be/src/exec/tablet_sink.cpp#L82
rpc_timeout_ms is set by query timeout, not the `config::tablet_writer_rpc_timeout_sec`.
But the solution can remain the same.
