### ISSUE TITLE
Routine Load cause be to hang

### ISSUE THREAD

**Issue by stalary** [apache/incubator-doris#3253]
**Describe the bug**
Routine Load cause be to hang
When I have a problem with my kafka data, be will die

**To Reproduce**
1. 
create table live_heartbeat_test
(
    id              varchar(255) comment 'id',
    type            varchar(50) comment '消息类型',
    progress        bigint default '0' comment '播放进度（ms）',
    background      BOOLEAN comment '是否后台播放',
    `interval`      bigint default '0' comment '和上次上报的间隔（ms）'
)
    ENGINE = olap UNIQUE KEY(id)
DISTRIBUTED BY HASH(id) BUCKETS 10
PROPERTIES(
    "replication_num" = "1",
    "storage_type"="column"
);

2.
CREATE ROUTINE LOAD test_db.live_heartbeat_test ON live_heartbeat_test
        COLUMNS TERMINATED BY ","
        PROPERTIES
        (
            "desired_concurrent_number"="3",
            "max_batch_interval" = "20",
            "max_batch_rows" = "300000",
            "max_batch_size" = "209715200",
            "strict_mode" = "false"
        )
        FROM KAFKA
        (
            "kafka_broker_list" = "localhost:9092",
            "kafka_topic" = "course_doris_test_live_heartbeat_test",
            "property.group.id" = "doris-test",
            "property.client.id" = "doris-test"
        );

3.  kafka-producer
> null,null,null,null,null
> 12null,null,null,null,null
> 232

**Expected behavior**
Report errors instead of be hangs

**version**
master

**Comment by stalary** [comment]
I think it's related to a field of type Boolean

**Comment by stalary** [comment]
create table live_heartbeat_test
(
    id              varchar(255) comment 'id',
    type            varchar(50) comment '消息类型',
    progress        bigint default '0' comment '播放进度（ms）',
    background      BOOLEAN comment '是否后台播放'
)
    ENGINE = olap UNIQUE KEY(id)
DISTRIBUTED BY HASH(id) BUCKETS 10
PROPERTIES(
    "replication_num" = "1",
    "storage_type"="column"
);

kafka-producer
> 1342,record,123323,false

This will cause be to die，I think it's related to a field of type Boolean

**Comment by imay** [comment]
@stalary 
Doris don't support Boolean type in segment V1.
If this table is created in segment V2 format, Boolean is supported.
