### ISSUE TITLE
Parquet reader handle_timestamp function is slow in broker load 

### ISSUE THREAD

**Issue by wyb** [apache/incubator-doris#3256]
**Describe the bug**
Broker load is slower than before this pull 
(Support 64 bit timestamp in from_unixtime (#3069))

**To Reproduce**
date column type in table
3 broker load jobs from parquet files concurrently

load time：
before this pull：1m30s
after this pull：4m15s

**Comment by wyb** [comment]
@HangyuanLiu

**Comment by HangyuanLiu** [comment]
#3300
