### ISSUE TITLE
Doris docment description error for version 0.11 English and Chinese

### ISSUE THREAD

**Issue by xbyang18** [apache/incubator-doris#3265]
**Docment description error**
It is error which the document description in
http://doris.apache.org/documentation/en/getting-started/basic-usage_EN.html#composite-partition
** SHOW LOAD WHERE LABLE = "table1_20170708" **
It is error word LABLE ,and replace  LABEL in English Vesion, Chinese too
this is authoritative figures for development,please repair it  as soon as possible

**Comment by imay** [comment]
@xbyang18 
Could you please help us to fix it?
