### ISSUE TITLE
Opening data dirs parallelly is not thread-safe

### ISSUE THREAD

**Issue by vagetablechicken** [apache/incubator-doris#3282]
**Describe the bug**
162b1c5d8bfd8afb7b01951ea5c5a79d1ffe1679 makes the data dirs init parallelly, but I found it's not thread-safe.
When be is starting, it may get this error:
```
[data_dir.cpp:249] fail to find file system, path=/xxx
```
I didn't notice that `DataDir::_init_file_system()` may have race conditions.
`getmntent()` value is `MT-Unsafe race:mntentbuf locale`
so mount_entry may be the wrong value `NULL` , `is_find` will be false.
https://github.com/apache/incubator-doris/blob/614a76beeac73821c78903c46e7a703b7956796b/be/src/olap/data_dir.cpp#L228-L251

We have two solutions:
1. use `getmntent_r()` instread, `getmntent_r()` value is MT-Safe locale.
1. split `_init_meta()`(open rocksdb), just `_init_meta()`  in parallel. Keep other parts of data dir init  in sequential order.

**Comment by imay** [comment]
I prefer option 1, it seems simple. Because the master branch has bug, hope that you can fix it ASAP.

**Comment by vagetablechicken** [comment]
> I prefer option 1, it seems simple. Because the master branch has bug, hope that you can fix it ASAP.

OK, it is my primary task today.
