### ISSUE TITLE
sql result is wrong when column type in doris is inconsistent with es

### ISSUE THREAD

**Issue by blackfox1983** [apache/incubator-doris#3287]
e.g. 
columnA in ES is 'keyword' (value is "0")
but in doris, it's bigint

select columnA from table; ==> return 48

we want 0 instead of 48.

refer @blackfox1983 

p.s. Root cause has been found, and further design is discussing offline.
 I'll sync up later

**Comment by blackfox1983** [comment]
关于后续doris on es的字段类型的初步考虑：
1、原则上字段类型需要一致。这样对于维护以及做自动化的同步工具都非常关键（如alter table时的新增字段，类型一致则可以自动化去做）


对于一些场景。如为了使用ES的索引性能，对于整数在ES中存储为keyword（string），使用原则1，则doris中的表类型也需为VARCHAR。这样在使用sum等函数的时候在sql中使用cast转换即可。而这种场景下，大多数的请求是在做term查询，因此在sql中使用cast的频率相对也不会太高。如果在ES中类型为long，那么doris中类型一般是bigint，此处不需要在sql中做cast，这个时候的场景，多是用ES在范围扫描，点查询相对不多。因此不论何种方式，均会牺牲掉一些特性，这里考虑到场景下的多数情况，采用了上述原则1的方式。

refer @wuyunfeng 欢迎补充

**Comment by wuyunfeng** [comment]
agree
