### ISSUE TITLE
hdfs导入到doris时报这个错误:type:LOAD_RUN_FAIL; msg:errCode = 2, detailMessage = Parse timestamp (-2208988800) error

### ISSUE THREAD

**Issue by zougengwei** [apache/incubator-doris#3303]
LOAD LABEL example_db.label
 (
        DATA INFILE("hdfs://hdfs_host:hdfs_port/user/palo/data/input/old_file")
        INTO TABLE `my_table`
        COLUMNS TERMINATED BY ","
        (k1, k2)
 )

通过hdfs导入数据到doris时，当导入文件中的列k1值为 1900-01-01 08:00:00时导入会报：type:LOAD_RUN_FAIL; msg:errCode = 2, detailMessage = Parse timestamp (-2208988800) error 的错误 自己尝试了设置max_filter_ratio也不行。想问能否在不改变原数据的情况下，有没有好的处理方案（例如：在导入语句方面做处理有没好的解决方案）

**Comment by HangyuanLiu** [comment]
你的导入文件是什么类型？

**Comment by zougengwei** [comment]
导入的是orc

**Comment by HangyuanLiu** [comment]
这个功能，在目前你不改变orc数值类型的前提下，是无法支持的。
但是这个功能是可以支持的，只不过目前被另一个PR阻塞住了，可能需要下周才能支持。

**Comment by HangyuanLiu** [comment]
#3300
