### ISSUE TITLE
UniqueRowsetIdGenerator may use a lot of memory

### ISSUE THREAD

**Issue by vagetablechicken** [apache/incubator-doris#3307]
**Describe the bug**
We tracked valid_rowset_ids size. And it may increase to 1G or more. One RowsetId cost 25B. So the total memory usage may exceed 25GB.
It wastes memory. We can use bitmap to save memory.
Working on it. Any advise?

**Comment by chaoyli** [comment]
How to use bitmap to store rowset_ids?

**Comment by vagetablechicken** [comment]
https://github.com/apache/incubator-doris/blob/cc31bf9cf96ec0bef2ce55553b247df7bbe598e3/be/src/olap/rowset/unique_rowset_id_generator.cpp#L31
rowset_id is combined of version, inc_id, be_uid hi, be_uid lo. And the version and be_uid would never change. **So a inc_id corresponds to a RowsetId.**
We can use a bitmap to store inc_id.

**Comment by vagetablechicken** [comment]
If you worry about the waste memory of unused rowset. e.g. we released rowset_id(_inc_id==1), then we never use it. But it's in the bitset.
 ### For memory-conserving
 we can use a map of bitset
```
std::map<int, bitset<SIZE>> bitsets;
```
So `bitsets[id/SIZE][id%SIZE]` is the rowset_id bit.
And if one bitset is all 0, we can delete it.(may need generate a gc task)

### For cleaner code
just use a set of inc_id to store valid rowset. We can save 17/25 of memory,  more than 2/ 3.

**Comment by chaoyli** [comment]
I think you store only inc_id is OK, and store _version and _backend_uid once is enough.
I am not understand that std::map<int, bitset<SIZE>> bitsets is for what?

**Comment by vagetablechicken** [comment]
> I think you store only inc_id is OK, and store _version and _backend_uid once is enough.
> I am not understand that std::map<int, bitset> bitsets is for what?

For minimum memory usage, but may has the worst case. So forget about it.
