### ISSUE TITLE
 [Doris On ES]  Replace /_cluster/state in Doris On ES

### ISSUE THREAD

**Issue by stalary** [apache/incubator-doris#3311]
**Is your feature request related to a problem? Please describe.**
Replace /_cluster/state in Doris On ES, because this interface requires too many permissions

**Describe the solution you'd like**
The detection of index mapping and shard location is divided into two phases

**Comment by wuyunfeng** [comment]
@stalary Can you add [Doris On ES] at the front of the title or pr ?

**Comment by wuyunfeng** [comment]
related: https://github.com/apache/incubator-doris/issues/3306
