### ISSUE TITLE
[Proposal] Making doris more friendly to new user and improving our Usability

### ISSUE THREAD

**Issue by yangzhg** [apache/incubator-doris#3314]
# Motivation
The main purpose of this proposal is to make doris more friendly to new users and improve ease of use. Although the current page of doris fe meets the functional requirements, the page is outdated and ugly, there are many style errors, and the web server ’s implementation is not elegant enough, static files and APIs are mixed together. And there is no function on the page that can be used by new users for simple trial. For example, it can submit some simple queries on the page, user and permission management, can import data by simply uploading small files such as csv, or import other database table through jdbc connection to try doris more easily, we can refer the phpMyadmin and implement the minimize function set
# Implementation
So the following work om out web interface we need  to implement
* we need web developers help us  beautify and modenlize the web pages and fix those style errors
* implements a more elegant web apis 
* implements user and permission management  in web ui
* implements import small data from other datasource(e.g.  csv, other db systems....)  in web ui
* implements submit simple query and view tables  in web ui
*  implements config broker load job in web ui

**Comment by kangkaisen** [comment]
It's a great work!
