### ISSUE TITLE
Support Java Verision HyperLogLog

### ISSUE THREAD

**Issue by wangbo** [apache/incubator-doris#3319]
**Description**
For Spark Load Process,we need a java version hll to calculate approximate distinct value.
The main request for java's implementation is try to keep consistent with Be C++ version

**Hll Write**
The ```Hll Write``` can be consistent with C++ version.
For java treats unsigned and signed numbers in the same way when execute addition,substraction, multiplication and shift. 
The above operator is enough for ```Hll Write```.
For ```mod operator```, we can use BigInteger to execute ```mod```

**data structure**
The main data structure for hll is Integer and not touch unsigned long, so this can be consistent with C++

**Hll.estimateCardinality**
Need a further research to judge whether C++ 's float-point calculation can be totally consistent with Java's float-point calculation.
Though they all follow ```IEEE 754``` rule, but for C++, OS architecture and compile option may affect the real calculation.
```estimateCardinality``` is not necessary for Spark Load Process, so this is not a urgent problem for now.

**Comment by 924060929** [comment]
@wangbo I already implement hll/bitmap scala version add do many unit test in our company, see data/spark-on-doris/common/src/main/scala/org/apache/doris/spark/sql/function/
