### ISSUE TITLE
Use LSAN to fix some memory leaks

### ISSUE THREAD

**Issue by acelyc111** [apache/incubator-doris#3328]
**Describe the bug**
In our production environment, we found BE physical memory consumed continuously and lead to OOM several days later.
![image](https://user-images.githubusercontent.com/10775040/79417113-b76e8a00-7fe3-11ea-90c2-8ccf4c64380b.png)

We doubt there are some memory leak in BE, we could use [LSAN](http://doris.apache.org/documentation/cn/developer-guide/debug-tool.html#lsan) to detect memory leak of unit tests at first.

**Comment by acelyc111** [comment]
After this issue has been resolved, we expect CI could run both in LSAN mode to detect memory leak problems as early as possible.

**Comment by XShun** [comment]
Good job!

**Comment by kangkaisen** [comment]
> we expect CI could run both in LSAN mode to detect memory leak problems as early as possible.

Good suggestion !  
I think we should do this work. @imay @morningman

**Comment by morningman** [comment]
> After this issue has been resolved, we expect CI could run both in LSAN mode to detect memory leak problems as early as possible.

Currently, we don't have enough resource to run CI with LSAN mode, it will takes a very long time. So you have to run LSAN in your local environment before upgrading.

**Comment by acelyc111** [comment]
I restart 2 BE servers the last Friday, one keep the old version, the other optimize memory usage, by https://github.com/apache/incubator-doris/pull/3316 and https://github.com/apache/incubator-doris/pull/3326, after 4 days observation, I found the physical memory usage gap between the two BE became about 14 GB, include https://github.com/apache/incubator-doris/pull/3316 which reduce about 6.6 GB (by rowset id count 415,756,350 * per rowset id memory reduce size 17 Bytes), that is to say https://github.com/apache/incubator-doris/pull/3326 can reduce about 7.4 GB.
![image](https://user-images.githubusercontent.com/10775040/79935183-dc9d4580-8486-11ea-91f3-bda54650206f.png)
106.bj: the old version
102.bj: optimize version
