### ISSUE TITLE
为什么在单机执行的聚合查询需要多个FRAGMENT

### ISSUE THREAD

**Issue by HappenLee** [apache/incubator-doris#3337]
在进行单机doris(单个be,fe) 进行性能测试时, 发现下面的查询语句生成了3个fragment：

 explain select max(C_PHONE) from customer group by C_MKTSEGMENT;
+-----------------------------------------------------------------------------+
| Explain String                                                              |
+-----------------------------------------------------------------------------+
| PLAN FRAGMENT 0                                                             |
|  OUTPUT EXPRS:<slot 3> |                                                    |
|   PARTITION: UNPARTITIONED                                                  |
|                                                                             |
|   RESULT SINK                                                               |
|                                                                             |
|   4:EXCHANGE                                                                |
|      tuple ids: 1                                                           |
|                                                                             |
| PLAN FRAGMENT 1                                                             |
|  OUTPUT EXPRS:                                                              |
|   PARTITION: HASH_PARTITIONED: <slot 2>                                     |
|                                                                             |
|   STREAM DATA SINK                                                          |
|     EXCHANGE ID: 04                                                         |
|     UNPARTITIONED                                                           |
|                                                                             |
|   3:AGGREGATE (merge finalize)                                              |
|   |  output: max(<slot 3>)                                                  |
|   |  group by: <slot 2>                                                     |
|   |  tuple ids: 1                                                           |
|   |                                                                         |
|   2:EXCHANGE                                                                |
|      tuple ids: 1                                                           |
|                                                                             |
| PLAN FRAGMENT 2                                                             |
|  OUTPUT EXPRS:                                                              |
|   PARTITION: RANDOM                                                         |
|                                                                             |
|   STREAM DATA SINK                                                          |
|     EXCHANGE ID: 02                                                         |
|     HASH_PARTITIONED: <slot 2>                                              |
|                                                                             |
|   1:AGGREGATE (update serialize)                                            |
|   |  STREAMING                                                              |
|   |  output: max(`C_PHONE`)                                                 |
|   |  group by: `C_MKTSEGMENT`                                               |
|   |  tuple ids: 1                                                           |
|   |                                                                         |
|   0:OlapScanNode                                                            |
|      TABLE: customer                                                        |
|      PREAGGREGATION: ON                                                     |
|      partitions=1/1                                                         |
|      rollup: customer                                                       |
|      tabletRatio=10/10                                                      |
|      tabletList=11039,11041,11043,11045,11047,11049,11051,11053,11055,11057 |
|      cardinality=29999999                                                   |
|      avgRowSize=46.694683                                                   |
|      numNodes=1                                                             |
|      tuple ids: 0                                                           |
+-----------------------------------------------------------------------------+

是否可以在单机执行时将多个FRAGMENT简化为单个FRAGMENT，来节省对应的资源消耗。@imay

**Comment by imay** [comment]
@HappenLee 
这个是比较难以做到的，当前在规划分片的时候只能通过tablet数目来做，而机器数只有在coordinate阶段才能感知。
如果想达到你的目的，那么你可以把tablet数目改成1就可以了。

**Comment by wutiangan** [comment]
@imay 
“机器数只有在coordinate阶段才能感知”
在analysis时为啥不能感知机器的数目呢？

**Comment by kangkaisen** [comment]
> 可以做到的。

在DistributedPlanner的createAggregationFragment 方法里，发现只有一个BE 节点，不拆两阶段就行。 改动很简单。
