### ISSUE TITLE
[Proposal] Materialized View 2.0

### ISSUE THREAD

**Issue by EmmyMiao87** [apache/incubator-doris#3344]
# The status of materialized view 1.0

In the present, we have supported the materialized views in Doris 0.12 version. The materialized view selector supports to select the most efficient mv and rewrite the SQL to query against the selected mv instead of the base table.
For query results contain a small number of rows where the original table has a large amount of data, the performance can reach the 5X to 100X times depends on the cardinality of the data.
The aggregate functions supported by the materialized view in 0.12 include: sum, min, max.

However, the aggregate functions supported by the current materialized view are not rich enough to fully cover the user's scene.
For example, in the `Order` scenario, user needs to analyze the number of orders in different dimensions.
Another example is the `count_distinct` function is used for analyzing PV and UV data in website traffic.

# The goal of materialized view 2.0

In order to support more scenarios, the materialized view 2.0 will support the following functions:

1. Materialized view supports aggregate functions: count, count_distinct (bitmap and hll)
2. Support to create materialized views of the same column with different aggregate functions. For example: ```select k1, sum (v1), min (v1) from table group by k1```

**Comment by morningman** [comment]
@EmmyMiao87 
Looking forward your PR.
And I think AVG method could be supported in next version.
