### ISSUE TITLE
[bug]Doris Documentations 给出的sql语句示例为中文

### ISSUE THREAD

**Issue by jevic** [apache/incubator-doris#3349]
https://doris.apache.org/documentation/en/administrator-guide/privilege_EN.html

文档中给出的示例:
例如:
CREATE USER cmy@’192.%’ IDENTIFIED BY “abcde”;

双引号均为中文;;; 建议调整为英文字符,比较严谨点!

**Comment by imay** [comment]
@jevic 
你可以提交个PR帮我们修复这个问题

**Comment by jevic** [comment]
> @jevic
> 你可以提交个PR帮我们修复这个问题

clone 查看了docs下面的md源文件, 里面的示例sql 语句字符都是英文的....是正确的. 但是页面上面为何显示中文字符。有点纳闷了
