### ISSUE TITLE
[Bug]OlapTableSink.finalize may use a another method name to avoid GC thread execute?

### ISSUE THREAD

**Issue by WingsGo** [apache/incubator-doris#3362]
I found that in OlapTableSink.java, there is a function named `finalize`. In Java, it will be called when GC destory the object, but I found that it will cause OOM. Because if we not define `finalize` method, the object will be recycle imediatelly, but if we define it, the object will insert into  `java.lang.ref.Finalizer.ReferenceQueue`, if we have large object in the queue, the fe will down cause by OOM.

https://github.com/apache/incubator-doris/blob/c6ac60bab9563a77b052a2766b0de859528aee41/fe/src/main/java/org/apache/doris/planner/OlapTableSink.java#L121-L137

![Snip20200421_14](https://user-images.githubusercontent.com/22497357/79837670-6a742480-83e4-11ea-89f5-8809da165ce9.png)

**Comment by kangkaisen** [comment]
Good job!
