### ISSUE TITLE
[Proposal] Make running profile clearer and more intuitive to improve usability

### ISSUE THREAD

**Issue by HappenLee** [apache/incubator-doris#3365]
# Motivation
The main purpose of this proposal is to make Doris more user-friendly and easy to use. Currently, Doris will print the running profile information of fragment in the log after the execution of fragment. This information is an important reference for Doris performance tuning and debugging. However, many of the information recorded in the current running profile is invalid, wrong or even misleading. We need to sort out the information of each counter in the current record, remove the invalid counter and add the missing but important counter. Write a document which guides user to monitor Doris and troubleshoot problems by running profile and add a reasonable counter to solve problems when appropriate.

# Implementation

So we need to do the following

* We need to eliminate invalid code and invalid monitoring items to simplify the current running profile information

* Fix which wrong and misleading monitoring items

* Add the important monitoring items but missing now

* Sort out the contents of each monitoring item and provide best practice or troubleshooting tutorials as documents for user

* Provide a document which guide user how to add monitoring items when it is necessary.

**Comment by kangkaisen** [comment]
@HappenLee Good job! look forward to your PR.
