### ISSUE TITLE
[New Feature] Batch update partition's property in one command

### ISSUE THREAD

**Issue by xy720** [apache/incubator-doris#3389]
As [ISSUE #2299] saying, if users wanna update the replication number of a table, users can only alter partition one by one.
We should support updating partitions' properties of a table in one command.

1、For unpartitioned table, we should support update table's property directly.(pr #3360 )

```
alter table test_tbl set ("replication_num" = "3");
```

2、For range table, we should let user know they are updating multi-partitions and let them to specify partitions that needed update.

Example:

- replication_num

```
alter table tbl_name modify partition (p1, p2, p3) set ("replication_num" = "3");
```

- storage_medium && storage_cooldown_time

```
alter table tbl_name modify partition (p1, p2, p3) set ("storage_medium" = "SSD", "storage_cooldown_time" = "2018-01-01 12:00:00");
```

- in_memory

```
alter table tbl_name modify partition (*) set ("in_memory" = "true");
```

**Comment by morningman** [comment]
Looking forward your PR
