### ISSUE TITLE
Dynamic partition UT bug

### ISSUE THREAD

**Issue by vagetablechicken** [apache/incubator-doris#3432]
**Describe the bug**
UT org.apache.doris.alter.AlterTest#testConflictAlterOperations may failed in 
https://github.com/apache/incubator-doris/blob/09eb40e3560bd23ed2609f1878cb7fb33aa8b94e/fe/src/test/java/org/apache/doris/alter/AlterTest.java#L178
```
java.lang.NullPointerException
	at org.apache.doris.alter.AlterTest.testConflictAlterOperations(AlterTest.java:178)
```

Because p1 is null, show the tbl partitions
I get
```
partition_id: 10085; name: p20200429; partition_state.name: NORMAL; 
partition_id: 10150; name: p3; partition_state.name: NORMAL; 
partition_id: 10143; name: p20200430; partition_state.name: NORMAL; 
```
So dynamic partiton overwrited the origin partitions, p1 & p2 disappeared.

**To Reproduce**
Infrequently.

**Comment by imay** [comment]
This bug may lead to data loss?
@morningman @WingsGo should investigate this issue.

**Comment by WingsGo** [comment]
> This bug may lead to data loss?
> @morningman @WingsGo should investigate this issue.

OK,I will try to reproduce the bug.

**Comment by morningman** [comment]
This is strange, there should not be any logic that can "overwrite" a partition...
I run this UT many times locally but it can not reproduce...But seems that the CI process
always met this bug.

**Comment by morningman** [comment]
Oh, I see. It is not "overwrite", the partition p1 and p2 are dropped by the DynamicPartitionScheduler.
Because the date `2020-02-01` and `2020-03-01` is "out of the range" of dynamic partition.

I will rewrite the UT to avoid this.
