### ISSUE TITLE
[Spark load] Doris support Spark load

### ISSUE THREAD

**Issue by wyb** [apache/incubator-doris#3433]
For many users who want to load data into doris for the first time, they have large amount of data, about 10G+，it is hard to support to load so large data into doris at one time using Broker load or Stream load. To resolve this problem, We proposal a new solution to load data by using spark cluster. 

Spark clusters are used to preprocess data (bitmap global dict build, partition, sort, aggregation) in spark load, which can improve Doris load performance of large data volume and save the computing resources of Doris. 

Spark load is mainly used for the initial migration from other systems or loading large amounts of data into Doris.

```
                 +
                 | 0. User create spark load job
            +----v----+
            |   FE    |---------------------------------+
            +----+----+                                 |
                 | 3. FE send push tasks                |
                 | 5. FE publish version                |
    +------------+------------+                         |
    |            |            |                         |
+---v---+    +---v---+    +---v---+                     |
|  BE   |    |  BE   |    |  BE   |                     |1. FE submit Spark ETL job
+---^---+    +---^---+    +---^---+                     |
    |4. BE push with broker   |                         |
+---+---+    +---+---+    +---+---+                     |
|Broker |    |Broker |    |Broker |                     |
+---^---+    +---^---+    +---^---+                     |
    |            |            |                         |
+---+------------+------------+---+ 2.ETL +-------------v---------------+
|               HDFS              +------->       Spark cluster         |
|                                 <-------+                             |
+---------------------------------+       +-----------------------------+

```

**Comment by wyb** [comment]
design doc
[Proposal] support spark load #2855
[Proposal] Support Spark Convert Doris Segment #2887
Spark load etl interface #3010

**Comment by imay** [comment]
1. can refer this issue in related PR and issue.
2. I will create a project "Spark Load" to track this feature.
3. You can create an issue for each part of this project.

**Comment by wangbo** [comment]
**Count Distinct Module**
#3319 Support Java Verision HyperLogLog(REVIEWING)
#3061 Doris Support Using Hive Table to Build Global Dict(TESTING)
#3088 Support Java version 64 bits Integers for BITMAP type(MERGED)

**Comment by wyb** [comment]
Add spark etl job config #3712

**Comment by wyb** [comment]
Add resource manager #3418

**Comment by wyb** [comment]
[Spark load] fe create job #3715

**Comment by wyb** [comment]
[Spark load] Fe submit spark etl job #3716

**Comment by wyb** [comment]
[Spark load] Fe process etl and loading state job #3717

**Comment by xy720** [comment]
**Be handle push task**
#3742 [Spark load][Be 1/1] Be handle push task
