### ISSUE TITLE
Support simple transitivity on join predicate pushdown

### ISSUE THREAD

**Issue by kangkaisen** [apache/incubator-doris#3452]
For query:
```
select t1.id, t1.value, t2.value
from t1
left join t2 on t1.id = t2.id
where t1.id > 1
```
We infer new  predicate `t2.id > 1` and pushdown it to t2 Scannode.

**Comment by chaoyli** [comment]
```
select t1.id, t1.value, t2.value
from t1
right join t2 on t1.id = t2.id
where t2.id > 1
```
I think this query is also can be pushed down?

**Comment by kangkaisen** [comment]
@chaoyli Of course. we could support right join and full out join. But inner join and left join are more common, and this PR has been tested in MeiTuan prod env two years. So I think we could merge this PR firstly, and then support  right join and full out join later.
