### ISSUE TITLE
[Bug] Push down predicate logic return wrong plan for semi join

### ISSUE THREAD

**Issue by morningman** [apache/incubator-doris#3480]
**Describe the bug**
Push down predicate logic return wrong plan for semi join

**To Reproduce**
```
select * from
join1 left semi join join2
on join1.id = join2.id and join2.id > 1;
```

the `join2.id > 1` should not be pushed down to table `join1`.

**Expected behavior**
`join2.id` should only push down to table `join2`.

**Comment by kangkaisen** [comment]
@morningman Hi, I have the check for join type:
```
            if ((tblRef.getJoinOp().isInnerJoin() || tblRef.getJoinOp().isLeftOuterJoin())) {
```

So why left semi join will be affected?

**Comment by morningman** [comment]
> @morningman Hi, I have the check for join type:
> 
> ```
>             if ((tblRef.getJoinOp().isInnerJoin() || tblRef.getJoinOp().isLeftOuterJoin())) {
> ```
> 
> So why left semi join will be affected?

For this example: 

```
select * from
join1 left semi join join2
on join1.id = join2.id and join2.id > 1;
```
When you call `join1.getJoinOp()`, the `joinOp` of table `join1` is null, but `getJoinOp()` will
return `INNER_JOIN`.

So for table `join1`, it will pass the `if(inner join)` check, and begin to do the predicate passing
through and push down.

**Comment by kangkaisen** [comment]
>When you call join1.getJoinOp(), the joinOp of table join1 is null, but getJoinOp() will
return INNER_JOIN.

So this is a bug？  the joinOp of table join1 should be `LEFT_SEMI_JOIN`, not null?  we should also fix this?

**Comment by morningman** [comment]
> > When you call join1.getJoinOp(), the joinOp of table join1 is null, but getJoinOp() will
> > return INNER_JOIN.
> 
> So this is a bug？ the joinOp of table join1 should be `LEFT_SEMI_JOIN`, not null? we should also fix this?

Seems not a bug. the `jionOp` is attach to the right. So `join1`'s `joinOp` is null, and `join2`'s `joinOp` is `LEFT SEMI JOIN`.

And as the comment of `joinOp` said, `null` means if default, which is `INNER JOIN`.

This can actually be understood as the "single-table processing of `join1`".
And the processing logic of single table about predicate pushdown is the same as "inner join"?
