### ISSUE TITLE
[BUG] Be all hang up

### ISSUE THREAD

**Issue by stalary** [apache/incubator-doris#3494]
**Describe the bug**
Be all hang up

<img width="888" alt="截屏2020-05-06 下午9 33 17" src="https://user-images.githubusercontent.com/24592373/81183121-55e97c00-8fe1-11ea-8944-13f8f4f1dd39.png">

When I used `select bitmap_to_string(bitmap_from_string('0, 1, 2'));`, the following error occurred
![03fa963949eeacc45f919be2a15e8f09](https://user-images.githubusercontent.com/24592373/81183327-9cd77180-8fe1-11ea-8e5d-5a172c9d6caf.jpg)

**version**
master

**Comment by morningman** [comment]
This bug may be fixed by #3451 . What is your Doris version?
