### ISSUE TITLE
Compile warnings should be errors

### ISSUE THREAD

**Issue by vagetablechicken** [apache/incubator-doris#3507]
We only add `-Werror` in Debug mode. But build.sh usually use release mode. It's dangerous.
If we can't fix all warnings, it better to use `-Wno-xxx`.

P.S.
```
In member function 'const char* doris_udf::FunctionContext::user() const':
cc1plus: warning: function may return address of local variable [-Wreturn-local-addr]
/root/doris-env/doris/be/src/udf/udf.cpp:242:33: note: declared here
     return  _impl->_state->user().c_str();
```
I'll fix it in the same pr.

**Comment by imay** [comment]
I'm not very sure, when I compile Doris with GCC 9+ there are a lot of error caused by thirdparty header files.
It will be better to compile Doris with higher version GCC when you add -Werror in RELEASE mode.

**Comment by vagetablechicken** [comment]
Higher version gcc will be more exclusive. If GCC 9+ should be taken into account, we can use `#pragma` to turn off warnings. Or simply, improve the build.sh, only add `-Werror` under GCC7.3 or so.

**Comment by vagetablechicken** [comment]
About the warning of udf:
```
In member function 'const char* doris_udf::FunctionContext::user() const':
cc1plus: warning: function may return address of local variable [-Wreturn-local-addr]
/root/doris-env/doris/be/src/udf/udf.cpp:242:33: note: declared here
     return  _impl->_state->user().c_str();
```
It is in the building of target DorisUdf.
So the RuntimeState is here:
https://github.com/apache/incubator-doris/blob/b62b3108641cc5cd03dd439115dbc798cd7d6c60/be/src/udf/udf.cpp#L60-L74

user() returns `const std::string`, so it is a local var.
It's better to have the same implementation of runtime/runtime_state.h, like
```
    const std::string& user() const {
        return _user;
    }

private:
    std::string _user = "";
```
