### ISSUE TITLE
Doris流式导入json数据，相关接口定义

### ISSUE THREAD

**Issue by worker24h** [apache/incubator-doris#3509]
此issue主要讨论，导入json数据接口定义

前提： 表1有 category,price,author三列， 以routine load导入举例说明
分类： 由于json支持嵌套，所以json数据可能很复杂，因为这里设计默认导入和精准导入
一、相关参数
    format: 指定导入数据格式，csv、json，默认是csv
    jsonpaths: 用于精准导入，指定导入数据
    is_multi_records: 布尔类型， 默认值是false, true 表示json数据以数组对象([])开始且数组中包含该多个对象类型({}),
                      此时doris会将对象转成tuple

二、默认导入（不提供jsonpath）
    默认导入，表示表列的顺序与json中key/value一一对应, 即表列名子等于json key的名字
    2.1 创建routine load语句， 该语句同事支持 场景1.1 和 场景1.2
        CREATE ROUTINE LOAD example_db.test_json_label_1 ON table1
        COLUMNS(category,price,author)
        PROPERTIES
        (
            "desired_concurrent_number"="3",
            "max_batch_interval" = "20",
            "max_batch_rows" = "300000",
            "max_batch_size" = "209715200",
            "strict_mode" = "false",
            "format" = "json"
        )
        FROM KAFKA
        (
            "kafka_broker_list" = "broker1:9092,broker2:9092,broker3:9092",
            "kafka_topic" = "my_topic",
            "kafka_partitions" = "0,1,2",
            "kafka_offsets" = "0,0,0"
        );
        format: 目前支持csv, json两种，默认是csv

    2.2 单object数据
        kafka中一条消息内容 => {"category":"a1", "price":10, "author":"c1"}
        导入后表数据：
        category      price      author
        -------------------------------
        a1            10         c1

    2.3 多object数据
        为了提升吞吐，支持一次性导入多条数据，其中RECORDS是关键字且为数组对象，数组中只能包含对象
        kafka中一条消息内容 => {
                            "RECORDS":[
                                {"category":"a1", "price":10, "author":"c1"},
                                {"author":"c2", "category":"a2"}
                                {"category":"a1", "price":30, "author":"c3"}
                            ]
                        }
        导入后表数据：
        category      price      author
        -------------------------------
        a1            10          c1
        a2            null        c2
        a3            30          c3
        【特别说明】 如果没有匹配到数据，默认是null

三、精准导入（提供jsonpaths）
    3.1 嵌套对象形式
    3.1.1 json数据格式
    {
        "book": {
            "category": "a1", 
            "author": "c1", 
            "price": 10
        }
    }
    3.1.2
    CREATE ROUTINE LOAD example_db.test_json_label_1 ON table1
    COLUMNS(category, price, author)
    PROPERTIES
    (
        "desired_concurrent_number"="3",
        "max_batch_interval" = "20",
        "max_batch_rows" = "300000",
        "max_batch_size" = "209715200",
        "strict_mode" = "false",
        "format" = "json",
        "jsonpaths" = "[\"$.book.category\",\"$.book.price\",\"$.book.author\"]"
    )
    FROM KAFKA
    (
        "kafka_broker_list" = "broker1:9092,broker2:9092,broker3:9092",
        "kafka_topic" = "my_topic",
        "kafka_partitions" = "0,1,2",
        "kafka_offsets" = "0,0,0"
    );
    导入后表数据：
    category      price      author
    -------------------------------
    a1            10          c1

    3.2 以数组开始的json字符串
    3.2.1 json数据格式
    [
        {"category": "a1", "author": "c1", "price": 10},
        {"category": "a2", "author": "c2"},
        {"category": "a3", "author": "c3", "price": 30}
    ]
    3.2.1 创建routine load语句
    CREATE ROUTINE LOAD example_db.test_json_label_1 ON table1
    COLUMNS(category, price, author)
    PROPERTIES
    (
        "desired_concurrent_number"="3",
        "max_batch_interval" = "20",
        "max_batch_rows" = "300000",
        "max_batch_size" = "209715200",
        "strict_mode" = "false",
        "format" = "json",
        "is_multi_records" = "true",
        "jsonpaths" = "[\"$.category\",\"$.price\",\"$.author\"]"
    )
    FROM KAFKA
    (
        "kafka_broker_list" = "broker1:9092,broker2:9092,broker3:9092",
        "kafka_topic" = "my_topic",
        "kafka_partitions" = "0,1,2",
        "kafka_offsets" = "0,0,0"
    );
    导入后表数据：
    category      price      author
    -------------------------------
    a1            10          c1
    a2            null        c2
    a3            30          c3
    【特别说明】
    1) 如果jsonpath未匹配到数据，则默认是null
    2) is_multi_records为true且json数据是[]开始， 那么说明[]中每个{}都是一行数据， 则在
       定义jsonpath时ROOT节点应该是{}而非[].

四、备注
    1) 由于jsonpath语法比较复杂，目前doris只实现简单语法格式

**Comment by YalanLuo** [comment]
Hi~ I'm so interested in the specific load you mentioned above, and I wonder whether the jsonpath approach can support nested structure well?

**Comment by imay** [comment]
@YalanLuo 
Could you please describe what's the nested structure you want. It will be better you give us a specific case.

**Comment by worker24h** [comment]
> Hi~ I'm so interested in the specific load you mentioned above, and I wonder whether the jsonpath approach can support nested structure well?

for a example?

**Comment by YalanLuo** [comment]
Thanks for your kindly reply.I'm trying to expand your example as follow:
`{
"book": {

"title":"The microservice architecture",

"chapter1":{

"title":"What is microservice architecture?"

},

"chapter2":{

"title":"Related patterns"

},

"category": "a1",
"author": "c1",
"price": 10
}
}`
I wonder whether the specific load (by jsonpath) can support the multi-layer nested structure like the example given above.

**Comment by imay** [comment]
Can you tell us about the table schema of the destination table?

**Comment by YalanLuo** [comment]
source:
`{
"book": {

"title":"The microservice architecture",

"chapter1":{

"title":"What is microservice architecture?"

},

"chapter2":{

"title":"Related patterns"

},

"category": "a1",
"author": "c1",
"price": 10
}
}`

--mapping : book.title, book.chapter1.title, book.chapter2.title, book.category, book.author, book.price

--sink: (load into Doris )
"The microservice architecture", "The microservice architecture","What is microservice architecture?", "a1", "c1",10

I'm not sure whether the jsonpath approach can implements the function of flatmap, convert JSON nested structure into fields which can be loaded into Doris directly.

**Comment by imay** [comment]
Current version of jsonpath can achieve your demand through jsonpaths = "$.book.title", "$.book.chapter1.title", "$.book.chapter2.title", "$.book.category","$.book.author","$.book.price" to extract fields and load data into Doris

**Comment by YalanLuo** [comment]
I'm so glad to hear that, and thanks for your patience and your guidance. It can liberate me from the elaborate preprocessing work. Thanks a lot !

**Comment by worker24h** [comment]
最新相关接口：
参数strip_outer_array： 表示是否展平数组
参数jsonpaths：json字符串且以数组对象开始，里面包含各个列对应的jsonpath
参数format：csv、json两种取值

例如：
CREATE ROUTINE LOAD example_db.test_json_label_1 ON table1
COLUMNS(category, price, author)
PROPERTIES
(
    "desired_concurrent_number"="3",
    "max_batch_interval" = "20",
    "max_batch_rows" = "300000",
    "max_batch_size" = "209715200",
    "strict_mode" = "false",
    "format" = "json",
    "strip_outer_array" = "true",
    "jsonpaths" = "[\"$.category\",\"$.price\",\"$.author\"]"
)
FROM KAFKA
(
    "kafka_broker_list" = "broker1:9092,broker2:9092,broker3:9092",
    "kafka_topic" = "my_topic",
    "kafka_partitions" = "0,1,2",
    "kafka_offsets" = "0,0,0"
);

**Comment by peterchen859** [comment]
什么版本中可以支持json

**Comment by zh0122** [comment]
> 最新相关接口：
> 参数strip_outer_array： 表示是否展平数组
> 参数jsonpaths：json字符串且以数组对象开始，里面包含各个列对应的jsonpath
> 参数format：csv、json两种取值
> 
> 例如：
> CREATE ROUTINE LOAD example_db.test_json_label_1 ON table1
> COLUMNS(category, price, author)
> PROPERTIES
> (
> "desired_concurrent_number"="3",
> "max_batch_interval" = "20",
> "max_batch_rows" = "300000",
> "max_batch_size" = "209715200",
> "strict_mode" = "false",
> "format" = "json",
> "strip_outer_array" = "true",
> "jsonpaths" = "["$.category","$.price","$.author"]"
> )
> FROM KAFKA
> (
> "kafka_broker_list" = "broker1:9092,broker2:9092,broker3:9092",
> "kafka_topic" = "my_topic",
> "kafka_partitions" = "0,1,2",
> "kafka_offsets" = "0,0,0"
> );

https://github.com/apache/incubator-doris/issues/3124

> I has completed this function.
> PR: `https://github.com/apache/incubator-doris/pull/3230`
> 
> For example:
> 
> ```
> CREATE TABLE `test_json_price`(
>   `category` varchar(32),
>   `author` varchar(32),
>   `title` varchar(32),
>   `price` double  SUM
> 
> ) ENGINE=OLAP
> AGGREGATE KEY(category, author, title)
> DISTRIBUTED BY HASH(category, author, title) BUCKETS 32
> PROPERTIES ("storage_type"="column","replication_num" = "1");
> 
> 
> CREATE ROUTINE LOAD mediavad.test_json_price_label001 ON test_json_price
> COLUMNS(category, author, title, price)
> PROPERTIES
> (
>     "desired_concurrent_number"="3",
>     "max_batch_interval" = "20",
>     "max_batch_rows" = "300000",
>     "max_batch_size" = "209715200",
>     "strict_mode" = "false",
>     "format" = "json",
>     "jsonpath" = "{\"jsonpath\":[{\"column\":\"category\",\"value\":\"$.store.book.category\"},{\"column\":\"author\",\"value\":\"$.store.book.author\"},{\"column\":\"title\",\"value\":\"$.store.book.title\"},{\"column\":\"price\",\"value\":\"$.store.book.price\"}]}"
> )
> FROM KAFKA
> (
>     "kafka_broker_list" = "192.168.125.110:9092,192.168.125.120:9092,192.168.125.130:9092",
>     "kafka_topic" = "KafkaLoadJsonForDoris",
>     "kafka_partitions" = "0,1,2",
>     "kafka_offsets" = "0,0,0"
> );
> ```

Hi worker24h, 

请问在0.13版中, jsonpath 的格式如何定义,  在Routine load 中, 如果json中字段和表中的字段名不一致, 请问如何指定导入规则? 

谢谢

**Comment by peterchen859** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
