### ISSUE TITLE
can not find main class in start_fe.sh

### ISSUE THREAD

**Issue by GavinYaoer** [apache/incubator-doris#3516]
编译完成后启动fe报找不到MainClass

查看启动脚本，发现定义了CLASSPATH，但是启动时并没有用到该属性

**Comment by imay** [comment]
可以提供更多的信息么？
你看看是不是进入了正确的路径。应该进入output/fe/

**Comment by pei-open** [comment]
看一下这个文件：https://github.com/apache/incubator-doris/blob/master/bin/start_fe.sh
这个里面的最后一部分

```
if [ ${RUN_DAEMON} -eq 1 ]; then
    nohup $LIMIT $JAVA $final_java_opt org.apache.doris.PaloFe ${HELPER} "$@" >> $LOG_DIR/fe.out 2>&1 </dev/null &
else
    $LIMIT $JAVA $final_java_opt org.apache.doris.PaloFe ${HELPER} "$@" >> $LOG_DIR/fe.out 2>&1 </dev/null
fi
```

我不确定这个脚本是否正确，但是确实是启动时没有指定-classpath参数，我加上了-classpath后可以启动。

···
if [ ${RUN_DAEMON} -eq 1 ]; then
    nohup $LIMIT $JAVA $final_java_opt -classpath ${CLASSPATH}  org.apache.doris.PaloFe ${HELPER} "$@" >> $LOG_DIR/fe.out 2>&1 </dev/null &
else
    $LIMIT $JAVA $final_java_opt -classpath ${CLASSPATH} org.apache.doris.PaloFe ${HELPER} "$@" >> $LOG_DIR/fe.out 2>&1 </dev/null
fi
···
