### ISSUE TITLE
[Proposal] Get the hot spot of the doris cluster.

### ISSUE THREAD

**Issue by chaoyli** [apache/incubator-doris#3517]
Nowadays, We have no insight about the hotspot the cluster.
During the time, we don't know the scanner rows of one table during time.
Now we should collect the scanner rows of the table and scanner bytes of the table for query.
Using this information, we can got the insight about the hot spot of cluster.

**Comment by chaoyli** [comment]
Supposing there are 10000 tablets in one BE node, the metric is like this
```
[
   {
      "tags":{
         "tablet_id":10010,
         "metric":"scanner_rows"
      },
      "value":1000,
      "unit":"number"
   },
   {
      "tags":{
         "tablet_id":10010,
         "metric":"scanner_bytes"
      },
      "value":1024,
      "unit":"bytes"
   }
]
```

**Comment by chaoyli** [comment]
There also exists another function using log.
If every query collecting the tablet scanner rows/bytes, and write it to log.
We can access the log to get the message, it needs log analysis which is not integrated in Doris.
So I will use the above method to solve this problem.

**Comment by imay** [comment]
This is a good job.
However I think something maybe discussed clearly before writing code.
1. Who will update this metrics?
2. How will updater get the table id?
3. How will the final metric be summary?

**Comment by chaoyli** [comment]
> This is a good job.
> However I think something maybe discussed clearly before writing code.
> 
> 1. Who will update this metrics?
> 2. How will updater get the table id?
> 3. How will the final metric be summary?

1. Scanner Thread will update the metrics, it is the same as the metric like the query profile.
2. Nowadays, tablet meta has save the table id in the metadata, so new table will know the table_id.
3. If metric has been collected by agent, you can store to another database, or can be summed by a central node. There are ok both.

**Comment by morningman** [comment]
I think we could refer to 
`https://pingcap.com/blog-cn/observability-of-distributed-system/`
and
`https://cloud.google.com/bigtable/docs/keyvis-overview`

to learn something
