### ISSUE TITLE
aarch64上编译不通过

### ISSUE THREAD

**Issue by codeofdave** [apache/incubator-doris#3526]
编译brpc时报错
/home/incubator-doris/thirdparty/src/incubator-brpc-0.9.5/src/bthread/context.h:69:1: error: expected initializer before ‘bthread_jump_fcontext’
 bthread_jump_fcontext(bthread_fcontext_t * ofc, bthread_fcontext_t nfc,
 ^~~~~~~~~~~~~~~~~~~~~
/home/incubator-doris/thirdparty/src/incubator-brpc-0.9.5/src/bthread/context.h:72:1: error: expected initializer before ‘bthread_make_fcontext’
 bthread_make_fcontext(void* sp, size_t size, void (* fn)( intptr_t));

**Comment by imay** [comment]
看起来是BRPC编译除了问题。
能提供更多的信息么？比如编译器版本，操作系统发行版等信息
