### ISSUE TITLE
Support loading data from Kafka

### ISSUE THREAD

**Issue by morningman** [apache/incubator-doris#353]
TODO

**Comment by EmmyMiao87** [comment]
The main progress of routine load is following:
Step1: User creates a routine load job.
Step2: Doris pulls data from streaming app such as kafka
Step3: Doris pushes data into itself.
Step4: Doris loop executes the step2 and 3.

**Comment by EmmyMiao87** [comment]
#967

**Comment by EmmyMiao87** [comment]
#1650 scheduler routine load job for stream load
