### ISSUE TITLE
编译BE报错 ‘FLAGS_log_filenum_quota’ was not declared in this scope

### ISSUE THREAD

**Issue by sking0089** [apache/incubator-doris#3554]
centos7.5
gcc5.4.0
执行sh build.sh,编译至BE部分报错。控制台输出信息：
[  0%] Building CXX object src/common/CMakeFiles/Common.dir/daemon.cpp.o
[  0%] Building CXX object src/agent/CMakeFiles/Agent.dir/agent_server.cpp.o
[  0%] Building CXX object src/common/CMakeFiles/Common.dir/status.cpp.o
[  0%] Building CXX object src/common/CMakeFiles/Common.dir/resource_tls.cpp.o
[  1%] Building CXX object src/common/CMakeFiles/Common.dir/logconfig.cpp.o
/opt/module/doris/apache-doris-0.12.0-incubating-src/be/src/common/logconfig.cpp: In function ‘bool doris::init_glog(const char*, bool)’:
/opt/module/doris/apache-doris-0.12.0-incubating-src/be/src/common/logconfig.cpp:68:5: error: ‘FLAGS_log_filenum_quota’ was not declared in this scope
     FLAGS_log_filenum_quota = config::sys_log_roll_num;
     ^
/opt/module/doris/apache-doris-0.12.0-incubating-src/be/src/common/logconfig.cpp:99:9: error: ‘FLAGS_log_split_method’ was not declared in this scope
         FLAGS_log_split_method = "day";
         ^
/opt/module/doris/apache-doris-0.12.0-incubating-src/be/src/common/logconfig.cpp:102:9: error: ‘FLAGS_log_split_method’ was not declared in this scope
         FLAGS_log_split_method = "hour";
         ^
/opt/module/doris/apache-doris-0.12.0-incubating-src/be/src/common/logconfig.cpp:105:9: error: ‘FLAGS_log_split_method’ was not declared in this scope
         FLAGS_log_split_method = "size";
         ^
make[2]: *** [src/common/CMakeFiles/Common.dir/logconfig.cpp.o] Error 1
make[1]: *** [src/common/CMakeFiles/Common.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  1%] Building CXX object src/agent/CMakeFiles/Agent.dir/heartbeat_server.cpp.o
[  1%] Building CXX object src/agent/CMakeFiles/Agent.dir/task_worker_pool.cpp.o
[  1%] Building CXX object src/agent/CMakeFiles/Agent.dir/utils.cpp.o
[  1%] Building CXX object src/agent/CMakeFiles/Agent.dir/cgroups_mgr.cpp.o
[  2%] Building CXX object src/agent/CMakeFiles/Agent.dir/topic_subscriber.cpp.o
[  2%] Building CXX object src/agent/CMakeFiles/Agent.dir/user_resource_listener.cpp.o
[  2%] Linking CXX static library libAgent.a

 cat be/build/CMakeFiles/CMakeError.log 查看报错日志，显示

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /opt/module/doris/apache-doris-0.12.0-incubating-src/be/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_10c9f/fast 
/usr/bin/gmake -f CMakeFiles/cmTC_10c9f.dir/build.make CMakeFiles/cmTC_10c9f.dir/build
gmake[1]: Entering directory `/opt/module/doris/apache-doris-0.12.0-incubating-src/be/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_10c9f.dir/CheckFunctionExists.c.o
/usr/local/bin/../bin/gcc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_10c9f.dir/CheckFunctionExists.c.o   -c /usr/bin/cmake-3.14.5/share/cmake-3.14/Modules/CheckFunctionExists.c
Linking C executable cmTC_10c9f
/usr/bin/cmake-3.14.5/bin/cmake -E cmake_link_script CMakeFiles/cmTC_10c9f.dir/link.txt --verbose=1
/usr/local/bin/../bin/gcc  -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_10c9f.dir/CheckFunctionExists.c.o  -o cmTC_10c9f -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_10c9f] Error 1
gmake[1]: Leaving directory `/opt/module/doris/apache-doris-0.12.0-incubating-src/be/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_10c9f/fast] Error 2

**Comment by HangyuanLiu** [comment]
编译完第三方依赖了吗？

**Comment by sking0089** [comment]
第三方依赖编译完了的

**Comment by sking0089** [comment]
> 编译完第三方依赖了吗？

第三方依赖编译完了的

**Comment by zhangchangwei** [comment]
问题+1，请问解决了吗？

**Comment by zhangchangwei** [comment]
![image](https://user-images.githubusercontent.com/7691964/87753393-163ade00-c835-11ea-9b8b-b8c59ab33752.png)

**Comment by yangzhg** [comment]
check that command `patch` is installed, after install `patch` rm `installed` dir and dirs in `src` then rebuild
