### ISSUE TITLE
[Build] Update Compiling environment of BE to Support C++14/17

### ISSUE THREAD

**Issue by HappenLee** [apache/incubator-doris#3563]
## Motivation
Currently, Doris supports be compilation by **GCC 4.8.2 and above**. 
GCC 4.8.2 is a version released seven years ago. It only supports the language standard of C++ 11, many new syntax features and the standard library of STL is not support well. 
C++ 11 is the first version of modern C++, many of the functions that have not been perfected by the Standards Committee have been completed in the subsequent C++ 14 and C++ 17.
so should we upgrade the basic version of GCC to support new language features. (in fact, we are already doing similar things, such as recommending GCC 5.3.1 in the document and GCC 7.2 in the docker environment for compilation. )

### It can bring us the following benefits:

1. We can make better use of the new features of C++ to develop Doris, which will arouse the enthusiasm of external developers. The same problem can be explained in a more elegant and concise way, rather than in ugly's old way.

2. The standard STL library has been enhanced and updated, which makes us no longer rely on boost for development and reduces the dependence on boost. Boost is a powerful template library, but it also slows down the compilation speed.

3. In this process, Doris should form a set of recommended code specifications and styles, which can significantly reduce the cost of developers' reading code and cooperative development.

## Implementation

1. First, we can refer to the following gcc compiler's support for C + + standard:
[https://en.cppreference.com/w/cpp/compiler_support](https://en.cppreference.com/w/cpp/compiler_support)

2. Upgrade the recommended version of GCC to an appropriate version. Unify it in the document and docker environment

3. Modify the compilation parameters in Cmakelists to enable the support of C++14 or C++17 （To be honest, C++14 is just a patch version of C++11. This upgrade can be completed without any effort. Maybe we should move forward gradually.）

4. Conduct sufficient testing and release the follow-up development support

5. Write documents to standardize the style and specification of Doris's C++ code

**Comment by imay** [comment]
This is a good proposal. Looking forward to your next work.
