### ISSUE TITLE
Download page issues

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-doris#3567]
The page http://doris.apache.org/master/en/downloads/downloads.html has some issues:

There must be a link to the KEYS file at https://downloads.apache.org/incubator/doris/KEYS

The phrase:
"compile and install Doirs."
should be
"compile and install Doris."

**Comment by sebbASF** [comment]
Also the source download links must use the ASF mirror system

**Comment by imay** [comment]
Thanks @sebbASF for your advice, we will fix it.

**Comment by imay** [comment]
Hi @sebbASF 
This issue has been fixed, please check

**Comment by sebbASF** [comment]
Looks OK now, thanks
