### ISSUE TITLE
[Proposal]独立于Base表的Rollup用于提供历史不可变数据的聚合能力

### ISSUE THREAD

**Issue by BabySid** [apache/incubator-doris#3585]
**Is your feature request related to a problem? Please describe.**
在实际的场景中，RollUp在加速数据查询方面起到了很大的作用。但是目前的实现强依赖Base表，当Base表删除时，Rollup表也随之删除。

当数据量很大时，存储成本逐渐上升，在实际的业务场景中，对于历史数据的明细很多时候不再读取也不再变更，但是对于聚合的数据仍有读取的需求，如跨越较长时间的趋势分析。

类似的功能在ES.Rollup以及Durid中都具备，为了统一业务线的存储，并降低维护和学习成本，希望Doris也可以支持类似的功能。

**Describe the solution you'd like**
对于若干时间之前的数据（如1个月前），可以根据某些时间日期列聚合为更粗粒度的数据，如明细为小时级，则可以聚合为天级，在更久的历史数据（如6个月前），可以基于天级的聚合为周级，再更前的，可以基于周级聚合为月级……

因此，RollUp数据是否可以分为多层，基于RollUp来不断的聚合为更高层次的RollUp。

只要明细完成了聚合，明细数据即可删除。如有了天级的，小时级的则可删除，有了周级的，天级的可以删除。

在查询时，如果查询的是聚合数据（非明细），跨越了多个历史阶段的，可以在内部Union起来统一返回。对使用者透明。

**Describe alternatives you've considered**
这个可以通过配置或者命令来触发进一步的聚合，两种模式均可。
如
```
-- 第一级rollup，提供天级的聚合
ALTER TABLE table1 ADD ROLLUP rollup_1(dt, citycode, pv);
-- 第二季rollup，提供周级的聚合
-- 其中week()为一个内置函数，可以根据日期计算周
ALTER TABLE rollup_1 ADD ROLLUP rollup_2(week, citycode, pv) properties ('week' = week(dt));
--如果觉得天级的数据没用了，可以删除
drop table rollup_1 [where dt > xxx]
```

**Additional context**
（无）

**Comment by yiguolei** [comment]
Why not use aggregate key model?

**Comment by blackfox1983** [comment]
> 
> 
> Why not use aggregate key model?

明细使用的是“aggregate key”，但是数据量上升，这部分本身就占用资源。独立的rollup，就是为了可用删除这部分资源，而保留rollup

**Comment by tongwei** [comment]
Hi,

Is it the only way to retain the data in the materialized view and delete the detailed data:
1. Use insert into select to back up the materialized view data and delete the detailed data
or
2. Import data into multiple tables
