### ISSUE TITLE
large bitmap serialization failed because of overflow of size

### ISSUE THREAD

**Issue by kangpinghuang** [apache/incubator-doris#3600]
**Describe the bug**
when use bitmap to do insertsect, if the bitmap is large than the MAX_INT, the allocation of memory from free pool will failed, which will lead to serialization failed because of core dump.

the following is the bitmap size I come to is 3G+.

**Comment by kangpinghuang** [comment]
One of the reason is that 3G+ is large than MAX_INT, but FreePool->allocate accept int as argment, overflow will lead to allocation and serialation bug.

**Comment by imay** [comment]
Hi, @kangpinghuang 
Can you explain the scenario that cause this problem?
I think it will cause many problems if the body is so large. And if we are going to support it, we should review all the related places.
