### ISSUE TITLE
[compaction] Cumulative compaction is skipped when a tablet do cumulative compaction the first time

### ISSUE THREAD

**Issue by acelyc111** [apache/incubator-doris#3687]
**Describe the bug**
When a tablet cumulate many rowsets and is picked to do cumulative compaction for the first time, cumulative compaction will be skipped, and cumulative point will be moved from -1(default value) to the last version + 1, and it will also influence the next base compaction of this tablet (because too many rowsets take part in base compaction, that may consume too many memory).

**To Reproduce**
1. Adjust some base compaction and cumulative compaction configs to make compaction execute very slowly (e.g. set base/cumulative_compaction_check_interval_seconds to a large number).
2. Load some data to generate many rowsets on a tablet.
3. Some tablet will be picked to do cumulative compaction, but will fail to do compaction actually, and cumulative point will be moved from -1 to max version + 1.
4. The next base compaction on this tablet will pick all rowsets to do compaction, and will consume many memory

**Expected behavior**
Cumulative point is -1 (default value) when a tablet hasn't been do any compactions, when it is picked to do cumulative compaction, the first config::max_cumulative_compaction_num_singleton_deltas 
 rowsets should be picked to do cumulative compaction.
That is to say, this tablet's cumulative point should be -1 (or 0?) when `calculate_cumulative_point` returned for the fisrt time.

**Screenshots**
![image](https://user-images.githubusercontent.com/10775040/82801981-c2ed8480-9eb0-11ea-8db4-fec45f11457c.png)

**Comment by acelyc111** [comment]
https://github.com/apache/incubator-doris/blob/a5922051c9bee4d75599847838596abcd8b0bd3b/be/src/olap/tablet.cpp#L681-L702

I'm not sure how does cumulative point calculated, can I consider that rowsets that haven't  done cumulative compaction must after cumulative point?

**Comment by chaoyli** [comment]
> https://github.com/apache/incubator-doris/blob/a5922051c9bee4d75599847838596abcd8b0bd3b/be/src/olap/tablet.cpp#L681-L702
> 
> I'm not sure what is the theoretical basis of cumulative point in Doris, can I consider that rowset that hasn't do cumulative compaction must after cumulative point? Or any singleton rowset (with only one version) must be after cumulative point?

Cumulative point is the point to divide BaseCompaction and Cumulative Compaction.
CumulativeCompaction will compact [cumulative_point, max_version].
BaseCompaction will compact [0, cumulative_point-1].

**Comment by acelyc111** [comment]
Yes, but singleton version ([v,v]) rowsets which must be wrote by sink, and they haven't do cumulative compaction (compacted rowsets' version [u, v], v must larger than u, not equal), they should be after compaction point, no mater they are NONOVERLAPPING or OVERLAPPING. Becasue newly generated singleton verison rowset with single segment is set as NONOVERLAPPING:
https://github.com/apache/incubator-doris/blob/a5922051c9bee4d75599847838596abcd8b0bd3b/be/src/olap/rowset/alpha_rowset_writer.cpp#L201-L203
So we should not skip these kind of rowset when calculate cumulative point, right?

**Comment by chaoyli** [comment]
Newly generated singleton rowset with single segment is set as NONOVERLAPPING should not be skipped. 
But newly generated singleton rowset may have much segments, which will do compaction when have lots of segments. We will do cumulative compaction only for this singleton rowset newly written.
