### ISSUE TITLE
[Proposal] Add query monitor detail in FE.

### ISSUE THREAD

**Issue by chaoyli** [apache/incubator-doris#3689]
Doris is absent of query monitor. It is not convenient when analyzing the query workload.
A query monitor should cover such features.
```
1. It can exhibit running queries at present.
2. It can analysis the query latency(mean/99 percentile) at defined interval.
    For example, DBA will want to about the mean latency between 11:00 and 11:05.
3. It can observe the query profile of queries over a period of time.
    For example, how much resource a query consumed is critical for analysis the hot spot.
```
To address the above problem, Doris should support query details for outside monitor to collect and analyze.

**Comment by chaoyli** [comment]
QP
```
create table query_detail (
    query_id varchar(100),
    start_time datetime,
    end_time datetime,
    latency int comment "unit is milliseconds",   
    state varchar(20) comment "RUNNING/FINISHED/FAILED"
)
duplicate key (query_id)
distributed by hash(query_id) buckets 10;
```

**Comment by morningman** [comment]
Can't this meet your needs?
http://doris.incubator.apache.org/master/zh-CN/extending-doris/audit-plugin.html

**Comment by chaoyli** [comment]
> Can't this meet your needs?
> http://doris.incubator.apache.org/master/zh-CN/extending-doris/audit-plugin.html

It can only analysis the history query. But not analysis the current query profile to get the hotspot.

**Comment by morningman** [comment]
You means profile of current running queries?
But in your proposal, you only talk about the finished query audit?

**Comment by chaoyli** [comment]
> You means profile of current running queries?
> But in your proposal, you only talk about the finished query audit?

All finished query comes from current query. If current query is send to MySQL, and it finished, it will be history queries.

**Comment by morningman** [comment]
I probably understand what you mean, but I am not sure whether the specific plan is feasible. In your proposal, only the query about latency is mentioned, which can be known through historical results. But what runtime state do we need for the query being executed? And how to collect these status?
Because I understand that most of the runtime state is at the BE node, if all are exposed through the FE node, will it cause the FE node to become a bottleneck?

**Comment by chaoyli** [comment]
> I probably understand what you mean, but I am not sure whether the specific plan is feasible. In your proposal, only the query about latency is mentioned, which can be known through historical results. But what runtime state do we need for the query being executed? And how to collect these status?
> Because I understand that most of the runtime state is at the BE node, if all are exposed through the FE node, will it cause the FE node to become a bottleneck?

1. Another field like profile can be added easily in following development.
    As you say, the profile is now in BE node, only report upon finishing query, So I not add the 
    profile field now. If query lasts for a long time, It will be better to report at interval. 
2. I will only store a fixed number(10000) query detail in FE memory. If one query has 100K, It wil 
    consume 1G memory which is acceptable. Considering QPS is 1000, Query Monitor collect 
    detail at 10 seconds can cover the query details statistics.
3. Query Monitor will collect the query detail at interval. If restart FE, It has non-sense, because  
    there is no query in system. The problem is Query Monitor outside is not connected to FE, it will
    lose some detail. I think it's also OK, because some queries takes no consideration have a little 
    thing.
