### ISSUE TITLE
[Spark load] Update hive table syntax in loadstmt

### ISSUE THREAD

**Issue by wyb** [apache/incubator-doris#3787]
1. Create an external hive table, including schema, hive db name, hive table name and load required properties (hive.metastore.uris).
Implement load from external hive table first, and report an error when querying from external hive table.
```sql
CREATE EXTERNAL TABLE example_db.external_hive_table (
  k1 DATE,
  k2 INT,
  v BIGINT
)
ENGINE=hive
PROPERTIES (
  "database" = "hivedb",
  "table" = "hivetable",
  "hive.metastore.uris" = "thrift://127.0.0.1:9083"
)
```

2. Load from external hive table
```sql
LOAD LABEL label0
(DATA FROM TABLE external_hive_table
INTO TABLE table0
set (v=bitmap_dict(v)))
WITH RESOURCE "spark0"
```

#3433

**Comment by wangbo** [comment]
Can it support visit hive metastore by ```hive-site.xml```?
We submit a Spark Job and upload hive-site.xml to visit hive.
For the case that we only need to use a hive table in Spark Load, create a external table in Doris is not necessary

**Comment by wyb** [comment]
> Can it support visit hive metastore by `hive-site.xml`?
Also support now.
> We submit a Spark Job and upload hive-site.xml to visit hive.
> For the case that we only need to use a hive table in Spark Load, create a external table in Doris is not necessary
We will support querying data from hive table in the future.
