### ISSUE TITLE
[Metric] Add new metrics to monitor TCP status

### ISSUE THREAD

**Issue by morningman** [apache/incubator-doris#3827]
**Motivation**

When we operate and maintain the cluster ourselves, we have encountered many times that the state of the Doris cluster is abnormal due to machine network failures, such as heartbeat failure and query blocking. 

Because there is no corresponding metrics, it takes a long time to troubleshoot the problem.

**New metrics**

Add 2 new metrics 

```
tcp_in_errs
tcp_retrans_segs
```

These 2 metrics is got from /proc/net/snmp, indicate the number of error tcp request and number of retransmit tcp requests.

**Comment by chaoyli** [comment]
If you have add TCP error, you can also add more error as follow. 
```
atmptf/s
estres/s
retrans/s
isegerr/s
orsts/s
```

**Comment by morningman** [comment]
> If you have add TCP error, you can also add more error as follow.
> 
> ```
> atmptf/s
> estres/s
> retrans/s
> isegerr/s
> orsts/s
> ```
> 
> You can get the manual from https://linux.die.net/man/1/sar.
> And also, you can use the following command to get the result.
> 
> ```
> sar -n ETCP 1
> ```

In our recent operation and maintenance experience, only these two parameters are currently instructive. Other parameters, such as `atmptf/s`, are always in a non-zero state, which is not helpful for troubleshooting. If there is a demand later, we can add it later.
