### ISSUE TITLE
Table names are not case sensitive

### ISSUE THREAD

**Issue by hf200012** [apache/incubator-doris#3849]
I want to add a case-insensitive function for table names and fields
Improve development efficiency

**Comment by morningman** [comment]
That would be good!
But Doris currently does not have a solid framework to address the name case sensitivity issue.
You can show us more details about your design.

**Comment by hf200012** [comment]
Thank you very much for your dedication
I study the code and think about it

**Comment by hf200012** [comment]
> That would be good!
> But Doris currently does not have a solid framework to address the name case sensitivity issue.
> You can show us more details about your design.

Thank you very much for your dedication
I study the code and think about it

**Comment by IswarPatro** [comment]
I want to work on this issue please assign me this issue.
