### ISSUE TITLE
[Proposal] Make BE web site more pretty

### ISSUE THREAD

**Issue by acelyc111** [apache/incubator-doris#3911]
**Is your feature request related to a problem? Please describe.**
Doris backends web server doesn't support to GET static file, and also doesn't support CSS style.
When we want to show more detail information on BE's web site, it's not easy to add elements. For example, as for https://github.com/apache/incubator-doris/issues/3714, we want to show memtrackers, it's hard to add elements and show them in a pretty style.

**Describe the solution you'd like**
Transfer the webserver utils which Impala and Kudu using:
- Web CSS framwork [boost-table](https://github.com/wenzhixin/bootstrap-table): helpful to make website more pretty
- A thirdparty library [mustache](https://github.com/henryr/cpp-mustache): helpful to tracnslate JSON structure to html

And then do some refactor on current BE web handler.
After that, our BE web site might looks like:
![image](https://user-images.githubusercontent.com/10775040/85109568-1e0e5f00-b244-11ea-8178-2c3503eb4187.png)

**Comment by yangzhg** [comment]
could you also improve the fe webserver？

**Comment by acelyc111** [comment]
> could you also improve the fe webserver and change it to restful
> #3314

I'll try if I have time, I'll reply #3314 if I start to work on it.

**Comment by morningman** [comment]
> > could you also improve the fe webserver and change it to restful
> > #3314
> 
> I'll try if I have time, I'll reply #3314 if I start to work on it.

Someone is working on FE's web server already~
