### ISSUE TITLE
[Proposal]Unify all frontend config behavior

### ISSUE THREAD

**Issue by WingsGo** [apache/incubator-doris#3935]
**Is your feature request related to a problem? Please describe.**
Currently in FE, we have different config, some of them are master only, so we need to directly connect the master FE to change the settings, and some frontend config is shown different in Master FE and no Master FE, it may leads some confusion, So I think maybe we can let non master fe to forward some master only config to Master FE, and keep all frontends display the config as same.

**Comment by morningman** [comment]
that would be good

**Comment by morningman** [comment]
Hi, I found that it already be implemented.

https://github.com/apache/incubator-doris/blob/5e5696fda2c26bf1f1e0dcc6045b280a314f7fbf/fe/src/main/java/org/apache/doris/analysis/AdminSetConfigStmt.java#L53-L59

**Comment by WingsGo** [comment]
> Hi, I found that it already be implemented.
> 
> https://github.com/apache/incubator-doris/blob/5e5696fda2c26bf1f1e0dcc6045b280a314f7fbf/fe/src/main/java/org/apache/doris/analysis/AdminSetConfigStmt.java#L53-L59

That's great, but it seems only support set frontend config DDL, not include show frontend config?

**Comment by morningman** [comment]
> That's great, but it seems only support `admin set frontend config` DDL, not include `admin show frontend config`?If we set some master only config in non master node the change will not shown in non master node, it will confused us if the config works?

You should execute `set forward_to_master=true` before executing `admin show frontend config`.

Because sometimes we DO want to know the config value of current connected FE.

**Comment by WingsGo** [comment]
> > That's great, but it seems only support `admin set frontend config` DDL, not include `admin show frontend config`?If we set some master only config in non master node the change will not shown in non master node, it will confused us if the config works?
> 
> You should execute `set forward_to_master=true` before executing `admin show frontend config`.
> 
> Because sometimes we DO want to know the config value of current connected FE.

Yes, That's what I want, thx~
