### ISSUE TITLE
[DOC-ERROR, Images can't be seen, cause of 404 in the urls]

### ISSUE THREAD

**Issue by francisoliverlee** [apache/incubator-doris#3963]
**Describe the bug**
images can't be seen in [http://doris.incubator.apache.org/master/zh-CN/developer-guide/fe-idea-dev.html#_1-%E7%8E%AF%E5%A2%83%E5%87%86%E5%A4%87](http://doris.incubator.apache.org/master/zh-CN/developer-guide/fe-idea-dev.html#_1-%E7%8E%AF%E5%A2%83%E5%87%86%E5%A4%87)

**To Reproduce**
1. Go to [http://doris.incubator.apache.org/master/zh-CN/developer-guide/fe-idea-dev.html#_1-%E7%8E%AF%E5%A2%83%E5%87%86%E5%A4%87](http://doris.incubator.apache.org/master/zh-CN/developer-guide/fe-idea-dev.html#_1-%E7%8E%AF%E5%A2%83%E5%87%86%E5%A4%87)
2. check images
![image](https://user-images.githubusercontent.com/5908412/85941070-11c88700-b953-11ea-9e74-85f1736a50b2.png)

**Expected behavior**
update images, make them can be seen

**Screenshots**
![image](https://user-images.githubusercontent.com/5908412/85941070-11c88700-b953-11ea-9e74-85f1736a50b2.png)

**Desktop (please complete the following information):**
 - OS mac
 - Browser chrome

**Comment by francisoliverlee** [comment]
@yangzhg i made a summary for how to build FE on mac, if it OK i can give out a PR for this.
http://demoworld.tech/c/%E5%9C%A8Mac%E4%B8%8A%E7%BC%96%E8%AF%91FEWindows%E5%90%8C%E7%90%86_%E6%9C%AA%E9%AA%8C%E8%AF%81

**Comment by yangzhg** [comment]
@francisoliverlee You are welcome to contribute. In step 4, if you import the root directory of doris into idea instead of fe directory, you don't need to copy the files under gensrc

**Comment by francisoliverlee** [comment]
@yangzhg ok， i will give it a try

**Comment by francisoliverlee** [comment]
fixed
