### ISSUE TITLE
./fe/pom.xml-Line92

### ISSUE THREAD

**Issue by 66coder66** [apache/incubator-doris#4100]
祝好： 
       我想请教一下，在执行build.sh的时候  会报依赖 Plugin net.sourceforge.czt.dev:cup-maven-plugin:1.6-cdh or one of its dependencies could not be resolved.... 错误，然后需要修改./fe/pom.xml 的92行 :将http改为https才能编译通过。是否能将项目里这个pom.xml文件92行处http给改为https呢?
       谢谢！

**Comment by yangzhg** [comment]
Could you commit a PR to fix this ?

**Comment by morningman** [comment]
Do you mean here:
https://github.com/apache/incubator-doris/blob/14ac49dde557b54e9578d91f9dba7e148e5c975b/fe/pom.xml#L90-L94
