### ISSUE TITLE
源码编译报错

### ISSUE THREAD

**Issue by zhangchangwei** [apache/incubator-doris#4113]
/opt/apache-doris/apache-doris-0.12.0/be/src/common/logconfig.cpp: In function ‘bool doris::init_glog(const char*, bool)’:
/opt/apache-doris/apache-doris-0.12.0/be/src/common/logconfig.cpp:68:5: error: ‘FLAGS_log_filenum_quota’ was not declared in this scope
     FLAGS_log_filenum_quota = config::sys_log_roll_num;
     ^
/opt/apache-doris/apache-doris-0.12.0/be/src/common/logconfig.cpp:99:9: error: ‘FLAGS_log_split_method’ was not declared in this scope
         FLAGS_log_split_method = "day";
         ^
/opt/apache-doris/apache-doris-0.12.0/be/src/common/logconfig.cpp:102:9: error: ‘FLAGS_log_split_method’ was not declared in this scope
         FLAGS_log_split_method = "hour";
         ^
/opt/apache-doris/apache-doris-0.12.0/be/src/common/logconfig.cpp:105:9: error: ‘FLAGS_log_split_method’ was not declared in this scope
         FLAGS_log_split_method = "size";
         ^
make[2]: *** [src/common/CMakeFiles/Common.dir/logconfig.cpp.o] Error 1
make[1]: *** [src/common/CMakeFiles/Common.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  1%] Building CXX object src/agent/CMakeFiles/Agent.dir/heartbeat_server.cpp.o
[  1%] Building CXX object src/agent/CMakeFiles/Agent.dir/task_worker_pool.cpp.o
[  1%] Building CXX object src/agent/CMakeFiles/Agent.dir/utils.cpp.o
[  1%] Building CXX object src/agent/CMakeFiles/Agent.dir/cgroups_mgr.cpp.o
[  2%] Building CXX object src/agent/CMakeFiles/Agent.dir/topic_subscriber.cpp.o
[  2%] Building CXX object src/agent/CMakeFiles/Agent.dir/user_resource_listener.cpp.o
[  2%] Linking CXX static library libAgent.a
[  2%] Built target Agent
make: *** [all] Error 2

详情日志如下：
File /opt/apache-doris/apache-doris-0.12.0/be/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /opt/apache-doris/apache-doris-0.12.0/be/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_13965/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_13965.dir/build.make CMakeFiles/cmTC_13965.dir/build
gmake[1]: Entering directory `/opt/apache-doris/apache-doris-0.12.0/be/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_13965.dir/CheckFunctionExists.c.o
/usr/local/bin/../bin/gcc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_13965.dir/CheckFunctionExists.c.o   -c /usr/local/share/cmake-3.9/Modules/CheckFunctionExists.c
Linking C executable cmTC_13965
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_13965.dir/link.txt --verbose=1
/usr/local/bin/../bin/gcc  -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_13965.dir/CheckFunctionExists.c.o  -o cmTC_13965 -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_13965] Error 1
gmake[1]: Leaving directory `/opt/apache-doris/apache-doris-0.12.0/be/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_13965/fast] Error 2

**Comment by vagetablechicken** [comment]
```
/opt/apache-doris/apache-doris-0.12.0/be/src/common/logconfig.cpp:68:5: error: ‘FLAGS_log_filenum_quota’ was not declared in this scope
```
So you'd better to check the glog header "glog/logging.h". It should have `DECLARE_int32(log_filenum_quota);`.

**Comment by francisoliverlee** [comment]
@zhangchangwei 
try compile use docker, so easy.
[how-to-build-doris-on-docker](http://doris.incubator.apache.org/master/zh-CN/installing/compilation.html)

**Comment by zhangchangwei** [comment]
thks，i have tried，it's ok

联系人:张长伟
公司:国网汇通金财(北京)信息科技有限公司
公司地址:北京西城区广安门内大街311号祥龙商务大厦一座
联系邮箱:zhangchangwei@sgec.sgcc.com.cn

**Comment by francisoliverlee** [comment]
@zhangchangwei ok

**Comment by lujisen** [comment]
starrocks  编译报错信息：
opt/starrocks/starrocks-2.5.4/be/src/common/logconfig.cpp: In function ‘bool starrocks::init_glog(const char*, bool)’:
/opt/starrocks/starrocks-2.5.4/be/src/common/logconfig.cpp:144:5: error: ‘FLAGS_log_filenum_quota’ was not declared in this scope
  144 |     FLAGS_log_filenum_quota = config::sys_log_roll_num;
      |     ^~~~~~~~~~~~~~~~~~~~~~~
/opt/starrocks/starrocks-2.5.4/be/src/common/logconfig.cpp:174:9: error: ‘FLAGS_log_split_method’ was not declared in this scope
  174 |         FLAGS_log_split_method = "day";
      |         ^~~~~~~~~~~~~~~~~~~~~~
/opt/starrocks/starrocks-2.5.4/be/src/common/logconfig.cpp:177:9: error: ‘FLAGS_log_split_method’ was not declared in this scope
  177 |         FLAGS_log_split_method = "hour";
      |         ^~~~~~~~~~~~~~~~~~~~~~
/opt/starrocks/starrocks-2.5.4/be/src/common/logconfig.cpp:180:9: error: ‘FLAGS_log_split_method’ was not declared in this scope
  180 |         FLAGS_log_split_method = "size";
      |         ^~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/common/CMakeFiles/Common.dir/build.make:118: src/common/CMakeFiles/Common.dir/logconfig.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:649: src/common/CMakeFiles/Common.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

解决方案：
1、这个报错是由于FLAGS_log_split_method 没有声明，logconfig.cpp文件中其实有很多FLAGS_开头的变量，部分没有声明，修改添加声明即可，这里引用的是Google的glog日志，所以需要在2中先了解下glog的用法和原理；
2、可以参考下这个链接，GFlags使用文档:https://blog.csdn.net/weixin_43778179/article/details/104668113,了解下；
3、logconfig.cpp文件引入#include <glog/logging.h>（本身已经引入的不用再次引入），然后找个starrocks的已安装的第三方库，路径一般为：/opt/starrocks/starrocks-2.5.4/thirdparty/installed/include/glog,这是编译好的，直接修改这个也可以，或者直接修改第三方库的源码中的glog/logging.h文件，重新编译三方库都可以；
4、在很多DECLARE_int32的下方声明上面报错的变量即可，我这里报错的是：FLAGS_log_split_method 和FLAGS_log_split_method ，所以这在文件中添加了两个变量的声明，如下：

// add by  lujisen01@inspur.com   
DECLARE_int32(log_filenum_quota);
DECLARE_string(log_split_method);

详细信息请登录我的CSDN账号查看：[https://blog.csdn.net/lujisen/article/details/130386165?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22130386165%22%2C%22source%22%3A%22lujisen%22%7D](https://blog.csdn.net/lujisen/article/details/130386165?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22130386165%22%2C%22source%22%3A%22lujisen%22%7D)
