### ISSUE TITLE
[Bug][Load][Json] Load json format with stream load failed

### ISSUE THREAD

**Issue by morningman** [apache/incubator-doris#4124]
**Describe the bug**
if the json data is larger than 4096 bytes, the data will be truncated, making it impossible to obtain the json data completely

**To Reproduce**
Load a large json file with stream load

**Comment by francisoliverlee** [comment]
@morningman 
4096 bytes means a row or a file ?

**Comment by morningman** [comment]
> @morningman
> 4096 bytes means a row or a file ?

file size.
