### ISSUE TITLE
[BUG] from_base64 

### ISSUE THREAD

**Issue by yuanfeng0905** [apache/incubator-doris#4130]
example sql:

```sql
select a,from_base64(a) 
from (
    select "aGVsbG8=" a 
    union all
    select null a
) t
```
The expect result is:

| a | from_base64(`a`) |
| - | - |
|  aGVsbG8= | hello |
|    |    |

But now the result is:

| a | from_base64(`a`) |
| - | - |
|  aGVsbG8= | hello |
|  | hello |

**Doris version: 0.11.25 (baidu-doris/incubator-doris)**

**Comment by yangzhg** [comment]
It is a bug,and I will fix it, to_base64 function also has this problem, and to_base64 also has an bug may cause memory problem
