### ISSUE TITLE
[BUG] Alter table add key column fails in agg module using LinkedSchemaChange policy

### ISSUE THREAD

**Issue by ZhangYu0123** [apache/incubator-doris#4142]
**Describe the bug**
When alter table add key column in agg model using LinkedSchemaChange policy, "ALTER, status_code: RUNTIME_ERROR"  will be returned. 
The error log as follows:

E0721 13:48:18.405797 34117 alpha_rowset.cpp:308] column pruning size is error.KeysType=AGG_KEYS, zone_maps_size=4, num_key_columns=5, num_columns=5
W0721 13:48:18.405853 34117 alpha_rowset_writer.cpp:227] rowset init failed when build new rowset, res=-402

**To Reproduce**
1. Create table
CREATE TABLE `table13` (
  `siteid` varchar(64) NOT NULL COMMENT "",
  `siteid2` varchar(64) NOT NULL COMMENT "",
  `siteid3` varchar(64) NOT NULL COMMENT ""
) ENGINE=OLAP
AGGREGATE KEY(`siteid`, `siteid2`, `siteid3`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`siteid`) BUCKETS 1
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);

2. insert data
3. alter table add key column
alter table `table13` add column b int key default '0' after `siteid2`

SHOW ALTER TABLE COLUMN;

**Expected behavior**
success

**Screenshots**
![image](https://user-images.githubusercontent.com/67053339/88165526-69070200-cc48-11ea-83b6-619d50a2333e.png)

**Comment by EmmyMiao87** [comment]
Same issue: #4617
