### ISSUE TITLE
[Bug] NIO Mysql Server is leaking sockets

### ISSUE THREAD

**Issue by morningman** [apache/incubator-doris#4191]
**Describe the bug**
Some lvs services will send probing connection requests to Doris' mysql protocol port,
and these requests will fail during the mysql handshake protocol phase.
These connections are not closed properly, causing socket leaks.

**To Reproduce**
1. Start Doris FE.
2. `nc 127.0.0.1 9030`
3. `Ctrl + C` to kill the `nc` process.
4. `lsof -p fe_pid |wc -l`, you will see the number increased.

**Version**
0.12

**Comment by francisoliverlee** [comment]
we hit it too. thank the PR
