### ISSUE TITLE
[Doris On ES][Bug] When multi fields with `text` type, query ES table would fails

### ISSUE THREAD

**Issue by hexian55** [apache/incubator-doris#4295]
**Describe the bug**
MappingPhase.resolveKeywordFields put null value in fetchFieldsContext

**To Reproduce**
1. es index mapping
{
  "test": {
    "mappings": {
      "properties": {
        "k1": {
          "type": "long"
        },
        "k2": {
          "type": "keyword"
        },
        "k3": {
          "type": "text",
          "fields": {
            "ik": {
              "type": "text",
              "analyzer": "ik_max_word"
            }
          }
        }
      }
    }
  }
}

2. create es table.....

3. See error
![image](https://user-images.githubusercontent.com/16074700/89702202-209e5280-d971-11ea-8c42-eee44a6a75bc.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wuyunfeng** [comment]
resolved by https://github.com/apache/incubator-doris/pull/4300
