### ISSUE TITLE
storage_format使用v2版本，导致backend crash

### ISSUE THREAD

**Issue by peterchen859** [apache/incubator-doris#4302]
操作系统 ubuntu 16,  doris 版本是0.12，只要是表的storage_format采用v2，在查询时，会导致be crash;
另外，就算storage_format是v1时，只要table中有字段类型为bitmap的，在查询时，也会导致be crash, 请问具体是什么原因？

**Comment by kongqiu** [comment]
遇到了跟你一样的问题，我验证了三套环境，操作系统都是Centos7.7的，三套环境用的是同一个编译好的二进制文件(在docker编译)，都是0.12的。
第一套是搭在虚拟机里的，storage_format无论是采用v1和v2都没有任何问题。
第二套是搭在云服务器里，storage_format为v1时，当表里含有bitmap字段时，插入第一条数据后查询无问题，当插入第二条数据后，再查询会导致 be crash 。 storage_format为v2时，查询直接 be crash。
第三套搭在物理机上，问题跟在云服务器的一模一样。

**Comment by chaoyli** [comment]
@peterchen859 @kongqiu 请问可以描述一下详细的问题，复现逻辑，估计处理的有bug。

**Comment by kongqiu** [comment]
doris版本0.12，编译环境 docker apachedoris/doris-dev:build-env-1.2 .
编译出的二进制软件包，部署到阿里云服务器Centos7.5上跑能正常运行，
部署到腾讯云服务器Centos7.5上，无论是storage_format 是v1还是v2，只要涉及到bitmap的字段的查询，都会导致be crash , 报错的信息提示 :  3756 alpha_rowset.cpp:178] failed to get largest_segment_group. is null: 1. version: 3-3. tablet: 10007.

好像是跟操作系统环境有关系，但是不知道是环境间的哪里的差别导致了问题发生。

**Comment by chaoyli** [comment]
https://github.com/apache/incubator-doris/issues?q=roaring
是不是roaring bitmap编译的问题，因为不同系统，可能支持的命令不同。

**Comment by peterchen859** [comment]
> @peterchen859 @kongqiu 请问可以描述一下详细的问题，复现逻辑，估计处理的有bug。

非常简单两个操作：
1、建表中storage_format采用v2，写入数据，再做查询，直接导致be crash;
2、建表storage_format是v1时，只要table中有字段类型为bitmap的，写入一条带bitmpa 字段的数据，再做查询时，也会导致be crash;

**Comment by kongqiu** [comment]
@chaoyli 确实是这个croaring bitmap的问题，按照  #3791 这个说明重新编译了libroaring.a 这个库文件，问题解决。 感谢！
