### ISSUE TITLE
[Question] How to alter the replication_num for all the partitions

### ISSUE THREAD

**Issue by Fullstop000** [apache/incubator-doris#4340]
I'm testing out to scale-in the cluster from 2 BEs to single BE. And it seems I need to set the `replication_num=1` to all the partitions of all the tables first.
Here is what I tried following the doc:
```
mysql> ALTER TABLE bi_day_all_hourly_report2 MODIFY PARTITION (*) SET ("replication_num"="1");
ERROR 1064 (HY000): errCode = 2, detailMessage = Syntax error in line 1:
..._report2 MODIFY PARTITION (*) SET ("replication_num"="1")
```
Is there any way to do this?

**Comment by morningman** [comment]
What is your Doris version.
`ALTER TABLE bi_day_all_hourly_report2 MODIFY PARTITION (*) SET ("replication_num"="1");`
this command will be supported in version 0.13, which has not been released yet.
