### ISSUE TITLE
等值join 被判定为 非等值join

### ISSUE THREAD

**Issue by fireofsun** [apache/incubator-doris#435]
**Describe the bug**
等值outer left join被判断为  non-equal LEFT OUTER JOIN

**To Reproduce**
数据库中存在orders表，该表包含Cost_Item 列，运行以下
使用mysql workbench连接数据库，运行以下sql

select * from
(select Cost_Item from orders)  a
left join 
(select Cost_Item from orders)  b
on a.Cost_Item=b.Cost_Item +b.Cost_Item

得到以下反馈：
11:44:46	select * from (select Cost_Item from orders)  a LEFT JOIN  (select Cost_Item from orders)  b on a.Cost_Item=b.Cost_Item +b.Cost_Item LIMIT 0, 50	Error Code: 1064. non-equal LEFT OUTER JOIN is not supported	0.042 sec

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ighack** [comment]
我也想用这种查询语句。现在可以了吗？

**Comment by EmmyMiao87** [comment]
目前还不可以。主要是join的条件不能是 a.Cost_Item=b.Cost_Item +b.Cost_Item，如果是 a.Cost_Item=b.Cost_Item是可以的。
