### ISSUE TITLE
[Doris On ES][Bug] ES queries always route at same 3 BE nodes

### ISSUE THREAD

**Issue by caoyang10** [apache/incubator-doris#4351]
I create a external ES table and test some queries on ES.Then I find all of the queries route at same 3 BE nodes.
I find the code at fe/fe-core/src/main/java/org/apache/doris/planner/EsScanNode.java
227: candidateBeList.add(backendList.get(beIndex++ % numBe));
numBe is always 3 when number of be is greater than 3. So that candidateBeList always add 3 front of beckendList.
It should be corrected like:
candidateBeList.add(backendList.get(beIndex++ % backendList.size()));
Then FE can balance ES queries between BE nodes.

**Comment by wuyunfeng** [comment]
Thanks @caoyang10 . Will you solve this problem, if you can, I would like to assign this issue to you.
