### ISSUE TITLE
[Question] a more complex query runs count(distinct) faster.

### ISSUE THREAD

**Issue by wyndia** [apache/incubator-doris#4353]
HI. I'm using Doris 0.12.0 on one single machine (1 FE, 1 BE). And I have table t looking like this:
```SQL
CREATE TABLE `t` (
  `user_id` char(16) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`user_id`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`user_id`) BUCKETS 64
PROPERTIES (
"storage_type" = "COLUMN",
 "colocate_with" = "group1",
 "replication_num" = "1",
 "in_memory" = "false"
);
```
It has about 90,000,000 records and they are all unique.
However, I find these two queries perform differently:
```SQL
select count(distinct a.user_id) from t a join t b on a.user_id = b.user_id;  -- finished in 22 sec
select count(distinct user_id) from t;  -- finished in 58s
```
The first one runs almost twice as fast as the second one.
I'm very confused right now. Does it have something to do with the colocation group? 
Can any one explain this for me please?

**Comment by morningman** [comment]
You can try to get a profile first,
http://doris.incubator.apache.org/master/zh-CN/administrator-guide/running-profile.html

**Comment by wyndia** [comment]
> You can try to get a profile first,
> http://doris.incubator.apache.org/master/zh-CN/administrator-guide/running-profile.html

Thank you! The profile is very helpful. 
I just find that modifying `parallel_fragment_exec_instance_num` will make improvements. (but will cost more resources)
