### ISSUE TITLE
[Bug] Some deleted tablets are not recycled on BE and occupy too much disk space!

### ISSUE THREAD

**Issue by yiguolei** [apache/incubator-doris#4400]
If a tablet is rebalanced to and from the same BE too many times, there will be many tablet folder on the BE. 

In tablet manager code, there is a shutdown tablet SET to track deleted tablets using  TABLET ID. But the tablet id is the same one if the same tablet is balanced to and from the same BE many times and there will be only one tablet id in the set at last. So that other folders with same tablet will not be recycled.

**Comment by stalary** [comment]
good, This solves the problem of my disk space not being freed

**Comment by yiguolei** [comment]
already merged

**Comment by morningman** [comment]
> already merged

This patch also slow down the startup time of BE...
Can you help us to improve it? LOL!
