### ISSUE TITLE
parse_url function can not parse "protocol" correctly

### ISSUE THREAD

**Issue by xinghuayu007** [apache/incubator-doris#4451]
**Describe the bug**
parse_url function can not parse "PROTOCOL" correctly, and can not support to parse "PORT", and it is case sensitive.

**To Reproduce**
1. execute sql **"select parse_url("http://www.baidu.com:8080", "PROTOCOL");"**
2. it returns error:
![2020-08-25 21-46-42屏幕截图](https://user-images.githubusercontent.com/12771191/91182686-132cea80-e71d-11ea-8fed-84d185bf1f9d.png)

3. execute sql "select parse_url("http://www.baidu.com:8080", "host");"
4. it returns error:
![2020-08-25 21-47-05屏幕截图](https://user-images.githubusercontent.com/12771191/91182792-36579a00-e71d-11ea-9c57-fe8e1b1e57f4.png)

5. execute sql "select parse_url("http://www.baidu.com:8080", "PORT");"
6. it returns error:
![2020-08-25 21-47-28屏幕截图](https://user-images.githubusercontent.com/12771191/91182879-55562c00-e71d-11ea-994a-9224b94f34f5.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Pslydhh** [comment]
+1, This looks correct to me.
