### ISSUE TITLE
master分支： Malformed packet错误

### ISSUE THREAD

**Issue by chxfantasy** [apache/incubator-doris#4455]
![image](https://user-images.githubusercontent.com/5556993/91283185-d6b0cb80-e7bc-11ea-9ad1-125b2d087054.png)

desc dwm_show_test all;
会返回ERROR 2027 (HY000): Malformed packet

**Comment by oiupoiupga1** [comment]
我也遇到这个问题了，show load会报这个错，Broker Load这种导数据的方式不行

**Comment by oiupoiupga1** [comment]
客户端的问题，改成sql yog连接就不会报错了
