### ISSUE TITLE
connect doris use mysql-driver error

### ISSUE THREAD

**Issue by stalary** [apache/incubator-doris#4483]
**Describe the bug**
 @@HikariPool@@ | doris-pool - Exception during pool initialization.
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: errCode = 2, detailMessage = Invalid number format:

**version**
master

**Comment by stalary** [comment]
select @@sql_mode AS sql_mode;
ERROR 1064 (HY000): errCode = 2, detailMessage = Invalid number format:

**Comment by francisoliverlee** [comment]
@stalary what's doris version ?

**Comment by stalary** [comment]
https://github.com/apache/incubator-doris/commit/3b7614e174d3999e18056d6d741641d664c52908

**Comment by stalary** [comment]
> @stalary what's doris version ?

https://github.com/apache/incubator-doris/commit/3b7614e174d3999e18056d6d741641d664c52908
