### ISSUE TITLE
json解析函数key中带有特殊关键字，比如（#  .   |）会出现无法解析的情况

### ISSUE THREAD

**Issue by 413331861** [apache/incubator-doris#449]
测试例子如下：

MySQL [test]> select * from a;
+------+-----------------------------------+
| id   | data                              |
+------+-----------------------------------+
|    2 | {"text.abc":"MXCHIP won a prize"} |
|    4 | {"text|abc":"MXCHIP won a prize"} |
|    1 | {"text_abc":"MXCHIP won a prize"} |
|    3 | {"text#abc":"MXCHIP won a prize"} |
+------+-----------------------------------+
4 rows in set (0.01 sec)

MySQL [test]> select get_json_string(data,'$.text_abc') from a;
+---------------------------------------+
| get_json_string(`data`, '$.text_abc') |
+---------------------------------------+
| NULL                                  |
| NULL                                  |
| MXCHIP won a prize                    |
| NULL                                  |
+---------------------------------------+
4 rows in set (0.01 sec)

MySQL [test]> select get_json_string(data,'$.text.abc') from a;
+---------------------------------------+
| get_json_string(`data`, '$.text.abc') |
+---------------------------------------+
| NULL                                  |
| NULL                                  |
| NULL                                  |
| NULL                                  |
+---------------------------------------+
4 rows in set (0.01 sec)

MySQL [test]> select get_json_string(data,'$.text#abc') from a;
+---------------------------------------+
| get_json_string(`data`, '$.text#abc') |
+---------------------------------------+
| NULL                                  |
| NULL                                  |
| NULL                                  |
| NULL                                  |
+---------------------------------------+
4 rows in set (0.01 sec)

MySQL [test]> select get_json_string(data,'$.text|abc') from a;
+---------------------------------------+
| get_json_string(`data`, '$.text|abc') |
+---------------------------------------+
| NULL                                  |
| NULL                                  |
| NULL                                  |
| NULL                                  |
+---------------------------------------+
4 rows in set (0.01 sec)

**Comment by morningman** [comment]
Using boost 'tokenizer' instead of 'split' to parse the json_path parameter.
This will impact the parsing performance(about 30%), will we find a way improve the json query performance in future
