### ISSUE TITLE
[BUG] Redundant columns are generated when the table is created

### ISSUE THREAD

**Issue by stalary** [apache/incubator-doris#4508]
**Describe the bug**
Redundant columns are generated when the table is created

**To Reproduce**
use master version

**Screenshots**
<img width="334" alt="截屏2020-09-01 下午4 44 34" src="https://user-images.githubusercontent.com/24592373/91926959-0571f900-ed0b-11ea-8fd8-1420f284c817.png">

**Comment by stalary** [comment]
@yangzhg

**Comment by stalary** [comment]
What's the status of this question

**Comment by yangzhg** [comment]
If the aggregation type of the table you use is unique and the fe configuration item enable_batch_delete_by_default is true or the table has executed enable feature batch_delete, this column will be created. This column will not affect your use. The hidden logic will be improved in subsequent versions to make it Invisible
