### ISSUE TITLE
[New Feature]Set the default quota value of the database in the configuration file

### ISSUE THREAD

**Issue by zhaojintaozhao** [apache/incubator-doris#4540]
Hi, All: 

In our system, we use software to automatically create the doris database. However, the default quota of the Doris database is 1 TB, That is too small. Therefore, after the program automatically creates the database, we need to manually set the quota to 10 TB.

Therefore, we hope that the default quota can be set in the configuration file. After the database is created, the quota is automatically set to the default value in the configuration file.

When Doris-FE startup, FE reads the quota value from the configuration file. When creating a database, set quota to the value in the configuration file.

I have implemented this feature. The database quota is read from the configuration file. When creating a database, set the quota value to the value read from the configuration file. I want to feed this feature back to Apache-Doris-Community.

**Comment by caoyang10** [comment]
I don't understand why we need to set database quota. 
Are there any problems if we don't set it?  

BTW, routine load job will stop (not pause) when data size is larger the quota size.
It may cause some other unexpected errors when it happened

**Comment by zhaojintaozhao** [comment]
> I don't understand why we need to set database quota.
> Are there any problems if we don't set it?
> 
> BTW, routine load job will stop (not pause) when data size is larger the quota size.
> It may cause some other unexpected errors when it happened

If we don't set,  It will use default quota 1TB just like before.
