### ISSUE TITLE
[BUG]BE crash occasionally 

### ISSUE THREAD

**Issue by caoyang10** [apache/incubator-doris#4568]
BE crash occasionally and I don't know the reason.
Here is the log:

*** Aborted at 1599640998 (unix time) try "date -d @1599640998" if you are using GNU date ***
PC: @          0x1374709 std::vector<>::operator=()
*** SIGSEGV (@0x78) received by PID 54137 (TID 0x7f0dc4166700) from PID 120; stack trace: ***
    @     0x7f0e25355270 (unknown)
    @          0x1374709 std::vector<>::operator=()
    @          0x136e81a doris::TTypeDesc::operator=()
    @          0x12f7a59 doris::TExprNode::TExprNode()
    @          0x12e66e0 std::vector<>::operator=()
    @          0x12ddd71 doris::TOlapTablePartition::TOlapTablePartition()
    @          0x12e6aa0 std::vector<>::operator=()
    @          0x12de235 doris::TOlapTablePartitionParam::TOlapTablePartitionParam()
    @          0x14d8ac6 doris::OlapTablePartitionParam::OlapTablePartitionParam()
    @          0x14e7f7a doris::stream_load::OlapTableSink::init()
    @          0x14749a5 doris::DataSink::create_data_sink()
    @          0x105f157 doris::PlanFragmentExecutor::prepare()
    @           0xfe9578 doris::FragmentMgr::exec_plan_fragment()
    @          0x109db09 doris::StreamLoadExecutor::execute_plan_fragment()
    @          0x103b2d8 doris::RoutineLoadTaskExecutor::exec_task()
    @          0x1039005 _ZN5boost6detail8function26void_function_obj_invoker0INS_3_bi6bind_tIvNS_4_mfi3mf3IvN5doris23RoutineLoadTaskExecutorEPNS7_17StreamLoadContextEPNS7_16DataConsumerPoolESt8functionIFvSA_EEEENS3_5list4INS3_5valueIPS8_EENSI_ISA_EENSI_ISC_EENSI_IZNS8_11submit_taskERKNS7_16TRoutineLoadTaskEEUlSA_E_EEEEEEvE6invokeERNS1_15function_bufferE
    @           0xfbb835 doris::PriorityThreadPool::work_thread()
    @          0x1aa7fbd thread_proxy
    @     0x7f0e2510be25 start_thread
    @     0x7f0e2541834d __clone

Doris version is : 3359467b9a8750883f2ba4a0d5bd0e4298354b79
Help wanted!

**Comment by morningman** [comment]
Not seeing this bug before.
We may need a coredump file and GDB it...

**Comment by caoyang10** [comment]
sorry, I lost BE log. 
I will post the issue next time and store the log.
