### ISSUE TITLE
指标不兼容prometheus2.6

### ISSUE THREAD

**Issue by yuanfeng0905** [apache/incubator-doris#457]
**prometheus2.6抓取指标报错**

level=warn ts=2018-12-21T09:48:35.525960902Z caller=scrape.go:835 component="scrape manager" scrape_pool=PALO_CLUSTER target=http://10.8.20.236:8040/metrics msg="append failed" err="invalid metric type \"GAUGE\""

**Comment by morningman** [comment]
We already fix it in 0.8.2.1, just change GAUGE to gauge.
