### ISSUE TITLE
表添加列失败

### ISSUE THREAD

**Issue by pangjianfei** [apache/incubator-doris#4617]
**Bug描述**

doris版本：0.12.19

出现bug的操作：执行  `alter table tmp_table add column appId int after tagId;` 命令添加列失败。

tmp_table表的数据大小为：267G

执行的结果：
![image](https://user-images.githubusercontent.com/26674357/93447887-89300600-f905-11ea-9c66-aeeaf12be553.png)

BE warning log日志：
![image](https://user-images.githubusercontent.com/26674357/93448074-c5fbfd00-f905-11ea-8b49-6d51a36cea59.png)

FE日志：
![image](https://user-images.githubusercontent.com/26674357/93448621-618d6d80-f906-11ea-9655-90a1b99c36ca.png)

不是每个表执行这个操作都会失败

**Comment by EmmyMiao87** [comment]
This is a duplicate issue: #4142

**Comment by pangjianfei** [comment]
thanks🙏
