### ISSUE TITLE
The thirdparty repository url is broken.

### ISSUE THREAD

**Issue by Cr1t-GYM** [apache/incubator-doris#4689]
When I execute the command "./download-thirdparty.sh", the bash reported the errors:

===== Downloading thirdparty archives...
Downloading libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip from https://doris-incubating-repo.bj.bcebos.com/thirdparty/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip to /home/yiming/Squirrel/incubator-doris/thirdparty/src
--2020-09-29 17:16:37--  https://doris-incubating-repo.bj.bcebos.com/thirdparty/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip
Resolving doris-incubating-repo.bj.bcebos.com (doris-incubating-repo.bj.bcebos.com)... 220.181.33.44, 220.181.33.43, 2409:8c00:6c21:10ad:0:ff:b00e:67d
Connecting to doris-incubating-repo.bj.bcebos.com (doris-incubating-repo.bj.bcebos.com)|220.181.33.44|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-09-29 17:16:38 ERROR 403: Forbidden.

Failed to download libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip. attemp: 1
/home/yiming/Squirrel/incubator-doris/thirdparty/src/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip md5sum check failed!
except-md5 e8b9ba50270ba3b520aec8ff1089f9d7
actual-md5 d41d8cd98f00b204e9800998ecf8427e  /home/yiming/Squirrel/incubator-doris/thirdparty/src/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip
Archive libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip will be removed and download again.
Failed to download libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip
Downloading libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip from https://doris-incubating-repo.bj.bcebos.com/thirdparty/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip to /home/yiming/Squirrel/incubator-doris/thirdparty/src
--2020-09-29 17:16:38--  https://doris-incubating-repo.bj.bcebos.com/thirdparty/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip
Resolving doris-incubating-repo.bj.bcebos.com (doris-incubating-repo.bj.bcebos.com)... 220.181.33.44, 220.181.33.43, 2409:8c00:6c21:10ad:0:ff:b00e:67d
Connecting to doris-incubating-repo.bj.bcebos.com (doris-incubating-repo.bj.bcebos.com)|220.181.33.44|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-09-29 17:16:38 ERROR 403: Forbidden.

Failed to download libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip. attemp: 1
/home/yiming/Squirrel/incubator-doris/thirdparty/src/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip md5sum check failed!
except-md5 e8b9ba50270ba3b520aec8ff1089f9d7
actual-md5 d41d8cd98f00b204e9800998ecf8427e  /home/yiming/Squirrel/incubator-doris/thirdparty/src/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip
Archive libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip will be removed and download again.
Failed to download libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip
Failed to download libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip

If I check the url in the web browser, it reported the massages:
{"code":"AccountOverdue","message":"Your request is denied because there is an overdue bill of your account.","requestId":"34341815-75e4-48b3-81ac-f4fe233d58aa"}

**Comment by morningman** [comment]
Use this instead:
https://doris-thirdparty-repo.bj.bcebos.com/thirdparty/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip


I will modify the code later
