### ISSUE TITLE
编译失败　brpc部分

### ISSUE THREAD

**Issue by cooper-zhzhang** [apache/incubator-doris#4698]
[ 97%] Built target Runtime
[ 97%] Building CXX object src/util/CMakeFiles/Util.dir/zlib.cpp.o
Scanning dependencies of target DorisUdf
[ 97%] Building CXX object src/udf/CMakeFiles/DorisUdf.dir/udf.cpp.o
[ 97%] Linking CXX static library libUtil.a
[ 99%] Built target Util
Scanning dependencies of target palo_be
make[2]: *** No rule to make target 'incubator-doris/thirdparty/installed//lib64/libbrpc.a', needed by 'src/service/palo_be'。 停止。
make[2]: *** 正在等待未完成的任务....
[ 99%] Building CXX object src/service/CMakeFiles/palo_be.dir/doris_main.cpp.o
[ 99%] Linking CXX static library libDorisUdf.a
[ 99%] Built target DorisUdf
Scanning dependencies of target meta_tool
make[2]: *** No rule to make target 'incubator-doris/thirdparty/installed//lib64/libbrpc.a', needed by 'src/tools/meta_tool'。 停止。
make[2]: *** 正在等待未完成的任务....
[ 99%] Building CXX object src/tools/CMakeFiles/meta_tool.dir/meta_tool.cpp.o
CMakeFiles/Makefile2:1064: recipe for target 'src/tools/CMakeFiles/meta_tool.dir/all' failed
make[1]: *** [src/tools/CMakeFiles/meta_tool.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
CMakeFiles/Makefile2:911: recipe for target 'src/service/CMakeFiles/palo_be.dir/all' failed
make[1]: *** [src/service/CMakeFiles/palo_be.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by yangzhg** [comment]
Please provide information about the building environment
