### ISSUE TITLE
Routine load report TOO_MANY_TASKS

### ISSUE THREAD

**Issue by stalary** [apache/incubator-doris#4713]
**Describe the bug**
errCode = 2, detailMessage = failed to send task: errCode = 2, detailMessage = failed to submit task. error code: TOO_MANY_TASKS, msg: 89314e0297ac4ce9-b0f4b443001c41e3.

But I don't have that many tasks running

**Version**
0.13.0-rc02

**Comment by DongTL** [comment]
请问解决了吗？我遇到了同样的问题。

**Comment by stalary** [comment]
> 请问解决了吗？我遇到了同样的问题。

Upgrading to 0.14.12.4 can be resolved

**Comment by DongTL** [comment]
> > 请问解决了吗？我遇到了同样的问题。
> 
> Upgrading to 0.14.12.4 can be resolved

请问，0.14.12.4版本在哪里下载，官网只看到有0.14.0

**Comment by stalary** [comment]
> > > 请问解决了吗？我遇到了同样的问题。
> > 
> > 
> > Upgrading to 0.14.12.4 can be resolved
> 
> 请问，0.14.12.4版本在哪里下载，官网只看到有0.14.0

http://palo.baidu.com/docs/%E4%B8%8B%E8%BD%BD%E4%B8%93%E5%8C%BA/%E9%A2%84%E7%BC%96%E8%AF%91%E7%89%88%E6%9C%AC%E4%B8%8B%E8%BD%BD/

**Comment by DongTL** [comment]
> > > > 请问解决了吗？我遇到了同样的问题。
> > > 
> > > 
> > > Upgrading to 0.14.12.4 can be resolved
> > 
> > 
> > 请问，0.14.12.4版本在哪里下载，官网只看到有0.14.0
> 
> http://palo.baidu.com/docs/%E4%B8%8B%E8%BD%BD%E4%B8%93%E5%8C%BA/%E9%A2%84%E7%BC%96%E8%AF%91%E7%89%88%E6%9C%AC%E4%B8%8B%E8%BD%BD/

thanks!

**Comment by zyw8136** [comment]
errCode = 2, detailMessage = failed to send task: errCode = 2, detailMessage = failed to submit task. error code: TOO_MANY_TASKS, msg: 744a464932ea4ce4-941cbeaa91959e95 升级到了最新版本还报这个错误！

**Comment by zyw8136** [comment]
升级到0.14.12.4还是有这个问题。

**Comment by morningman** [comment]
#6342 This may solve this problem

**Comment by ilLiker** [comment]
我是1.1.5，也遇到了这个问题。
