### ISSUE TITLE
Log4j RollingFileAppender performance sometimes be the bottlenecks for high qps of fe thrift server

### ISSUE THREAD

**Issue by caiconghui** [apache/incubator-doris#4765]
many threads of thrift server stuck like following:
![image](https://user-images.githubusercontent.com/55968745/96447684-df65d100-1244-11eb-972e-a4b08f07c1fc.png)

**Comment by caiconghui** [comment]
![image](https://user-images.githubusercontent.com/55968745/96447739-f60c2800-1244-11eb-81be-5b8d8bfce387.png)

**Comment by caiconghui** [comment]
![image](https://user-images.githubusercontent.com/55968745/96447776-06240780-1245-11eb-8780-28818a53c39c.png)

**Comment by imay** [comment]
@caiconghui 
Dit you try to log asynchronously？

**Comment by caiconghui** [comment]
> @caiconghui
> Dit you try to log asynchronously？

This is a solution, but there are still some risk to lost log data for this solution. In my option, the log level should be changed from info to debug in some class such as  FrontendServiceImpl, which process event may be in high qps. and only when we want to trace problem should we log data again. many useless log cause the log file huge at the same time.

**Comment by caiconghui** [comment]
https://logging.apache.org/log4j/2.x/manual/async.html  another solution is https://logging.apache.org/log4j/2.x/manual/async.html
