### ISSUE TITLE
[Bug] UNION ALL query return wrong empty set

### ISSUE THREAD

**Issue by ccoffline** [apache/incubator-doris#4772]
**Describe the bug**

```sql
-- create table
DROP TABLE IF EXISTS `test_t`;
CREATE TABLE `test_t` (
  `name` VARCHAR(1000) NULL COMMENT "string"
) ENGINE=OLAP
DUPLICATE KEY(`name`)
DISTRIBUTED BY HASH(`name`) BUCKETS 5
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);

-- insert data
INSERT INTO test_t (`name`)
VALUES ('aaaaa'), ('ccccc')
;

-- returns wrong empty set
SELECT `t1`.`name`
FROM (
   SELECT `name`
   FROM `test_t`
GROUP BY `name`
   ) `t1`
UNION ALL
SELECT `t2`.`name`
FROM (
   SELECT `name`,
      -1 as `bool`
   FROM `test_t`
GROUP BY `name`
   ) `t2`
WHERE `t2`.`bool` = 1
;

-- returns correct result ‘aaaaa’ and ‘ccccc’
SELECT `t2`.`name`
FROM (
   SELECT `name`,
      -1 as `bool`
   FROM `test_t`
GROUP BY `name`
   ) `t2`
WHERE `t2`.`bool` = 1
UNION ALL
SELECT `t1`.`name`
FROM (
   SELECT `name`
   FROM `test_t`
GROUP BY `name`
   ) `t1`
;
```

**Additional context**
Fixing, may need some help QAQ.

**Comment by ccoffline** [comment]
This is most likely because Doris treats UNION clause conditions as conditions for the entire previous query.
Test result on `MySQL 5.7` shows that these two queries return the same result.
I haven't found any description of union queries like this in the SQL standard, but I think Doris should keep the same actions as `MySQL`.

**Comment by ccoffline** [comment]
This bug was caused by #4206's fix #4235, `scanNodes.clear()` here remove all previous `scanNodes` if the last statement's condition is false.
https://github.com/apache/incubator-doris/blob/a61eea3b2e76d741c98b9faed8cec51c1d469f94/fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java#L284-L290

**Comment by kangkaisen** [comment]
I forget to submit a PR to the Github master branch.
You could change the code to, and submit a PR.
```
        if (analyzer.hasEmptyResultSet()) {
            List<TupleId> scanTupleIds = root.getAllScanTupleIds();
            PlanNode node = createEmptyNode(stmt, analyzer);
            // Ensure result exprs will be substituted by right outputSmap
            node.setOutputSmap(root.outputSmap);

            // Must and could only remove the scanNode that the tuple id is same with EmptyNode,
            // otherwise we will get NPE in Coordinator::computeScanRangeAssignment
            scanNodes.removeIf(scanNode -> scanTupleIds.contains(scanNode.getTupleIds().get(0)));
            // Currently, getMaterializedTupleIds for AnalyticEvalNode is wrong,
            // So we explicitly add AnalyticEvalNode tuple ids to EmptySetNode
            if (root instanceof AnalyticEvalNode) {
                node.getTupleIds().addAll(root.tupleIds);
            }
            return node;
        }
```

**Comment by ccoffline** [comment]
> I forget to submit a PR to the Github master branch.
> You could change the code to, and submit a PR.
> 
> ```
>         if (analyzer.hasEmptyResultSet()) {
>             List<TupleId> scanTupleIds = root.getAllScanTupleIds();
>             PlanNode node = createEmptyNode(stmt, analyzer);
>             // Ensure result exprs will be substituted by right outputSmap
>             node.setOutputSmap(root.outputSmap);
> 
>             // Must and could only remove the scanNode that the tuple id is same with EmptyNode,
>             // otherwise we will get NPE in Coordinator::computeScanRangeAssignment
>             scanNodes.removeIf(scanNode -> scanTupleIds.contains(scanNode.getTupleIds().get(0)));
>             // Currently, getMaterializedTupleIds for AnalyticEvalNode is wrong,
>             // So we explicitly add AnalyticEvalNode tuple ids to EmptySetNode
>             if (root instanceof AnalyticEvalNode) {
>                 node.getTupleIds().addAll(root.tupleIds);
>             }
>             return node;
>         }
> ```

I can't find method `getAllScanTupleIds` in `PlanNode root`

**Comment by kangkaisen** [comment]
@ccoffline Sorry. you could add this method to `PlanNode`:

```
    protected List<TupleId> getAllScanTupleIds() {
        List<TupleId> tupleIds = Lists.newArrayList();
        List<OlapScanNode> scanNodes = Lists.newArrayList();
        collectAll(Predicates.instanceOf(OlapScanNode.class), scanNodes);
        for(OlapScanNode node: scanNodes) {
            tupleIds.addAll(node.getTupleIds());
        }
        return tupleIds;
    }
```
