### ISSUE TITLE
Exceed the maximal row size while creating table

### ISSUE THREAD

**Issue by Karl-WangSK** [apache/incubator-doris#4789]
what do I need to set in prop when occurring 
java.sql.SQLSyntaxErrorException: errCode = 2, detailMessage =  The size of a row (157200) exceed the maximal row size: 100000

**Comment by morningman** [comment]
Currently, Doris only support a row with max length of 100KB.
You can add the config in `fe.conf`
```
max_layout_length_per_row=xxx
```
to configure this value, the default is 100000, unit is Byte.

And it may impact the performance, which we are not sure about it.

**Comment by Karl-WangSK** [comment]
Can I add this in PROPERTIES while creating table ? Or must be set in `fe.conf`?

**Comment by Karl-WangSK** [comment]
> Currently, Doris only support a row with max length of 100KB.
> You can add the config in `fe.conf`
> 
> ```
> max_layout_length_per_row=xxx
> ```
> 
> to configure this value, the default is 100000, unit is Byte.
> 
> And it may impact the performance, which we are not sure about it.

Can I add this in PROPERTIES while creating table ? Or must be set in fe.conf?

**Comment by morningman** [comment]
Property is not supported yet, you have to set it in fe.conf, currently.

**Comment by Karl-WangSK** [comment]
> Property is not supported yet, you have to set it in fe.conf, currently.

Thank you. I figured out.
Set this in clause.
ADMIN SET FRONTEND CONFIG ("fe_config_name" = "fe_config_value");

**Comment by Karl-WangSK** [comment]
BTW ,  do you know why I get return msg without any reason?  The status is 200... And I stream load  1000 sample data.
 Content:{
    "TxnId": 4017,
    "Label": "1603694731567",
    "Status": "Fail",
    "Message": "",
    "NumberTotalRows": 0,
    "NumberLoadedRows": 0,
    "NumberFilteredRows": 0,
    "NumberUnselectedRows": 0,
    "LoadBytes": 0,
    "LoadTimeMs": 0,
    "BeginTxnTimeMs": 1003,
    "StreamLoadPutTimeMs": 1011,
    "ReadDataTimeMs": 0,
    "WriteDataTimeMs": 0,
    "CommitAndPublishTimeMs": 0
}
