### ISSUE TITLE
ErrorReason{code=errCode = 104, msg='be 10003 abort task with reason: Broker: Offset out of range'} 

### ISSUE THREAD

**Issue by demon-gu** [apache/incubator-doris#4832]
从Kafka中拉取数据到Doris出现这个问题ErrorReason{code=errCode = 104, msg='be 10003 abort task with reason: Broker: Offset out of range'} ，建表语句定义的offset是"kafka_offsets"="0,0,0,0,0,0,0,0,0"，请问这是什么原因呀？

**Comment by imay** [comment]
是不是Kafka中已经没有这么多的数据了？

**Comment by demon-gu** [comment]
> 是不是Kafka中已经没有这么多的数据了？

我这边解决了，设置一下property.kafka_default_offsets为OFFSET_END或者OFFSET_BEGING就可以了
