### ISSUE TITLE
when use Doris as sink target of Flink job, it failed with message "Unknown system variable 'performance_schema'"

### ISSUE THREAD

**Issue by petermenglei** [apache/incubator-doris#4871]
Caused by: java.sql.SQLException: errCode = 2, detailMessage = Unknown system variable 'performance_schema'

**Comment by imay** [comment]
This has been fixed in current master branch. You can update your Doris to 0.13

**Comment by petermenglei** [comment]
@imay thanks for the update.  Regarding the verison of jdbc driver, any specific version I need to use for 0.13 (I'm using 8.0.15 )? or just the latest version would do

**Comment by zhaojintaozhao** [comment]
> @imay thanks for the update. Regarding the verison of jdbc driver, any specific version I need to use for 0.13 (I'm using 8.0.15 )? or just the latest version would do

Hi, This problem has been resolved in  issue: 4542. It has been merged into the master version of 0.13 
You can see this:  
https://github.com/apache/incubator-doris/pull/4542
