### ISSUE TITLE
物理机环境 源码编译报错

### ISSUE THREAD

**Issue by ningyanhui** [apache/incubator-doris#4892]
Scanning dependencies of target Common
[  1%] Building CXX object src/common/CMakeFiles/Common.dir/daemon.cpp.o
[  1%] Building CXX object src/common/CMakeFiles/Common.dir/status.cpp.o
[  1%] Building CXX object src/common/CMakeFiles/Common.dir/resource_tls.cpp.o
[  2%] Building CXX object src/common/CMakeFiles/Common.dir/logconfig.cpp.o
/root/ningyanhui/incubator-doris-0.13.0-rc03/be/src/common/logconfig.cpp: In function ‘bool doris::init_glog(const char*, bool)’:
/root/ningyanhui/incubator-doris-0.13.0-rc03/be/src/common/logconfig.cpp:73:5: error: ‘FLAGS_log_filenum_quota’ was not declared in this scope
     FLAGS_log_filenum_quota = config::sys_log_roll_num;
     ^~~~~~~~~~~~~~~~~~~~~~~
/root/ningyanhui/incubator-doris-0.13.0-rc03/be/src/common/logconfig.cpp:104:9: error: ‘FLAGS_log_split_method’ was not declared in this scope
         FLAGS_log_split_method = "day";
         ^~~~~~~~~~~~~~~~~~~~~~
/root/ningyanhui/incubator-doris-0.13.0-rc03/be/src/common/logconfig.cpp:107:9: error: ‘FLAGS_log_split_method’ was not declared in this scope
         FLAGS_log_split_method = "hour";
         ^~~~~~~~~~~~~~~~~~~~~~
/root/ningyanhui/incubator-doris-0.13.0-rc03/be/src/common/logconfig.cpp:110:9: error: ‘FLAGS_log_split_method’ was not declared in this scope
         FLAGS_log_split_method = "size";
         ^~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/common/CMakeFiles/Common.dir/logconfig.cpp.o] Error 1
make[1]: *** [src/common/CMakeFiles/Common.dir/all] Error 2
make: *** [all] Error 2

联系方式如下：
宁彦辉 ：中移物联网有限公司智能连接部
邮箱： ningshaochi@163.com
地址：重庆市渝北区杨柳北路8号高新园拓展D区(渝兴广场 V客部落）

未找到可直接使用的已编译包，不知是否能提供已编译完成的安装包以供使用，ThankS

**Comment by HappenLee** [comment]
Hi，you can use Docker to compile Doris eazily, This is the way we strongly recommend. 

If you need a binary of Doris, you can find it in link:https://github.com/baidu-doris/incubator-doris

**Comment by ningyanhui** [comment]
> Hi，you can use Docker to compile Doris eazily, This is the way we strongly recommend.
> 
> If you need a binary of Doris, you can find it in link:https://github.com/baidu-doris/incubator-doris


Sorry,  company does not recommend deploying docker environment

**Comment by HappenLee** [comment]
> Sorry, company does not recommend deploying docker environment

You just compile binary of Doris in Docker, no need deploying docker environment. You can copy the binary of Doris use in any where environment you like.

**Comment by ningyanhui** [comment]
> > Sorry, company does not recommend deploying docker environment
> 
> You just compile binary of Doris in Docker, no need deploying docker environment. You can copy the binary of Doris use in any where environment you like.

ok,Thanks

**Comment by morningman** [comment]
You can find a pre-compiled binary here:
