### ISSUE TITLE
BE启动报错

### ISSUE THREAD

**Issue by ningyanhui** [apache/incubator-doris#4898]
报错日志如下：
I1113 16:22:26.980127 41905 daemon.cpp:232]  version 0.13.9-release RELEASE (build git://43833c6c2351/root/incubator-doris@7b2762b1b12ca971fd74b1abb9b2e
e1489aa4098)
Built on Wed, 21 Oct 2020 08:29:59 UTC by root@43833c6c2351
I1113 16:22:26.984030 41905 mem_info.cpp:82] Physical Memory: 251.36 GB
I1113 16:22:26.985383 41905 daemon.cpp:262] Cpu Info:
  Model: Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
  Cores: 48
  Max Possible Cores: 48
  L1 Cache: 32.00 KB (Line: 64.00 B)
  L2 Cache: 256.00 KB (Line: 64.00 B)
  L3 Cache: 30.00 MB (Line: 64.00 B)
  Hardware Supports:
    ssse3
    sse4_1
    sse4_2
    popcnt
    avx
    avx2
  Numa Nodes: 2
  Numa Nodes of Cores: 0->0 | 1->0 | 2->0 | 3->0 | 4->0 | 5->0 | 6->0 | 7->0 | 8->0 | 9->0 | 10->0 | 11->0 | 12->1 | 13->1 | 14->1 | 15->1 | 16->1 | 17-
>1 | 18->1 | 19->1 | 20->1 | 21->1 | 22->1 | 23->1 | 24->0 | 25->0 | 26->0 | 27->0 | 28->0 | 29->0 | 30->0 | 31->0 | 32->0 | 33->0 | 34->0 | 35->0 | 36-
>1 | 37->1 | 38->1 | 39->1 | 40->1 | 41->1 | 42->1 | 43->1 | 44->1 | 45->1 | 46->1 | 47->1 |
I1113 16:22:26.985431 41905 daemon.cpp:263] Disk Info: 
  Num disks 14: sdm, sdg, sdl, sdc, sdf, sda, sdj, sdk, sdi, sde, sdd, sdb, sdh, dm-
I1113 16:22:26.985437 41905 daemon.cpp:264] Mem Info: 251.36 GB
CGroup Info: Process CGroup Info: memory.limit_in_bytes=9223372036854771712, cpu cfs limits: unlimited
I1113 16:22:26.986955 41905 backend_options.cpp:77] local host ip=192.168.108.193
I1113 16:22:26.987335 41905 storage_engine.cpp:101] starting backend using uid:3446883b5e1115d2-32f6913d9f2f3b8c
I1113 16:22:26.987679 41911 data_dir.cpp:980] path: /opt/DORIS-0.13.9-release/be/storage total capacity: 1175868932096, available capacity: 109238813491
2
I1113 16:22:26.987804 41911 data_dir.cpp:269] path: /opt/DORIS-0.13.9-release/be/storage, hash: 1937097799078370978
I1113 16:22:27.003283 41980 data_dir.cpp:641] start to load tablets from /opt/DORIS-0.13.9-release/be/storage
I1113 16:22:27.003340 41980 data_dir.cpp:634] successfully check incompatible old format meta /opt/DORIS-0.13.9-release/be/storage
I1113 16:22:27.003345 41980 data_dir.cpp:651] begin loading rowset from meta
I1113 16:22:27.003350 41980 data_dir.cpp:670] load rowset from meta finished, data dir: /opt/DORIS-0.13.9-release/be/storage
I1113 16:22:27.003353 41980 data_dir.cpp:675] begin loading tablet from meta
I1113 16:22:27.003358 41980 data_dir.cpp:714] load tablet from meta finished, loaded tablet: 0, error tablet: 0, path: /opt/DORIS-0.13.9-release/be/stor
age
I1113 16:22:27.004256 41905 storage_engine.cpp:105] success to init storage engine.
I1113 16:22:27.005673 42040 fragment_mgr.cpp:514] FragmentMgr cancel worker start working.
W1113 16:22:27.027580 41905 cgroups_mgr.cpp:350] Could not find a valid cgroups path for resource isolation,current value is . ignore it.
I1113 16:22:27.027592 42117 result_buffer_mgr.cpp:147] result buffer manager cancel thread begin.
I1113 16:22:27.027664 41905 load_path_mgr.cpp:54] Load path configured to [/opt/DORIS-0.13.9-release/be/storage/mini_download]
I1113 16:22:27.027858 41905 exec_env_init.cpp:189] Using global memory limit: 201.08 GB
I1113 16:22:27.028545 41905 tmp_file_mgr.cc:116] Using scratch directory /opt/DORIS-0.13.9-release/be/storage/doris-scratch on disk 13
I1113 16:22:27.028631 41905 olap_server.cpp:50] unused rowset monitor thread started
I1113 16:22:27.028667 41905 olap_server.cpp:57] garbage sweeper thread started
I1113 16:22:27.028704 41905 olap_server.cpp:64] disk stat monitor thread started
I1113 16:22:27.029011 41905 olap_server.cpp:87] compaction tasks producer thread started
I1113 16:22:27.029045 42148 olap_server.cpp:320] try to start compaction producer process!
I1113 16:22:27.029065 41905 olap_server.cpp:98] tablet checkpoint thread started
I1113 16:22:27.029081 42149 olap_server.cpp:304] begin to do tablet meta checkpoint:/opt/DORIS-0.13.9-release/be/storage
I1113 16:22:27.029099 41905 olap_server.cpp:105] fd cache clean thread started
I1113 16:22:27.029155 42151 olap_server.cpp:285] try to perform path scan!
I1113 16:22:27.029167 41905 olap_server.cpp:124] path scan/gc threads started. number:1
I1113 16:22:27.029168 42151 data_dir.cpp:895] start to scan data dir path:/opt/DORIS-0.13.9-release/be/storage
I1113 16:22:27.029171 41905 olap_server.cpp:127] all storage engine's background threads are started.
I1113 16:22:27.029181 42153 olap_server.cpp:260] try to start path gc thread!
I1113 16:22:27.029198 42153 olap_server.cpp:263] try to perform path gc by tablet!
I1113 16:22:27.029198 42151 data_dir.cpp:944] scan data dir path:/opt/DORIS-0.13.9-release/be/storage finished. path size:0
I1113 16:22:27.030421 42188 task_worker_pool.cpp:1037] waiting to receive first heartbeat from frontend
I1113 16:22:27.030462 42189 task_worker_pool.cpp:1094] waiting to receive first heartbeat from frontend
I1113 16:22:27.030957 41905 agent_server.cpp:93] Register user resource listener
I1113 16:22:27.031024 41905 backend_service.cpp:92] DorisInternalService listening on 9060
I1113 16:22:27.031373 41905 thrift_server.cpp:353] ThriftServer 'backend' started on port: 9060
W1113 16:22:27.032699 42187 utils.cpp:101] fail to get master client from cache. host=, port=0, code=7
W1113 16:22:27.032717 42187 task_worker_pool.cpp:1015] report task failed. status: -1, master host: port: 0
I1113 16:22:27.038944 41905 server.cpp:1037] Server[doris::PInternalServiceImpl<palo::PInternalService>+doris::PInternalServiceImpl<doris::PBackendServi
ce>] is serving on port=8060.
I1113 16:22:27.038954 41905 server.cpp:1040] Check out http://cdh193.cqwlw.com:8060 in web browser.
F1113 16:22:27.039674 41905 ev_http_server.cpp:95] Check failed: _bind().ok()

**Comment by EmmyMiao87** [comment]
F1113 16:22:27.039674 41905 ev_http_server.cpp:95] Check failed: _bind().ok()

The port used by backend is occupied

**Comment by ningyanhui** [comment]
> F1113 16:22:27.039674 41905 ev_http_server.cpp:95] Check failed: _bind().ok()
> 
> The port used by backend is occupied

lsof -i:port  not  occupied
