### ISSUE TITLE
Doris 0.13 build error

### ISSUE THREAD

**Issue by bingfeng2004** [apache/incubator-doris#4920]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check (validproject fe-common: Execution validate of goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1 failed: Plugin org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0 or one of its dependencies t be resolved: Could not transfer artifact com.ibm.icu:icu4j:jar:63.1 from/to spring-plugins (http.spring.io/plugins-release/): Authentication failed for https://repo.spring.io/plugins-release/com/icu4j/63.1/icu4j-63.1.jar 401 Unauthorized -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following ar
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

**Comment by EmmyMiao87** [comment]
I strongly recommend you to use docker to compile Doris

**Comment by bingfeng2004** [comment]
yes, I am used docker to compile

**Comment by EmmyMiao87** [comment]
Is the remote maven repo set by maven official?

**Comment by bingfeng2004** [comment]
Sorry, Docker refers to maven configuration on the host. The problem is solved after the maven configuration on the host is cancelled, but another problem is encountered, as follows:
[ERROR] Plugin net.sourceforge.czt.dev:cup-maven-plugin:1.6-cdh or one of its dependencies could not be resolved: Could not find artifact net.sourceforge.czt.dev:cup-maven-plugin:jar:1.6-cdh in spring-plugins (https://repo.spring.io/plugins-release/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
![image](https://user-images.githubusercontent.com/26488625/99609999-ebaf9a80-2a4b-11eb-980c-b8d4bca2c762.png)

**Comment by morningman** [comment]
Replace the `fe/pom.xml` file with that file in trunk and rebuild again.

**Comment by bingfeng2004** [comment]
Thank you, it has been compiled successfully.
