### ISSUE TITLE
Optimize the read performance of AGG and UNIQUE table  with too much versions

### ISSUE THREAD

**Issue by yangzhg** [apache/incubator-doris#4957]
When there are many versions of a table, we have a lot of time spent on sorting and merging rowset
In our scenario, this sorting is actually a merge sorting of multiple ordered queues, and usually due to the existence of compaction, we will have a relatively large base rowset and several small rowset, so we can combine The small rowset is sorted first and merged with the large rowset to optimize the read performance

**Comment by HappenLee** [comment]
Nice job，look forward for you pr~~
