### ISSUE TITLE
关于使用单/双引号转义自身的建议

### ISSUE THREAD

**Issue by exialym** [apache/incubator-doris#4974]
Doris 现在只支持使用反斜杠转义单/双引号，如：
`select * from table where col = 'I\'m'`
期望支持使用自身转义单/双引号的方式，如：
`select * from table where col = 'I''m'`

其他数据库现状：
支持自身转义的数据库：MySQL，Oracle，SQL Server，Postgres...
只支持自身转义，不支持反斜杠转义的数据库：Oracle，SQL Server，Postgres...

由于很多数据库只支持自身转义的情况，对接多数据库的系统一般都采用自身转义的方式来处理，Doris 如果也能支持的话，会减小多数据库系统对接 Doris 的成本。

**Comment by Kate605690919** [comment]
诶诶，我们也遇到了这个问题，特别希望能支持下

**Comment by sduzh** [comment]
This can be achieved by adding a simple patch on `fe/fe-core/src/main/jflex/sql_scanner.flex`, I'll create PR later.
