### ISSUE TITLE
Doris master branch compile failed

### ISSUE THREAD

**Issue by caiconghui** [apache/incubator-doris#4980]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project fe-core: Compilation failure: Compilation failure: 
[ERROR] /home/cch/Project/incubator-doris/fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java:[1314,72] cannot find symbol
[ERROR]   symbol:   variable scanRangeLength
[ERROR]   location: class org.apache.doris.qe.Coordinator
[ERROR] /home/cch/Project/incubator-doris/fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java:[1319,63] cannot find symbol
[ERROR]   symbol:   variable scanRangeLength
[ERROR]   location: class org.apache.doris.qe.Coordinator
[ERROR] -> [Help 1]
[ERROR]

**Comment by morningman** [comment]
#4979
