### ISSUE TITLE
Push down predicate on value column of unique table to base rowset

### ISSUE THREAD

**Issue by yangzhg** [apache/incubator-doris#5024]
When reading the base rowset of the unique table, the predicate on the value column can be pushed down to the storage engine for filtering. 
Normally, the base rowset is the largest rowset in the entire table, so it can speed up the query.

**Comment by chaoyli** [comment]
You can see the #3288, it will has bug to push predicate to value of replace column

**Comment by yangzhg** [comment]
this optimize only use on unique table instead of agg table with replace columns

**Comment by chaoyli** [comment]
OK
