### ISSUE TITLE
Doris does not create partition in dynamic partition table

### ISSUE THREAD

**Issue by EmmyMiao87** [apache/incubator-doris#5042]
**Describe the bug**

Doris supports the creation of dynamic partition tables, but the actual partitions have not been created successfully.

**To Reproduce**
1.  admin set frontend config ("dynamic_partition_enable" = "false");
2. create dynamic partition table

```
CREATE TABLE dynamic_partition
    (
    k1 DATE not null,
    k2 INT,
    k3 SMALLINT,
    v1 VARCHAR(2048),
    v2 DATETIME DEFAULT "2014-02-04 15:36:00"
    )
    ENGINE=olap
    DUPLICATE KEY(k1, k2, k3)
    PARTITION BY RANGE (k1)
    (
    PARTITION p1 VALUES LESS THAN ("2014-01-01"),
    PARTITION p2 VALUES LESS THAN ("2014-06-01"),
    PARTITION p3 VALUES LESS THAN ("2014-12-01")
    )
    DISTRIBUTED BY HASH(k2) BUCKETS 32
    PROPERTIES(
    "storage_medium" = "SSD",
    "dynamic_partition.time_unit" = "DAY",
    "dynamic_partition.start" = "-3",
    "dynamic_partition.end" = "3",
    "dynamic_partition.prefix" = "p",
    "dynamic_partition.buckets" = "32",
    "replication_num" = "1"
     );
```

3. waiting for 10 minutes more, partition is not created.

**Expected behavior**

Forbidden creating dynamic partition table when dynamic_partition_enable is false.

**Comment by Qyokizzzz** [comment]
The statement I wrote is as follows:

CREATE TABLE `F_PO_DETAIL` 
(
    ...
    `SK_MONTH` INT NOT NULL COMMENT "订货年月代理键",
    `PRODUCT_NO` VARCHAR(30) NOT NULL COMMENT "产品代码键",
    `PO_TOT_AMT` DECIMAL(27, 5) NULL COMMENT "销售额",
    ...
)
ENGINE=OLAP
DUPLICATE KEY(`DM_ETL_TIME`, `DM_DC_TIME`, `SK_MONTH`)
PARTITION BY RANGE(`SK_MONTH`)()
DISTRIBUTED BY HASH(`SK_MONTH`)
PROPERTIES 
(
    "dynamic_partition.time_unit" = "MONTH",
    "dynamic_partition.prefix" = "p",
    "dynamic_partition.buckets" = "10"
);

But it doesn’t meet my needs. 
I saw the official document but the examples given are all for managing future data.
How to import historical data with dynamic partition？
