### ISSUE TITLE
[Bug] BE Memory Leak In Json Load

### ISSUE THREAD

**Issue by stdpain** [apache/incubator-doris#5069]
**Describe the bug**
BE Memory Leak

**To Reproduce**
1. Create a Table
2. Using JSON load multiple times
3. Memory increased from 400M to 3G in 20 mins
4. when i stop json load, mem will stay at 2G
5. I use tcmalloc heap profile，I found a memory leak at StreamLoadPipe::read_one_message

**Screenshots**
Here is the HEAP_PROFILE
![58EC867964F7159A66F4526DD67C35D1](https://user-images.githubusercontent.com/34912776/101917249-fd2b3300-3c02-11eb-8b3c-fae6eb853279.jpg)

I Found the leak Here and run the profile again
![image](https://user-images.githubusercontent.com/34912776/101917381-23e96980-3c03-11eb-9470-05a3591a0907.png)

![0192AB9EAA3D761A665A402887057E8F](https://user-images.githubusercontent.com/34912776/101917595-64e17e00-3c03-11eb-99e7-066cd562332e.jpg)

So I want to use smart pointers to refactor this code

**Comment by HappenLee** [comment]
@stdpain It's a good time to refactor this part of the code to use unique_ptr avoid the use of the raw pointer.
