### ISSUE TITLE
[BUG] FE CPU 100%

### ISSUE THREAD

**Issue by stdpain** [apache/incubator-doris#5075]
**Describe the bug**
when i use stream load , cpu will increate to 100%

**To Reproduce**
1. start fe
2. start be
3. use stream load
4. cpu will increase to 100%
5. stop fe
6. cpu will recover to normal

**Expected behavior**
cpu should't cost so much cpu

**Screenshots**
![image](https://user-images.githubusercontent.com/34912776/102042907-f8869a80-3e0d-11eb-9985-0d105c338911.png)

**Additional context**
1 FE 1BE

**Comment by caiconghui** [comment]
what's your doris version?

**Comment by stdpain** [comment]
I use jstack, i found it hang here 
![image](https://user-images.githubusercontent.com/34912776/102043171-a8f49e80-3e0e-11eb-80c2-c316fb63632c.png)

**Comment by stdpain** [comment]
@caiconghui master 
I found it was a BUG when no BE avaliable

**Comment by francisoliverlee** [comment]
> @caiconghui master
> I found it was a BUG when no BE avaliable

is there BE alive when CPU 100% ?
