### ISSUE TITLE
Can't access https://doris-incubating-repo.bj.bcebos.com/thirdparty/

### ISSUE THREAD

**Issue by spihiker** [apache/incubator-doris#5080]
When build,I can't access https://doris-incubating-repo.bj.bcebos.com/thirdparty/.

===== Downloading thirdparty archives...
Downloading libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip from https://doris-incubating-repo.bj.bcebos.com/thirdparty/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip to /home/soft/apache-doris-0.13.0-incubating-src/thirdparty/src
--2020-12-15 10:46:12--  https://doris-incubating-repo.bj.bcebos.com/thirdparty/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip
Resolving doris-incubating-repo.bj.bcebos.com (doris-incubating-repo.bj.bcebos.com)... 220.181.33.43, 220.181.33.44, 2409:8c00:6c21:10ad:0:ff:b00e:67d
Connecting to doris-incubating-repo.bj.bcebos.com (doris-incubating-repo.bj.bcebos.com)|220.181.33.43|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-12-15 10:46:12 ERROR 404: Not Found.

**Comment by blueChild** [comment]
Hi, I meet the same problem, and the following issue had fixed this error: https://github.com/apache/incubator-doris/issues/4689

**Comment by spihiker** [comment]
Think you very much. I found a binary package.
