### ISSUE TITLE
【bug】开启routineLoad的merge功能后，自动暂停，报错ReasonOfStateChanged: ErrorReason{code=errCode = 2, msg='failed to create task: errCode = 2, detailMessage = unknown reference column, column=__DORIS_DELETE_SIGN__, reference=del'}

### ISSUE THREAD

**Issue by li-ang-666** [apache/incubator-doris#5094]
在0.12.21版本, 我的建表语句:
CREATE TABLE `dwd_activities` (
  `org_id` varchar(65530) NULL COMMENT "",
  `id` bigint(20) NULL COMMENT "",
  `application_id` bigint(20) NULL COMMENT "",
  `type` bigint(20) NULL COMMENT "",
  `operator_id` bigint(20) NULL COMMENT "",
  `created_at` datetime NULL COMMENT "",
  `data` varchar(65530) NULL COMMENT "",
  `related_res_id` varchar(65530) NULL COMMENT "",
  `visible` smallint(6) NULL COMMENT "",
  `operation` varchar(65530) NULL COMMENT "",
  `updated_at` datetime NULL COMMENT "",
  `operator_name` varchar(65530) NULL COMMENT "",
  `indexed` smallint(6) NULL COMMENT "",
  `candidate_id` bigint(20) NULL COMMENT "",
  `del` tinyint(4) NULL COMMENT ""
) ENGINE=OLAP
UNIQUE KEY(`org_id`, `id`, `application_id`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`application_id`) BUCKETS 20
PROPERTIES (
"replication_num" = "3",
"colocate_with" = "application_id",
"in_memory" = "false",
"storage_format" = "V2"
);
升级到0.13.12版本后，我进行了如下操作:
1、
ALTER TABLE dwd_activities ENABLE FEATURE "BATCH_DELETE";
2、
stop routine load for dwd_activities;
3、
CREATE ROUTINE LOAD `dwd_activities` ON `dwd_activities`
with merge
COLUMNS(`org_id`,`id`,`application_id`,`type`,`operator_id`,`created_at_ffaakkee`,`created_at` = if(locate(' ',`created_at_ffaakkee`) > 0,`created_at_ffaakkee`,from_unixtime(`created_at_ffaakkee` / 1000 - 28800)),`data`,`related_res_id`,`visible`,`operation`,`updated_at_ffaakkee`,`updated_at` = if(locate(' ',`updated_at_ffaakkee`) > 0,`updated_at_ffaakkee`,from_unixtime(`updated_at_ffaakkee` / 1000 - 28800)),`operator_name`,`indexed`,`candidate_id`,`del_ffaakkee`,`del` = if(`del_ffaakkee` = 0 or `del_ffaakkee` is null,0,1)),
delete on del = 1
PROPERTIES
(
  "desired_concurrent_number" = "1",
  "max_batch_interval" = "30",
  "max_error_number" = "100",
  "format" = "json",
  "jsonpaths" = "[\"$.org_id\",\"$.id\",\"$.application_id\",\"$.type\",\"$.operator_id\",\"$.created_at\",\"$.data\",\"$.related_res_id\",\"$.visible\",\"$.operation\",\"$.updated_at\",\"$.operator_name\",\"$.indexed\",\"$.candidate_id\",\"$.del\"]"
)
FROM KAFKA
(
  "kafka_broker_list" = "172.17.89.173:9092,172.17.89.174:9092,172.17.89.175:9092",
  "property.group.id" = "Poseidon_test",
  "kafka_topic" = "Poseidon_test_1",
  "kafka_partitions" = "0",
  "kafka_offsets" = "OFFSET_END"
);

0.13.12版本的routine load建立语句只是多了第二行的“with merge”和第四行的“delete on”
del字段是一直都在表里存在的

**Comment by li-ang-666** [comment]
和dev交流了一下，目前主要有2点：
1、写在DELETE ON中的字段，在COLUMN中不能是衍生列。我的语句中del = XXXXXX，即为衍生列
2、写在DELETE ON中的字段，必须对为null的情况做处理

目前我使用
DELETE ON del_ffaakkee is not null and del_ffaakkee != 0
是可行的

**Comment by yangzhg** [comment]
这个问题的根源和 DELETE ON 条件没有关系，是 doris 在导入的时候不支持目前不支持 v1 , v2 = v1+1, v3 =v2+1  这种对于衍生列的引用表达式，我提了pr 修复了这个问题
