### ISSUE TITLE
[Proposal] Add Histogram Metrics Implementation

### ISSUE THREAD

**Issue by Skysheepwang** [apache/incubator-doris#5146]
Currently, Doris supports three types of metrics, which are Atomic, LockSimple and CoreLocalCounter. All of them are not quite suitable for statistics analysis. 
Histogram metrics is already in used in many DBMS like kudu, rocksdb and so on. It measures the distribution of values in a stream of data and allow you to measure not just easy things like the min, mean, max, and standard deviation of values, but also quantiles like the median or 95th percentile.
As metrics for statistics analysis, the following interface should be supported:
- `add(uint64_t value)`
- `min()`, `max()`, `num()`, `sum()`
- `average()`, `median()`, `percentile(double p)`, `standard_deviation()`

**Comment by xinghuayu007** [comment]
support
