### ISSUE TITLE
build local source code with docker met error "mkdir: cannot create directory 'build': File exists"

### ISSUE THREAD

**Issue by bauerctu** [apache/incubator-doris#517]
**Describe the bug**
===== begin build gflags-2.2.0
mkdir: cannot create directory 'build': File exists
CMake Error: The source directory "/var/local/incubator-doris/thirdparty/src" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

===== begin build brpc-0.9.0
mkdir: cannot create directory 'build': File exists
CMake Error: The source directory "/var/local/incubator-doris/thirdparty/src" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**To Reproduce**
1. Get latest source code 'git clone https://github.com/apache/incubator-doris.git /path/to/incubator-doris/'
2. Start docker and enter container  'docker run -it --name doris-dev-test -v /path/to/incubator-doris/:/var/local/incubator-doris/ doris-dev:v1.0'
3. compile FE and BE  'sh build.sh --fe --be --clean'

**Expected behavior**
build pass.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS 10.12.6
 - Docker: Docker Desktop Community Version 2.0.0.0-mac81(29211)
 - Doris Version: v0.8.2 lastest master branch

**Comment by morningman** [comment]
plz use docker dev env to build from source
