### ISSUE TITLE
[Bug] Function `PERCENTILE_APPROX` return error result. 

### ISSUE THREAD

**Issue by HappenLee** [apache/incubator-doris#5171]
**Describe the bug**
Column Data A: (65536, null, null,null)
Call function `percentile_approx(`A`, 0.5)` should return `65536`, but result is `nan`

**To Reproduce**
1. create table
```
CREATE TABLE `per` (
  `A` bigint(20) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`A`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`A`) BUCKETS 5
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "V2"
);
```

2. Insert data into the table
```
insert into per values(65536)
```

3. set parallel_fragment_exec_instance_num
```
set parallel_fragment_exec_instance_num = 15;
```

4. Do query
```
SELECT PERCENTILE_APPROX(A, 0.5) from per;
+-----------------------------+
| percentile_approx(`A`, 0.5) |
+-----------------------------+
|                   65536                |
+-----------------------------+
```

There is a certain probability

result is

```
SELECT PERCENTILE_APPROX(A, 0.5) from per;
+-----------------------------+
| percentile_approx(`A`, 0.5) |
+-----------------------------+
|                   nan              |
+-----------------------------+
```

**Comment by ICEMAN-CN** [comment]
I encountered the same problem, how did you solve this problem later?

**Comment by HappenLee** [comment]
> I encountered the same problem, how did you solve this problem later?

@ICEMAN-CN This problem already fixed，please look at：https://github.com/apache/incubator-doris/pull/5172
 I will close this issue
