### ISSUE TITLE
Some errors in the document need to be rectified

### ISSUE THREAD

**Issue by blueChild** [apache/incubator-doris#5178]
Hi, all.
I found some mistakes in our document, such as spelling errors、default values error. For example:

1. spelling mistakes:
`docs\zh-CN\sql-reference\sql-statements\Administration\ADMIN SET CONFIG.md`: 可设置的配置项，可以通过 `AMDIN` SHOW FRONTEND CONFIG; 命令查看。 `AMDIN` should be `ADMIN`

2. default value mistakes:
`docs\zh-CN\administrator-guide\operation\tablet-repair-and-balance.md`: disable_balance default value should be false

And so on.

I want to correct these mistakes. I will submit my changes soon.

**Comment by morningman** [comment]
Thanks for your contribution!
