### ISSUE TITLE
cocolate join在查询中带函数的情况下会失效

### ISSUE THREAD

**Issue by hwwxg** [apache/incubator-doris#5184]
同一个表包含聚合函数的查询时，也必须要join，但是却不是cocolate join，总是报"colocate: false, reason: Node type not match"，为什么会这样，能优化吗？
比如下列语句：
select count() from (select user_id from t_event where  event_name = 'AppOpen' group by user_id having count() > 5) t1 where user_id in (select user_id from t_event where  event_name = 'Buy' group by user_id having count() > 3)

**Comment by HappenLee** [comment]
This feature already support in Doris. If you query do not support colocate join, Please check the query and principle of colocate join.

**Comment by hwwxg** [comment]
我发现和是不是同一个表没关系，而是只要条件中带了聚合函数，就会报"colocate: false, reason: Node type not match"，比如
select count() from (select user_id from t_event where event_name = 'AppOpen' group by user_id having count() > 3) t1 where user_id in (select user_id from t_tag where tag_1 ='male') 

如果没带聚合函数，就可以走cocolate join，如
select count() from (select user_id from t_event where event_name = 'AppOpen' ) t1 where user_id in (select user_id from t_tag where tag_1 ='male')

**Comment by HappenLee** [comment]
Yes, It seems not the colocate join problem. It's the problem of `group by` should know the data distribution of colocate table and the normal table. In this case, no need two layer aggregation operation. 

Doris should condiser to do optimization of this case.

**Comment by hwwxg** [comment]
not only 'group by', but also 'distinct' and other functions

**Comment by EmmyMiao87** [comment]
This is indeed a point that can be optimized. 
When the partitioning method of the upper plan node is the same as that of the lower layer, Doris can use colocate.
I can be responsible for this function.

**Comment by EmmyMiao87** [comment]
This pr resolved this problem #5521 @hwwxg
