### ISSUE TITLE
When compiling with build.sh, prompt to download the third-party library 404

### ISSUE THREAD

**Issue by andotorg** [apache/incubator-doris#5217]
**Describe the bug**
When compiling with build.sh, prompt to download the third-party library 404

**To Reproduce**
1. Go to doris
2. sh build
3. ===== Downloading thirdparty archives...
Downloading libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip from https://doris-incubating-repo.bj.bcebos.com/thirdparty/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip to /usr/local/app/doris/thirdparty/src
--2021-01-11 09:32:59--  https://doris-incubating-repo.bj.bcebos.com/thirdparty/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip
Resolving doris-incubating-repo.bj.bcebos.com (doris-incubating-repo.bj.bcebos.com)... 2409:8c00:6c21:10ad:0:ff:b00e:67d, 220.181.33.44, 220.181.33.43
Connecting to doris-incubating-repo.bj.bcebos.com (doris-incubating-repo.bj.bcebos.com)|2409:8c00:6c21:10ad:0:ff:b00e:67d|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-01-11 09:32:59 ERROR 404: Not Found.

**Desktop (please complete the following information):**
 - OS: CentOS
 - Version 7.9.2009

**Comment by blueChild** [comment]
hi, which version doris do you using ? 
Is this same problem: #4689 ?

**Comment by blueChild** [comment]
Maybe you'll have the following problems：
https://github.com/apache/incubator-doris/issues/5126
https://github.com/apache/incubator-doris/issues/4920
good luck

**Comment by morningman** [comment]
We do not recommend compiling third-party libraries by yourself, but use the docker dev image we provide for compilation.
If you insist on compiling a third-party library yourself, you can use `thirdparty/vars.sh` under the trunk code to replace your file and try again.

**Comment by andotorg** [comment]
I just started using the docker image compilation, but there was an error, so I used my own compilation method

**Comment by andotorg** [comment]
> Maybe you'll have the following problems：
> #5126
> #4920
> good luck


It's different from that one. My display is 404, but it can be downloaded by using this link alone

**Comment by andotorg** [comment]
### I compiled using docker mode, and the same error occurred


d01798303745470e6c498bf606e88724a.zip to /var/local/thirdparty/src
--2021-01-11 23:18:42--  https://doris-incubating-repo.bj.bcebos.com/thirdparty/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip
Resolving doris-incubating-repo.bj.bcebos.com (doris-incubating-repo.bj.bcebos.com)... 220.181.33.43, 220.181.33.44, 2409:8c00:6c21:10ad:0:ff:b00e:67d
Connecting to doris-incubating-repo.bj.bcebos.com (doris-incubating-repo.bj.bcebos.com)|220.181.33.43|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-01-11 23:18:42 ERROR 404: Not Found.

Failed to download libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip. attemp: 1
/var/local/thirdparty/src/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip md5sum check failed!
except-md5 e8b9ba50270ba3b520aec8ff1089f9d7 
actual-md5 d41d8cd98f00b204e9800998ecf8427e  /var/local/thirdparty/src/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip
Archive libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip will be removed and download again.
Failed to download libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip
Failed to download libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip

**Comment by blueChild** [comment]
> ### I compiled using docker mode, and the same error occurred
> d01798303745470e6c498bf606e88724a.zip to /var/local/thirdparty/src
> --2021-01-11 23:18:42-- https://doris-incubating-repo.bj.bcebos.com/thirdparty/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip
> Resolving doris-incubating-repo.bj.bcebos.com (doris-incubating-repo.bj.bcebos.com)... 220.181.33.43, 220.181.33.44, 2409:8c00:6c21:10ad:0:ff:b00e:67d
> Connecting to doris-incubating-repo.bj.bcebos.com (doris-incubating-repo.bj.bcebos.com)|220.181.33.43|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2021-01-11 23:18:42 ERROR 404: Not Found.
> 
> Failed to download libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip. attemp: 1
> /var/local/thirdparty/src/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip md5sum check failed!
> except-md5 e8b9ba50270ba3b520aec8ff1089f9d7
> actual-md5 d41d8cd98f00b204e9800998ecf8427e /var/local/thirdparty/src/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip
> Archive libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip will be removed and download again.
> Failed to download libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip
> Failed to download libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip

use https://doris-thirdparty-repo.bj.bcebos.com/thirdparty/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip

**Comment by andotorg** [comment]
this question in docker  solved， thanks for your。
