### ISSUE TITLE
add solr support for doris

### ISSUE THREAD

**Issue by baisui1981** [apache/incubator-doris#5223]
**Is your feature request related to a problem? Please describe.**
by now, doris has introduced Elasticsearch as external data supporting ，https://doris.apache.org/master/zh-CN/extending-doris/doris-on-es.html

that's good, but  when the user using the component of doris-on-es in production environment ,he need to import data by invoking es rest api and maintain consistency with data sources by buid an increasement channel（example：mysql-> canal -> flink -> es）, It's going to be a lot of extra work. It's a lot of trouble

**Describe the solution you'd like**
 i have a  project similarly to  Elasticsearch  , named as  TIS (http://tis.pub/), include  another two abilities which is  fulldata import and increase data synchronizing.

i am going to integrate TIS with Doris, is that ok?

i have read the Doris code which has relevant to  doris-on-es component :

FE:
 https://github.com/apache/incubator-doris/tree/master/fe/fe-core/src/main/java/org/apache/doris/external/elasticsearch/*
BE:
1. ./be/src/exec/es/es_scan_reader.cpp
2. ./be/src/exec/es/es_scroll_query.cpp
3. ./be/src/exec/es_scan_node.cpp
4. .//be/src/exec/exec_node.cpp

if i will make this implemention ,is there any suggesting to me ?

**Describe alternatives you've considered**

**Additional context**

**Comment by EmmyMiao87** [comment]
So far, Doris already supports ES data sources, and there are no plans to support solr for the time being.
Of course, if there are business who really need it, you can also leave us a message under this issue.

**Comment by baisui1981** [comment]
regret
