### ISSUE TITLE
[Doris On ES][Feature] Does Doris support external ES table with `SSL` secured and configurable node sniffing?

### ISSUE THREAD

**Issue by stalary** [apache/incubator-doris#5324]
**Is your feature request related to a problem? Please describe.**
Our ES cluster uses HTTPS, now Doris cannot connect, and sometimes need to connect to the specified node, do not want to enable node scanning.

**Describe the solution you'd like**
Forged SSL Certificates support connections to HTTPS clusters

**Comment by stalary** [comment]
SSL Certificates Do we use real user certificates or fake ones?

**Comment by wuyunfeng** [comment]
fake ones is a quickly ones, maybe we should support `real` SSL with certificate
