### ISSUE TITLE
weekofyear and auto create partition name is different 

### ISSUE THREAD

**Issue by peng-xin** [apache/incubator-doris#5362]
What is the reason for this design?

![image](https://user-images.githubusercontent.com/13350489/106988544-0112a600-67ab-11eb-8702-f8e598aca422.png)

![image](https://user-images.githubusercontent.com/13350489/106988527-f6f0a780-67aa-11eb-8708-c93df61e02f6.png)

**Comment by HappenLee** [comment]
Because 2021-01-03，it is 53th week of 2020.

**Comment by peng-xin** [comment]
but dynamic_partition auto create partition is not 5th(weekofyear is 5th) week at 2021-02-01,it is 2021_06.

**Comment by HappenLee** [comment]
@peng-xin please give me create table code, thanks~

**Comment by peng-xin** [comment]
this is my table create sql:

> CREATE TABLE `f_fact_ad_keyword_test` (
`key` varchar(64),
`business_date` date,
`card_count_time` datetime,
`etl_time` datetime,
`data_deadline_time` datetime,
`hbase_update_time` datetime,
`opportunity_count_time` datetime,
`online_starting_count` int sum,
`effictive_starting_count` int sum,
`opportunity_count` int sum,
`impression_count` int sum,
`chat_count` int sum,
`click_count` int sum,
`card_count` int sum,
`pv_count` int sum,
`registrationnumber` int sum,
`starting_count` int sum,
`account_budget_amount` double sum,
`price_amount` double sum,
`cash_amount` double sum,
`journal_amount` double sum,
`cost_amount` double sum,
`journalaccount` double sum,
`plan_budget_amount` double sum,
`weight_position` double sum
) ENGINE=OLAP
AGGREGATE KEY(`key`,`business_date`,`card_count_time`,`etl_time`,`data_deadline_time`,`hbase_update_time`,`opportunity_count_time`)
COMMENT "OLAP"
PARTITION BY RANGE(`business_date`)
(PARTITION p2019_14 VALUES [('2019-04-01'), ('2019-04-08')),
PARTITION p2019_15 VALUES [('2019-04-08'), ('2019-04-15')),
PARTITION p2019_16 VALUES [('2019-04-15'), ('2019-04-22')),
PARTITION p2019_17 VALUES [('2019-04-22'), ('2019-04-29')),
PARTITION p2019_18 VALUES [('2019-04-29'), ('2019-05-06')),
PARTITION p2019_19 VALUES [('2019-05-06'), ('2019-05-13')),
PARTITION p2019_20 VALUES [('2019-05-13'), ('2019-05-20')),
PARTITION p2019_21 VALUES [('2019-05-20'), ('2019-05-27')),
PARTITION p2019_22 VALUES [('2019-05-27'), ('2019-06-03')),
PARTITION p2019_23 VALUES [('2019-06-03'), ('2019-06-10')),
PARTITION p2019_24 VALUES [('2019-06-10'), ('2019-06-17')),
PARTITION p2019_25 VALUES [('2019-06-17'), ('2019-06-24')),
PARTITION p2019_26 VALUES [('2019-06-24'), ('2019-07-01')),
PARTITION p2019_27 VALUES [('2019-07-01'), ('2019-07-08')),
PARTITION p2019_28 VALUES [('2019-07-08'), ('2019-07-15')),
PARTITION p2019_29 VALUES [('2019-07-15'), ('2019-07-22')),
PARTITION p2019_30 VALUES [('2019-07-22'), ('2019-07-29')),
PARTITION p2019_31 VALUES [('2019-07-29'), ('2019-08-05')),
PARTITION p2019_32 VALUES [('2019-08-05'), ('2019-08-12')),
PARTITION p2019_33 VALUES [('2019-08-12'), ('2019-08-19')),
PARTITION p2019_34 VALUES [('2019-08-19'), ('2019-08-26')),
PARTITION p2019_35 VALUES [('2019-08-26'), ('2019-09-02')),
PARTITION p2019_36 VALUES [('2019-09-02'), ('2019-09-09')),
PARTITION p2019_37 VALUES [('2019-09-09'), ('2019-09-16')),
PARTITION p2019_38 VALUES [('2019-09-16'), ('2019-09-23')),
PARTITION p2019_39 VALUES [('2019-09-23'), ('2019-09-30')),
PARTITION p2019_40 VALUES [('2019-09-30'), ('2019-10-07')),
PARTITION p2019_41 VALUES [('2019-10-07'), ('2019-10-14')),
PARTITION p2019_42 VALUES [('2019-10-14'), ('2019-10-21')),
PARTITION p2019_43 VALUES [('2019-10-21'), ('2019-10-28')),
PARTITION p2019_44 VALUES [('2019-10-28'), ('2019-11-04')),
PARTITION p2019_45 VALUES [('2019-11-04'), ('2019-11-11')),
PARTITION p2019_46 VALUES [('2019-11-11'), ('2019-11-18')),
PARTITION p2019_47 VALUES [('2019-11-18'), ('2019-11-25')),
PARTITION p2019_48 VALUES [('2019-11-25'), ('2019-12-02')),
PARTITION p2019_49 VALUES [('2019-12-02'), ('2019-12-09')),
PARTITION p2019_50 VALUES [('2019-12-09'), ('2019-12-16')),
PARTITION p2019_51 VALUES [('2019-12-16'), ('2019-12-23')),
PARTITION p2019_52 VALUES [('2019-12-23'), ('2019-12-30')),
PARTITION p2020_01 VALUES [('2019-12-30'), ('2020-01-06')),
PARTITION p2020_02 VALUES [('2020-01-06'), ('2020-01-13')),
PARTITION p2020_03 VALUES [('2020-01-13'), ('2020-01-20')),
PARTITION p2020_04 VALUES [('2020-01-20'), ('2020-01-27')),
PARTITION p2020_05 VALUES [('2020-01-27'), ('2020-02-03')),
PARTITION p2020_06 VALUES [('2020-02-03'), ('2020-02-10')),
PARTITION p2020_07 VALUES [('2020-02-10'), ('2020-02-17')),
PARTITION p2020_08 VALUES [('2020-02-17'), ('2020-02-24')),
PARTITION p2020_09 VALUES [('2020-02-24'), ('2020-03-02')),
PARTITION p2020_10 VALUES [('2020-03-02'), ('2020-03-09')),
PARTITION p2020_11 VALUES [('2020-03-09'), ('2020-03-16')),
PARTITION p2020_12 VALUES [('2020-03-16'), ('2020-03-23')),
PARTITION p2020_13 VALUES [('2020-03-23'), ('2020-03-30')),
PARTITION p2020_14 VALUES [('2020-03-30'), ('2020-04-06')),
PARTITION p2020_15 VALUES [('2020-04-06'), ('2020-04-13')),
PARTITION p2020_16 VALUES [('2020-04-13'), ('2020-04-20')),
PARTITION p2020_17 VALUES [('2020-04-20'), ('2020-04-27')),
PARTITION p2020_18 VALUES [('2020-04-27'), ('2020-05-04')),
PARTITION p2020_19 VALUES [('2020-05-04'), ('2020-05-11')),
PARTITION p2020_20 VALUES [('2020-05-11'), ('2020-05-18')),
PARTITION p2020_21 VALUES [('2020-05-18'), ('2020-05-25')),
PARTITION p2020_22 VALUES [('2020-05-25'), ('2020-06-01')),
PARTITION p2020_23 VALUES [('2020-06-01'), ('2020-06-08')),
PARTITION p2020_24 VALUES [('2020-06-08'), ('2020-06-15')),
PARTITION p2020_25 VALUES [('2020-06-15'), ('2020-06-22')),
PARTITION p2020_26 VALUES [('2020-06-22'), ('2020-06-29')),
PARTITION p2020_27 VALUES [('2020-06-29'), ('2020-07-06')),
PARTITION p2020_28 VALUES [('2020-07-06'), ('2020-07-13')),
PARTITION p2020_29 VALUES [('2020-07-13'), ('2020-07-20')),
PARTITION p2020_30 VALUES [('2020-07-20'), ('2020-07-27')),
PARTITION p2020_31 VALUES [('2020-07-27'), ('2020-08-03')),
PARTITION p2020_32 VALUES [('2020-08-03'), ('2020-08-10')),
PARTITION p2020_33 VALUES [('2020-08-10'), ('2020-08-17')),
PARTITION p2020_34 VALUES [('2020-08-17'), ('2020-08-24')),
PARTITION p2020_35 VALUES [('2020-08-24'), ('2020-08-31')),
PARTITION p2020_36 VALUES [('2020-08-31'), ('2020-09-07')),
PARTITION p2020_37 VALUES [('2020-09-07'), ('2020-09-14')),
PARTITION p2020_38 VALUES [('2020-09-14'), ('2020-09-21')),
PARTITION p2020_39 VALUES [('2020-09-21'), ('2020-09-28')),
PARTITION p2020_40 VALUES [('2020-09-28'), ('2020-10-05')),
PARTITION p2020_41 VALUES [('2020-10-05'), ('2020-10-12')),
PARTITION p2020_42 VALUES [('2020-10-12'), ('2020-10-19')),
PARTITION p2020_43 VALUES [('2020-10-19'), ('2020-10-26')),
PARTITION p2020_44 VALUES [('2020-10-26'), ('2020-11-02')),
PARTITION p2020_45 VALUES [('2020-11-02'), ('2020-11-09')),
PARTITION p2020_46 VALUES [('2020-11-09'), ('2020-11-16')),
PARTITION p2020_47 VALUES [('2020-11-16'), ('2020-11-23')),
PARTITION p2020_48 VALUES [('2020-11-23'), ('2020-11-30')),
PARTITION p2020_49 VALUES [('2020-11-30'), ('2020-12-07')),
PARTITION p2020_50 VALUES [('2020-12-07'), ('2020-12-14')),
PARTITION p2020_51 VALUES [('2020-12-14'), ('2020-12-21')),
PARTITION p2020_52 VALUES [('2020-12-21'), ('2020-12-28')),
PARTITION p2020_53 VALUES [('2020-12-28'), ('2021-01-04')),
PARTITION p2021_01 VALUES [('2021-01-04'), ('2021-01-11')),
PARTITION p2021_02 VALUES [('2021-01-11'), ('2021-01-18')),
PARTITION p2021_03 VALUES [('2021-01-18'), ('2021-01-25')),
PARTITION p2021_04 VALUES [('2021-01-25'), ('2021-02-01')),
PARTITION p2021_05 VALUES [('2021-02-01'), ('2021-02-08'))
)
DISTRIBUTED BY HASH(`key`) BUCKETS 10
PROPERTIES (
"replication_num" = "1",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "week",
"dynamic_partition.end" = "2",
"dynamic_partition.prefix" = "p",
"dynamic_partition.replication_num" = "1",
"dynamic_partition.buckets" = "3",
"dynamic_partition.start_day_of_week" = "1",
"in_memory" = "false",
"storage_format" = "V2"
);

when i excute the insert stmt `insert into f_fact_ad_keyword_test(`key`,`business_date`,`online_starting_count`) values('2','2021-02-09','1');`,this table will auto create 2 new partition.but the new partition week of year is not the function weekofyear‘s value.

![image](https://user-images.githubusercontent.com/13350489/107136046-eff89f00-693a-11eb-8cd2-66390351d21f.png)

**Comment by HappenLee** [comment]
I found this problem. Will try to fix it, Thank you~ @peng-xin

**Comment by peng-xin** [comment]
> I found this problem. Will try to fix it, Thank you~ @peng-xin

fine，thanks
