### ISSUE TITLE
Lots of issues with page links

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-doris#5405]
Page links don't appear to be working.

For example the following page:
http://doris.apache.org/master/en/community/how-to-contribute.html
contains the text:

Your suggestions, comments and comments on Doris can be made directly through GitHub's [Issues] (https://github.com/apache/incubator-doris/issues/new/selection).

I assume the entry in () is supposed to be a link, but it is not displayed as such.

As it happens the link is mis-spelt anyway, it should be:
https://github.com/apache/incubator-doris/issues/new/choose

**Comment by morningman** [comment]
Thanks for your reporting. We will fix it.
