### ISSUE TITLE
挂一台BE之后使用Spark的读取Doris的分区表到dataframe会报错，在客户端用sql查询不会有问题

### ISSUE THREAD

**Issue by demon-gu** [apache/incubator-doris#5420]
挂一台BE之后使用Spark的读取Doris的分区表到dataframe会报错，在客户端用sql查询不会有问题

**Comment by wuyunfeng** [comment]
This should be caused by the failure of Doris DataSource to deal with the problematic tablet, and an error was reported when requesting the BE that crash.

**Comment by demon-gu** [comment]
> This should be caused by the failure of Doris DataSource to deal with the problematic tablet, and an error was reported when requesting the BE that crash.

How to solve this problem？

**Comment by wuyunfeng** [comment]
Can't solve it temporarily,  you can start the dead BE first

**Comment by demon-gu** [comment]
> Can't solve it temporarily, you can start the dead BE first. We need to think about how to better solve

OK~Thanks！

**Comment by wuyunfeng** [comment]
@demon-gu  I would resolve this problem soon.
