### ISSUE TITLE
docker build-env-1.2:fe-core 3.4.0 failure

### ISSUE THREAD

**Issue by Feral-Jas** [apache/incubator-doris#5435]
**Describe the bug**
`Plugin net.sourceforge.czt.dev:cup-maven-plugin:1.6-cdh or one of its dependencies could not be resolved: Failed to read artifact descriptor for net.sourceforge.czt.dev:cup-maven-plugin:jar:1.6-cdh: Could not transfer artifact net.sourceforge.czt.dev:cup-maven-plugin:pom:1.6-cdh from/to spring-plugins (https://repo.spring.io/plugins-release/): Authentication failed for https://repo.spring.io/plugins-release/net/sourceforge/czt/dev/cup-maven-plugin/1.6-cdh/cup-maven-plugin-1.6-cdh.pom 401 Unauthorized -> [Help 1]`

**To Reproduce**
1. sh build.sh
2. fe-core 3.4.0 failure

**Expected behavior**
build sucess

**Screenshots**
![image](https://user-images.githubusercontent.com/58321077/109477961-9e63b000-7ab3-11eb-8a4a-3c286c53cb7f.png)

**Desktop (please complete the following information):**
 - OS: [ubuntu-kylin]

**Comment by zhangboya1** [comment]
需要把fe/pom.xml中下载的Repository地址改下
<id>cloudera-thirdparty</id>
<url>https://repository.cloudera.com/content/repositories/third-party/</url>
改为：
<id>cloudera-public</id>
<url>https://repository.cloudera.com/artifactory/public/</url>

<id>cloudera-plugins</id>
<url>https://repository.cloudera.com/content/groups/public/</url>
改为：
<id>cloudera-public</id>
<url>https://repository.cloudera.com/artifactory/public/</url>

**Comment by Feral-Jas** [comment]
> 需要把fe/pom.xml中下载的Repository地址改下
> cloudera-thirdparty
> https://repository.cloudera.com/content/repositories/third-party/
> 改为：
> cloudera-public
> https://repository.cloudera.com/artifactory/public/
> 
> cloudera-plugins
> https://repository.cloudera.com/content/groups/public/
> 改为：
> cloudera-public
> https://repository.cloudera.com/artifactory/public/

thx. Now fixed.

**Comment by insanebeast** [comment]
> 需要把fe/pom.xml中下载的Repository地址改下
> cloudera-thirdparty
> https://repository.cloudera.com/content/repositories/third-party/
> 改为：
> cloudera-public
> https://repository.cloudera.com/artifactory/public/
> 
> cloudera-plugins
> https://repository.cloudera.com/content/groups/public/
> 改为：
> cloudera-public
> https://repository.cloudera.com/artifactory/public/

thanks! it helps~

**Comment by eleven-1105** [comment]
> > 需要把fe/pom.xml中下载的Repository地址改下 cloudera-thirdparty https://repository.cloudera.com/content/repositories/third-party/ 改为： cloudera-public https://repository.cloudera.com/artifactory/public/
> > cloudera-plugins https://repository.cloudera.com/content/groups/public/ 改为： cloudera-public https://repository.cloudera.com/artifactory/public/
> 
> 谢谢！有帮助~
Still encountering an error
