### ISSUE TITLE
undefined reference to `malloc_stats_print'

### ISSUE THREAD

**Issue by carlziess** [apache/incubator-doris#5437]
OS：Ubuntu 18.04 LTS Server
Doris Version: 0.13
Error Info:
incubator-doris/thirdparty/src/rocksdb-5.14.2/db/malloc_stats.cc:51: undefined reference to `malloc_stats_print'

I just need compile Doris in real OS by source code, I have tried to download all the third parties and compile has done, but the final step has failure when "WITH_MYSQL=1 bash build.sh" directive was executed. I have been checking the third parts' version and reading the manual again, May I have something wrong with the procedures, Could you give me some help please? Our system does not permit Docker.

**Comment by caiconghui** [comment]
@carlziess I build doris in ubuntu 14.04, and fix some build problem, may PR #5439 can help you.

**Comment by carlziess** [comment]
@caiconghui It's failure again, it's a similar error. But thanks a lot, I will read the source code and try to fix it.

**Comment by caiconghui** [comment]
> @caiconghui It's failure again, it's a similar error. But thanks a lot, I will read the source code and try to fix it.

or you can add my wechat caiconghui001. I doubt it is still environment problem

**Comment by caiconghui** [comment]
PR #5439 fix some downloading and buliding problems for thirdparty, and succeed in building doris be on ubuntu14.04 and ubuntu18.04
