### ISSUE TITLE
Doris元数据管理和BE的问题请教

### ISSUE THREAD

**Issue by androidMake** [apache/incubator-doris#5461]
请问Doris的元数据如何读取，我看文档上说的默认的库是为了和mysql兼容，数据不及时，那元数据该从什么地方读呢？我这边要做一个元数据管理的东西出来，还有就是每次我启动BE的时候都能启动，就是show backends的时候显示磁盘为0.0B，这个是怎么回事啊？感谢您的不吝赐教！

**Comment by morningman** [comment]
1. Meta data is saving in memory. We built plenty of statements and commands to get the meta data such as tables/columns/backends.

2. You can execute "set forward_to_master=true" than execute "show backends" to see the disk capacity.

**Comment by androidMake** [comment]
1、感谢您的回答，其实我是想知道获取元数据的命令有哪些，因为我在官方操作文档中并没有找到，
2、好的，我试一下这个命令！多谢

**Comment by morningman** [comment]
Which type of meta data do you want to get?

**Comment by androidMake** [comment]
例如所有的数据库名，表名、列名，因为要做类似于atlas那样的元数据管理，所以获取的越全面越好

**Comment by morningman** [comment]
You can find most of them in infomation_schema db, just like MySQL.
But some details may not be found in that database.

You need find them here `http://doris.incubator.apache.org/master/zh-CN/sql-reference/sql-statements/Account%20Management/SHOW%20ROLES.html`
Try some `SHOW XXX` statement.

**Comment by androidMake** [comment]
好的，多谢啦

**Comment by androidMake** [comment]
不好意思还得打扰一下，就是FE和BE同时部署在一个节点上是不是有问题呀？要改些什么配置呢？
