### ISSUE TITLE
Add a colocate join meta repair tool

### ISSUE THREAD

**Issue by kangkaisen** [apache/incubator-doris#549]
refer to https://github.com/apache/incubator-doris/issues/546  If our code has bug, the colocate meta maybe wrong. So we should add more Test and a repair tool.

The repair tool should have these abilities：
1 get all colocate meta
2 update each colocate meta, for example：group2BackendsPerBucketSeq， balancingGroups，group2DBs， table2Groups， group2Tables.

Yesterday I have created a tmp Http API repair tool and repaired our colocate meta.

I want to discuss what a repair tool format should we use: HTTP? SQL? CommandLine?

Any comments are welcome.

**Comment by imay** [comment]
I think HTTP or SQL is OK. CommandLine need admin to login in the host where service locates on, so it's not convenient.

For HTTP and SQL, I prefer HTTP because following reasons.

1. HTTP is more flexible. Admin can pass data through Headers, URL or request body.
2. No need to design command syntax and to change Sql Parser
3. It's more easier to find a HTTP client.

**Comment by morningman** [comment]
There is a serious problem that if the metadata has error, the Frontend instance may not even able to start, so that both HTTP or SQL way is useless...

In your case, you may be able to start the FE and fix the bug using some tools. So it is OK to develop a specified tool to fit your situation. But for a common 'metadata fix tools', we should consider more.

And also, we currently don't have a framework to redirect the request from non-master FE to Master FE(which SQL has), so you need to send the request directly to the Master FE, which may not be able to do so in some environment, such as visiting a proxy with 3 Frontends under it. You need also think about it.

**Comment by morningman** [comment]
By the way, this issue #540 you may need to know. And we decided to unify the tablet balance operation in this new framework.
Currently, I add a FE config `use_new_tablet_scheduler`(default is false), so that every is expecting to go as the old way (using CloneChecker).
And if set `use_new_tablet_scheduler` to true, you must also set `disable_colocate_join` to true, cause  the new TabletChecker will not handle the colocation table's tablets.

**Comment by kangkaisen** [comment]
@morningman  

 >There is a serious problem that if the metadata has error, the Frontend instance may not even able to start, so that both HTTP or SQL way is useless...

Yes.  I agree with you. So this tool only handle colocate meta, not all Doris meta.  If the colocate meta is broken, the Fe could run normally.


>And also, we currently don't have a framework to redirect the request from non-master FE to Master FE(which SQL has), so you need to send the request directly to the Master FE, which may not be able to do so in some environment, such as visiting a proxy with 3 Frontends under it. You need also think about it.

This tool is for Doris Admin. So I think a Doris Admin should know which FE is master.

**Comment by kangkaisen** [comment]
> By the way, this issue #540 you may need to know. And we decided to unify the tablet balance operation in this new framework.
> Currently, I add a FE config `use_new_tablet_scheduler`(default is false), so that every is expecting to go as the old way (using CloneChecker).
> And if set `use_new_tablet_scheduler` to true, you must also set `disable_colocate_join` to true, cause the new TabletChecker will not handle the colocation table's tablets.

OK, I see.

**Comment by imay** [comment]
> @morningman
> 
> > There is a serious problem that if the metadata has error, the Frontend instance may not even able to start, so that both HTTP or SQL way is useless...
> 
> Yes. I agree with you. So this tool only handle colocate meta, not all Doris meta. If the colocate meta is broken, the Fe could run normally.
> 
> > And also, we currently don't have a framework to redirect the request from non-master FE to Master FE(which SQL has), so you need to send the request directly to the Master FE, which may not be able to do so in some environment, such as visiting a proxy with 3 Frontends under it. You need also think about it.
> 
> This tool is for Doris Admin. So I think a Doris Admin should know which FE is master.

Doris can redirect HTTP request to master, you can refer to "http/rest/MultiStart.java", call `redirectToMaster` can redirect request to the master.

**Comment by morningman** [comment]
> Doris can redirect HTTP request to master, you can refer to "http/rest/MultiStart.java", call `redirectToMaster` can redirect request to the master.

My bad, there is a redirect method of HTTP

**Comment by kangkaisen** [comment]
last Friday, After I have developed the initial version and tested the FE Http API. **I found there were some `100-continue` http header issues**.

Because the  backendsPerBucketSeq meta maybe large, I wanted to extract the backendsPerBucketSeq meta by Http post body, not parameter. So I used `HttpObjectAggregator` and get http body by `FullHttpRequest`, All Api for Colocate Join Meta worked well, but `HttpObjectAggregator`  is conflicting with `LoadAction`. `HttpObjectAggregator`  will handle `100-continue` header and remove it, which isn't we expected.

So I customized a `DorisHttpObjectAggregator` by copying the `HttpObjectAggregator` and removing 
`100-continue` header handle logic. then, the Java HTTP client could request `LoadAction` successfully.  but the curl client request `LoadAction`  still get a error:

```
* Empty reply from server
* Connection #0 to host xxx left intact
curl: (52) Empty reply from server
```
After I debugged, I found which should be the java Http client and curl client have different response logic for Netty Server.

I'm not familiar with Netty. I think there are at least three ways to resolve this `100-continue` http header issue:

1. extract the backendsPerBucketSeq meta by Http parameter, not http body.
2. directly parse `HttpRequest`, `HttpContent`, `LastHttpContent`, not use `HttpObjectAggregator`
3. customize `HttpObjectAggregator`, and dive into why curl client get the error.

Currently,  I prefer the first way, although which isn't canonical，which is simple.

@imay  @morningman What do you think of it?

**Comment by imay** [comment]
@kangkaisen 
Could you provide more details when executing `LoadAction` with curl.
You can use `curl -v` to print more information. 

And did you use `curl` client with `--location-trusted` option?

**Comment by kangkaisen** [comment]
Yes. I used `curl -v` and added ` --location-trusted` option.

```
[#2#kangkaisen@kks ~ 11:00:22]$seq 1 10 | awk '{OFS="\t"}{print $1, $1 * 10}' | curl -v  --location-trusted -u root:xxx -T - http://xh-data-palo-query-dev01.gh.sankuai.com:8410/api/test/stream1/_stream_load
*   Trying 10.76.45.16...
* TCP_NODELAY set
* Connected to xh-data-palo-query-dev01.gh.sankuai.com (10.76.45.16) port 8410 (#0)
* Server auth using Basic with user 'root'
> PUT /api/test/stream1/_stream_load HTTP/1.1
> Host: xh-data-palo-query-dev01.gh.sankuai.com:8410
> Authorization: Basic xxxx
> User-Agent: curl/7.54.0
> Accept: */*
> Transfer-Encoding: chunked
> Expect: 100-continue
>
* Empty reply from server
* Connection #0 to host xh-data-palo-query-dev01.gh.sankuai.com left intact
curl: (52) Empty reply from server
```

**Comment by imay** [comment]
> Yes. I used `curl -v` and added ` --location-trusted` option.
> 
> ```
> [#2#kangkaisen@kks ~ 11:00:22]$seq 1 10 | awk '{OFS="\t"}{print $1, $1 * 10}' | curl -v  --location-trusted -u root:xxx -T - http://xh-data-palo-query-dev01.gh.sankuai.com:8410/api/test/stream1/_stream_load
> *   Trying 10.76.45.16...
> * TCP_NODELAY set
> * Connected to xh-data-palo-query-dev01.gh.sankuai.com (10.76.45.16) port 8410 (#0)
> * Server auth using Basic with user 'root'
> > PUT /api/test/stream1/_stream_load HTTP/1.1
> > Host: xh-data-palo-query-dev01.gh.sankuai.com:8410
> > Authorization: Basic xxxx
> > User-Agent: curl/7.54.0
> > Accept: */*
> > Transfer-Encoding: chunked
> > Expect: 100-continue
> >
> * Empty reply from server
> * Connection #0 to host xh-data-palo-query-dev01.gh.sankuai.com left intact
> curl: (52) Empty reply from server
> ```

It seems that client was waiting for server's reply, however server reply nothing.
I'm not very familiar with `HttpObjectAggregator` and how you use it.
And it's strange that adding a new API causes `StreamLoad` failed, you can debug more to see what happen in `StreamLoad` handler

**Comment by kangkaisen** [comment]
for java Http client 
```
        Request request = asyncHttpClient.preparePut(url).setBody(content)
                .setHeader("Expect", "100-continue")
                .setHeader("Authorization", basicAuthHeader())
                .setFollowRedirect(true)
                .build();

        Response response =  asyncHttpClient.executeRequest(request).get();
```
the code will run into `MessageAggregator`. `decode`:
```
            // Merge the received chunk into the content of the current message.
            CompositeByteBuf content = (CompositeByteBuf) currentMessage.content();
```
which is normal.

but for curl client,  the code will not  run into above line and will finally run into `ByteToMessageDecoder`
```
    /**
     * Called when the input of the channel was closed which may be because it changed to inactive or because of
     * {@link ChannelInputShutdownEvent}.
     */
    void channelInputClosed(ChannelHandlerContext ctx, List<Object> out) throws Exception {
        if (cumulation != null) {
            callDecode(ctx, cumulation, out);
            decodeLast(ctx, cumulation, out);
        } else {
            decodeLast(ctx, Unpooled.EMPTY_BUFFER, out);
        }
    }
```
so the curl client will get a error.

**Comment by imay** [comment]
@kangkaisen 

I found that curl's request has HTTP header "Transfer-Encoding: chunked". Maybe this encoding type caused the different results?

After see your PR, I prefer option 2. The reasons is followings
1. I'm not sure that it's ok to put this channel to all request
2. writing a custom class isn't a good way.

**Comment by kangkaisen** [comment]
@imay  I added header "Transfer-Encoding: chunked" to java http client, which still work well. After I debugged, I think either the Netty HttpObjectAggregator or curl has a bug.

OK, I will try the second way.

**Comment by imay** [comment]
> @imay I added header "Transfer-Encoding: chunked" to java http client, which still work well. After I debugged, I think either the Netty HttpObjectAggregator or curl has a bug.
> 
> OK, I will try the second way.

When there is a "Transfer-Encoding: chunked"  in HTTP header, there is often no "Content-Length"  header. So your adding "Transfer-Encoding: chunked" maybe has no effect.

You can echo your test to a temporary file, and then use curl to upload it, instead of using command pipeline. Then, curl client is supposed to send "Content-Length" other than "Transfer-Encoding: chunked".

**Comment by kangkaisen** [comment]
After read Netty source code and debugged, I have found out the reason for all issues. I will do a full test, update the PR and explain all the issues.

**Comment by kangkaisen** [comment]
The reason for  curl failed is `HttpServerHandler.channelReadComplete` close the connect early.  we shouldn't close ctx even if the action is null when we want to get the http body.

Besides，we shouldn't handle the request having chunked transfer-encoding header. because the `HttpObjectAggregator` will remove  chunked transfer-encoding header and add content-length header. 

In a word,  because  the FE is a proxy for BE for some API, so we shouldn't handle **chunked transfer-encoding header** and  **100-continue header**.

So, we only need to extend `HttpObjectAggregator` and don't handle 100-continue and chunked transfer-encoding http header. which is reasonable and simple.

**Comment by imay** [comment]
> The reason for curl failed is `HttpServerHandler.channelReadComplete` close the connect early. we shouldn't close ctx even if the action is null when we want to get the http body.

Why we can't close ctx if action is null? I think when action is null, we have no handler to handle this request?

**Comment by kangkaisen** [comment]
Refer to the java doc and debug, the `HttpServerHandler.channelReadComplete` will be called many times.When the first time call for `MessageAggregator.decode`, the msg is HttpMessage, the CodecOutputList size will be zero, the `HttpServerHandler.channelReadComplete` will be called, the action will be null, so we shouldn't close the ctx. 
```
     * Invoked when the last message read by the current read operation has been consumed by
     * {@link #channelRead(ChannelHandlerContext, Object)}. 
```

**Comment by lingbin** [comment]
> Refer to the java doc and debug, the `HttpServerHandler.channelReadComplete` will be called many times.When the first time call for `MessageAggregator.decode`, the msg is HttpMessage, the CodecOutputList size will be zero, the `HttpServerHandler.channelReadComplete` will be called, the action will be null, so we shouldn't close the ctx.
> 
> ```
>      * Invoked when the last message read by the current read operation has been consumed by
>      * {@link #channelRead(ChannelHandlerContext, Object)}. 
> ```

Before there is a problem, that is, when using chrome browser access FE, if get the `favicon.ico` request failed, chrome will retry again and again (should be up to 6 times), if the end has been obtained, then the chrome stuck occasionally happen, may be because the chrome think this url is inaccessible. Would you like to try and see if this is still a problem in the new version of chrome?

**Comment by imay** [comment]
@kangkaisen I think returning 404 is OK if it can stop Chrome sending request

**Comment by kangkaisen** [comment]
Yes. Returning 404 could work.
