### ISSUE TITLE
The log message is wrong when ReportHandler can not find tablet meta from TabletInvertedIndex

### ISSUE THREAD

**Issue by caiconghui** [apache/incubator-doris#5496]
ReportHandler need to delete tablet from backend when  it cannot find related info from foundTabletsWithValidSchema, but when   ReportHandler can not find tablet meta from TabletInvertedIndex,
we will see the following log message:
***
[ReportHandler.deleteFromBackend():677] failed add to meta. tablet[19029], backend[13004]. errCode = 2, detailMessage = db[-1] does not exist
***
It make us confused, the real reason is that tablet meta does not exist in tablet inverted index but not that db does not exist

**Comment by qidaye** [comment]
I encountered this problem too, the error message should be more clear.
The only way to know the real reason for this is when you read the code.

```java
    TabletMeta tabletMeta = invertedIndex.getTabletMeta(tabletId);
    long dbId = tabletMeta != null ? tabletMeta.getDbId() : TabletInvertedIndex.NOT_EXIST_VALUE;
    ...

    Database db = Catalog.getCurrentCatalog().getDb(dbId);
    if (db == null) {
        throw new MetaNotFoundException("db[" + dbId + "] does not exist");
    }
```
