### ISSUE TITLE
Meaningless saving tablet_meta leads to too many sync

### ISSUE THREAD

**Issue by chaoyli** [apache/incubator-doris#555]
Storage Engine will garbage collect expired incremental delta at interval.
It will save tablet_meta after deleting increment deltas from header.
Now, Storage Engine always call save_header function even if there are no incremental deltas in tablet meta.
If there are millions of tablet in a be node, Storage Engine will write RocksDB too many times when GC.

**Comment by morningman** [comment]
This is already fixed
