### ISSUE TITLE
In some cases, be will do the useless cumulative compaction after restart

### ISSUE THREAD

**Issue by weihongkai2008** [apache/incubator-doris#5556]
When doris rewrites the t-1 day data every day, many tablete versions become [0-1],[2-2]. And these data will not be changed in the future. Under the current cumulative compaction logic, after doris be restarts, it will re-execute the compaction of the rowset of version [2-2]. At the same time, the number of such tablets is very large, resulting in a long query delay after be restarted. long. These compactions are not necessary because they have been done before the restart of dorie be.

**Comment by HappenLee** [comment]
I have found same problem and will try to find why doris do the behavior like this.
