### ISSUE TITLE
1、mysql开启binlog，写入kafka消息队列。但是doris 无法解析binlog的数据，有什么好的办法做mysql实时同步到doris吗？

### ISSUE THREAD

**Issue by pigdance** [apache/incubator-doris#5557]
Reason: actual column number is less than schema column number. actual number: 1 sep: 	, schema number: 4; . src line: [{"data":[{"id":"26","name":"222","status":"22","date":"0000-00-00"}],"database":"test","es":1616467578000,"id":7,"isDdl":false,"mysqlType":{"id":"bigint(20)","name":"varchar(45)","status":"varchar(45)","date":"date"},"old":null,"pkNames":["id"],"sql":"","sqlType":{"id":-5,"name":12,"status":12,"date":91},"table":"canal_test","ts":1616467578825,"type":"INSERT"}];

**Comment by hxianshun** [comment]
> Reason: actual column number is less than schema column number. actual number: 1 sep: , schema number: 4; . src line: [{"data":[{"id":"26","name":"222","status":"22","date":"0000-00-00"}],"database":"test","es":1616467578000,"id":7,"isDdl":false,"mysqlType":{"id":"bigint(20)","name":"varchar(45)","status":"varchar(45)","date":"date"},"old":null,"pkNames":["id"],"sql":"","sqlType":{"id":-5,"name":12,"status":12,"date":91},"table":"canal_test","ts":1616467578825,"type":"INSERT"}];

u can use flink to preprocess your json data, and write into a new topic, then use Routine load to consume data.

你可以用flink预处理下json数据，处理成doris认识的数据格式，然后写进一个新topic，再使用doris的Routine load导入

**Comment by hf200012** [comment]
> > Reason: actual column number is less than schema column number. actual number: 1 sep: , schema number: 4; . src line: [{"data":[{"id":"26","name":"222","status":"22","date":"0000-00-00"}],"database":"test","es":1616467578000,"id":7,"isDdl":false,"mysqlType":{"id":"bigint(20)","name":"varchar(45)","status":"varchar(45)","date":"date"},"old":null,"pkNames":["id"],"sql":"","sqlType":{"id":-5,"name":12,"status":12,"date":91},"table":"canal_test","ts":1616467578825,"type":"INSERT"}];
> 
> u can use flink to preprocess your json data, and write into a new topic, then use Routine load to consume data.
> 
> 你可以用flink预处理下json数据，处理成doris认识的数据格式，然后写进一个新topic，再使用doris的Routine load导入

After flink processing, directly use stream load to table

**Comment by pigdance** [comment]
写了个消费kafka的sink，然后批量insert 到doris里。

**Comment by 812406210** [comment]
> 写了个消费kafka的sink，然后批量insert 到doris里。
你好，请问routine为啥消费kafka到doris没有数据呢，感觉是没有消费到一样
