### ISSUE TITLE
Doris 什么时候支持Flink导入导出？

### ISSUE THREAD

**Issue by yangmingjie2018** [apache/incubator-doris#5573]
我知道，Flink可将计算完成的结果写入到Kafka，然后，Doris通过Routine load 方式导入（不知道延迟多少）？  
但是，还有个导出的问题：
在Doris中的数据，我希望能导出到kafka中；是否有办法？

**Comment by morningman** [comment]
You can watch this #5375

**Comment by yangmingjie2018** [comment]
> You can watch this #5375

thanks

I want to know, who I use it?

**Comment by morningman** [comment]
> > You can watch this #5375
> 
> thanks
> 
> I want to know, who I use it?

Sorry, I can't understand..

**Comment by yangmingjie2018** [comment]
> > > You can watch this #5375
> > 
> > 
> > thanks
> > I want to know, who I use it?
> 
> Sorry, I can't understand..

我想确认，现在doris已经支持flink的 读和写了吗？
另外，我需要在flink还是doris怎么操作（例如，引入jar包？）能使用该功能？

谢谢

**Comment by morningman** [comment]
> > > > You can watch this #5375
> > > 
> > > 
> > > thanks
> > > I want to know, who I use it?
> > 
> > 
> > Sorry, I can't understand..
> 
> 我想确认，现在doris已经支持flink的 读和写了吗？
> 另外，我需要在flink还是doris怎么操作（例如，引入jar包？）能使用该功能？
> 
> 谢谢

This PR is under development. Once it finished, you can use flink to read data from or write data inot Doris.
And there will be a document to explain how to use.
Coming soon.

**Comment by yangmingjie2018** [comment]
> > > > > You can watch this #5375
> > > > 
> > > > 
> > > > thanks
> > > > I want to know, who I use it?
> > > 
> > > 
> > > Sorry, I can't understand..
> > 
> > 
> > 我想确认，现在doris已经支持flink的 读和写了吗？
> > 另外，我需要在flink还是doris怎么操作（例如，引入jar包？）能使用该功能？
> > 谢谢
> 
> This PR is under development. Once it finished, you can use flink to read data from or write data inot Doris.
> And there will be a document to explain how to use.
> Coming soon.

多谢大神，希望早日看到 。

**Comment by hf200012** [comment]
> > > > > > You can watch this #5375
> > > > > 
> > > > > 
> > > > > thanks
> > > > > I want to know, who I use it?
> > > > 
> > > > 
> > > > Sorry, I can't understand..
> > > 
> > > 
> > > 我想确认，现在doris已经支持flink的 读和写了吗？
> > > 另外，我需要在flink还是doris怎么操作（例如，引入jar包？）能使用该功能？
> > > 谢谢
> > 
> > 
> > This PR is under development. Once it finished, you can use flink to read data from or write data inot Doris.
> > And there will be a document to explain how to use.
> > Coming soon.
> 
> 多谢大神，希望早日看到 。

You can try it now，from: https://github.com/JNSimba/incubator-doris/tree/flink-connector-doris

**Comment by hf200012** [comment]
You can consume Kafka data through flink, and then store it in the library through stream load
You can also try the flink doris connector, which is not currently in the development and testing phase
https://github.com/JNSimba/incubator-doris/tree/flink-connector-doris

**Comment by yangmingjie2018** [comment]
> You can consume Kafka data through flink, and then store it in the library through stream load
> You can also try the flink doris connector, which is not currently in the development and testing phase
> https://github.com/JNSimba/incubator-doris/tree/flink-connector-doris

请问，大神，这个flink-connector-doris 大概什么时候能上线？

**Comment by yangmingjie2018** [comment]
可否给一个flink-connector-doris的jar包？ 我自己编译了一个一直不成功（我是.net的，不太会弄这个）。

**Comment by morningman** [comment]
[doris-flink-1.0-SNAPSHOT.jar.zip](https://github.com/apache/incubator-doris/files/6363797/doris-flink-1.0-SNAPSHOT.jar.zip)

But you should be able to compile it by yourself, it words for me, try the latest trunk code

**Comment by yangmingjie2018** [comment]
![image](https://user-images.githubusercontent.com/46737906/115844306-4bbec880-a452-11eb-9c29-dfc131cf1473.png)

**Comment by yangmingjie2018** [comment]
> [doris-flink-1.0-SNAPSHOT.jar.zip](https://github.com/apache/incubator-doris/files/6363797/doris-flink-1.0-SNAPSHOT.jar.zip)
> 
> But you should be able to compile it by yourself, it words for me, try the latest trunk code

收到，多谢

**Comment by yangmingjie2018** [comment]
已经支持，点赞！ @hf200012 @morningman
