### ISSUE TITLE
downLoad and parse __repo_info file can update createTime when creating repository  which name is used and remote FilePath exsists

### ISSUE THREAD

**Issue by WindyGao** [apache/incubator-doris#5625]
**encountering problem**
I found a problem
Delete the REPOSITORY like `hdfs_repo`
create a new REPOSITORY named `hdfs_repo` too, and the RepoId has changed.The configuration is the same
but the create-time is not the latest time
![image](https://user-images.githubusercontent.com/36130371/114255938-3f198980-99e9-11eb-8e43-3da90739d636.png)

**souceCode analysis**
![image](https://user-images.githubusercontent.com/36130371/114255979-928bd780-99e9-11eb-8fbc-537686efc175.png)

**suggestion**

 Is it better to update the create_time field that is parsed out of the  __repo_info file when it pulled to local

**Comment by abothli** [comment]
I seem to have found this problem too

**Comment by WindyGao** [comment]
there  is no bug ,that's how it's designed
