### ISSUE TITLE
TabletNum has increased sharply than before

### ISSUE THREAD

**Issue by WindyGao** [apache/incubator-doris#5626]
# enviroment
## version
0.13.15
## node num
13 fe ——node1-node13
13 be——node1-node13
9 broker——node1-node9
# encounter with
TableNum raise quickly
The Tablet, which used to be less than 10, 000, now goes up by 30, 000 a night
# operation
- I have done the decommission operation of 3 BE nodes before this evening
- and A task was submitted on the Azkaban platform to run”drop tmp table “,"create tmp table like table A"  , ”replace with (swap =false)“ once per minute
After or at the same time, the tablet keeps going up
When I rebooted the master node, nothing happened, but after rebooting all the Follower nodes, something magical happened and the number of tablets dropped below 10,000！
But the days after that tablets were still going up

**Comment by WindyGao** [comment]
![image](https://user-images.githubusercontent.com/36130371/114260857-e6a6b400-9a09-11eb-8788-4db4a8d26f71.png)
`2021-04-10 13:31:06,387 WARN (Thread-35|79) [ReportHandler.deleteFromBackend():676] failed add to meta. tablet[61452152], backend[28194075]. errCode = 2, detailMessage = db[-1] does not exist
2021-04-10 13:31:06,387 WARN (Thread-35|79) [ReportHandler.deleteFromBackend():689] delete tablet[61452152 - 1645640934] from backend[28194075] because not found in meta
`

**Comment by WindyGao** [comment]
fe master log :
`2021-04-10 13:31:06,387 WARN (Thread-35|79) [ReportHandler.deleteFromBackend():676] failed add to meta. tablet[61452152], backend[28194075]. errCode = 2, detailMessage = db[-1] does not exist
2021-04-10 13:31:06,387 WARN (Thread-35|79) [ReportHandler.deleteFromBackend():689] delete tablet[61452152 - 1645640934] from backend[28194075] because not found in meta
`

**Comment by morningman** [comment]
This is because when replacing table with swap=false, the tablets of old table is not dropped.
