### ISSUE TITLE
sh build.sh compile error

### ISSUE THREAD

**Issue by Keysluomo** [apache/incubator-doris#5674]
[WARNING] The POM for net.sourceforge.czt.dev:java-cup:jar:0.11-a-czt02-cdh is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.480 s
[INFO] Finished at: 2021-04-19T03:52:22Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project doris-fe: Could not resolve dependencies for project org.apache:doris-fe:jar:3.4.0: Failure to find net.sourceforge.czt.dev:java-cup:jar:0.11-a-czt02-cdh in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
环境：windows 10 + Docker
docker pull apachedoris/doris-dev:build-env-1.2
启动并进入容器：
wget https://dist.apache.org/repos/dist/dev/incubator/doris/0.12.0-rc01/apache-doris-0.12.0-incubating-src.tar.gz
sh build.sh

How do you solve this problem ？

**Comment by Keysluomo** [comment]
已经解决

**Comment by aws0me** [comment]
> 已经解决

你是怎么解决的?我用的mac的docker,1.3的doris也有类似的问题
