### ISSUE TITLE
[Bug] The aggregation result does not meet expectations when using grouping set

### ISSUE THREAD

**Issue by e0c9** [apache/incubator-doris#5690]
![截屏2021-04-22 下午12 51 32](https://user-images.githubusercontent.com/45457672/115657633-cfe95100-a369-11eb-8e4b-2959761998d8.png)

**Comment by HappenLee** [comment]
Could you please offer the table struct and raw data for me to test the case， thank you~

**Comment by e0c9** [comment]
Has been fixed in #5431
