### ISSUE TITLE
Difficult to find Issue Tracker

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-doris#5715]
It's not at all easy to find how to report bugs.

The only link I could find required navigating several pages.
The link on the page http://doris.incubator.apache.org/master/en/community/how-to-contribute.html#if-a-bug-or-problem-is-found leads to  https://github.com/apache/incubator-doris/issues/new/select which does not actually work.

I would expect to find a direct link to the Issue tracker in one of the menus as well.

**Comment by morningman** [comment]
Fixed by #5716

**Comment by sebbASF** [comment]
This issue is not actually addressed by #5716 yet

**Comment by morningman** [comment]
> This issue is not actually addressed by #5716 yet

Do you mean to directly add an entry for submitting an issue in the first-level menu of the sidebar?

**Comment by sebbASF** [comment]
Yes, for example under Apache Community alongside "Subscribe to mailing lists"

**Comment by sebbASF** [comment]
It is OK to have additional links where appropriate in the body text, but please ensure that they actually work

**Comment by morningman** [comment]
> It is OK to have additional links where appropriate in the body text, but please ensure that they actually work

OK, I got it.

**Comment by sebbASF** [comment]
Still not fixed

**Comment by morningman** [comment]
That is weird. Seems that the doc didn't pushed to the website, I will check it later.

**Comment by sebbASF** [comment]
Looks OK now, thanks
