### ISSUE TITLE
ODBC doris on mysql bug

### ISSUE THREAD

**Issue by liuxiaoxiong** [apache/incubator-doris#5718]
hi everyone，this maybe a bug in doris 0.14.7
when i use ODBC for doris on mysql , i found that problem like this：
(各位大佬好，这可能是个bug在0.14.7，当我再使用odbc驱动下的doris 作为mysql的映射表事，我发现以下问题：)
![image](https://user-images.githubusercontent.com/25683936/116336700-9605c800-a80b-11eb-9a21-f5d5f60d68b9.png)
 
sales_department is a table for doris on mysql
sales_department is just a doris olap table   
so,how can i use where when data is chinese?
（如图所示，sales_department是一张mysql映射的表，sales_department_doris是一张普通的olap表，当内容数据是中文的时候，就有这问题，各位大佬有遇到这个问题吗？）

**Comment by HappenLee** [comment]
please show the odbcinst.ini config. which mysql driver you are using now。

**Comment by liuxiaoxiong** [comment]
cat odbcinst.ini 
[MySQL]
Description = MySQL ODBC driver
Driver = /usr/lib64/libmyodbc8a.so
FileUsage = 1 

关于这点，我记得我用过/usr/lib64/libmyodbc8w.so   但是建立mysql映射表的时候报错一直找不到driver，用上 /usr/lib64/libmyodbc8a.so就建表成功了。

**Comment by HappenLee** [comment]
You should not use the ANSI driver
![image](https://user-images.githubusercontent.com/10553413/116343147-7a53ef00-a816-11eb-92ae-c5db6e5082a1.png)

**Comment by liuxiaoxiong** [comment]
Thanks,this problem is solved
(感谢还真是驱动问题。。。)
