### ISSUE TITLE
flink doris connector 支持flink 1.12吗？

### ISSUE THREAD

**Issue by yangmingjie2018** [apache/incubator-doris#5740]
请问，flink doris connector 支持flink 1.12吗？

**Comment by JNSimba** [comment]
supported

**Comment by yangmingjie2018** [comment]
多谢！大神！

**Comment by 13264494701** [comment]
我之前成功编译了1.11.2版本的connector 并且运行成功 但是最近flink版本升级到了1.12.3 我重新编译成功 但是运行相同代码的时候报了如下错误 不知道是什么原因？Caused by: java.lang.ClassNotFoundException: org.apache.doris.flink.table.DorisDynamicOutputFormat   我看了这个jar包里面是有这个类的。
