### ISSUE TITLE
flink doris connector 数据不能实时同步。

### ISSUE THREAD

**Issue by yangmingjie2018** [apache/incubator-doris#5743]
![image](https://user-images.githubusercontent.com/46737906/116660396-8c27c480-a9c5-11eb-85ac-6678602f3596.png)

**Comment by yangmingjie2018** [comment]
补充：
在flink job运行的时候，mysql中的数据变化，不会同步到doris中；
在flink job进行取消后，mysql中的数据变化，才会同步到doris中。  

猜想应该是取消的时候，同步的。

**Comment by JNSimba** [comment]
If you want to use real-time effects, you can set the **sink.batch.size =1**  ，default value is 100

**Comment by yangmingjie2018** [comment]
多谢大神
