### ISSUE TITLE
_stream_load 发送json报 no valid Basic authorization 错误

### ISSUE THREAD

**Issue by taoxu1234** [apache/incubator-doris#5747]
描述
1. 我用postman 发送 _stream_load json请求时，报no valid Basic authorization
2. 有时候是成功的，不是每次都报no valid Basic authorization，也会 success

步骤
1. 我的版本是最新执行git clone https://github.com/apache/incubator-doris.git 的版本，具体版本号暂时不清楚在哪看，调用接口ip:port/api/bootstrap 显示的{"replayedJournalId":0,"queryPort":0,"rpcPort":0,"version":"","status":"OK","msg":"Success"} 中version为空。
2. 我的环境是1个fe加上3个be
3. 由于本地安装了docker,网卡比较多，我的ip通过配置文件写死了。
4. 用postman 发送http请求 有时候是成功，有时候显示 no valid Basic authorization，看了下日志也没有明显的报错信息，
5. 执行SHOW PROC '/frontends';  SHOW PROC '/backends'; 两个命令，机器状态也正常。

**Expected behavior**
全部都是成功
**Screenshots**
![suc](https://user-images.githubusercontent.com/83450258/116684356-73c6a280-a9e3-11eb-86b2-321ca6797160.png)
![au](https://user-images.githubusercontent.com/83450258/116684370-775a2980-a9e3-11eb-935e-51eefb474da5.png)
![fe](https://user-images.githubusercontent.com/83450258/116680716-95715b00-a9de-11eb-9955-93edf49f0ee4.png)
![be1](https://user-images.githubusercontent.com/83450258/116680724-97d3b500-a9de-11eb-87c7-c75650161b0f.png)
![be2](https://user-images.githubusercontent.com/83450258/116680732-9a360f00-a9de-11eb-9c4a-2fdc974b5f1b.png)
![be3](https://user-images.githubusercontent.com/83450258/116680744-9e622c80-a9de-11eb-8dfb-11b01e7feec2.png)
![tail](https://user-images.githubusercontent.com/83450258/116680757-a28e4a00-a9de-11eb-929a-ed7f5e8b5617.png)

**Comment by zjd-melo** [comment]
solved?

**Comment by sjahongir** [comment]
`curl --location-trusted -u root -T _data.csv  -H "label:20" -H "format:csv_with_names" -H "Expect:100-continue" -H "column_separator:," http://192.168.88.13:8030/api/test_db/test_streamload/_stream_load`

This curl works in cmd, postman and go app but not works in C#, node, python.
The error: [NOT_AUTHORIZED]no valid Basic authorization

**Comment by sunmingqiaa** [comment]
> > `curl --location-trusted -u root -T _data.csv -H "label:20" -H "format:csv_with_names" -H "Expect:100-continue" -H "column_separator:," http://192.168.88.13:8030/api/test_db/test_streamload/_stream_load`
> > This curl works in cmd, postman and go app but not works in C#, node, python. The error: [NOT_AUTHORIZED]no valid Basic authorization
> 
> `使用 Session 保持授权信息（防止重定向时丢失 Authorization）`
> 
> ```
> headers = {
>     "Expect": "100-continue",
>     'Content-Type': 'text/plain; charset=UTF-8',
>     "merge_type": "APPEND",
>     "format": "csv_with_names",
>     "column_separator": ",",
> }
> auth = HTTPBasicAuth(username, password)
> session = requests.sessions.Session()
> session.should_strip_auth = lambda old_url, new_url: False  # **禁用 requests 的自动去掉 Authorization 头部的功能**
> 
> # 上传文件
> file_path = "test.csv"
> with open(file_path, "rb") as file:
>     resp = session.request('PUT', url=url, data=file, headers=headers, auth=auth)
> ```

这个有用
