### ISSUE TITLE
Flink-doris数据更新和数据重复

### ISSUE THREAD

**Issue by yaowanli** [apache/incubator-doris#5760]
Flink-doris-connector千呼万唤始出来了！
目前看了源码stream-load那块，结合目前我们自己简单开发的connector进行对比，发现有两个问题：
1.目前是有数据进入，才调flush方法，并判断batchsize是否符合条件；如果一直没有新数据进来，会导致batch数组里的数据无法落入doris；之前参考Flink-JDBCSink那块做了类似的connector，里面是定时器newScheduledThreadPool去调用flush()，社区可以参考下；
2.如果两条相同主键，但先后更新的数据落入batch数组，目前无法做去重操作，doris是如何去保证两条数据不会乱序的呢？即后来先插的问题。

**Comment by JNSimba** [comment]
1.thank you so much for your suggestion，This piece of follow-up needs to be optimized
2.Since write to doris is based on streamload, if your table is a UNIQUE model, it will automatically update based on the sequence of data

**Comment by morningman** [comment]
这种有序需要用到 doris的 sequence column 功能，单独的 unique无法保证

**Comment by JNSimba** [comment]
1.In the document：[sequence column](http://doris.apache.org/master/zh-CN/administrator-guide/load-data/sequence-column-manual.html#%E4%BD%BF%E7%94%A8%E7%A4%BA%E4%BE%8B)  function compares time type or incremental type fields. If there is no time type field in the table, how to ensure that the data is out of order?
2.For the uniq model, I tested it. Streamload is inserted according to the sequence of the data. In what scenarios will there be disorder?

**Comment by yaowanli** [comment]
Thank you for your reply.
I have seen sequence column function which is useful ,I think it can solve the second problem which I mention. but it is still in the master branch.I looking forward to the stable version of it so that I can update the version when I use branch-0.12 now. 
Howerver,the first problem, data uodate late, may need to be considered.

**Comment by sniperxing** [comment]
sequence在flink doris connecter中如何设置呢？我看文档中没有对应的参数

**Comment by JNSimba** [comment]
> sequence在flink doris connecter中如何设置呢？我看文档中没有对应的参数

Set when the table is created 
http://doris.apache.org/master/zh-CN/administrator-guide/load-data/sequence-column-manual.html#%E4%BD%BF%E7%94%A8%E7%A4%BA%E4%BE%8B

**Comment by sniperxing** [comment]
> > sequence在flink doris connecter中如何设置呢？我看文档中没有对应的参数
> 
> Set when the table is created
> http://doris.apache.org/master/zh-CN/administrator-guide/load-data/sequence-column-manual.html#%E4%BD%BF%E7%94%A8%E7%A4%BA%E4%BE%8B

建表的时候只能设置sequence的type
而flink doris connecter中使用的是stream load，stram load需要在header中设置sequence coloum，但是flink doris connecter中没有提供该参数呀

**Comment by JNSimba** [comment]
> > > sequence在flink doris connecter中如何设置呢？我看文档中没有对应的参数
> > 
> > 
> > Set when the table is created
> > http://doris.apache.org/master/zh-CN/administrator-guide/load-data/sequence-column-manual.html#%E4%BD%BF%E7%94%A8%E7%A4%BA%E4%BE%8B
> 
> 建表的时候只能设置sequence的type
> 而flink doris connecter中使用的是stream load，stram load需要在header中设置sequence coloum，但是flink doris connecter中没有提供该参数呀

well, currently, Flink connector does not support this parameter

**Comment by JNSimba** [comment]
> > > > sequence在flink doris connecter中如何设置呢？我看文档中没有对应的参数
> > > 
> > > 
> > > Set when the table is created
> > > http://doris.apache.org/master/zh-CN/administrator-guide/load-data/sequence-column-manual.html#%E4%BD%BF%E7%94%A8%E7%A4%BA%E4%BE%8B
> > 
> > 
> > 建表的时候只能设置sequence的type
> > 而flink doris connecter中使用的是stream load，stram load需要在header中设置sequence coloum，但是flink doris connecter中没有提供该参数呀
> 
> well, currently, Flink connector does not support this parameter

#6199
