### ISSUE TITLE
FlinkSQL查询报错

### ISSUE THREAD

**Issue by DongTL** [apache/incubator-doris#5771]
**Describe the bug**
使用FlinkSQL的sql-client客户端，创建一张表连接Doris：
```sql
Flink SQL> CREATE TABLE flink_doris_source
> (
>     siteid INT,
>     citycode INT,
>     username STRING,
>     pv INT
> )
>     WITH (
>       'connector' = 'doris',
>       'fenodes' = 'xxx:8030',
>       'table.identifier' = 'example_db.table1',
>       'username' = 'root',
>       'password' = 'admin123',
>       'sink.batch.size' = '1'
> );
```
然后执行查询
```
select * from flink_doris_source;
```
若表是空的则查询数秒后程序停止
若表中有数据，数据查询不到 ，查询数秒后报错：
```
[ERROR] Could not execute SQL statement.Reason:java.lang.NoSuchMethodError: 

scala.collection.JavaConversions$.deprecated$u0020asScalaSet(Ljava/util/Set;)Lscala/collection/mutable/Set;
```

- doris-version:0.13
- flink-version:1.11.3
- doris-flink-connector-version:1.0.0

希望大佬解答。

**Comment by yangmingjie2018** [comment]
各种组件的版本，特别是scala：

![image](https://user-images.githubusercontent.com/46737906/117528796-a5082980-b006-11eb-87f2-aac914f6bf4f.png)

**Comment by yangmingjie2018** [comment]
https://github.com/apache/incubator-doris/blob/master/docs/zh-CN/extending-doris/flink-doris-connector.md

**Comment by DongTL** [comment]
> 各种组件的版本，特别是scala：
> 
> ![image](https://user-images.githubusercontent.com/46737906/117528796-a5082980-b006-11eb-87f2-aac914f6bf4f.png)

您好，您的意思是我应该更换Doris0.14版本吗？

**Comment by JNSimba** [comment]
may be  scala-related package conflict

**Comment by hf200012** [comment]
> > 各种组件的版本，特别是scala：
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/46737906/117528796-a5082980-b006-11eb-87f2-aac914f6bf4f.png)
> 
> 
> 
> 您好，您的意思是我应该更换Doris0.14版本吗？

不是doris版本，是scala的版本，你使用2.12.*版本编译打包flink doris connector

**Comment by DongTL** [comment]
> > > 各种组件的版本，特别是scala：
> > 
> > 
> > > 
> > 
> > 
> > > ![image](https://user-images.githubusercontent.com/46737906/117528796-a5082980-b006-11eb-87f2-aac914f6bf4f.png)
> > 
> > 
> > 您好，您的意思是我应该更换Doris0.14版本吗？
> 
> 不是doris版本，是scala的版本，你使用2.12.*版本编译打包flink doris connector

您好，我是使用doris-dev:build-env-1.2镜像进行编译的。
