### ISSUE TITLE
flinksql doris insert exception:stream load error: too many filtered rows

### ISSUE THREAD

**Issue by DongTL** [apache/incubator-doris#5796]
doris table:

```sql
CREATE TABLE `business_order2` (
  `id` bigint(20) NOT NULL COMMENT '主键',
  `order_no` varchar(50) DEFAULT NULL COMMENT '订单号'
)
UNIQUE KEY(`id`, `order_no`)
DISTRIBUTED BY HASH(`id`) BUCKETS 10
PROPERTIES("replication_num" = "1");
```

flinksql doris table:

```sql
CREATE TABLE `doris_business_order2` (
  `id` bigint NOT NULL,
  `order_no` varchar
) WITH (
      'connector' = 'doris',
      'fenodes' = 'xxx:8030',
      'table.identifier' = 'prod_order.business_order',
      'username' = 'root',
      'password' = 'xxx',
      'sink.batch.size' = '1'
);
```

insert:

```sql
INSERT INTO doris_business_order2
select `id` ,`order_no` 
from mysql_business_order
where deleted = 1 ;
```
Table update statement has been successfully submitted to the cluster.

but,flink dashboard show FAILED:

```
stream load error: too many filtered rows
```

**Comment by FireFreedomK** [comment]
你好，我用的0.15.0版本的doris，用spark dataframe将数据导入doris，也出现了一样的问题，请问你是怎么解决的

**Comment by hf200012** [comment]
> 你好，我用的0.15.0版本的doris，用spark dataframe将数据导入doris，也出现了一样的问题，请问你是怎么解决的

This is your data problem, there may be several cases, the field separator (the number of columns that cause the field split to be inconsistent with the number of columns in the table, generally more), the row separator, the actual number of imported fields and the table are inconsistent, Imported data causes some fields to be overly long, etc.

**Comment by elisondba2022** [comment]
Caused by: org.apache.flink.util.SerializedThrowable: stream load error: too many filtered rows, see more in http://192.168.168.215:8040/api/_load_error_log?file=__shard_25/error_log_insert_stmt_874b6649b376fa9b-d6cb775095dfb4b1_874b6649b376fa9b_d6cb775095dfb4b1
