### ISSUE TITLE
创建Routine失败

### ISSUE THREAD

**Issue by 812406210** [apache/incubator-doris#5806]
你好，请问为啥显示format不支持呢，我看其他issue是支持的。是哪个有错吗？可以指点下吗，困扰很久了。
使用版本是0.12版本
![image](https://user-images.githubusercontent.com/22192011/118104937-5b587e00-b40e-11eb-92e0-59c4520a33dd.png)

**Comment by hf200012** [comment]
CREATE ROUTINE LOAD example_db.test1 ON example_tbl
        COLUMNS(category, author, price, timestamp, dt=from_unixtime(timestamp, '%Y%m%d'))
        PROPERTIES
        (
            "desired_concurrent_number"="3",
            "max_batch_interval" = "20",
            "max_batch_rows" = "300000",
            "max_batch_size" = "209715200",
            "strict_mode" = "false",
            "format" = "json",
            "jsonpaths" = "[\"$.category\",\"$.author\",\"$.price\",\"$.timestamp\"]",
            "strip_outer_array" = "true",
            "json_root" = "$.RECORDS"
        )
        FROM KAFKA
        (
            "kafka_broker_list" = "broker1:9092,broker2:9092,broker3:9092",
            "kafka_topic" = "my_topic",
            "kafka_partitions" = "0,1,2",
            "kafka_offsets" = "0,0,0"
        );

**Comment by 812406210** [comment]
> CREATE ROUTINE LOAD example_db.test1 ON example_tbl
> COLUMNS(category, author, price, timestamp, dt=from_unixtime(timestamp, '%Y%m%d'))
> PROPERTIES
> (
> "desired_concurrent_number"="3",
> "max_batch_interval" = "20",
> "max_batch_rows" = "300000",
> "max_batch_size" = "209715200",
> "strict_mode" = "false",
> "format" = "json",
> "jsonpaths" = "["$.category","$.author","$.price","$.timestamp"]",
> "strip_outer_array" = "true",
> "json_root" = "$.RECORDS"
> )
> FROM KAFKA
> (
> "kafka_broker_list" = "broker1:9092,broker2:9092,broker3:9092",
> "kafka_topic" = "my_topic",
> "kafka_partitions" = "0,1,2",
> "kafka_offsets" = "0,0,0"
> );
感谢，但是我按这种方法，识别不了$符，这个又是怎么回事呀？
![image](https://user-images.githubusercontent.com/22192011/118112659-e12cf700-b417-11eb-8386-6a02bc37f42a.png)

**Comment by SpenserZC** [comment]
> 你好，请问为啥显示format不支持呢，我看其他issue是支持的。是哪个有错吗？可以指点下吗，困扰很久了。
> 使用版本是0.12版本
> ![image](https://user-images.githubusercontent.com/22192011/118104937-5b587e00-b40e-11eb-92e0-59c4520a33dd.png)

您好，请问您解决了吗？是什么原因呢？

**Comment by 812406210** [comment]
换一个高版本



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhang ***@***.***&gt;; 
发送时间: 2021年8月23日(星期一) 晚上7:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [apache/incubator-doris] 创建Routine失败 (#5806)





  
你好，请问为啥显示format不支持呢，我看其他issue是支持的。是哪个有错吗？可以指点下吗，困扰很久了。
 使用版本是0.12版本
 
  
您好，请问您解决了吗？是什么原因呢？
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SpenserZC** [comment]
> 换一个高版本
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Zhang ***@***.***&gt;; 发送时间: 2021年8月23日(星期一) 晚上7:39 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; "State ***@***.***&gt;; 主题: Re: [apache/incubator-doris] 创建Routine失败 (#5806) 你好，请问为啥显示format不支持呢，我看其他issue是支持的。是哪个有错吗？可以指点下吗，困扰很久了。 使用版本是0.12版本 您好，请问您解决了吗？是什么原因呢？ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

好吧，谢谢了哈
