### ISSUE TITLE
江湖救急，fe配置不起作用！

### ISSUE THREAD

**Issue by yangmingjie2018** [apache/incubator-doris#5808]
补充：其他配置都起作用，只有priority_networks，不管配置成内网还是外网IP，当show proc '/frontends'的时候都127.0.0.1

**Comment by yangmingjie2018** [comment]
补充：其他配置都起作用，只有priority_networks，不管配置成内网还是外网IP，当show proc '/frontends'的时候都127.0.0.1

**Comment by morningman** [comment]
meta dir 清掉重来一遍

**Comment by yangmingjie2018** [comment]
> meta dir 清掉重来一遍

![image](https://user-images.githubusercontent.com/46737906/118203565-e8431c00-b48e-11eb-808b-39307f02fcaa.png)

**Comment by 812406210** [comment]
> meta dir 清掉重来一遍

你好我也碰到了，清除之后，be里面的数据就用不了了，不知道怎么回事，我最后又把be的storage给删了，但是如果用在生产，这问题怎么破？

**Comment by morningman** [comment]
我说的这个方法仅适用于初次搭建环境。你的问题是初次搭建环境时IP就设置错了，所有本身集群也不会有数据。

**Comment by morningman** [comment]
> > meta dir 清掉重来一遍
> 
> ![image](https://user-images.githubusercontent.com/46737906/118203565-e8431c00-b48e-11eb-808b-39307f02fcaa.png)
> 
> 我用的版本是0.14

还不行，可能是你配置的 priority_networks 值不对，ifconfig 确认下吧

**Comment by xinghuayu007** [comment]
121.41.219.202/24，子网掩码是24位的话，不应该写成121.41.219.0/24？

**Comment by morningman** [comment]
> 121.41.219.202/24，子网掩码是24位的话，不应该写成121.41.219.0/24？

理论上都可以，只会匹配掩码部分

**Comment by xiyueliuyun** [comment]
> ![image](https://user-images.githubusercontent.com/46737906/118115653-ceb4bc80-b41b-11eb-9cd8-5ddf2ff30da6.png)
> 补充：其他配置都起作用，只有priority_networks，不管配置成内网还是外网IP，当show proc '/frontends'的时候都127.0.0.1

你这是个公网IP，本机网卡上没有吧，用你的内网IP 10.152.0.205

**Comment by yangmingjie2018** [comment]
> > > meta dir 清掉重来一遍
> > 
> 
> 还不行，可能是你配置的 priority_networks 值不对，ifconfig 确认下吧  

配置没有问题，以下是ifconfig的内容（我是在阿里云linux服务器）
![image](https://user-images.githubusercontent.com/46737906/118217230-9bb80a80-b4a7-11eb-92b6-f18f31fc2d55.png)

下面是运行日志：

![image](https://user-images.githubusercontent.com/46737906/118217282-b5f1e880-b4a7-11eb-9c03-5768d3b640cf.png)

**Comment by yangmingjie2018** [comment]
> 用你的内网IP 10.152.0.205

是的大神，ifconfig中没有外网地址（阿里云服务器）
![image](https://user-images.githubusercontent.com/46737906/118217359-e0dc3c80-b4a7-11eb-8fb2-3266c58d8568.png)

我用过内网地址10.152.0.205，但是服务起不来
![image](https://user-images.githubusercontent.com/46737906/118217409-fe110b00-b4a7-11eb-8adb-28b7f576a2b4.png)

**Comment by yangmingjie2018** [comment]
doris有在阿里云服务器上部署的文章吗？

**Comment by yangmingjie2018** [comment]
doris有在阿里云服务器上部署的文章吗？
