### ISSUE TITLE
install document issue

### ISSUE THREAD

**Issue by lenmom** [apache/incubator-doris#581]
The build document in compile document should to be refine:
In CentOS, install gcc5.3 is using 
yum install devtoolset-4 report no package found which lead to the installation faield.

Provide a set of command to install gcc v5.2+
**sudo yum install centos-release-scl**
**sudo yum install devtoolset-4-gcc***

to use gcc 5.3, type  the following command in the terminal:
**scl enable devtoolset-4 bash**

we have three ways to make gcc5.3 avalible permanantly: 
1st.  **sudo ln -s [path_to_gcc_5.3] /usr/bin**
2nd.  
**vim ~/.bashrc or vim  ~/.bash_profile
source scl_source enable devtoolset-4**
3rd.
**echo "source /opt/rh/devtoolset-3/enable" >> /etc/bashrc
source /etc/bashrc**

**Comment by morningman** [comment]
Thanks. We will merge it into INSTALL wiki

**Comment by blackfox1983** [comment]
echo "source /opt/rh/devtoolset-3/enable" >> /etc/bashrc 错误。应该改为：
echo "source /opt/rh/devtoolset-4/enable" >> /etc/bashrc
