### ISSUE TITLE
创建物化视图导致写入rowset数量达到上限

### ISSUE THREAD

**Issue by 643251132** [apache/incubator-doris#5936]
场景：一张doris表  dw_table_xxx ，按照日期做分区，保存过去30天分区，写入频次为 30s一次。![image](https://user-images.githubusercontent.com/34223991/119973984-baa9b700-bfe6-11eb-9509-b65844240195.png)
对上述表dw_table_xxx 新建物化视图 dw_table_xxx_view。  创建物化视图耗时约 5 小时。

max_tablet_version_num 为默认值 500

异常现象：rowset version 达到上限，导致写入失败。

![image](https://user-images.githubusercontent.com/34223991/119973984-baa9b700-bfe6-11eb-9509-b65844240195.png)

经过排查发现：当日分区下的物化视图tablet一直没有进行 compaction，导致超过了上限max_tablet_version_num = 500
![image](https://user-images.githubusercontent.com/34223991/119974005-c301f200-bfe6-11eb-8cb1-90f2c44c6499.png)

![image](https://user-images.githubusercontent.com/34223991/119974022-c7c6a600-bfe6-11eb-812b-dd13a25c2bfb.png)

虽然可以通过调整max_tablet_version_num大小来避免写入失败，但是如果一直得不到compaction的话，最终rowset数量还是会超过上限。

已知每30s写入一次，生成一个rowset version。如果超过4小时没有进行compaction，rowset version则会超过500

那么问题来了：compaction的逻辑是怎样？在创建物化视图的时候，是按照分区从旧到新，对每个分区下的tablet 进行 compaction 吗？

多谢您的解答~~

**Comment by morningman** [comment]
一直没有compaction是有问题的，compaction每次会选取版本最多的tablet进行compaction，你得看下be.INFO里有没有相关的compaction失败信息

**Comment by 643251132** [comment]
一直没有compaction的原因找到了：
在进行tablet选取的过程中 ：find_best_tablet_to_compaction  会过滤掉 state 为TABLET_NOTREADY的 tablet
而正在进行物化视图创建的tablet state = TABLET_NOTREADY  所以正在创建中的物化视图下tablet在rollup 任务没有结束前，根本不会进行compaction，如果rollup历史数据的速度很慢的话，最新写入的tablet下的rowset version将会超过限制，从而导致写入失败。

版本为0.14.7   源码链接：https://github.com/baidu-doris/incubator-doris/blob/f30f14c4474e15f99c02e9036e82c909d90fc702/be/src/olap/tablet_manager.cpp#L713

对于此场景，doris团队将考虑通过什么方式解决呢？
