### ISSUE TITLE
[Doris On ES][Bug] publish_address has hostname, it causes  bug

### ISSUE THREAD

**Issue by ChPi** [apache/incubator-doris#5949]
**Describe the bug**
https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/http/HttpInfo.java
当es publish_address包含host，则不能连接到es集群。EsNodeInfo需要剔除host

**Comment by wuyunfeng** [comment]
Describe the problem you want to solve in detail？？

**Comment by stalary** [comment]
Using network.publish_host=hostname causes this problem
