### ISSUE TITLE
flink connector sql 模式 从 hive 表查询数据 插入 doris date 类型字段 值发生错误

### ISSUE THREAD

**Issue by 1272870698** [apache/incubator-doris#5958]
1. hive 原始值
![image](https://user-images.githubusercontent.com/55021823/120459230-94ab5a80-c3ca-11eb-9c7a-3fc64ee6fe8e.png)

2. doris 写入时的值
![image](https://user-images.githubusercontent.com/55021823/120459262-9c6aff00-c3ca-11eb-97f1-a55207747adf.png)

**Comment by hf200012** [comment]
@JNSimba

**Comment by JNSimba** [comment]
Can you show code? I tried it and it’s ok.

**Comment by 1272870698** [comment]
> Can you show code? I tried it and it’s ok.
你好 代码如下
`EnvironmentSettings settings = EnvironmentSettings.newInstance()
                .useBlinkPlanner().build();

        TableEnvironment tableEnv = TableEnvironment.create(settings);

        System.setProperty("HADOOP_USER_NAME", "hive");
        HiveCatalog hiveCatalog = new HiveCatalog("hive", "xxx", "src/main/resources");
        tableEnv.registerCatalog("hive", hiveCatalog);
        tableEnv.useCatalog("hive");

        tableEnv.executeSql("drop table xxx");
        String dorisSinkTb = "CREATE TABLE xxx (\n" +
                "  `stsc_date` date  ,\n" +
                "  `stsc_week` string  ,\n" +
                "  `stsc_year_mon` string ,\n" +
                "  `stsc_quater` string  ,\n" +
                "  `stsc_year` string  ,\n" +
                "  `type_code` string  ,\n" +
                "  `type_name` string  ,\n" +
                "  `site_code` string  ,\n" +
                "  `company_code` string  ,\n" +
                "  `company_name` string ,\n" +
                "  `goods_code` string  ,\n" +
                "  `goods_name` string  ,\n" +
                "  `common_name` string  ,\n" +
                "  `pron_fact_code` string  ,\n" +
                "  `pron_fact_name` string  ,\n" +
                "  `mete_unit_code` string  ,\n" +
                "  `mete_unit_name` string,\n" +
                "  `pres_type_code` string  ,\n" +
                "  `pres_type_name` string  ,\n" +
                "  `dosa_type_code` string  ,\n" +
                "  `dosa_type_name` string  ,\n" +
                "  `intl_code` string  ,\n" +
                "  `trad` string ,\n" +
                "  `norms` string ,\n" +
                "  `sale_tax_clas_code` string ,\n" +
                "  `is_recipe_flag` string ,\n" +
                "  `is_fine_flag` string ,\n" +
                "  `prod_cate_lev1_code` string ,\n" +
                "  `prod_cate_lev1_name` string,\n" +
                "  `prod_cate_lev2_code` string ,\n" +
                "  `prod_cate_lev2_name` string,\n" +
                "  `prod_cate_lev3_code` string,\n" +
                "  `prod_cate_lev3_name` string,\n" +
                "  `prod_cate_lev4_code` string ,\n" +
                "  `prod_cate_lev4_name` string,\n" +
                "  `purc_clas_lev1_code` string,\n" +
                "  `purc_clas_lev1_name` string ,\n" +
                "  `purc_clas_lev2_code` string,\n" +
                "  `purc_clas_lev2_name` string,\n" +
                "  `purc_clas_lev3_code` string,\n" +
                "  `purc_clas_lev3_name` string,\n" +
                "  `purc_range` string,\n" +
                "  `goods_sttu_code` string,\n" +
                "  `goods_sttu_name` string,\n" +
                "  `last_purc_date` date,\n" +
                "  `ask_times` int,\n" +
                "  `sati_times` int ,\n" +
                "  `ask_qty` int,\n" +
                "  `sati_qty` int,\n" +
                "  `sale_qty` decimal(22,4)  ,\n" +
                "  `sale_amt` decimal(22,4)  ,\n" +
                "  `sale_cost` decimal(22,4) ,\n" +
                "  `gros_prof_amt` decimal(22,4) ,\n" +
                "  `stk_qty` decimal(22,4) ,\n" +
                "  `avai_qty` decimal(22,4) ,\n" +
                "  `stk_amt` decimal(22,4) ,\n" +
                "  `latest_ntax_price` decimal(22,4) ,\n" +
                "  `latest_tax_price` decimal(22,4) ,\n" +
                "  `last_purc_doc` string ,\n" +
                "  `eff_bill_cnt` int  \n" +
                ") \n" +
                "    WITH (\n" +
                "      'connector' = 'doris',\n" +
                "      'fenodes' = 'xxxx:8031',\n" +
                "      'table.identifier' = 'test.xxxx',\n" +
                "      'sink.batch.size' = '500000', " +
                "      'username' = 'root',\n" +
                "      'password' = ''" +
                ")";

  
        tableEnv.executeSql(dorisSinkTb);
        tableEnv.executeSql("insert into xxxx(stsc_date, stsc_week, stsc_year_mon, stsc_quater, stsc_year, type_code, type_name, site_code, company_code, company_name, goods_code, goods_name, common_name, pron_fact_code, pron_fact_name, mete_unit_code, mete_unit_name, pres_type_code, pres_type_name, dosa_type_code, dosa_type_name, intl_code, trad, norms, sale_tax_clas_code, is_recipe_flag, is_fine_flag, prod_cate_lev1_code, prod_cate_lev1_name, prod_cate_lev2_code, prod_cate_lev2_name, prod_cate_lev3_code, prod_cate_lev3_name, prod_cate_lev4_code, prod_cate_lev4_name, purc_clas_lev1_code, purc_clas_lev1_name, purc_clas_lev2_code, purc_clas_lev2_name, purc_clas_lev3_code, purc_clas_lev3_name, purc_range, goods_sttu_code, goods_sttu_name, last_purc_date, ask_times, sati_times, ask_qty, sati_qty, sale_qty, sale_amt, sale_cost, gros_prof_amt, stk_qty, avai_qty, stk_amt, latest_ntax_price, latest_tax_price, last_purc_doc, eff_bill_cnt) select stsc_date, stsc_week, stsc_year_mon, stsc_quater, stsc_year, type_code, type_name, site_code, company_code, company_name, goods_code, goods_name, common_name, pron_fact_code, pron_fact_name, mete_unit_code, mete_unit_name, pres_type_code, pres_type_name, dosa_type_code, dosa_type_name, intl_code, trad, norms, sale_tax_clas_code, is_recipe_flag, is_fine_flag, prod_cate_lev1_code, prod_cate_lev1_name, prod_cate_lev2_code, prod_cate_lev2_name, prod_cate_lev3_code, prod_cate_lev3_name, prod_cate_lev4_code, prod_cate_lev4_name, purc_clas_lev1_code, purc_clas_lev1_name, purc_clas_lev2_code, purc_clas_lev2_name, purc_clas_lev3_code, purc_clas_lev3_name, purc_range, goods_sttu_code, goods_sttu_name, last_purc_date, ask_times, sati_times, ask_qty, sati_qty, sale_qty, sale_amt, sale_cost, gros_prof_amt, stk_qty, avai_qty, stk_amt, latest_ntax_price, latest_tax_price, last_purc_doc, eff_bill_cnt from hive.xxx.testc ");
`

**Comment by JNSimba** [comment]
The **DATE** type of doris corresponds to the string in flink. You can modify it to string and try.

**Comment by 1272870698** [comment]
> The **DATE** type of doris corresponds to the string in flink. You can modify it to string and try.
谢谢！用 string 是可以的，但是需要在 sql 中使用 cast(date as string)
