### ISSUE TITLE
left join结果不符合预期

### ISSUE THREAD

**Issue by crazyleeyang** [apache/incubator-doris#5971]
**Describe the bug**
left join时出现非预期结果

**To Reproduce**
**doris表1:sku_doris1**

```sql
CREATE TABLE sku_doris1
(
  sku_id int(11) NOT NULL
) ENGINE=OLAP
DISTRIBUTED BY HASH(sku_id) BUCKETS 1
PROPERTIES(
  "storage_type" = "COLUMN",
  "replication_num" = "1"
);
```

**sku_doris1表插入数据**

```sql
insert into sku_doris1 (sku_id) values (100),(101),(102),(103);
```

**doris表1:sku_doris2**

```sql
CREATE TABLE sku_doris2
(
  sku_id int(11) NOT NULL
) ENGINE=OLAP
DISTRIBUTED BY HASH(sku_id) BUCKETS 1
PROPERTIES(
  "storage_type" = "COLUMN",
  "replication_num" = "1"
);
```

**sku_doris2表插入数据**

```sql
insert into sku_doris2 (sku_id) values (10000),(10001),(10002),(10003);
```

查询语句

```sql
select a.sku_id, c.price from sku_doris1 a left join
(select sku_id, 999 as price from sku_doris2 b)c
on a.sku_id=c.sku_id;
```

**期待的结果为**
|  sku_id   | price  |
|  ----  | ----  |
| 100  | NULL |
| 101  | NULL |
| 102  | NULL |
| 103  | NULL |

**实际的结果为**
|  sku_id   | price  |
|  ----  | ----  |
| 100  | 999 |
| 101  | 999 |
| 102  | 999 |
| 103  | 999 |

**环境信息**
* 版本:Doris version 0.12.21-release

**Comment by HappenLee** [comment]
This is a bug of FE, I will try to fix it, Thank you
