### ISSUE TITLE
doris spark load一直报错,请大神帮忙，非常感谢

### ISSUE THREAD

**Issue by AndyChang521** [apache/incubator-doris#5974]
LOAD LABEL dmp_report.hive2doris
        (
            DATA INFILE("hdfs://zz-bigdata/user/hive/warehouse/apus_dmp_report.db/dmp_active_adduser/dt=2021-06-02/*")
            INTO TABLE dmp_active_adduser format as "parquet" (cid,pkg,channel) set (cid=cid,dt='2021-06-02',pkg=pkg,channel=channel)
        )
        WITH RESOURCE 'spark2doris'("spark.executor.memory" = "3g","broker.username" = "spark2doris","broker.password" = "123456")
        PROPERTIES
        (
            "timeout" = "259000",
            "max_filter_ratio" = "0.1"
        );

spark load一直报以下这个错：
![image](https://user-images.githubusercontent.com/85340665/120776549-f4cf0780-c556-11eb-81bf-dbee27f00b05.png)
哪位大神能解释一下，非常感谢；

**Comment by wangbo** [comment]
看下fe日志有没有什么错误堆栈，这个是作业提交后，由于拿不到appid导致的

**Comment by AndyChang521** [comment]
大佬，方便加个微信或者QQ聊一下哈。

**Comment by AndyChang521** [comment]
> 看下fe日志有没有什么错误堆栈，这个是作业提交后，由于拿不到appid导致的

大佬，方便加个微信或者QQ聊一下哈。非常感谢！

**Comment by wangbo** [comment]
> > 看下fe日志有没有什么错误堆栈，这个是作业提交后，由于拿不到appid导致的
> 
> 大佬，方便加个微信或者QQ聊一下哈。非常感谢！

我在doris开源用户群里的，名字同github id

**Comment by AndyChang521** [comment]
> > > 看下fe日志有没有什么错误堆栈，这个是作业提交后，由于拿不到appid导致的
> > 
> > 
> > 大佬，方便加个微信或者QQ聊一下哈。非常感谢！
> 
> 我在doris开源用户群里的，名字同github id
你方便加一下我qq吗？442419626,我没找到你，不好意思啊。
