### ISSUE TITLE
[Bug] Connect to Fe to add Be node failed.

### ISSUE THREAD

**Issue by tarepanda1024** [apache/incubator-doris#6004]
**Describe the bug**
After I compiled Be And Fe use apache/incubator-doris:build-env-1.2 with doris version 0.14.0.I started Fe  successfully. But  when I connect to Fe use ```mycli -uroot -P 9030``` or Idea DB tools. It thows ```(1064, 'errCode = 2, detailMessage = candidate backends is empty')  . ```

**To Reproduce**
1. compile doris use apache/incubator-doris:build-env-1.2 and https://github.com/apache/incubator-doris/releases/tag/0.14.0 like https://doris.incubator.apache.org/master/zh-CN/installing/compilation.html#%E4%BD%BF%E7%94%A8-docker-%E5%BC%80%E5%8F%91%E9%95%9C%E5%83%8F%E7%BC%96%E8%AF%91%EF%BC%88%E6%8E%A8%E8%8D%90%EF%BC%89
2.  copy output/be output/fe to ~/doris . change fe/conf/fe.conf  ```priority_networks = 10.219.48.0/24```  like https://doris.incubator.apache.org/master/zh-CN/installing/install-deploy.html#%E9%9B%86%E7%BE%A4%E9%83%A8%E7%BD%B2
3. start fe use ```./bin/start_fe.sh --daemon ```
4.  use mycli or idea db tools to connect fe. ``` mycli -uroot -P 9030 -h 10.219.48.248```
5. It thows error.

**Expected behavior**
It can login in to db.

**Screenshots**
![image](https://user-images.githubusercontent.com/23069203/121302030-a4c3bc80-c92b-11eb-95bf-c7a4aace7728.png)
![image](https://user-images.githubusercontent.com/23069203/121302077-b86f2300-c92b-11eb-95d0-0c01a5d966c8.png)
![image](https://user-images.githubusercontent.com/23069203/121303519-c625a800-c92d-11eb-9455-3d467b5140ec.png)

**Desktop (please complete the following information):**
 - OS: deepin
 - Version [20.2.1]

**Comment by tarepanda1024** [comment]
I Know . Only mysql client can connect to the FE . The mycli or Idea db tools will failed.

**Comment by mhyeagle** [comment]
I cannot ping container success, with community's help, I pull a mysql client and connect sucess
https://hub.docker.com/_/mysql
The reason maybe docker network setting, default bridge, but two container is in the same network default, so the mysql container connect 9030 port success

**Comment by anjia0532** [comment]
You need to register the Be to Fe. The error msg `Be is empty`.
