### ISSUE TITLE
Support to alter default bucket_num after create table

### ISSUE THREAD

**Issue by ucasfl** [apache/incubator-doris#6024]
**Is your feature request related to a problem? Please describe.**
When user create a table, since they may not known the data scale at the first, so they may choose a unsuitable bucket num. When add new partition later, they may use new bucket num, if we can change the default bucket num of a table after creation, then user will do not need to specify bucket num exactly when add new partition.

**Describe the solution you'd like**
Add sql statement `alter table t set("default.bucket_num" = "n")` to modify the default bucket num of table t to `n`.

**Describe alternatives you've considered**

**Additional context**

**Comment by EmmyMiao87** [comment]
In fact, when adding partitions, if the user does not specify the number of buckets, Doris will use the number of buckets when creating the table as the number of buckets for the new partition.

So under what circumstances need to specify the default number of buckets?
