### ISSUE TITLE
[BUG] FE startup error, Failed to bind properties under'spring.servlet.multipart.max-file-size'

### ISSUE THREAD

**Issue by xinyiZzz** [apache/incubator-doris#6071]
**Describe the bug**
FE startup error, Failed to bind properties under'spring.servlet.multipart.max-file-size' to org.springframework.uti
l.unit.DataSize.

Failed to convert from type [java.lang.String] to type [org.springframework.util.unit.DataSize] for value '100M'; nested exception is java.lang.IllegalArgumentException: '100M' is not a valid data size

**Comment by stalary** [comment]
LGTM，I had the same problem
