### ISSUE TITLE
[Feature] Support create table as select...

### ISSUE THREAD

**Issue by stalary** [apache/incubator-doris#6101]
**Is your feature request related to a problem? Please describe.**
Support create table as select...，This statement is handy for building ADS tables

**Describe the solution you'd like**
Get select field type to create table, It also presets some default configurations

**Comment by stalary** [comment]
```sql
CREATE TABLE test_select_table
AS SELECT...
[DUPLICATE KEY(xxx)]
[COMMENT 'XXX']
DISTRIBUTED BY HASH(xxx) | RANDOMLY [BUCKETS xx]
[PROPERTIES (xxx)]
```

**Comment by stalary** [comment]
For the time being, only `DUPLICATE KEY` are supported

**Comment by morningman** [comment]
There is no `RANDOMLY` in Doris now. So we can just keep consistency with the `CREATE TABLE` syntax to only support `DISTRIBUTED BY HASH`

**Comment by stalary** [comment]
> There is no `RANDOMLY` in Doris now. So we can just keep consistency with the `CREATE TABLE` syntax to only support `DISTRIBUTED BY HASH`

ok

**Comment by stalary** [comment]
I want to use this syntax to achieve into SQL automatic table build，but `DISTRIBUTED BY HASH` need to manually set

**Comment by stalary** [comment]
I'm going to check if distributionDesc is null use first column
