### ISSUE TITLE
[Feature] Support configuring blocklist by user level to deny the specified SQL

### ISSUE THREAD

**Issue by stalary** [apache/incubator-doris#6103]
**Is your feature request related to a problem? Please describe.**
Sometimes different users have different query permissions, for example, some user can use join, and others can't，and count(*) not limit it's the same thing

**Describe the solution you'd like**
1. use fe.conf or admin set frontend config
2. support show blacklists and restful api

**Comment by stalary** [comment]
I will support this feature soon

**Comment by stalary** [comment]
ruleId | user | rule

**Comment by stalary** [comment]
## Design Doc
Rules are stored using sqlblockList, stored in metadata, and managed in catalog，Rules are divided by user, with support for configuring the defalut user, which represents the default rule

Enable way
- use enable_sql_blocklist，@ConfField(mutable = true, masterOnly = true)
- admin set frontend config ("enable_sql_blocklist" = "true")

Sqlblocklist info
- name
- user
- sql
- enable

Supoort grammar
- SHOW BLOCKLIST [WHERE name|sql|user|enable = "xxx"]
- CREATE BLOCKLIST test_rule PROPERTIES ("user"="default", "sql"="select .* from .* join .*", "enable": "true")
- ALTER BLOCKLIST test_rule PROPERTIES ("user"="test_user", "enable": "false")
- DROP BLOCKLIST (test_rule|test_rule1,test_rule2)

Interception point
- StmtExecutor.execute -> QueryStmt -> regex match -> deny

**Comment by morningman** [comment]
LGTM, the keyword can be `SQL_BLOCK_RULE`?

**Comment by stalary** [comment]
> LGTM, the keyword can be `SQL_BLOCK_RULE`?

Okay, no problem.
