### ISSUE TITLE
routine load  kafka property 未生效

### ISSUE THREAD

**Issue by wenbaoup** [apache/incubator-doris#6138]
**Describe the bug**
routine load  kafka property  "property.isolation.level"="read_committed" 无效
**To Reproduce**

**Expected behavior**
希望只读kafak中commit的数据

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by stalary** [comment]
let me see see

**Comment by morningman** [comment]
The version of the librdkafka we currently used does not support this property...

**Comment by stalary** [comment]
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#broker-version--01000-or-trunk
It looks like we are also forward compatible after we upgrade to 1.0
`isolation.level`  is generally used to exactly once in stream processing.
https://github.com/edenhill/librdkafka/releases/tag/v1.2.0 we need upgrade v1.2.0 support consumer transaction

**Comment by WindyGao** [comment]
@morningman @stalary 
it's related with [issue-3682](https://github.com/apache/incubator-doris/issues/3682) and [issue-5485](https://github.com/apache/incubator-doris/issues/5485)
after some research, the rdKafka client cames to the following conclusions

- Idempotent Producer - supported in librdkafka v1.0.0 ✅
- Producer transactions - supported in v1.4.0 ✅
- Consumer transactions - supported in v1.2.0 ✅

that said, it's theoretically possible to upgrade doris's rdKafka client to v1.4 or higher
I will be testing against v1.4~v1.6 of the rdKafka client for routine load job

**Comment by WindyGao** [comment]
v1.2

> @morningman
> https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#compatibility
> It looks like we are also forward compatible after we upgrade to 1.0
> `isolation.level` is generally used to exactly once in stream processing.
> https://github.com/edenhill/librdkafka/releases/tag/v1.2.0 we need upgrade v1.2.0 support consumer transaction

yeah v1.2 is enough actually
