### ISSUE TITLE
[Bugfix]HTTP v2 version stream load importing large data files will cause connection reset problems

### ISSUE THREAD

**Issue by hf200012** [apache/incubator-doris#6148]
For the http v2 version of stream load, the problem of connection reset will occur when importing large data files. After investigation, it is confirmed that it is the problem of the content tomcat container's implementation of 307 temporary redirection.
solution:
Switch the built-in web container of http v2 SpringBoot to jetty. After testing, this problem can be solved well.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sjahongir** [comment]
`curl --location-trusted -u root -T _data.csv  -H "label:20" -H "format:csv_with_names" -H "Expect:100-continue" -H "column_separator:," http://192.168.88.13:8030/api/test_db/test_streamload/_stream_load`

This curl works in cmd, postman and go app but not works in C#, node, python.
The error: [NOT_AUTHORIZED]no valid Basic authorization
