### ISSUE TITLE
Failed to download package DataTables.zip

### ISSUE THREAD

**Issue by IVitamin-C** [apache/incubator-doris#6185]
version 0.14.0
download DataTables.zip
https://datatables.net/download/builder?bs-3.3.7/jq-3.3.1/dt-1.10.23

Error: Only libraries of the current release version can be used by the. package builder. The library DataTables's current release version is 1.10.25. Please reload the download builder page to have it use the latest libraries.

**Comment by stdpain** [comment]
modify $DORIS_HOME/thridparty/vars.sh

DATATABLES_DOWNLOAD="https://datatables.net/download/builder?bs-3.3.7/jq-3.3.1/dt-1.10.25"
DATATABLES_NAME="DataTables.zip"
DATATABLES_SOURCE="DataTables-1.10.25"
DATATABLES_MD5SUM="109ce4359b370565f968932607460624"

**Comment by IVitamin-C** [comment]
DATATABLES_MD5SUM=c8fd73997c9871e213ee4211847deed5

**Comment by IVitamin-C** [comment]
https://github.com/aws/s2n-tls/archive/v0.10.0.tar.gz
 /data/doris-source/incubator-doris-0.14.0/thirdparty/src/s2n-0.10.0.tar.gz md5sum check failed!
except-md5 9b3b39803b7090c2bd937f9cc73bc03f 
actual-md5 345aa5d2f9e82347bb3e568c22104d0e  /data/doris-source/incubator-doris-0.14.0/thirdparty/src/s2n-0.10.0.tar.gz

**Comment by morningman** [comment]
I decide to move this dependency to our own http server.
