### ISSUE TITLE
Fail to start BE

### ISSUE THREAD

**Issue by lijinwang-web** [apache/incubator-doris#6251]
./start_be.sh: line 119: 27813 Illegal instruction     $LIMIT ${DORIS_HOME}/lib/palo_be "$@" >> $LOG_DIR/be.out 2>&1 < /dev/null
be.out has no any messages.

**Comment by stdpain** [comment]
try to use 
```
bash ./be/bin/start_be.sh
```

**Comment by lijinwang-web** [comment]
> try to use
> 
> ```
> bash ./be/bin/start_be.sh
> ```

it not works

**Comment by lijinwang-web** [comment]
I started 3 be,the other 2 success and this one failed. what is "Illegal instruction"

**Comment by stdpain** [comment]
try to use this
```
cat /proc/cpuinfo|grep avx2
```

may be your machine not support avx2 instruction

please provide your doris version

**Comment by lijinwang-web** [comment]
> try to use this
> 
> ```
> cat /proc/cpuinfo|grep avx2
> ```
> 
> may be your machine not support avx2 instruction
> 
> please provide your doris version

you are right!  I use another machine and success.Thank you very much!!!
