### ISSUE TITLE
为什么需要自己编译，而不是直接提供可以下载二进制包呢？

### ISSUE THREAD

**Issue by xiaozhiliaoo** [apache/incubator-doris#6259]
**Describe the bug**
为什么需要自己编译，而不是直接提供可以下载二进制包呢？

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hf200012** [comment]
http://palo.baidu.com/docs/%E4%B8%8B%E8%BD%BD%E4%B8%93%E5%8C%BA/%E9%A2%84%E7%BC%96%E8%AF%91%E7%89%88%E6%9C%AC%E4%B8%8B%E8%BD%BD/

**Comment by xiaozhiliaoo** [comment]
谢谢~

**Comment by xiaozhiliaoo** [comment]
已找到。
