### ISSUE TITLE
[Proposal] Support large variable-length string type

### ISSUE THREAD

**Issue by yangzhg** [apache/incubator-doris#6276]
## Background

There are currently two types of strings: CHAR and VARCHAR. Char stores fixed-length strings and VARCHAR stores variable-length strings. The maximum length of VARCHAR is 65533. This length can meet most demand scenarios, but for some scenarios. In the scenario of storing larger strings in doris, it is not enough, so we need to add a new data type String. String can correspond to blob or text storage in mysql. The maximum length is 2GB, but we still don't recommend it. Store more than 64K strings in DORIS

## Other system implementation

* MYSQL: Mysql uses blob or TEXT as the storage type for very long strings. MySQL can perform string operations on these types, but performance is not guaranteed. In actual storage, the data will be stored in the overflow page. And according to the version and storage engine in the data page, the first n characters will be stored for indexing
* parquet/ORC: These two pairs and large strings are directly stored in the data area, and there is no special processing and only dictionary encoding

## Design

* Added the String type, which represents a string of any length. In order to be compatible with mysql, the maximum length is set to 2G-4, and 4 bytes are used to store the length of the string
* The data storage is similar to the varchar type, the previous length identifier is changed to 4 bytes
* Indexes are not currently supported, and zonemap indexes will be enabled after the zonemap length limit is ready.

**Comment by HappenLee** [comment]
We should suppot limit zonemap index.

In the current scenario of doris, excessively long zonemap indexes do not contribute significantly to query improvement, but rather consume a lot of additional memory and storage resources. So it is wise to limit the length of zonemap for large types of objects and long strings

For example, postgresql's Brin index, by default, records 128 rows of data once. The current Doris default page size is 64k, so a reasonable zonemap index length should be about 512byte.
