### ISSUE TITLE
flink-doris-connector  若有空字段，则会报错

### ISSUE THREAD

**Issue by yangmingjie2018** [apache/incubator-doris#6431]
各位大神请教个问题：

1）源是mysql-cdc，字段A可空，实际也是null  
2）目标是doris，字段X可空 
3）使用flink-doris-connector的时候报错如下：  

![企业微信截图_16287580616849](https://user-images.githubusercontent.com/46737906/129168181-046da51f-9b45-458b-8fdc-51f0e433e3c8.png)

![企业微信截图_16287581027150](https://user-images.githubusercontent.com/46737906/129168207-195fd693-d7cf-4b54-b933-abe09a72a2ef.png)

![企业微信截图_16287581393925](https://user-images.githubusercontent.com/46737906/129168218-9652ba08-b99c-4a07-b8e7-9c8a7af77fcf.png)

**Comment by JNSimba** [comment]
#6165
resolved,  need upgrade jar
