### ISSUE TITLE
Query error with union all containing join predicate

### ISSUE THREAD

**Issue by morningman** [apache/incubator-doris#645]
create table t1 (k1 int) distributed by hash (k1) buckets 1;
insert into k1[streaming] select 1;
create view v2 as (select t1.k1 from t1 left outer join t1 as t11 on t1.k1 = t11.k1);
select count(*) from (select 1 as nn from v2 union all select 2 as nn from v2) a where 1=2;

Expected:
0
Actual:
1

the where predicate doesn't work

**Comment by EmmyMiao87** [comment]
please change title to "Query error with union all containing join predicate "

**Comment by EmmyMiao87** [comment]
Query error : select 1 from t1, t1 as t11 where t1.k1=t11.k1 union all select 2 from t1 where 1=2; The predicate 1=2 does not belong to any tuple. It is allocated to the first stmt when it has a join predicate.

**Comment by EmmyMiao87** [comment]
[https://github.com/apache/incubator-doris/pull/657](url) This commit fix this bug
