### ISSUE TITLE
[Bug] incorrect value in bitmap when spark load with multi-rollup

### ISSUE THREAD

**Issue by spaces-X** [apache/incubator-doris#6452]
Multi-rollups may hold the same  Ref of bitmap_value object in spark load etl job, which will cause the bitmap to be updated repeatedly.
``` 
  // In-place bitwise OR (union) operation. The current bitmap is modified.
    public void or(BitmapValue other) {
        switch (other.bitmapType) {
            case EMPTY:
                break;
            case SINGLE_VALUE:
                add(other.singleValue);
                break;
            case BITMAP_VALUE:
                switch (this.bitmapType) {
                    case EMPTY:
                        this.bitmap = other.bitmap;    // here just shallow copy 
                        this.bitmapType = BITMAP_VALUE;
                        break;
                    case SINGLE_VALUE:
                        this.bitmap = other.bitmap;
                        this.bitmap.add(this.singleValue);
                        this.bitmapType = BITMAP_VALUE;
                        break;
                    case BITMAP_VALUE:
                        this.bitmap.or(other.bitmap);
                        break;
                }
                break;
        }
    }
```

For example, the baseIndex and Rollups are as follows.
- baseIndex
   - R1
   - R2
   - R3

In this situation, R1 will be calculated based on baseIndex and meanwhile unfortunately bitmap value object holded by baseIndex may be updated by R1.  Then the result of R2 , which is calculated based on baseIndex, will be incorrect because the base index has been modified by R1.

To avoid the above situation, it is supposed to do a deep copy of bitmap value object in the operator  `or` function.

**Comment by wangbo** [comment]
Please add some ut for the ```multi-rollups``` case.
You can add it to ```BitmapValueTest```
