### ISSUE TITLE
Build failed in centos

### ISSUE THREAD

**Issue by crazy2323** [apache/incubator-doris#6530]
[ 94%] Running C++ protocol buffer compiler on view.proto
/bin/sh: --cpp_out: command not found
make[2]: *** [tools/rpc_view/CMakeFiles/rpc_view.dir/build.make:62: tools/rpc_view/view.pb.cc] Error 127
make[1]: *** [CMakeFiles/Makefile2:532: tools/rpc_view/CMakeFiles/rpc_view.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target parallel_http
Scanning dependencies of target trackme_server
Scanning dependencies of target rpc_replay
Scanning dependencies of target rpc_press
......
......
/opt/apache-doris-0.14.0-incubating-src/thirdparty/src/incubator-brpc-0.9.5/src/bvar/recorder.h:31:8: note: ‘struct bvar::Stat’ declared here
   31 | struct Stat {
      |        ^~~~
[ 95%] Linking CXX executable ../../output/bin/parallel_http
[ 96%] Linking CXX executable ../../output/bin/trackme_server
[ 97%] Linking CXX executable ../../output/bin/rpc_replay
[ 98%] Linking CXX executable ../../output/bin/rpc_press
[ 98%] Built target parallel_http
[ 98%] Built target trackme_server
[ 98%] Built target rpc_replay
[ 98%] Built target rpc_press
make: *** [Makefile:128: all] Error 2

**Comment by yangzhg** [comment]
you shoud post all more build log

**Comment by crazy2323** [comment]
upgrade gcc version

**Comment by bluemasion** [comment]
hi ,I met the same issue  ,and also updated the gcc to version 8,but still got the issue, cloud give me some advise to solve it ?

**Comment by bluemasion** [comment]
> upgrade gcc version

hi ,I met the same issue ,and also updated the gcc to version 8,but still got the issue, cloud give me some advise to solve it ?

**Comment by crazy2323** [comment]
> 

use docker build
