### ISSUE TITLE
doris-flink-connecter数据换行配置不起作用

### ISSUE THREAD

**Issue by yangmingjie** [apache/incubator-doris#6550]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.0.0

### What's Wrong?

在使用doris-connector的时候，数据导入到doris一部分的试试报错：
![image](https://user-images.githubusercontent.com/5827183/130569914-51f90209-1f28-44a4-a2f2-7cd1c4d1ce94.png)

最后发现问题如下：

mysql数据库中有个字段mateName是varchar（255），如下：
![image](https://user-images.githubusercontent.com/5827183/130567216-94860c88-8c43-41b3-8de9-bc1b0a7204f5.png)
拷贝出来后内容，有换行：
![image](https://user-images.githubusercontent.com/5827183/130567284-6fc3d660-34e3-4b2a-9353-433b7b60081b.png)

然后，

![image](https://user-images.githubusercontent.com/5827183/131081684-4a9130f1-b33f-4ddd-9d88-acd450a953be.png)

但是 还是报一次样的错误。

### What You Expected?

希望设置换行符 sink.properties.line_delimiter 和 sink.properties.column_separator 能起作用。或者其他解决这个问题的办法。

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JNSimba** [comment]
#6497

**Comment by mincwang** [comment]
@JNSimba  Has this problem been solved?

**Comment by JNSimba** [comment]
> @JNSimba Has this problem been solved?
Specify the newline character to set the 
     sink.properties.line_delimiter   parameters

**Comment by mincwang** [comment]
doris ddl：
```sql
CREATE TABLE `product` (
  `id` int(11) NULL COMMENT "",
...
  `gmt_modified` datetime NULL COMMENT "",
  `gmt_create` datetime NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`id`, `id_hash`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`id`) BUCKETS 10
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"storage_format" = "V2"
);

```


flink sql doris-sink ddl：

```sql
CREATE TABLE product (
 id INT,
...
 gmt_modified TIMESTAMP(6),
 gmt_create TIMESTAMP(6) ) 
WITH (  
 'connector' = 'doris', 
 'fenodes' = 'n3:8031', 
  'table.identifier' = 'dev.product',  
  'username' = 'root',
  'sink.batch.size' = '100',
  'sink.properties.column_separator' = '\x01',
  'sink.properties.line_delimiter' = '\x02',
  'sink.batch.interval' = '2s' , 
  'password' = 'doris'
);
```
```sql
# flink insert sql
insert into product 
select * from product_cdc_table ;
```

When we write data to dorsi by flink streaming, have following error occurs.


```bash
Reason: Parse json data for JsonDoc failed. code = 2, error-info:The document root must not be followed by other values.. 
```

**Comment by mincwang** [comment]
> @JNSimba thanks for your reply. here is my code, and some errors.
> doris ddl：
> 
> ```sql
> CREATE TABLE `product` (
>   `id` int(11) NULL COMMENT "",
> ...
>   `gmt_modified` datetime NULL COMMENT "",
>   `gmt_create` datetime NULL COMMENT ""
> ) ENGINE=OLAP
> DUPLICATE KEY(`id`, `id_hash`)
> COMMENT "OLAP"
> DISTRIBUTED BY HASH(`id`) BUCKETS 10
> PROPERTIES (
> "replication_num" = "3",
> "in_memory" = "false",
> "storage_format" = "V2"
> );
> ```
> 
> flink sql doris-sink ddl：
> 
> ```sql
> CREATE TABLE product (
>  id INT,
> ...
>  gmt_modified TIMESTAMP(6),
>  gmt_create TIMESTAMP(6) ) 
> WITH (  
>  'connector' = 'doris', 
>  'fenodes' = 'n3:8031', 
>   'table.identifier' = 'dev.product',  
>   'username' = 'root',
>   'sink.batch.size' = '100',
>   'sink.properties.column_separator' = '\x01',
>   'sink.properties.line_delimiter' = '\x02',
>   'sink.batch.interval' = '2s' , 
>   'password' = 'doris'
> );
> ```
> 
> ```sql
> # flink insert sql
> insert into product 
> select * from product_cdc_table ;
> ```
> 
> When we write data to dorsi by flink streaming, have following error occurs.
> ![image](https://user-images.githubusercontent.com/33626973/133186128-5f0e2aeb-7660-4df2-8f52-7844b6ffd05d.png)

doris version: 0.14
flink-doris-connector version : master
flink version ： 1.12.2

**Comment by yangmingjie** [comment]
> > @JNSimba Has this problem been solved?
> 
> Specify the newline character to set the
> sink.properties.line_delimiter parameters

我这里试了还是不行，最近一忙就没顾上  @mincwang

**Comment by JNSimba** [comment]
> > > @JNSimba Has this problem been solved?
> > 
> > 
> > Specify the newline character to set the
> > sink.properties.line_delimiter parameters
> 
> 我这里试了还是不行，最近一忙就没顾上 @mincwang

@yangmingjie your param line_delimiter(%%%%)  and column_separator(%%%%) has the same prefix value, may cause doris to be indistinguishable，modify them to a different prefix and it works

**Comment by mincwang** [comment]
> > @JNSimba thanks for your reply. here is my code, and some errors.
> > doris ddl：
> > ```sql
> > CREATE TABLE `product` (
> >   `id` int(11) NULL COMMENT "",
> > ...
> >   `gmt_modified` datetime NULL COMMENT "",
> >   `gmt_create` datetime NULL COMMENT ""
> > ) ENGINE=OLAP
> > DUPLICATE KEY(`id`, `id_hash`)
> > COMMENT "OLAP"
> > DISTRIBUTED BY HASH(`id`) BUCKETS 10
> > PROPERTIES (
> > "replication_num" = "3",
> > "in_memory" = "false",
> > "storage_format" = "V2"
> > );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > flink sql doris-sink ddl：
> > ```sql
> > CREATE TABLE product (
> >  id INT,
> > ...
> >  gmt_modified TIMESTAMP(6),
> >  gmt_create TIMESTAMP(6) ) 
> > WITH (  
> >  'connector' = 'doris', 
> >  'fenodes' = 'n3:8031', 
> >   'table.identifier' = 'dev.product',  
> >   'username' = 'root',
> >   'sink.batch.size' = '100',
> >   'sink.properties.column_separator' = '\x01',
> >   'sink.properties.line_delimiter' = '\x02',
> >   'sink.batch.interval' = '2s' , 
> >   'password' = 'doris'
> > );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```sql
> > # flink insert sql
> > insert into product 
> > select * from product_cdc_table ;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When we write data to dorsi by flink streaming, have following error occurs.
> > ![image](https://user-images.githubusercontent.com/33626973/133186128-5f0e2aeb-7660-4df2-8f52-7844b6ffd05d.png)
> 
> doris version: 0.14
> flink-doris-connector version : master
> flink version ： 1.12.2
> 
> When we repalce `column_separator=%x01 ` and `line_delimiter=%x02`, have other error occurs :
> 
> ```shell
> Reason: actual column number is more than schema column number. actual number: 1900 sep: %, schema number: 19; . src line: [689%x018a7c7089faaf00c850b90154e74fb821%x01101787%x0111%x010%x010%x010%x01%x01%x01QARFEE 
> ```
> 
> We check barch-0.14 and master, look the commit message `[Load] Support multi bytes LineDelimiter and ColumnSeparator` (#5462) in `broker_scanner.cpp`, so we are going to verify it.

@JNSimba Can this PR fix the above problems? please help to confirm.

**Comment by JNSimba** [comment]
@mincwang it is work to change to other characters，hexadecimal may be has problem

**Comment by mincwang** [comment]
> @mincwang it is work to change to other characters，hexadecimal may be has problem

What do you recommend for `column_separator` and `line_delimiter ` set ?

**Comment by JNSimba** [comment]
> > @mincwang it is work to change to other characters，hexadecimal may be has problem
> 
> What do you recommend set for `column_separator` and `line_delimiter` ?

It can be set as a character that does not appear frequently according to the specific business, or it can be set as a combination of multiple characters

**Comment by mincwang** [comment]
> > > @mincwang it is work to change to other characters，hexadecimal may be has problem
> > 
> > 
> > What do you recommend set for `column_separator` and `line_delimiter` ?
> 
> It can be set as a character that does not appear frequently according to the specific business, or it can be set as a combination of multiple characters

But we doris version is 0.14，only master version support of  multiple characters ，fix above problem by this PR #5462.

**Comment by JNSimba** [comment]
> > > > @mincwang it is work to change to other characters，hexadecimal may be has problem
> > > 
> > > 
> > > What do you recommend set for `column_separator` and `line_delimiter` ?
> > 
> > 
> > It can be set as a character that does not appear frequently according to the specific business, or it can be set as a combination of multiple characters
> 
> But we doris version is 0.14，only master version support of multiple characters ，fix above problem by this PR #5462.

Sorry, I may not make it clear, I mean it can be specified as multiple letters, like **column_separator=doris**

**Comment by yangmingjie** [comment]
> > > > @JNSimba Has this problem been solved?
> > > 
> > > 
> > > Specify the newline character to set the
> > > sink.properties.line_delimiter parameters
> > 
> > 
> > 我这里试了还是不行，最近一忙就没顾上 @mincwang
> 
> @yangmingjie your param line_delimiter(%%%%) and column_separator(%%%%) has the same prefix value, may cause doris to be indistinguishable，modify them to a different prefix and it works

还是不行，是不是我用的不对？
![企业微信截图_16317736024312](https://user-images.githubusercontent.com/5827183/133560942-aafd96ca-39dd-4f89-a59c-2429677ed257.png)  
目标脚本如下：
![企业微信截图_16317724243359](https://user-images.githubusercontent.com/5827183/133560973-c6dd6a17-fc02-43fc-bfc2-caa3811213ed.png)
另外，换成单个字符，也还是不行，例如：
'sink.properties.line_delimiter'='#',
'sink.properties.column_separator'='*'
也是一样的问题。

**Comment by yangmingjie** [comment]
我们用的是master分支最新代码打包出来的connector

**Comment by JNSimba** [comment]
> > > > > @JNSimba Has this problem been solved?
> > > > 
> > > > 
> > > > Specify the newline character to set the
> > > > sink.properties.line_delimiter parameters
> > > 
> > > 
> > > 我这里试了还是不行，最近一忙就没顾上 @mincwang
> > 
> > 
> > @yangmingjie your param line_delimiter(%%%%) and column_separator(%%%%) has the same prefix value, may cause doris to be indistinguishable，modify them to a different prefix and it works
> 
> 还是不行，是不是我用的不对？
> 目标脚本如下：
> ![企业微信截图_16317736024312](https://user-images.githubusercontent.com/5827183/133560942-aafd96ca-39dd-4f89-a59c-2429677ed257.png)
> 错误：
> ![企业微信截图_16317724243359](https://user-images.githubusercontent.com/5827183/133560973-c6dd6a17-fc02-43fc-bfc2-caa3811213ed.png)
> 另外，换成单个字符，也还是不行，例如：
> 'sink.properties.line_delimiter'='#',
> 'sink.properties.column_separator'='*'
> 也是一样的问题。

 may not the problem of the separator. It is recommended to see if the sql  fields  are consistent with the fields in the doris table.

**Comment by mincwang** [comment]
> > > > > > @JNSimba Has this problem been solved?
> > > > > 
> > > > > 
> > > > > Specify the newline character to set the
> > > > > sink.properties.line_delimiter parameters
> > > > 
> > > > 
> > > > 我这里试了还是不行，最近一忙就没顾上 @mincwang
> > > 
> > > 
> > > @yangmingjie your param line_delimiter(%%%%) and column_separator(%%%%) has the same prefix value, may cause doris to be indistinguishable，modify them to a different prefix and it works
> > 
> > 
> > 还是不行，是不是我用的不对？
> > 目标脚本如下：
> > ![企业微信截图_16317736024312](https://user-images.githubusercontent.com/5827183/133560942-aafd96ca-39dd-4f89-a59c-2429677ed257.png)
> > 错误：
> > ![企业微信截图_16317724243359](https://user-images.githubusercontent.com/5827183/133560973-c6dd6a17-fc02-43fc-bfc2-caa3811213ed.png)
> > 另外，换成单个字符，也还是不行，例如：
> > 'sink.properties.line_delimiter'='#',
> > 'sink.properties.column_separator'='*'
> > 也是一样的问题。
> 
> may not the problem of the separator. It is recommended to see if the sql fields are consistent with the fields in the doris table.

@JNSimba Can you add a JSON import way? i think will have not these  problems.

**Comment by JNSimba** [comment]
> > > > > > > @JNSimba Has this problem been solved?
> > > > > > 
> > > > > > 
> > > > > > Specify the newline character to set the
> > > > > > sink.properties.line_delimiter parameters
> > > > > 
> > > > > 
> > > > > 我这里试了还是不行，最近一忙就没顾上 @mincwang
> > > > 
> > > > 
> > > > @yangmingjie your param line_delimiter(%%%%) and column_separator(%%%%) has the same prefix value, may cause doris to be indistinguishable，modify them to a different prefix and it works
> > > 
> > > 
> > > 还是不行，是不是我用的不对？
> > > 目标脚本如下：
> > > ![企业微信截图_16317736024312](https://user-images.githubusercontent.com/5827183/133560942-aafd96ca-39dd-4f89-a59c-2429677ed257.png)
> > > 错误：
> > > ![企业微信截图_16317724243359](https://user-images.githubusercontent.com/5827183/133560973-c6dd6a17-fc02-43fc-bfc2-caa3811213ed.png)
> > > 另外，换成单个字符，也还是不行，例如：
> > > 'sink.properties.line_delimiter'='#',
> > > 'sink.properties.column_separator'='*'
> > > 也是一样的问题。
> > 
> > 
> > may not the problem of the separator. It is recommended to see if the sql fields are consistent with the fields in the doris table.
> 
> @JNSimba Can you add a JSON import way? i think will have not these problems.

@mincwang  Good idea, will be put on PR as soon as possible

**Comment by mincwang** [comment]
> > > > > > > > @JNSimba Has this problem been solved?
> > > > > > > 
> > > > > > > 
> > > > > > > Specify the newline character to set the
> > > > > > > sink.properties.line_delimiter parameters
> > > > > > 
> > > > > > 
> > > > > > 我这里试了还是不行，最近一忙就没顾上 @mincwang
> > > > > 
> > > > > 
> > > > > @yangmingjie your param line_delimiter(%%%%) and column_separator(%%%%) has the same prefix value, may cause doris to be indistinguishable，modify them to a different prefix and it works
> > > > 
> > > > 
> > > > 还是不行，是不是我用的不对？
> > > > 目标脚本如下：
> > > > ![企业微信截图_16317736024312](https://user-images.githubusercontent.com/5827183/133560942-aafd96ca-39dd-4f89-a59c-2429677ed257.png)
> > > > 错误：
> > > > ![企业微信截图_16317724243359](https://user-images.githubusercontent.com/5827183/133560973-c6dd6a17-fc02-43fc-bfc2-caa3811213ed.png)
> > > > 另外，换成单个字符，也还是不行，例如：
> > > > 'sink.properties.line_delimiter'='#',
> > > > 'sink.properties.column_separator'='*'
> > > > 也是一样的问题。
> > > 
> > > 
> > > may not the problem of the separator. It is recommended to see if the sql fields are consistent with the fields in the doris table.
> > 
> > 
> > @JNSimba Can you add a JSON import way? i think will have not these problems.
> 
> @mincwang Good idea, will be put on PR as soon as possible

@JNSimba I look forward to your contribution, i hope it can support rowkind convert to  a hidden column `__DELETE_SIGN__`  when use Doris unique model. https://doris.apache.org/master/en/administrator-guide/load-data/batch-delete-manual.html#principle

<!DOCTYPE html><figure class="md-table-fig md-focus" cid="n2" mdtype="table" style="box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; caret-color: rgb(184, 191, 198); color: rgb(184, 191, 198); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: rgb(54, 59, 64); text-decoration: none;">

RowKind | __DELETE_SIGN__
-- | --
+I | false
+U | false
-D | true

</figure>

**Comment by mincwang** [comment]
![image](https://user-images.githubusercontent.com/33626973/133745308-dae48a85-25ae-4973-919f-6f6539bcb6f5.png)

@JNSimba You can re test my this UT?


```
public static void main(String[] args) {
        final StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
        env.setParallelism(1);
        final StreamTableEnvironment tEnv = StreamTableEnvironment.create(env);

        List<Tuple2<String, Integer>> data = new ArrayList<>();
        data.add(new Tuple2<>("doris", 1));
        data.add(new Tuple2<>("flink", 2));
        DataStreamSource<Tuple2<String, Integer>> source = env.fromCollection(data);
        tEnv.createTemporaryView("doris_test", source, $("name"), $("age"));

        tEnv.executeSql(
                "CREATE TABLE doris_test_sink ("
                        + "name STRING,"
                        + "age INT"
                        + ") "
                        + "WITH (\n"
                        + "  'connector' = 'doris',\n"
                        + "  'fenodes' = 'n3:8031',\n"
                        + "  'table.identifier' = 'erp_dev.student_unique',\n"
                        + "  'sink.properties.column_separator' ='\\t',\n" 
                        + "  'sink.properties.line_delimiter' = '\\n',\n"
                        + "  'username' = 'root',\n"
                        + "  'password' = 'doris'\n"
                        + ")");

        tEnv.executeSql("INSERT INTO doris_test_sink select name,age from doris_test");
    }
```
dorsi be version : 0.14

**Comment by mincwang** [comment]
My guess this is when  `DorisStreamLoad#getConnection` method body execute `conn.addRequestProperty(streamLoadProp)`，error when carrying these request parameters  requesting BE because be 0.14 does not support multi-character delimiters.

**Comment by JNSimba** [comment]
> ![image](https://user-images.githubusercontent.com/33626973/133745308-dae48a85-25ae-4973-919f-6f6539bcb6f5.png)
> 
> @JNSimba You can re test my this UT?
> 
> ```
> public static void main(String[] args) {
>         final StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
>         env.setParallelism(1);
>         final StreamTableEnvironment tEnv = StreamTableEnvironment.create(env);
> 
>         List<Tuple2<String, Integer>> data = new ArrayList<>();
>         data.add(new Tuple2<>("doris", 1));
>         data.add(new Tuple2<>("flink", 2));
>         DataStreamSource<Tuple2<String, Integer>> source = env.fromCollection(data);
>         tEnv.createTemporaryView("doris_test", source, $("name"), $("age"));
> 
>         tEnv.executeSql(
>                 "CREATE TABLE doris_test_sink ("
>                         + "name STRING,"
>                         + "age INT"
>                         + ") "
>                         + "WITH (\n"
>                         + "  'connector' = 'doris',\n"
>                         + "  'fenodes' = 'n3:8031',\n"
>                         + "  'table.identifier' = 'erp_dev.student_unique',\n"
>                         + "  'sink.properties.column_separator' ='\\t',\n" 
>                         + "  'sink.properties.line_delimiter' = '\\n',\n"
>                         + "  'username' = 'root',\n"
>                         + "  'password' = 'doris'\n"
>                         + ")");
> 
>         tEnv.executeSql("INSERT INTO doris_test_sink select name,age from doris_test");
>     }
> ```
> 
> dorsi be version : 0.14

It is work for me on version 0.14.12

**Comment by JNSimba** [comment]
> My guess this is when `DorisStreamLoad#getConnection` method body execute `conn.addRequestProperty(streamLoadProp)`，error when carrying these request parameters requesting BE because be 0.14 does not support multi-character delimiters.
> 
> [Load] Support multi bytes LineDelimiter and ColumnSeparator #5462

@mincwang 
Yes, the above example will fail.
Since the specified separator is \\t, sink-format uses \\t when splicing data, but when sending a streamload http request, the separator \\t in the request header is recognized as an escape character \t , The two are not equal, so it cannot be imported.
And \t 、 \n are the default separators, you don’t need to specify them

**Comment by JNSimba** [comment]
@mincwang Currently the separator is set to \t, HttpURLConnection.checkMessageHeader will report an error: IllegalArgumentException: Illegal character(s) in message header value
I tried to modify the request to HttpClient to avoid this error, and I will modify it as soon as possible.

**Comment by mincwang** [comment]
@JNSimba Looking forward to your fix, and how do I check my version of doris?

**Comment by JNSimba** [comment]
> @JNSimba Looking forward to your fix, and how do I check my version of doris?

what mean check the doris version  ？
