### ISSUE TITLE
[Bug] pad function wrong result when `len.val==str_char_size`

### ISSUE THREAD

**Issue by BiteTheDDDDt** [apache/incubator-doris#6563]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

Pad function get wrong result when input string have chinese charactor and input string length euqal to second param.
for example:
```sql
SELECT RPAD(‘你',1,'123');
```

### What You Expected?

fix this bug at lpad and rpad 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zbtzbtzbt** [comment]
you can see [vec-pr143](https://github.com/doris-vectorized/doris-vectorized/pull/143)
and i created a similar issue , [issue-6562](https://github.com/apache/incubator-doris/issues/6562)

**Comment by BiteTheDDDDt** [comment]
> 
> 
> you can see [vec-pr143](https://github.com/doris-vectorized/doris-vectorized/pull/143)
> and i created a similar issue , [issue-6562](https://github.com/apache/incubator-doris/issues/6562)

@zbtzbtzbt 
The problem mentioned in #6562 has been fixed by #6564.
