### ISSUE TITLE
[Bug] 文档中的连接失效

### ISSUE THREAD

**Issue by li-keguo** [apache/incubator-doris#6565]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

incubator-doris/docs/zh-CN/downloads/downloads.md
![image](https://user-images.githubusercontent.com/33576070/131946974-eba73e4f-04b2-4bde-b7fb-119891dfad68.png)

跳转到：
https://github.com/apache/incubator-doris/blob/master/docs/zh-CN/installing/install-deploy.html

![image](https://user-images.githubusercontent.com/33576070/131946996-9b553734-0467-4d39-9b9d-5ab31235897f.png)

### What You Expected?

https://github.com/apache/incubator-doris/blob/master/docs/zh-CN/installing/install-deploy.md

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by qidaye** [comment]
The reason why the document link does not work is because it ends in `html`, rather not `md`.
If you are interested, you can submit a pull request to fix it, note that you need to fix both Chinese and English documents.

Welcom to contribute :D

**Comment by li-keguo** [comment]
yes

**Comment by qidaye** [comment]
Thanks for your contribution~
