### ISSUE TITLE
[Feature] Support query hive table 

### ISSUE THREAD

**Issue by qidaye** [apache/incubator-doris#6568]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Currently, Hive external tables are only used by Spark Load, and queries are not supported.

Many users have the need to query the Hive table, and it is too cumbersome to import the data into Doris and then perform the query operation.

### Use case

Users can directly query the data in the hive table in Doris, and can use join to perform complex queries without laboriously importing data from hive

### Related issues

None.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by imay** [comment]
Actually, this is a feature, and this feature will change usage interface. When this is merged, it is hard to changed any more, because a database should keep back compatible with old version.
I suggest that it will be better to add user interface to let people discuss.

**Comment by imay** [comment]
I see a good case from Impala community, which I think we can refer. 
The following mail list is about adding unnest feature.
https://lists.apache.org/thread.html/r1095fd324e65b8fbbc31b7da61a69367e08bbf5cb6fcd1fd9e72f133%40%3Cdev.impala.apache.org%3E

**Comment by qidaye** [comment]
>  this feature will change usage interface. 

What do you mean? 

With this feature, users can not only import Hive data to Doris olap table by Spark load, but also can query hive external table by Doris. These two funcitons dose not confict. It keeps back compatible with old versions.

**Comment by imay** [comment]
> > Actually, this is a feature
> 
> Thanks for pointing out.
> 
> > this feature will change usage interface.
> 
> What do you mean? I'm a little confused.
> 
> With this feature, users can not only import Hive data to Doris olap table by Spark load, but also can query hive external table by Doris. These two funcitons dose not confict. It keeps back compatible with old versions.

I think you misunderstand my point, what I want to say is that this issue will introduce new SQL interface, such as 'CREATE TABLE'. This needs to be disscussed before coding to avoid later modification.

**Comment by qidaye** [comment]
> this issue will introduce new SQL interface , such as 'CREATE TABLE'. 

This issue does not introduce any new SQL interface. 

We already have create hive external table syntax, which can see by command `help create table`.
What I intend to do is to implement the query hive external table. Dose not change any SQL interface.

You can see the create hive table syntax in the related PR, which is exactly the same as Doris' existing create hive external table statement.
