### ISSUE TITLE
[Bug] `replace` function incorrect

### ISSUE THREAD

**Issue by qidaye** [apache/incubator-doris#6604]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

trunk version , commit_id = `2c58724c84021ae5c9fdd5ba304808b1e79191d4`

### What's Wrong?

The `replace` function cannot replace corecctly when the old substring is at the beginning of the original string.

```sql 
MySQL [(none)]>  select replace('http://www.baidu.com:9090','http', 'ftp');
+-----------------------------------------------------+
| replace('http://www.baidu.com:9090', 'http', 'ftp') |
+-----------------------------------------------------+
| http://www.baidu.com:9090                           |
+-----------------------------------------------------+
1 row in set (0.034 sec)
```

### What You Expected?

The correct result is :

```sql 
mysql> select replace('http://www.baidu.com:9090','http', 'ftp');
+-----------------------------------------------------+
| replace('http://www.baidu.com:9090', 'http', 'ftp') |
+-----------------------------------------------------+
| ftp://www.baidu.com:9090                            |
+-----------------------------------------------------+
1 row in set (0.02 sec)
```

### How to Reproduce?

```sql 
MySQL [(none)]>  select replace('http://www.baidu.com:9090','http', 'ftp');
+-----------------------------------------------------+
| replace('http://www.baidu.com:9090', 'http', 'ftp') |
+-----------------------------------------------------+
| http://www.baidu.com:9090                           |
+-----------------------------------------------------+
1 row in set (0.034 sec)
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CraftLCL** [comment]
try use  regexp_replace   select  regexp_replace('http://www.baidu.com:9090','http', 'ftp')  .
The replace function is not mentioned in the documentation.

**Comment by qidaye** [comment]
> try use regexp_replace select regexp_replace('http://www.baidu.com:9090','http', 'ftp') .

They are different functions.

> The replace function is not mentioned in the documentation.

The docmentation of `replace` function already exists. But it is not showing in the side bar of doc website. 
I'll fix it. 

Besides, you also can see the help contents by command `help replcace`.
