### ISSUE TITLE
[Feature] show create table support StorageMedium

### ISSUE THREAD

**Issue by stalary** [apache/incubator-doris#6641]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

show create table support StorageMedium/CooldownTime

### Use case

We are currently migrating some tables from HDD to SSD. Currently, we can only check whether the table uses SSD through /dbs, which is not intuitive

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by morningman** [comment]
Doris do not support setting these property for each partition in `create table stmt`.
So what will you do to support this?

**Comment by stalary** [comment]
when use show create test

**Comment by stalary** [comment]
Currently, there is a problem. If there is no show create table, it may cause HDD to be built in the next table reconstruction
