### ISSUE TITLE
[Bug] 字段varchar(3000) 长字符串被自动截取前80左右字符

### ISSUE THREAD

**Issue by boboyunz** [apache/incubator-doris#6689]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.40

### What's Wrong?

字段varchar(3000) 长字符串被自动截取前80左右字符

### What You Expected?

能够保存全部字符串

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by boboyunz** [comment]
please help

**Comment by ChPi** [comment]
有例子复现不

**Comment by boboyunz** [comment]
![image](https://user-images.githubusercontent.com/45583988/133714373-3005f5b3-0ef0-4ce2-8bdb-af1751eaa52c.png)
![image](https://user-images.githubusercontent.com/45583988/133714457-7556fb4b-4c60-4031-8cf1-f05b679dfd2c.png)
![image](https://user-images.githubusercontent.com/45583988/133714473-bd4c9573-5458-4a73-9de4-b46d321166af.png)

**Comment by boboyunz** [comment]
OTHERINFO 的字段类型是varchar(3000)

**Comment by boboyunz** [comment]
waiting online.....

**Comment by ChPi** [comment]
我自己建了表测了下没截取呢。你建表语句都能完整给下我复现下不

**Comment by boboyunz** [comment]
> 我自己建了表测了下没截取呢。你建表语句操作流程都能完整给下我复现下不

我的微信31433611 可否沟通一下：）

**Comment by boboyunz** [comment]
waiting online.....

**Comment by boboyunz** [comment]
问题原因找到了，是navicat客户端工具，展示长字段的时候会自动截断字符串，提高数据展示速度，数据库底层存储没有问题。谢谢各位大佬的帮助.万分感谢
