### ISSUE TITLE
[Bug] 多个INNER JOIN 的时候发生找不到字段的错误SQL 错误 [1054] [42S22]:

### ISSUE THREAD

**Issue by ggggujqw** [apache/incubator-doris#6696]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0.14.13.1

### What's Wrong?

![image](https://user-images.githubusercontent.com/58762901/133869192-5cbd0d00-da68-49e2-a047-287898b0fd4e.png)
![image](https://user-images.githubusercontent.com/58762901/133869205-56dbe0b0-18a9-4d5f-b252-59eb7d8ac6ad.png)
inner中关联了2张表的数据就会找不到第二个字段，如果使用同一个表的就没问题

### What You Expected?

无

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by morningman** [comment]
Could you please offer the create table stmt and SQL in text?

**Comment by ggggujqw** [comment]
> 你能提供文本中的创建表stmt和SQL吗？

我知道了，是因为升级而导致的，重新建表，让后再导入就好了
