### ISSUE TITLE
New SQL Optimizer

### ISSUE THREAD

**Issue by imay** [apache/incubator-doris#676]
Now, Doris's query optimizer is inherited from Apache Impala. Current optimizer is based on rule and not a cost based optimizer, as a result for some query it can't get optimal execution plan. Besides this, this optimizer is not extensible, so it's difficult to add new operators.

I want to implement a new optimizer to replace current one. Now cascades like optimizer has been proven to be extensible and effective in many Database System, such as SQL Server. And there is enough related materials to help to understand it. So I want to implement a optimizer based on cascades.

Because query optimizer is a huge project, I can't implement a perfect optimizer at once. I decided to divide this project to several steps.

1. Implementing optimizer framework according to cascades. After this work, the new optimizer can optimize simple query and get its optimal plan. For those queries which it can't optimize we can use old optimizer. 

2. Adding more function to replace old optimizer completely.

During all of this work, something we should follow.

1. Don't modify any exist class for not including any error posiblity.
2. Be compatible with current plan, make it easy to fallback to old optimizer.

**Comment by imay** [comment]
We will do our work on [this branch](https://github.com/apache/incubator-doris/tree/new-optimizer)

**Comment by chenhao7253886** [comment]
New SQL Optimizer will be a option with old optimizer at early stage and it will replace the old in the end.  Firstly we will implement cost-based optimizer framework and it can optimize plan tree processed by old impala heuristic optimizer. Secondly we will implement a new heuristic optimizer to replace Impala's optimizer completely and add statistics for cost. Thirdly we will support some queries that Doris does not support in tpcds under the framework.
It will take a long time and we will try to make sure that every stage is available.

**Comment by bigtreeliujie** [comment]
This is a huge improvement for doris！
