### ISSUE TITLE
[Bug] Left() function behaves not identically to the mysql implementation

### ISSUE THREAD

**Issue by tianhui5** [apache/incubator-doris#6810]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

a6e905e

### What's Wrong?

When I use string function of `left()`, it's not entirely identical to MySQL implemention. Because when the input string is empty, the result of function is NULL instead of empty string.

### What You Expected?

I think the result of function `left("", 10)` should be empty string just like MySQL did.

### How to Reproduce?

Input query of: `SELECT LEFT("", 10) FROM sample_table;`, and make sure `sample_table` is not empty, you can get the result of NULL.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EmmyMiao87** [comment]
I realize the behaviors of Doris as following:

```
MySQL [ml_test]> select left("", 10) ;
+--------------+
| left('', 10) |
+--------------+
| NULL         |
+--------------+
1 row in set (0.020 sec)

MySQL [ml_test]> select left("", 1) ;
+-------------+
| left('', 1) |
+-------------+
| NULL        |
+-------------+
1 row in set (0.020 sec)

MySQL [ml_test]> select left("a", 1) ;
+--------------+
| left('a', 1) |
+--------------+
| a            |
+--------------+
1 row in set (0.021 sec)

MySQL [ml_test]> select left("a", 2) ;
+--------------+
| left('a', 2) |
+--------------+
| a            |
+--------------+
1 row in set (0.020 sec)
```

When number > str len, the original str should be returned
