### ISSUE TITLE
[Bug] fix NumberFormatException for partition cache

### ISSUE THREAD

**Issue by ChPi** [apache/incubator-doris#6845]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0.14

### What's Wrong?

if the data type of partition column is not date or number, causes exception

### What You Expected?

no bug

### How to Reproduce?

```sql
CREATE TABLE `tbl1` (
  `k1` datetime NULL COMMENT "",
  `id` int(11) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`k1`, `id`)
COMMENT "OLAP"
PARTITION BY RANGE(`k1`)
(PARTITION p20211015 VALUES [('2021-10-15 00:00:00'), ('2021-10-16 00:00:00')),
PARTITION p20211016 VALUES [('2021-10-16 00:00:00'), ('2021-10-17 00:00:00')),
PARTITION p20211017 VALUES [('2021-10-17 00:00:00'), ('2021-10-18 00:00:00')))
DISTRIBUTED BY HASH(`k1`) BUCKETS 10
PROPERTIES (
"replication_num" = "1",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "day",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.end" = "2",
"dynamic_partition.prefix" = "p",
"dynamic_partition.replication_num" = "1",
"dynamic_partition.buckets" = "1",
"in_memory" = "false",
"storage_format" = "V2"
);
insert into tbl1 values("2021-10-15 00:01:00", 1);
```
query
```sql
select k1,count(*) from tbl1
where k1 >= "2021-08-01 00:00:00"
and k1 <= "2021-12-01 00:00:00"
GROUP BY k1;
```
throw 
`
For input string: "2021-10-15 00:01:00", Time: 0.020000s
`

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ChPi** [comment]
Can anyone have a look at this issue。if datetime type needs to be supported，I am willing to participate。

**Comment by morningman** [comment]
I tested in version 0.15.0-rc01, it works well on it. No error happend.
And since `k1` is datetime type, and `2021-10-15 00:01:00` is also a valid datetime value, I don’t think there should be any problems even in the previous version...

![image](https://user-images.githubusercontent.com/2899462/140516623-d7c24bed-661e-4ef2-8e52-3e8fdc7123e2.png)

**Comment by ChPi** [comment]
> I tested in version 0.15.0-rc01, it works well on it. No error happend. And since `k1` is datetime type, and `2021-10-15 00:01:00` is also a valid datetime value, I don’t think there should be any problems even in the previous version...
> 
> ![image](https://user-images.githubusercontent.com/2899462/140516623-d7c24bed-661e-4ef2-8e52-3e8fdc7123e2.png)

Thank you for the quick reply。have you enabled partition cache？
on our doris cluster of the 0.14.0 version , it threw exception，then i submitted a pr。i will check it again and test it in the 0.15.0-rc01。

**Comment by morningman** [comment]
> Thank you for the quick reply。have you enabled partition cache？

Ops, looks like it is a bug of partition cache. I reproduced this error on 0.15.0-rc01. Sorry for missing your PR.
I will review it soon.

**Comment by ChPi** [comment]
> > Thank you for the quick reply。have you enabled partition cache？
> 
> Ops, looks like it is a bug of partition cache. I reproduced this error on 0.15.0-rc01. Sorry for missing your PR. I will review it soon.

谢谢谢谢，麻烦看一下。期待 0.15！
