### ISSUE TITLE
[Feature] I hope to support more bitmap functions with the same functions as Clickhouse

### ISSUE THREAD

**Issue by liu391447823** [apache/incubator-doris#6875]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

1. bitmapSubsetInRange

bitmapSubsetInRange(bitmap, range_start, range_end)
参数：
bitmap – 位图对象.
range_start – 范围起始点（含）.
range_end – 范围结束点（不含）

2. bitmapSubsetLimit

bitmapSubsetLimit(bitmap, range_start, limit)
参数：
bitmap – 位图对象.
range_start – 范围起始点（含）.
limit – 子位图基数上限

3. subBitmap
subBitmap(bitmap, offset, limit)
参数：
bitmap – 位图对象.
offset – 跳过多少个元素.
limit – 子位图基数上限

### Use case

需求：
我们有一个系统是基于用户画像的推送系统，根据用户画像的标签构建用户群组bitmap，然后根据构建的bitmap导出用户id，
基于用户id去做推送。
遇到的问题：
目前遇到的问题是，当构建的bitmap数据量比较大时（比如达到百万级别的基数），我们无法通过bitmap_to_string函数导出
所有的用户id，所以我们想的办法是通过分页的方式，每次构建子bitmap，然后将子bitmap进行导出

### Related issues

#bit

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wentaotang0** [comment]
I also hope to support more bitmap functions with the same functions as Clickhouse！

**Comment by lipeng562837199** [comment]
I'm hoping so eagerly that there are more support for bitmap functions!

**Comment by morningman** [comment]
Coming soon

**Comment by morningman** [comment]
> > Coming soon
> 
> Will it be released in version 0.15？

Yes, maybe in 0.15.x

**Comment by liu391447823** [comment]
There are also bitmapmax and bitmapandnot functions

**Comment by EmmyMiao87** [comment]
If the bitmap is too large, ```to_string```  does have a problem. 
A temporary solution is to use select into file to export the query results to a file. 
However, this method is not directly obtained by segmentation. So I very much support the addition of this similar function.

**Comment by liu391447823** [comment]
> > > Coming soon
> > 
> > 
> > Will it be released in version 0.15？
> 
> Yes, maybe in 0.15.x

When was 0.15 officially released? Yesterday's attempt to compile 0.15 failed

![image](https://user-images.githubusercontent.com/11533344/138019434-0b90bb12-dd67-4dbf-9ae3-97df0ed040a1.png)


My compilation script is as follows:
docker run -it -v /Users/liujinliang/.m2:/root/.m2 -v /Users/liujinliang/doris-src/incubator-doris-branch-0.15/:/root/doris-0.15/ apache/incubator-doris:build-env-1.4.0
cd doris-0.15
sh build.sh

**Comment by EmmyMiao87** [comment]
> > > > Coming soon
> > > 
> > > 
> > > Will it be released in version 0.15？
> > 
> > 
> > Yes, maybe in 0.15.x
> 
> When was 0.15 officially released? Yesterday's attempt to compile 0.15 failed
> 
> ![image](https://user-images.githubusercontent.com/11533344/138019434-0b90bb12-dd67-4dbf-9ae3-97df0ed040a1.png)
> 
> My compilation script is as follows: docker run -it -v /Users/liujinliang/.m2:/root/.m2 -v /Users/liujinliang/doris-src/incubator-doris-branch-0.15/:/root/doris-0.15/ apache/incubator-doris:build-env-1.4.0 cd doris-0.15 sh build.sh

You need to update your docker image

**Comment by EmmyMiao87** [comment]
> > > > > > Coming soon
> > > > > 
> > > > > 
> > > > > Will it be released in version 0.15？
> > > > 
> > > > 
> > > > Yes, maybe in 0.15.x
> > > 
> > > 
> > > When was 0.15 officially released? Yesterday's attempt to compile 0.15 failed
> > > ![image](https://user-images.githubusercontent.com/11533344/138019434-0b90bb12-dd67-4dbf-9ae3-97df0ed040a1.png)
> > > My compilation script is as follows: docker run -it -v /Users/liujinliang/.m2:/root/.m2 -v /Users/liujinliang/doris-src/incubator-doris-branch-0.15/:/root/doris-0.15/ apache/incubator-doris:build-env-1.4.0 cd doris-0.15 sh build.sh
> > 
> > 
> > You need to update your docker image
> 
> The latest image version I found in docker hub is 1.4.0. I think the latest version in the official document is 1.4.1, but I can't get 1.4.1 from anywhere

@yangzhg
