### ISSUE TITLE
[Proposal] Add tablets number limit to affend wrong usage

### ISSUE THREAD

**Issue by tianhui5** [apache/incubator-doris#7009]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description
A user input a SQL like
 `alter table sample_table add partition  tmp20211103 VALUES [("20211102"),("20211103")) DISTRIBUTED BY HASH(hour,keyword,tagId) BUCKETS 20211103`
So there is 20211103 tablets, costs very large number of FE memory.
The monitor is below:
![image](https://user-images.githubusercontent.com/15223868/140300625-7a4d1f66-7c44-4864-8acb-efc6f8dd1aa0.png)
![image](https://user-images.githubusercontent.com/15223868/140300832-78856c3d-1c7a-44f0-a212-5294ed1262f5.png)
As above image shows, too many tablets cause frontend OOM. I think it's necessary to add tablets number limit.
 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xinghuayu007** [comment]
up
