### ISSUE TITLE
[Bug] Memory consumption of JDBC MySQL Driver

### ISSUE THREAD

**Issue by KKtwo** [apache/incubator-doris#7028]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0.14.0

### What's Wrong?

Describe the bug
我的项目部署在docker中，当我使用jdbc:mysql连接doris查询3000W行数据的时候，内存消耗过大OOM，导致项目自动重启了，我的连接信息是
My project is deployed in Docker. When I used JDBC :mysql to connect Doris to query 3000W rows of data, the memory consumption was too large, causing the project to restart automatically. My connection information is
`jdbc:mysql://$host:$port/$database?zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&useUnicode=true&characterEncoding=UTF8&useCursorFetch=true`
并且设置了FetchSize
`val settings = new Settings().withParamType(ParamType.INLINED).withFetchSize(500).withStatementType(StatementType.STATIC_STATEMENT)`
我也尝试把FetchSize设置为Integer.MIN_VALUE，但是还是出现了OOM
驱动的版本是`mysql-connector-java-5.1.47.jar`
![image](https://user-images.githubusercontent.com/38353785/140611644-722f9a82-6175-4a17-a6d2-44a26c5901ed.png)
As far as I know, this problem was fixed in version 0.14.0 

### What You Expected?

fixed

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by KKtwo** [comment]
modify

**Comment by weilai201** [comment]
这个问题如何解决哈。我也遇到了，从doris同步5000万数据到pg库中，提示内存超限了。be内存会一直膨胀
