### ISSUE TITLE
[Bug] Compiler error

### ISSUE THREAD

**Issue by code81192** [apache/incubator-doris#7040]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

 Docker image version: 1.4.1
Source code version: 0.14.0

### What's Wrong?

[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /root/incubator-doris/fe/fe-core/src/main/java/org/apache/doris/common/logger/TaggableLogger.java:[21,30] cannot find symbol
  symbol:   class PUniqueId
  location: package org.apache.doris.proto
[ERROR] /root/incubator-doris/fe/fe-core/src/main/java/org/apache/doris/common/logger/TaggableLogger.java:[60,42] cannot find symbol
  symbol:   class PUniqueId
  location: interface org.apache.doris.common.logger.TaggableLogger
[INFO] 2 errors

### What You Expected?

''

### How to Reproduce?

Execute the compile command after cloning the source code in the container

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by morningman** [comment]
Fixed: #7029
