### ISSUE TITLE
[Feature] Transitive Closure

### ISSUE THREAD

**Issue by EmmyMiao87** [apache/incubator-doris#7096]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Transitive Closure 应用在 Doris 中主要指的是添加冗余 SQL 连接条件，通过冗余条件减少查询的数据量从而提升查询性能的一种 SQL 优化。 
形式上，这称为传递闭包，即如果 a=b 和 a=1，则它遵循 b=1。

Doris 当前支持两个表之间的谓词传递，比如 a=b and a=1 。但他不支持多个表之间的传递。比如 a= b and b=c and a=1 这时，a=1 只能传递为 b=1 但是不能传递出 c=1。

### Use case

举个例子
```
select * from t1, t2, t3 where t1.id=t2.id and t2.id=t3.id and t3.id=1;
```
上面这个查询他应该能传递出下面两个谓词
```
t2.id = 1
t1.id = 1
```
则查询效果应该等同于
```
select * from t1, t2, t3 where t1.id=t2.id and t2.id=t3.id and t3.id=1 and t2.id=1 and t1.id=1;
```

这么做的好处在于当 filter predicate 传递给了其他表，他就可以提前过滤掉大量数据，从而提升查询性能。

### Detail design

当前代码实现位置：PredicatePushDown.java

优化后位置：语义解析完成后，统一对 Predicate 进行扩展，格式化，去重及合并。

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhengshiJ** [comment]
working on this

**Comment by EmmyMiao87** [comment]
Warshall算法计算 Transitive Closure

**Comment by zhengshiJ** [comment]
1. 注册一个新的规则InferFiltersrule，添加到GlobalState中。
2. 遍历Conjunct构造on/where的等值连接、数值连接以及isNullPredicate。
3. 利用Warshall算法推断出全部的等值连接
4. 构造出额外的数值连接和isNullPredicate

1. Register a new rule InferFiltersrule and add it to GlobalState.
2. Traverse Conjunct to construct on/where equivalence connection, numerical connection and isNullPredicate.
3. Use Warshall to infer all equivalence connections
4. Construct additional numerical connections and isNullPredicate

**Comment by zhengshiJ** [comment]
1. 注册一个新的规则InferFiltersrule，添加到GlobalState中。
2. 遍历Conjunct构造on/where的等值连接、数值连接以及isNullPredicate。
3.利用Warshall推理出全部的等值连接
4.构造出额外的数值连接和isNullPredicate


1. Register a new rule InferFiltersrule and add it to GlobalState.
2. Traverse Conjunct to construct on/where equivalence connection, numerical connection and isNullPredicate.
3. Use Warshall to infer all equivalence connections
4. Construct additional numerical connections and isNullPredicate
