### ISSUE TITLE
[Bug] Build ZSTD failed due to inappropriate Cmake option

### ISSUE THREAD

**Issue by zhengshengjun** [apache/incubator-doris#7110]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master branch

### What's Wrong?

![image](https://user-images.githubusercontent.com/74281684/141445418-d9530c15-9f04-40c1-8485-fd763195cd2c.png)

### What You Expected?

change -ZSTD_BUILD_STATIC=ON to -DZSTD_BUILD_STATIC=ON

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yangzhg** [comment]
Would you please fix it?

**Comment by zhengshengjun** [comment]
> Would you please fix it?
sure, https://github.com/apache/incubator-doris/pull/7111/files

**Comment by morningman** [comment]
Fixed by #7111

**Comment by morningman** [comment]
Hi @zhengshengjun , next time , you can write a `Fix #issue_number` in your Pull request. So that github can automatically link this issue to the PR and will also close this issue when PR merged.
