### ISSUE TITLE
Flink Doris Connector使用报错

### ISSUE THREAD

**Issue by hnwkz** [apache/incubator-doris#7203]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris集群版本0.13

### What's Wrong?

![image](https://user-images.githubusercontent.com/21251671/143011323-5879ee08-9239-4645-9bd8-ecc84d63ffc9.png)
通过官网教程，编译出来jar包，然后编写代码，通过DorisSink写入doris，代码如图：
![image](https://user-images.githubusercontent.com/21251671/143011689-e5bef443-684e-4cd9-9c0f-6790fa051e33.png)
启动之后，报错如下：
![image](https://user-images.githubusercontent.com/21251671/143011915-bffd7f95-27ad-4aa4-8e8f-f57325131d87.png)
配置已开启：enable_http_server_v2 = true，fe已经重启
界面可以访问相关页面：
![image](https://user-images.githubusercontent.com/21251671/143012126-579087ff-a4e6-40c3-823e-77dbe5aceaad.png)

![image](https://user-images.githubusercontent.com/21251671/143012169-bae9d048-424b-4fa3-b06b-b7c8b8b95634.png)
网络也都是通的，这是否代表最新编译的doris-flink-1.0.0-SNAPSHOT.jar包，不支持链接doris 0.13的集群？
![image](https://user-images.githubusercontent.com/21251671/143012566-5303a576-a572-44ea-b86f-e6a7c844b929.png)

### What You Expected?

是否只有升级doris一个途径能解决这个办法？

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hf200012** [comment]
你需要手动开启http v2

**Comment by hnwkz** [comment]
> 



> 你需要手动开启http v2
感谢回复，上面已经描述过，开启了

**Comment by hnwkz** [comment]
> 你需要手动开启http v2

![image](https://user-images.githubusercontent.com/21251671/143027175-2983fa99-ab46-483d-b182-c83fa93cc318.png)

**Comment by hf200012** [comment]
你是0.13哪个版本，如果是社区版本，那么久没有包含http v2，v2是在百度发行版0.13.12之后才有

**Comment by hnwkz** [comment]
> 你是0.13哪个版本，如果是社区版本，那么久没有包含http v2，v2是在百度发行版0.13.12之后才有
好的，感谢大佬回复，是社区版本，找个时间升级下。

**Comment by BigdataGit** [comment]
@hf200012 
<img width="825" alt="image" src="https://user-images.githubusercontent.com/27194698/190049584-36e1cd75-3da4-40fd-84f2-f9f2331ba9be.png">
I have the same problem. The version of doris I use is 1.1.1
