### ISSUE TITLE
[Bug]  Spark Doris Connector：add batch req success but status isn't ok

### ISSUE THREAD

**Issue by doudianer** [apache/incubator-doris#7209]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris：0.14.13

### What's Wrong?

The amount of data written by spark is 1000000000, occupying 10GB of storage. The specified number of partitions is 20, and an error is found when writing. The specified number of partitions is 5, and it is found that the write speed is 10000 pieces / min.

Spark写入数据量在10亿，占用存储10GB。指定分区数为20，发现写入报错。指定分区数为5，发现写入速度在10000 条/分钟

The code is as follows：
代码如下：
`dataFrame.write.format("doris")
      .option("doris.table.identifier", "test.table_test")
      .option("doris.fenodes", "IP:PORT")
      .option("user", "user")
      .option("password", "password")`
 
The error information is as follows：
报错信息如下：
<img width="1390" alt="infoflow 2021-11-23 21-36-11" src="https://user-images.githubusercontent.com/33255987/143044501-43553cb3-3047-4a25-a87c-179ab05af81c.png">

### What You Expected?

The write speed is close to the broker load
写入速度接近broker load

### How to Reproduce?

无

### Anything Else?

无

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by morningman** [comment]
-235 means load frequency is too high. But Spark-connector does not have a config to modify the interval of loading batch.

**Comment by doudianer** [comment]
Spark Doris connector does not open this configuration. Do I need to adjust it based on the source code？

**Comment by hf200012** [comment]
Your import frequency is too high. OLAP data is generally received in batches. You can try to read and import 10,000 or more in each batch. If you are migrating data from legacy systems such as spark and Hive, such as your 20G For data, you can try spark load or broker load
Your import frequency is too high. OLAP data is generally received in batches. You can try to read and import 10,000 or more in each batch. If you are migrating data from legacy systems such as spark and Hive, such as your 20G For data, you can try spark load or broker load

**Comment by doudianer** [comment]
Thank you. I found doris.batch.size: batch size for reading and writing. The size I set is 5000000, which is very good in my business scenario.
