### ISSUE TITLE
0.15 rc4 be 宕机

### ISSUE THREAD

**Issue by 391518331** [apache/incubator-doris#7245]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0.15 rc 4

### What's Wrong?

start time: Mon Nov 29 14:06:57 CST 2021
*** Aborted at 1638168662 (unix time) try "date -d @1638168662" if you are using GNU date ***
PC: @          0x1c91f7f doris::DataStreamSender::find_partition()
*** SIGSEGV (@0x0) received by PID 3794642 (TID 0x7f7407792700) from PID 0; stack trace: ***
    @          0x218e9f2 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f743fb4eb20 (unknown)
    @          0x1c91f7f doris::DataStreamSender::find_partition()
    @          0x1c922a9 doris::DataStreamSender::compute_range_part_code()
    @          0x1c952e1 doris::DataStreamSender::send()
    @          0x15d417f doris::PlanFragmentExecutor::open_internal()
    @          0x15d892f doris::PlanFragmentExecutor::open()
    @          0x154da8e doris::FragmentExecState::execute()
    @          0x1551936 doris::FragmentMgr::_exec_actual()
    @          0x155a5cf std::_Function_handler<>::_M_invoke()
    @          0x16c2d73 doris::ThreadPool::dispatch_thread()
    @          0x16bcebc doris::Thread::supervise_thread()
    @     0x7f743fb4414a start_thread
    @     0x7f743f4f3f23 __GI___clone
    @                0x0 (unknown)

### What You Expected?

no

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangxingsen666** [comment]
![image](https://user-images.githubusercontent.com/73706454/143859040-c5297e43-8795-406b-aa0b-391b4f4ae0ad.png)

**Comment by morningman** [comment]
This bug does not include in 0.15.0-rc04, and it has been fixed by #7172

**Comment by wangxingsen666** [comment]
> This bug does not include in 0.15.0-rc04, and it has been fixed by #7172

Thanks!

**Comment by wangxingsen666** [comment]
> This bug does not include in 0.15.0-rc04, and it has been fixed by #7172

This bug still exists in 0.15.0-rc04 !

**Comment by morningman** [comment]
That is strange. You can see that there is no `~BitShufflePageDecoder` deconstructor in 0.15.0-rc04:
```
https://github.com/apache/incubator-doris/blob/0.15.0-rc04/be/src/olap/rowset/segment_v2/bitshuffle_page.h
```
But exist on master branch:

```
https://github.com/apache/incubator-doris/blob/master/be/src/olap/rowset/segment_v2/bitshuffle_page.h
```

**Comment by wangxingsen666** [comment]
OK, I will use the master branch.

**Comment by morningman** [comment]
> OK, I will use the master branch.

Master branch is unstable...

**Comment by wangxingsen666** [comment]
I will develop my project on the master of doris, and waiting for your release version. Thank You!
