### ISSUE TITLE
flink-connector-doris 为啥每次flush数据都要创建一个httpclient?

### ISSUE THREAD

**Issue by gj-zhang** [apache/incubator-doris#7329]
### Discussed in https://github.com/apache/incubator-doris/discussions/7328

<div type='discussions-op-text'>

<sup>Originally posted by **gj-zhang** December  6, 2021</sup>
如题
![image](https://user-images.githubusercontent.com/21170229/144832866-9d3f092f-b072-4f7e-b178-690d75cac0a4.png)
</div>

**Comment by aihai** [comment]
I am willing to submit a PR

**Comment by aihai** [comment]
#7450
