### ISSUE TITLE
[Bug] show frontends cause FE oom

### ISSUE THREAD

**Issue by morningman** [apache/incubator-doris#7334]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0.15

### What's Wrong?

`show frontends` or `show backends` cause FE oom.
This because:

1. For some other reason, there is no valid Master FE.
2. `show frontends` will forward to master FE, but Master FE is not ready, so it try to forward again.
3. Endless forward cause OOM

### What You Expected?

Return error when master FE is not ready.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangbo** [comment]
This patch can also be applied for 0.14 too.
