### ISSUE TITLE
[Bug] 0.14 FE can't read 0.15 FE's metadata

### ISSUE THREAD

**Issue by tinkerrrr** [apache/incubator-doris#7344]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0.14.0 and 0.15.0

### What's Wrong?

I was going to upgrade Doris from 0.14.0 to 0.15.0, it performs well during the upgrade process. But a complete upgrade plan of production environment should contain degradation plan. When degrade from 0.15 to 0.14, FE crash with exception: 

```
java.io.EOFException
    at java.io.DataInputStream.readFully(DataInputStream.java:197)
    at org.apache.doris.common.io.Text.readString(Text.java:415)
    at org.apache.doris.catalog.Catalog.loadMasterInfo(Catalog.java:1580)
    at org.apache.doris.catalog.Catalog.loadImage(Catalog.java:1479)
    at org.apache.doris.catalog.Catalog.initialize(Catalog.java:760)
    at org.apache.doris.PaloFe.start(PaloFe.java:108)
    at org.apache.doris.PaloFe.main(PaloFe.java:60)
```

This could reduce the confidence of upgrading

### What You Expected?

Guarantee compatibility between FE 0.14 and FE 0.15

### How to Reproduce?

upgrade from 0.14 to 0.15 and then degrade from 0.15 to 0.14

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by morningman** [comment]
Doris just guarantee backward compatibility, not forward.

**Comment by tinkerrrr** [comment]
> Doris just guarantee backward compatibility, not forward.

Do we have any insurance policy to keep data safe in case of upgrade failure? I think it is worth considering
