### ISSUE TITLE
查询时间较长时，偶尔会返回空的结果，客户端不抛异常

### ISSUE THREAD

**Issue by dlooss** [apache/incubator-doris#736]
从2019-3-5开始，查询时间较长时，偶尔会返回空的结果，客户端不抛异常。2019-3-5日以前，超时会抛异常。客户端采用Python的MySQLdb。

**Comment by dlooss** [comment]
版本：Server version: 5.1.0 Doris version 0.9.9-release；
默认超时时间：300s；

**Comment by dlooss** [comment]
排查发现，python2.6.6，MySQL_python-1.2.3下可以重现。
升级到python 2.7后，暂没发现问题；

**Comment by imay** [comment]
@dlooss 
Can you close this issue now? And if you are not convenient, I will close this issue next week.
