### ISSUE TITLE
log4j漏洞修复

### ISSUE THREAD

**Issue by zhouhoo** [apache/incubator-doris#7381]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

log4j最近暴露了比较严重的漏洞，目前官方给出了log4j的修复版本。咱们项目什么时候更新呢？

### Solution

log4j给出了修复漏洞的版本https://github.com/apache/logging-log4j2/releases/tag/log4j-2.15.0-rc2。怎么修复到Doris？我直接替换fe目录下的lib文件夹内的旧jar，结果FE无法启动。

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by qidaye** [comment]
You can refer to this article [ApacheDoris Security](https://mp.weixin.qq.com/s?src=11&timestamp=1639536577&ver=3497&signature=3viyIyREdBzrajzqu7LkohVfW6ulLxHJTMAxWgD3OQsHz0K2l-cu1V37ZnlgEqlx8YpVkmVCSxb7uzbDzpGg6bJr6ZGNBLphBM2Mz9Xkipst16QsEsH-7WVsSJoDK-GB&new=1)

**Comment by hugengyong** [comment]
直接升级log4j-2.17.0吧
