### ISSUE TITLE
[Bug] flink-connector-doris  NullPointExceptin at  SchemaUtils.convertToSchema(openResult.getSelectedColumns)

### ISSUE THREAD

**Issue by gj-zhang** [apache/incubator-doris#7387]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

flink version 1.14.0  scala 2.11

doris 0.15

### What's Wrong?

Caused by: java.lang.NullPointerException
	at org.apache.doris.flink.rest.SchemaUtils.lambda$convertToSchema$0(SchemaUtils.java:36)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.apache.doris.flink.rest.SchemaUtils.convertToSchema(SchemaUtils.java:36)
	at org.apache.doris.flink.datastream.ScalaValueReader.<init>(ScalaValueReader.scala:127)
	at org.apache.doris.flink.table.DorisRowDataInputFormat.open(DorisRowDataInputFormat.java:96)
	at org.apache.doris.flink.table.DorisRowDataInputFormat.open(DorisRowDataInputFormat.java:45)
	at org.apache.flink.streaming.api.functions.source.InputFormatSourceFunction.run(InputFormatSourceFunction.java:84)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:116)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:73)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:323)

### What You Expected?

success

### How to Reproduce?

flink sql 
```sql
create table doris_sbo_t (
    `name` string
) with (
'connector' = 'doris',
'fenodes' = 'ip：host',
'table.identifier' = 'db.table',
'username' = 'root',
'password' = ''
);

select * from doris_sbo_t limit 10;
```
### Anything Else?

我自己用flink1.14  scala2.11重新编译了

![image](https://user-images.githubusercontent.com/21170229/145815298-bfa71ee1-2733-4ee4-b7ca-9f106c21ab2e.png)

除了 DORIS_DELETE_SIGN字段 的type不是null。 剩下其他字段的type全部是null

doris 表结构
```sql
 CREATE TABLE `standard_business_object_v2` (
  `_id` text NULL COMMENT "",
  `name` text NULL COMMENT "",
  ......
) ENGINE=OLAP
UNIQUE KEY(`_id`, `name`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`_id`, `name`) BUCKETS 4
PROPERTIES (
"replication_allocation" = "tag.location.default: 3",
"in_memory" = "false",
"storage_format" = "V2"
)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gj-zhang** [comment]
and i use flink 1.11.2 and scala 2.12 , this problem happen too.

**Comment by JNSimba** [comment]
Your doris table may have [batch delete enabled](https://doris.apache.org/master/zh-CN/administrator-guide/load-data/batch-delete-manual.html#%E5%8E%9F%E7%90%86), you can view the document verification。
Then，you can add a hidden column field when creating a table in Flink to solve this problem

**Comment by gj-zhang** [comment]
@JNSimba yes.  desc tablename, there is a field 
```sql
| __DORIS_DELETE_SIGN__ | TINYINT | No   | false | 0       | REPLACE |
```

and, how to add a hidden column field when creating a table in flink? like this?
```sql
create table doris_sbo_t (
    `name` string,
    `__DORIS_DELETE_SIGN__` tinyint
) with (
'connector' = 'doris',
'fenodes' = 'ip：host',
'table.identifier' = 'db.table',
'username' = 'root',
'password' = ''
);
```
if so, i get the same error.

**Comment by JNSimba** [comment]
> @JNSimba yes. desc tablename, there is a field
> 
> ```sql
> | __DORIS_DELETE_SIGN__ | TINYINT | No   | false | 0       | REPLACE |
> ```
> 
> and, how to add a hidden column field when creating a table in flink? like this?
> 
> ```sql
> create table doris_sbo_t (
>     `name` string,
>     `__DORIS_DELETE_SIGN__` tinyint
> ) with (
> 'connector' = 'doris',
> 'fenodes' = 'ip：host',
> 'table.identifier' = 'db.table',
> 'username' = 'root',
> 'password' = ''
> );
> ```
> 
> if so, i get the same error.

It may be that your version is too old, the old version does not support the String type, you can see this PR
https://github.com/apache/incubator-doris/pull/7075.

**Comment by gj-zhang** [comment]
@JNSimba i change the type to varchar, same error.
and stacktrace 
```java
org.apache.doris.flink.backend.BackendClient#openScanner

logger.debug("OpenScanner to '{}', parameter is '{}'.", routing, openParams);
        if (!isConnected) {
            open();
        }
        TException ex = null;
        for (int attempt = 0; attempt < retries; ++attempt) {
            logger.debug("Attempt {} to openScanner {}.", attempt, routing);
            try {
                TScanOpenResult result = client.openScanner(openParams);
                if (result == null) {
                    logger.warn("Open scanner result from {} is null.", routing);
                    continue;
                }
        ...
```
```shell
Caused by: java.lang.NullPointerException
	at org.apache.doris.flink.rest.SchemaUtils.lambda$convertToSchema$0(SchemaUtils.java:36)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.apache.doris.flink.rest.SchemaUtils.convertToSchema(SchemaUtils.java:36)
	at org.apache.doris.flink.datastream.ScalaValueReader.<init>(ScalaValueReader.scala:127)
	at org.apache.doris.flink.table.DorisRowDataInputFormat.open(DorisRowDataInputFormat.java:96)
	at org.apache.doris.flink.table.DorisRowDataInputFormat.open(DorisRowDataInputFormat.java:45)
	at org.apache.flink.streaming.api.functions.source.InputFormatSourceFunction.run(InputFormatSourceFunction.java:85)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:100)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:63)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:213)
```
the field of TScanColumnDesc,  type is null.

**Comment by JNSimba** [comment]
> @JNSimba i change the type to varchar, same error. and stacktrace
> 
> ```java
> org.apache.doris.flink.backend.BackendClient#openScanner
> 
> logger.debug("OpenScanner to '{}', parameter is '{}'.", routing, openParams);
>         if (!isConnected) {
>             open();
>         }
>         TException ex = null;
>         for (int attempt = 0; attempt < retries; ++attempt) {
>             logger.debug("Attempt {} to openScanner {}.", attempt, routing);
>             try {
>                 TScanOpenResult result = client.openScanner(openParams);
>                 if (result == null) {
>                     logger.warn("Open scanner result from {} is null.", routing);
>                     continue;
>                 }
>         ...
> ```
> 
> ```shell
> Caused by: java.lang.NullPointerException
> 	at org.apache.doris.flink.rest.SchemaUtils.lambda$convertToSchema$0(SchemaUtils.java:36)
> 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
> 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
> 	at org.apache.doris.flink.rest.SchemaUtils.convertToSchema(SchemaUtils.java:36)
> 	at org.apache.doris.flink.datastream.ScalaValueReader.<init>(ScalaValueReader.scala:127)
> 	at org.apache.doris.flink.table.DorisRowDataInputFormat.open(DorisRowDataInputFormat.java:96)
> 	at org.apache.doris.flink.table.DorisRowDataInputFormat.open(DorisRowDataInputFormat.java:45)
> 	at org.apache.flink.streaming.api.functions.source.InputFormatSourceFunction.run(InputFormatSourceFunction.java:85)
> 	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:100)
> 	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:63)
> 	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:213)
> ```
> 
> the field of TScanColumnDesc, type is null.

Is the data type of doris also **varchar**?

**Comment by gj-zhang** [comment]
it's text

**Comment by JNSimba** [comment]
@gj-zhang Well, just upgrade the connector jar package

**Comment by gj-zhang** [comment]
@JNSimba ok  i  try

**Comment by gj-zhang** [comment]
> @gj-zhang Well, just upgrade the connector jar package

it works. thank you very much. and can you tell me why? I am very confused

**Comment by JNSimba** [comment]
> > @gj-zhang Well, just upgrade the connector jar package
> 
> it works. thank you very much. and can you tell me why? I am very confused

You can look at this PR https://github.com/apache/incubator-doris/pull/7075, the previous version did not do string compatibility processing, so the return is null
