### ISSUE TITLE
[Bug] timeout transactions still in running list

### ISSUE THREAD

**Issue by lordk911** [apache/incubator-doris#7398]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Git : git://37942ae4575f/root/incubator-doris@b067bdcdd54e22d70ef79e332816f182b3d5872a

Version : trunk

BuildInfo : root@37942ae4575f

BuildTime : Fri, 06 Aug 2021 08:13:44 UTC

### What's Wrong?

![image](https://user-images.githubusercontent.com/19989300/146001331-e55e5e79-359f-41e5-af90-d3e92c0dfe71.png)

**transactions that submited several days ago ,still running...**

### What You Expected?

how to delete then from the running list ? 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by morningman** [comment]
The txn in state COMMITTED must be change to VISIBLE.
It looks like there is some thing wrong with your publish task execution.
See Master FE's fe.log to find some errors about "publish".

**Comment by lordk911** [comment]
after upgrade to doris 0.15 the problem was gone.
