### ISSUE TITLE
[Bug] 查询导出时数据展示问题

### ISSUE THREAD

**Issue by sunbc996** [apache/incubator-doris#7419]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0.14

### What's Wrong?

有如下数据和操作：
col1       col2
6,2,8,2   5,7,2,8

使用函数：
regexp_replace(col1, ",", "\n"), regexp_replace(col2, ",", "\n")

### What You Expected?

理论得到的结果：
    6   5
    2   7
    8   2
    2   8

实际得到的值：
    6
    2
    8
    2
    5
    7
    2
    8

### How to Reproduce?

我觉得它应该在使用替换的时候，依旧维持2个字段的状态，而不是已经转化成了字符串，再进行字符串转化。应该每个字段内就使用字符串转化。
不知道是否应该是这样？

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by morningman** [comment]
I tested in 0.15:

```
create table tbl1(k1 string, k2 string) distributed by hash(k1) buckets 1;
insert into tbl1 values("6,2,8,2", "5,7,2,8");
```

The result is as expected:
```
mysql> select regexp_replace(k1, ",", "\n") col1, regexp_replace(k2, ",", "\n") col2 from tbl1\G
*************************** 1. row ***************************
col1: 6
2
8
2
col2: 5
7
2
8
1 row in set (0.02 sec)
```
