### ISSUE TITLE
libsasl2.a missing

### ISSUE THREAD

**Issue by zhouhoo** [apache/incubator-doris#7452]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master 

### What's Wrong?

ninja: error: '/var/local/thirdparty/installed/lib/libsasl2.a', needed by 'src/service/palo_be', missing and no known rule to make it

### What You Expected?

no error 

### How to Reproduce?

1. git clone the lasteast master branch 
2. sh build.sh

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by BiteTheDDDDt** [comment]
you should update your thirdparty lib cyrus_sasl

**Comment by jackwener** [comment]
Remove thirdparty/installed/ and create a empty dir thirdparty/installed/.

it's will be ok.

close it if there are still wrong, please reply.
