### ISSUE TITLE
[Bug] forbidden create materialized view with distinct

### ISSUE THREAD

**Issue by xuzifu666** [apache/incubator-doris#7516]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0.15

### What's Wrong?

when user create materialized view with distinct, the materialized view can be created. it is not fit for the current condition, because  it is not can be used and doris does not suppot create materialized view for count distinct. so should forbid the operator.

### What You Expected?

we should forbid the operator when user create materialized view for count distinct.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EmmyMiao87** [comment]
This pr #7494 prohibits the distinct semantics that may appear in aggregate functions. 
For example, ```select count(distinct c1) from table1```

But there is another situation that is distinct in the select item. 
For example, ```select distinct c1, c2 from table```
And this situation can actually be supported. It is equivalent to select c1, c2 from table group by c1, c2.
Can you help us add this part of the changes in the follow-up pr?

**Comment by xuzifu666** [comment]
> This pr #7494 prohibits the distinct semantics that may appear in aggregate functions. For example, `select count(distinct c1) from table1`
> 
> But there is another situation that is distinct in the select item. For example, `select distinct c1, c2 from table` And this situation can actually be supported. It is equivalent to select c1, c2 from table group by c1, c2. Can you help us add this part of the changes in the follow-up pr?

ok，i would commit follow-up pr to improve the function，thanks.
