### ISSUE TITLE
[Roadmap] Implement IO manager

### ISSUE THREAD

**Issue by morningman** [apache/incubator-doris#7581]
root issue

**Comment by yinzhijian** [comment]
# 性能测试
## 思路
构造一个场景使得当某个盘热点时，其它盘的查询不受影响（表现为比原始版本的性能更好）。
<h1 class="mp-heading" data-morpho-type="heading" data-uuid="61960990-7f65-11ec-942b-6b025c2fe606" data-slate-node="element" style="text-align:left;padding-left:0px">环境</h1><p class="mp-paragraph-wrapper" data-morpho-type="paragraph" style="text-align:left;padding-left:0px" data-slate-node="element">单BE，6块disk。</p><p class="mp-paragraph-wrapper" data-morpho-type="paragraph" style="text-align:left;padding-left:0px" data-slate-node="element">额外配置：</p><div class="mp-block-code-container"><pre spellcheck="false" data-lang="cpp" data-autowrap="true" class="mp-block-code-wrapper language-cpp " style="overflow:hidden"><div class="mp-block-code-content mp-block-code-content-auto-wrap" style="overflow:auto"><div class="mp-block-code-line"><span class="mp-block-code-line-content">disable_storage_page_cache = true #禁用pagecache</span></div><div class="mp-block-code-line"><span class="mp-block-code-line-content">doris_scanner_thread_pool_thread_num=24</span></div></div></pre></div><p class="mp-paragraph-wrapper" data-morpho-type="paragraph" style="text-align:left;padding-left:0px" data-slate-node="element">单FE。</p><h1 class="mp-heading" data-morpho-type="heading" data-uuid="896c1b40-8982-11ec-9591-1189e67d2a9e" data-slate-node="element" style="text-align:left;padding-left:0px">方法</h1><h2 class="mp-heading" data-morpho-type="heading" data-uuid="af7e16c0-8983-11ec-9591-1189e67d2a9e" data-slate-node="element" style="text-align:left;padding-left:0px">数据以及环境准备</h2><ol data-morpho-type="ordered-list-item" data-slate-node="element" class="mp-ordered-list"><li class="mp-list-item" data-morpho-list-depth="0" data-morpho-list-index="1" data-morpho-list-initial-number="1"><div class="mp-list-item-child"><div>总共有两个ssb数据库，ssb1跟ssb2，两者的表结构、表数据完全一致。不同之处在于，ssb1的所有分片落在disk1上，ssb2的分片落在disk2~disk6上。【disk1热点不影响其它disk的查询处理】</div></div></li><li class="mp-list-item" data-morpho-list-depth="0" data-morpho-list-index="2"><div class="mp-list-item-child"><div>对disk1模拟io热点。</div></div><ol data-morpho-type="ordered-list-item" data-slate-node="element" class="mp-ordered-list"><li class="mp-list-item" data-morpho-list-depth="1" data-morpho-list-index="1"><div class="mp-list-item-child"><div>修改代码，在env_posix.cpp的do_readv_at函数中，添加读取disk1文件时sleep 1ms的逻辑（模拟io wait）。</div></div></li></ol></li></ol><h2 class="mp-heading" data-morpho-type="heading" data-uuid="b5482cd0-8983-11ec-9591-1189e67d2a9e" data-slate-node="element" style="text-align:left;padding-left:0px">性能测试</h2><ol data-morpho-type="ordered-list-item" data-slate-node="element" class="mp-ordered-list"><li class="mp-list-item" data-morpho-list-depth="0" data-morpho-list-index="1" data-morpho-list-initial-number="1"><div class="mp-list-item-child"><div>同时运行两个jmeter，分别对ssb1和ssb2发起单次40并发的压测。</div></div><ol data-morpho-type="ordered-list-item" data-slate-node="element" class="mp-ordered-list"><li class="mp-list-item" data-morpho-list-depth="1" data-morpho-list-index="1"><div class="mp-list-item-child"><div>环境设置：set parallel_fragment_exec_instance_num=8</div></div></li><li class="mp-list-item" data-morpho-list-depth="1" data-morpho-list-index="2"><div class="mp-list-item-child"><div>sql为select count(*) from lineorder;【其它sql结果类似】</div></div></li></ol></li><li class="mp-list-item" data-morpho-list-depth="0" data-morpho-list-index="2"><div class="mp-list-item-child"><div>测试结果：</div></div></li></ol><p class="mp-paragraph-wrapper" data-morpho-type="paragraph" style="text-align:left;padding-left:0px" data-slate-node="element">ssb2的整体耗时如下（其它盘性能有明显提升）：</p><div class="mp-table-wrapper"><div data-slate-node="element" style="padding-left:0px" class="mp-table-container">

\总时间\ | 向量化版本 | 非向量化版本
-- | -- | --
disk绑定版本 | 51s | 2min40s
原始版本 | 1min08s | 2min54s

</div><div class="mp-table-serialize-flag"><br/></div></div>
<p class="mp-paragraph-wrapper" data-morpho-type="paragraph" style="text-align:left;padding-left:0px" data-slate-node="element">ssb1的整体耗时如下（热点盘无影响）：</p><div class="mp-table-wrapper"><div data-slate-node="element" style="padding-left:0px" class="mp-table-container">

\总时间\ | 向量版本 | 非向量版本
-- | -- | --
disk绑定版本 | 1min34s | 3min15s
原始版本 | 1min35s | 3min14s

</div><div class="mp-table-serialize-flag"><br/></div></div>
