### ISSUE TITLE
[Bug] query faild after enable_vectorized_engine

### ISSUE THREAD

**Issue by lordk911** [apache/incubator-doris#7646]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Version : 0.15.0-rc04

### What's Wrong?

```
mysql> select count(1) from test.aplog;
+----------+
| count(1) |
+----------+
| 31004409 |
+----------+
1 row in set (1.92 sec)

mysql> set enable_vectorized_engine = true;
Query OK, 0 rows affected (0.00 sec)

mysql> select count(1) from test.aplog;
ERROR 1064 (HY000): RpcException, msg: rpc failed, host: 10.0.105.250
```

### What You Expected?

why? what's the matter?

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lordk911** [comment]
enable_vectorized_engine -> query -> backends dead

**Comment by yiguolei** [comment]
Could you please login to BE and find the error logs? Maybe BE is dead.

**Comment by lordk911** [comment]
> Could you please login to BE and find the error logs? Maybe BE is dead.

Yes, BE is dead. if I set enable_vectorized_engine=true, then run a Aggregation query，BE will all dead ，but set enable_vectorized_engine=false ， all will be fine

**Comment by morningman** [comment]
`0.15.0-rc04` does not contains `vectorized_engine`.

**Comment by yiguolei** [comment]
@lordk911 you could use vector branch. https://github.com/apache/incubator-doris/commits/vectorized

**Comment by lordk911** [comment]
thanks
