### ISSUE TITLE
[Bug] branch-0.15/be/src/util/aes_util.cpp

### ISSUE THREAD

**Issue by ljmat** [apache/incubator-doris#7651]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

branch-0.15

### What's Wrong?

branch-0.15/be/src/util/aes_util.cpp
line 105 and 153
EVP_CIPHER_CTX aes_ctx; 

apache-doris-0.15.0-incubating-src/be/src/util/aes_util.cpp:105:20: error: aggregate 'EVP_CIPHER_CTX aes_ctx' has incomplete type and cannot be defined

### What You Expected?

I want to compile smoothly in docker evn.

### How to Reproduce?

execute the command in docker container as below
**sh build.sh --clean --be --fe --ui**

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by morningman** [comment]
you need to use docker-dev-env-0.15to compile branch-0.15

**Comment by ljmat** [comment]
> 

thanks you answer.
but how can I use the docker-dev-env-0.15? any guide for help?

**Comment by morningman** [comment]
https://doris.apache.org/master/zh-CN/installing/compilation.html#%E4%BD%BF%E7%94%A8-docker-%E5%BC%80%E5%8F%91%E9%95%9C%E5%83%8F%E7%BC%96%E8%AF%91-%E6%8E%A8%E8%8D%90

search build-env-for-0.15
