### ISSUE TITLE
Add HLL colum by alter table result in doris all be core dump

### ISSUE THREAD

**Issue by karllolee** [apache/incubator-doris#768]
`alter table ttt add column set2 hll hll_union` 
Add hll column by alter table as above, and then all BE core dump。

**Comment by chenhao7253886** [comment]
it's a bug , now adding hll to schema is't  supported,  i will fix it and return a hint that add hll is't supported.

**Comment by chenhao7253886** [comment]
I have support add or drop hll column in Schemachange, you can try it.

**Comment by chenhao7253886** [comment]
Fix it in https://github.com/apache/incubator-doris/pull/1033
