### ISSUE TITLE
[Vectorized][Feature] support function conv

### ISSUE THREAD

**Issue by BiteTheDDDDt** [apache/incubator-doris#7692]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

support function conv

### Use case

```sql
MySQL [ssb]> select conv('b',16,10);
+-------------------+
| conv('b', 16, 10) |
+-------------------+
| 11                |
+-------------------+
1 row in set (0.017 sec)

MySQL [ssb]> select conv(9,16,10);
+-----------------+
| conv(9, 16, 10) |
+-----------------+
| 9               |
+-----------------+
1 row in set (0.014 sec)

MySQL [ssb]> select conv(9,10,2);
+----------------+
| conv(9, 10, 2) |
+----------------+
| 1001           |
+----------------+
1 row in set (0.017 sec)
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangbo** [comment]
Can you add a document?
I still don't know what is this thing used for after see your user case.

**Comment by BiteTheDDDDt** [comment]
> Can you add a document? I still don't know what is this thing used for after see your user case.
Ok, I will add a document.
conv is a function what can converts numbers between different number bases.
https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_conv
