### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by freshsun** [apache/incubator-doris#7701]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0.15.1-rc09

### What's Wrong?

multiple select system variables like

 select @@storage_engine,@@storage_engine;

return 

ERROR 1064 (HY000): errCode = 2, detailMessage = Unexpected exception: null

### What You Expected?

it should display two columns 

### Anything Else?

block using jetbrains datagrip

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by GoGoWen** [comment]
It should be an issue,  i will create a pr  to fix it.
