### ISSUE TITLE
[Enhancement] some datetime functions can be marked as constant to help partition pruning

### ISSUE THREAD

**Issue by littleeleventhwolf** [apache/incubator-doris#7726]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

When I run sql below, failed to push-down predicate
```
explain select field1, field2
  from tbl
 where datekey between cast(date_format(substr('2021-11-18 20:00:00',1,10), '%Y%m%d') as int) and cast(date_format(substr('2021-11-19 00:00:00',1,10), '%Y%m%d') as int)
```

### Solution

Some `datetime` functions can be marked as constant.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by GoGoWen** [comment]
if want constant fold，  set enable_fold_constant_by_be=true;  can help u.

**Comment by littleeleventhwolf** [comment]
Got it. Thank u.
