### ISSUE TITLE
[Enhancement][Vectorized] Speed up column filtering via SIMD

### ISSUE THREAD

**Issue by zenoyang** [apache/incubator-doris#7774]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

- In the current Column Filter, when it is judged that the mask is not all 1, the elements will be traversed in a non-SIMD way, so there will be no performance improvement here. The test below also verifies this (currently sse_for).
    - code: https://github.com/apache/incubator-doris/blob/685f45229efb42b327a9351143115863a5fdcbed/be/src/vec/columns/columns_common.cpp#L202
- Add AVX2 accelerated filtering

I tested 6000000 elements to filter，The time consumption for each implementation is as follows:

filter data set all is 0, such as 00000000...
```
origin cost: 19553 microseconds
sse cost: 1856 microseconds
sse_for cost: 1848 microseconds
avx2 cost: 1020 microseconds
```

filter data set 1/5 is 1, such as 00001000010000100001...
```
origin cost: 49023 microseconds
sse cost: 38613 microseconds
sse_for cost: 46018 microseconds
avx2 cost: 36195 microseconds
```

filter data set 1/3 is 1, such as 001001001001...
```
origin cost: 68974 microseconds
sse cost: 61366 microseconds
sse_for cost: 69220 microseconds
avx2 cost: 58368 microseconds
```

filter data set 1/2 is 1, such as 01010101...
```
origin cost: 96398 microseconds
sse cost: 95707 microseconds
sse_for cost: 96138 microseconds
avx2 cost: 88001 microseconds
```

filter data set all is 1, such as 11111111...
```
origin cost: 193828 microseconds
sse cost: 188143 microseconds
sse_for cost: 189108 microseconds
avx2 cost: 127760 microseconds
```

test code: https://godbolt.org/z/Gf6hvcnej

### Solution

no

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by HappenLee** [comment]
nice job！
