### ISSUE TITLE
[Bug] 0.15.1导出hdfs报错

### ISSUE THREAD

**Issue by LT519** [apache/incubator-doris#7789]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

PALO-0.15.1-rc08

### What's Wrong?

doris 数据导出到hdfs，数据表类型是UNIQUE KEY的提示：
ERROR 1054 (42S22): errCode = 2, detailMessage = Unknown column '__DORIS_DELETE_SIGN__' in 'table list'

### What You Expected?

正常导出

### How to Reproduce?

mysql> EXPORT TABLE userData 
    -> TO "hdfs://172.16.25.22:9000" 
    -> WITH BROKER "broker_name" (
    -> "username"="root", 
    -> "password"=""
    -> );
ERROR 1054 (42S22): errCode = 2, detailMessage = Unknown column '__DORIS_DELETE_SIGN__' in 'table list'

### Anything Else?

no

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EmmyMiao87** [comment]
1. create table unique_table (k1 int, k2 int) unique key(k1) distributed by hash(k1);
2. EXPORT TABLE unique_table TO "hdfs://xxx:9000/xxx" WITH BROKER "xxx" ("username"="xxx", "password"="");
