### ISSUE TITLE
reader will failed because the version is compacted

### ISSUE THREAD

**Issue by kangpinghuang** [apache/incubator-doris#779]
**Describe the bug**
reader will failed because can not aquire the data source of the right version:
W0320 10:22:42.038903 31688 olap_table.cpp:396] fail to generate shortest version path. [version='0-927' table='584857.41372972']
W0320 10:22:42.038920 31688 reader.cpp:493] fail to acquire data sources. [table_name='584857.41372972' version=0-927]
W0320 10:22:42.038930 31688 reader.cpp:311] fail to init reader when acquire data sources.[res=-214]
W0320 10:22:42.038939 31688 olap_scanner.cpp:121] fail to init reader.[res=-214]

compaction:
I0320 10:22:35.352181 31661 cumulative_compaction.cpp:480] succeed to do cumulative compaction. [table=584857.41372972; cumulative_version=2-928]

**Comment by kangpinghuang** [comment]
this problem will be solved by using the following mechanism(deferred delete mechanism):
1. add a delete flag field and delete_time field to the rowset
2. delete rowset will not be added unused rowsets queue. It will be reserved for a peroid(eg: 10 minutes, can be configured by config) so that the late reader with the old version will get the old version rowset.
3. Tablet will manage a extra deleted rowsets queue and will check the queue periodically to move the timeout rowsets in the deleted rowsets queue to the unused rowsets in StorageEngine.
4. One point to figure out is that make sure the rowset version can be obtained from version graph and can be aquired through tabblet's get_rowset api.

**Comment by kangpinghuang** [comment]
related problems should be considered:
1. the disk space
2. version graph
3. how long to spare
4. base rowset

**Comment by kangkaisen** [comment]
https://github.com/apache/incubator-doris/pull/1400/ has fixed this issue.
