### ISSUE TITLE
Failed to send data in csv format using CURL

### ISSUE THREAD

**Issue by luanmacidian** [apache/incubator-doris#783]
**The command is as follows：**

curl --location-trusted -u root:root -H 'Content-Type:text/csv' -H 'column_separator:,' -H 'Expect:100-continue' --data '2017-07-16,6,2,jack,3' -XPUT http://host:port/api/test/table2/_stream_load

**My console returns as follows：**

{
    "TxnId": 2040,
    "Label": "aa1d6fef-ce2d-4a9f-bae5-c79bfe90ce23",
    "Status": "Fail",
    "Message": "all partitions have no load data",
    "NumberLoadedRows": 0,
    "NumberFilteredRows": 0,
    "LoadBytes": 21,
    "LoadTimeMs": 7
}

**Comment by imay** [comment]
This bug is because there is no 'newline' in data, so we ignore this line.

**Comment by imay** [comment]
@luanmacidian 
This bug has been fixed by PR #785 , can you try it and close this issue? And if you're not convenient, I will close this issue next week.
