### ISSUE TITLE
[Bug] compilation with ldb-toolchain failed when build thirdparty for openssl in ubuntu20.04 

### ISSUE THREAD

**Issue by caiconghui** [apache/incubator-doris#7843]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

engines/e_afalg.c:40:11: fatal error: linux/if_alg.h: No such file or directory
   40 | # include <linux/if_alg.h>
      |           ^~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:6398: engines/e_afalg.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/cch13/Work/Project/incubator-doris/thirdparty/src/openssl-OpenSSL_1_1_1m'
make: *** [Makefile:174: all] Error 2

and we can see

~/Work/Project/incubator-doris$ ll /usr/include/linux/if_alg.h 
-rw-r--r-- 1 root root 1534 1月  12 23:16 /usr/include/linux/if_alg.h

### What You Expected?

build openssl succeed

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by amosbird** [comment]
It's because some macro guards are controlled by kernel verions. I'll try to compile doris on recent kernel and revise ldb_toolchain with a new version.

**Comment by amosbird** [comment]
Please try https://github.com/apache/incubator-doris/pull/7846 with ldb_toolchain v0.4 https://github.com/amosbird/ldb_toolchain_gen/releases/download/v0.4/ldb_toolchain_gen.sh

I've tested it with ubuntu20.04 on kernel 5.15.16-1-lts.

**Comment by caiconghui** [comment]
> Please try #7846 with ldb_toolchain v0.4 https://github.com/amosbird/ldb_toolchain_gen/releases/download/v0.4/ldb_toolchain_gen.sh
> 
> I've tested it with ubuntu20.04 on kernel 5.15.16-1-lts.

it works， thanks
