### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by aubdiy** [apache/incubator-doris#7891]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0.15.0-incubating

### What's Wrong?

compile  error:  

sh build.sh

```
lz4 libraries installed
make[1]: Leaving directory '/data/sae-dp-files/tmp/apache-doris-0.15.0-incubating-src/thirdparty/src/lz4-1.9.3/lib'
make[1]: Entering directory '/data/sae-dp-files/tmp/apache-doris-0.15.0-incubating-src/thirdparty/src/lz4-1.9.3/programs'
Installing binaries
ln: failed to create symbolic link '/data/sae-dp-files/tmp/apache-doris-0.15.0-incubating-src/thirdparty/installed/bin/lz4c': File exists
make[1]: *** [Makefile:166: install] Error 1
make[1]: Leaving directory '/data/sae-dp-files/tmp/apache-doris-0.15.0-incubating-src/thirdparty/src/lz4-1.9.3/programs'
make: *** [Makefile:95: install] Error 2
```

### What You Expected?

that's ok

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aubdiy** [comment]
user docker compile, is ok .

**Comment by morningman** [comment]
you can simply remove the `/data/sae-dp-files/tmp/apache-doris-0.15.0-incubating-src/thirdparty/installed/bin/lz4c` before executing `build-thirdparty.sh` again
