### ISSUE TITLE
Use funciton (count and HLL_UNION_AGG) in one column cause doris return wrong value

### ISSUE THREAD

**Issue by qdore** [apache/incubator-doris#794]
**Describe the bug**

The following sql cause doris return wrong value:
```
SELECT DATE(event_day) AS __timestamp,
       if (true, HLL_UNION_AGG(uv),count(distinc(cuid)))
    FROM visd_novel_searchbox_operate_hll
    WHERE event_day >= STR_TO_DATE('2019-03-15 00:00:00', '%Y-%m-%d %H:%i:%s') AND 
          event_day <= STR_TO_DATE('2019-03-22 00:00:00', '%Y-%m-%d %H:%i:%s') AND 
          ((bdcloud_module_app_name = 'tcbox'     and bdcloud_cateid = 1      and evtType = 'show'     and evtName = 'novel-detail'))
 GROUP BY DATE(event_day)
 LIMIT 100;
```

**To Reproduce**
1. Use COUNT and HLL_UNION_AGG in a column with function like IF or COALESCE. For example:
```
IF (true, HLL_UNION_AGG(uv),count(distinct cuid))
IF(HLL_UNION_AGG(uv)!=count(distinct cuid), HLL_UNION_AGG(uv),count(distinct cuid))
COALESCE(IF(count(distinct cuid)>1, count(distinct cuid), null), HLL_UNION_AGG(uv))

```
2. The function always return 1.

**Expected behavior**
return correct value

**Screenshots**
<img width="711" alt="MacHi 2019-03-22 17-47-57" src="https://user-images.githubusercontent.com/6831829/54814422-a95c1600-4cca-11e9-8f77-efa4cbd33dd0.png">

**Comment by chenhao7253886** [comment]
Can you try to explicitly cast HLL_UNION_AGG' result to bigint, and is the query return right value ?

**Comment by qdore** [comment]
Use cast type to bigint is fine:
<img width="955" alt="MacHi 2019-03-22 18-16-32" src="https://user-images.githubusercontent.com/6831829/54816202-a400ca80-4cce-11e9-82ae-934bdda395d2.png">

**Comment by qdore** [comment]
Still has some problems:

<img width="958" alt="MacHi 2019-03-22 18-18-42" src="https://user-images.githubusercontent.com/6831829/54816338-f93cdc00-4cce-11e9-9252-90a0ff1dd76d.png">

**Comment by imay** [comment]
> Still has some problems:
> 
> <img alt="MacHi 2019-03-22 18-18-42" width="958" src="https://user-images.githubusercontent.com/6831829/54816338-f93cdc00-4cce-11e9-9252-90a0ff1dd76d.png">

@qdore Because your `if` function's second argument is a `bool` type, so this `if` function will return a `bool` type. If you change second argument `count > 1` to `count`, it would be wok

**Comment by qdore** [comment]
> > Still has some problems:
> > <img alt="MacHi 2019-03-22 18-18-42" width="958" src="https://user-images.githubusercontent.com/6831829/54816338-f93cdc00-4cce-11e9-9252-90a0ff1dd76d.png">
> 
> @qdore Because your `if` function's second argument is a `bool` type, so this `if` function will return a `bool` type. If you change second argument `count > 1` to `count`, it would be wok

My fault,  thank you so much :)
