### ISSUE TITLE
set password failed

### ISSUE THREAD

**Issue by imay** [apache/incubator-doris#797]
**Describe the bug**
I can't set password.

**To Reproduce**
execute `SET PASSWORD = PASSWORD('111')`

Doris will execute failed with message "ERROR 1064 (HY000): User 'root'@'a.b.c.d' does not exist"

Server version: 5.1.0 Doris version 0.9.9-release

**Comment by morningman** [comment]
I try this logic in mysql:

case 1:
1. create user `cmy@'%'`
2. login using `cmy` from hostA, 
3. `select user();` returns `cmy@'hostA'`, and `select current_user();` returns `cmy@'%'`
3. now we can set password for `cmy@'%'`

case 2:
1. create user `cmy@'hostA'`
2. login using `cmy` from host
3. `select user();` returns `cmy@'hostA'`, and `select current_user();` returns `cmy@'hostA'`
4. now we can not set password for `cmy@'%'`, but we can set password for `cmy@'hostA'`

So the conclusion is:

user is allowed to set password for what `current_user()` returns
