### ISSUE TITLE
[Bug] Spark connector not support STRING type

### ISSUE THREAD

**Issue by Wahno** [apache/incubator-doris#7990]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Apache doris 0.15.0

### What's Wrong?

When the STRING type is in the doris table structure, using the spark connector to import data will throw an exception: Unsupported type STRING.

### What You Expected?

Support STRING type

### How to Reproduce?

Create a table containing a STRING type, and use the Spark connector to import data to this table.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hf200012** [comment]
Which version of your connector is？

**Comment by Wahno** [comment]
2.3.4-2.11-1.0.0-SNAPSHOT，compiled latest code from the master branch.

**Comment by hf200012** [comment]
<dependency>
  <groupId>org.apache.doris</groupId>
  <artifactId>doris-spark-connector</artifactId>
  <version>2.3.4-2.11-SNAPSHOT</version>
</dependency>

**Comment by Wahno** [comment]
Yes. You can check getCatalystType method from SchemaUtils class.

**Comment by hf200012** [comment]
> 2.3.4-2.11-1.0.0-SNAPSHOT，compiled latest code from the master branch.

```
<dependency>
  <groupId>org.apache.doris</groupId>
  <artifactId>doris-spark-connector</artifactId>
  <version>2.3.4-2.11-SNAPSHOT</version>
</dependency>
```

**Comment by Wahno** [comment]
Maybe we should add a mapping of STRING type and DataTypes.StringType.

**Comment by hf200012** [comment]
> Maybe we should add a mapping of STRING type and DataTypes.StringType.

I saw that this place needs to be added. What is your usage method? It may not be completely modified last time. You are welcome to submit a PR

**Comment by Wahno** [comment]
> > Maybe we should add a mapping of STRING type and DataTypes.StringType.
> 
> I saw that this place needs to be added. What is your usage method? It may not be completely modified last time. You are welcome to submit a PR

The usage is that the user only needs to specify the table identifiers of spark and doris, and the structure of the spark table and the doris table may be changed. My idea is to read the schema of the doris table and construct the matching data in spark and import it into doris.

**Comment by hf200012** [comment]
> > > Maybe we should add a mapping of STRING type and DataTypes.StringType.
> > 
> > 
> > I saw that this place needs to be added. What is your usage method? It may not be completely modified last time. You are welcome to submit a PR
> 
> The usage is that the user only needs to specify the table identifiers of spark and doris, and the structure of the spark table and the doris table may be changed. My idea is to read the schema of the doris table and construct the matching data in spark and import it into doris.

The RDD that was only considered before, this part of SQL may be ignored

Thank you very much for your PR

**Comment by Wahno** [comment]
> > > > Maybe we should add a mapping of STRING type and DataTypes.StringType.
> > > 
> > > 
> > > I saw that this place needs to be added. What is your usage method? It may not be completely modified last time. You are welcome to submit a PR
> > 
> > 
> > The usage is that the user only needs to specify the table identifiers of spark and doris, and the structure of the spark table and the doris table may be changed. My idea is to read the schema of the doris table and construct the matching data in spark and import it into doris.
> 
> The RDD that was only considered before, this part of SQL may be ignored
> 
> Thank you very much for your PR

I have observed that there may be problems with the delimiter used in data splicing, such as '\t' or '\n' in normal data. I have replaced data transmission with json in my usage. Of course there may be performance degradation, but this method is still usable in the case of poor data quality.
