### ISSUE TITLE
[Bug] BE crashed after altering int field to string

### ISSUE THREAD

**Issue by englefly** [apache/incubator-doris#8073]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

branch-0.14
branch-0.15 df2c7563b08e94801daeb4370a1627886dbc3d34

### What's Wrong?

after alter schema, changing bigint column to string (release 0.14) or varchar (release 0.15), be is down.

### What You Expected?

safely alter schema:
`alter table table_1 modify column b varchar(1);`

### How to Reproduce?

1. create a table `table_1`
```
CREATE TABLE `table_1` ( 
    `a` bigint(20) NULL COMMENT "主键", 
    `b` int(11) NULL COMMENT "", 
ENGINE=OLAP UNIQUE KEY(`a`) COMMENT "" 
DISTRIBUTED BY HASH(`a`) BUCKETS 8 
PROPERTIES ( 
    "replication_num" = "1", 
    "in_memory" = "false", 
    "storage_format" = "V2"
);
```
2. load data into `table_1` ( 10000 tuples)
3. `alter table table_1 modify column b varchar(1);`
4. BE crashed.

### Anything Else?

with a few tuples, eg. 10 tuples, after altering schema, BE still alive, but results of `select * from table_1`  are messed.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 254288935** [comment]
alter table时，目前不支持BIGINT到CHAR的转换，
是否需要支持BIGINT到VARCHAR的转换呢？

**Comment by morningman** [comment]
> alter table时，目前不支持BIGINT到CHAR的转换， 是否需要支持BIGINT到VARCHAR的转换呢？

I think we do support convert BIGINT to CHAR. Why you say it not support?

**Comment by 254288935** [comment]
> > alter table时，目前不支持BIGINT到CHAR的转换， 是否需要支持BIGINT到VARCHAR的转换呢？
> 
> I think we do support convert BIGINT to CHAR. Why you say it not support?

mysql> create table t(a int, b bigint) duplicate key(a) distributed by hash(a) buckets 5 PROPERTIES ("replication_num" = "1");
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t values(1,111111111);
Query OK, 1 row affected (0.04 sec)
{'label':'insert_37ddf33352aa45e2-be78d5486b802511', 'status':'VISIBLE', 'txnId':'23'}

mysql> select * from t;
+------+-----------+
| a    | b         |
+------+-----------+
|    1 | 111111111 |
+------+-----------+
1 row in set (0.01 sec)

mysql> alter table t modify column b char(10);
ERROR 1105 (HY000): errCode = 2, detailMessage = Can not change BIGINT to CHAR

----
master分支上，我是这样操作的
