### ISSUE TITLE
[Bug] 当开启向量化时函数或语法报错

### ISSUE THREAD

**Issue by westgatepark** [apache/incubator-doris#8149]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0.15.1-rc09

### What's Wrong?

当开启向量化时: SET enable_vectorized_engine=true,使用某些语法或函数会提示参数类型错误或者函数不存在，例如case when.. 。 show version() select current_timestamp等

### What You Expected?

兼容没开启向量化时能正常执行的sql

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yiguolei** [comment]
最新的master 已经支持了，你可以更新一下试试
