### ISSUE TITLE
[Bug] s3 BROKER LOAD 不识别s3前缀

### ISSUE THREAD

**Issue by westgatepark** [apache/incubator-doris#8155]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0.15.1-rc09

### What's Wrong?

  **使用broker load 装载s3数据时，报错：ERROR 1064 (HY000): errCode = 2, detailMessage = Invalid export path. please use valid 'HDFS://', 'AFS://' or 'BOS://' path.**
模版参考的show broker load 中的：
        LOAD LABEL example_db.label11
        (
        DATA INFILE("s3a://my_bucket/input/file")
        INTO TABLE `my_table`
        FORMAT AS "parquet"
        (k1, k2, k3)
        )
        WITH BROKER my_s3a_broker
        (
        "fs.s3a.access.key" = "xxxxxxxxxxxxxxxxxxxxxxxxxx",
        "fs.s3a.secret.key" = "yyyyyyyyyyyyyyyyyyyy",
        "fs.s3a.endpoint" = "s3.amazonaws.com"
        );

  **可以正常通过s3sdk装载数据:**
      LOAD LABEL load_label
      (
      ...
      )
      WITH S3
      (
      ..
      );

**但是这样就没法指定节点去执行装载任务，因为虽然be做了资源隔离,但是s3 sdk装载任务不受隔离限制。**

### What You Expected?

**期望当开启资源隔离时，根据 用户来分配执行 s3 sdk load 所占用的资源。
或者使s3 broker load 正常运行，这样可以根据broker name 来映射对应的资源组。**

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yiguolei** [comment]
”BE 做了资源隔离“ 具体是怎么做的啊？ 你是隔离了broker吗？

**Comment by westgatepark** [comment]
be:
alter system modify backend "***:9050" set ("tag.location" = "group_batch");
...
...
alter system modify backend "***:9050" set ("tag.location" = "group_stream");
...
...
user:
set property for '***' 'resource_tags.location' = 'group_batch';
set property for '***' 'resource_tags.location' = 'group_stream';

**Comment by westgatepark** [comment]
我把一些be节点卸载了broker组件,这些节点依然参与了s3load，所以目前没法对装载任务占用资源隔离.

**Comment by caiconghui** [comment]
just simply separated by broker name?

**Comment by westgatepark** [comment]
您是说指定broker name吗：
LOAD LABEL ...
WITH BROKER <broker_name>
...

这样会报错识别不了s3前缀，所以我只能s3 sdk load：
...
WITH S3
...
