### ISSUE TITLE
Doris On ES链接至阿里云ES 报错

### ISSUE THREAD

**Issue by feiver** [apache/incubator-doris#8192]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

1064 - errCode = 2, detailMessage = fetch es table [***] metadata failure: index[***] type[_doc] mapping not found for the ES Cluster

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hf200012** [comment]
you are using it incorrectly
```
CREATE EXTERNAL TABLE `test_3` (
  `order_id` varchar(200) COMMENT "",
  `taxful_total_price` decimal(20,4) COMMENT "",
  `total_quantity` int COMMENT ""
) ENGINE=ELASTICSEARCH 
PROPERTIES (
"hosts" = "http://e****y2.public.elasticsearch.aliyuncs.com:9200",
"index" = "kibana_sample_data_ecommerce",
"type" = "_doc",
"user" = "***",
"password" = "****@",
"nodes_discovery"="false"
);
```

**Comment by feiver** [comment]
经查验 为 type错误
