### ISSUE TITLE
The "root" user without password failed to connection FE-Server 

### ISSUE THREAD

**Issue by zhaidongbo** [apache/incubator-doris#822]
**Describe the bug**
The "root" user without password failed to connection FE-Server 
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading authorization packet', system error: 0

![image](https://user-images.githubusercontent.com/3367429/55071100-a7c39100-50c2-11e9-9e54-c960e76e4e0b.png)

The root should be add to currentUser?

**Comment by imay** [comment]
Could you provide us you connect command?
