### ISSUE TITLE
[Bug] replace()无法替换首位字符，仅对首位以后的字符生效。

### ISSUE THREAD

**Issue by WhiskeyShang** [apache/incubator-doris#8220]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0.13.15-4e19c23

### What's Wrong?

[Bug] replace()无法替换首位字符，仅对首位以后的字符生效。
例如：
select REPLACE("http://www.baidu.com:9090", "http", "");

### What You Expected?

可以替换任意位置出现的字符

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dataalive** [comment]
i tried this on version 0.13.15, it shows the same error like above.  
mysql> select REPLACE("http://www.baidu.com:9090", "http", "");
+--------------------------------------------------+
| replace('http://www.baidu.com:9090', 'http', '') |
+--------------------------------------------------+
| http://www.baidu.com:9090                        |
+--------------------------------------------------+
1 row in set (2.81 sec)

mysql> select REPLACE("http://www.baidu.com:9090", "ttp", "");
+-------------------------------------------------+
| replace('http://www.baidu.com:9090', 'ttp', '') |
+-------------------------------------------------+
| h://www.baidu.com:9090                          |
+-------------------------------------------------+
1 row in set (0.00 sec)

on version 0.15 ,it works fine.

mysql> select REPLACE("http://www.baidu.com:9090", "http", "");
+--------------------------------------------------+
| replace('http://www.baidu.com:9090', 'http', '') |
+--------------------------------------------------+
| ://www.baidu.com:9090                            |
+--------------------------------------------------+
1 row in set (0.01 sec)

**Comment by qidaye** [comment]
Thanks for your report @WhiskeyShang @dataalive . 
This bug has been fixed in [pr](https://github.com/apache/incubator-doris/pull/6605)
