### ISSUE TITLE
Powerful Improve: parallel scan exec instance

### ISSUE THREAD

**Issue by kangkaisen** [apache/incubator-doris#831]
Currently, we always allocate one scan instance exec node for one fragment in one BE, even if there are a lot of tablets and the cluster resource is abundant.

So, I think we could parallel scan exec instance ，take full advantage of cluster resource and speed the query.

Specifically speaking，we could introduce a new config `parallel_scan_exec_instance_num`.
If the `parallel_scan_exec_instance_num` is 10 and there are 100 tablets one fragment in one BE, we could allocate 100 / 10 = 10 scan instance exec node for one fragment in one BE.

The following is the test result for this improve:
All SQL are from our prod env
The config `parallel_scan_exec_instance_num` is 5.
**I test the following SQL use same BE cluster and different FE(whether has this improve)**

SQL 1:
```
select count(*), datekey from table group by datekey order by datekey;
```
SQL 2:
```
SELECT  sum(account_dr) AS account_dr, SUM(account_cr) AS account_cr
FROM table
WHERE  deliver_date >= '2019-03-01' AND deliver_date <= '2019-03-30';
```

SQL 3:
```
select count(*) from (
select crawl_time_hour0, room_status_result, row_number()
   over(partition by crawl_time_hour0, mt_room_id, mt_breakfast order by mt_room_status asc, comp_room_status asc) rn
from table
where  datekey <= 20190327 and  datekey >= 20190325 and crawl_time_hour0 >= 11230 and crawl_time_hour0 <= 12000) t;
```
SQL 4:
```
select count(*)  
FROM  t1
INNER JOIN [shuffle] t5
   ON ((t1.dt = t5.dt) AND (t1.wm_poi_id = t5.wm_poi_id))
INNER JOIN [shuffle]  t6
   ON ((t1.dt = t6.dt) AND (t1.wm_poi_id = t6.wm_poi_id))
where t1.dt <= 20190327 and t1.dt >= 20190201;
```

SQL 5:
```
select count(*) from (
select crawl_time_hour0, room_status_result, row_number()
   over(partition by crawl_time_hour0, mt_room_id, mt_breakfast order by mt_room_status asc, comp_room_status asc) rn
from table
where  datekey <= 20190328 and  datekey >= 20190320) t;
```

The following picture illustrate the test result:

![image](https://user-images.githubusercontent.com/9894906/55157763-2fc79a80-5198-11e9-9e56-73d31fdb98af.png)

**Comment by imay** [comment]
@kangkaisen 

Wonderful job!!!

It is very useful for single query's performance. However this is bad for broadcast join, because inner table will be sent more times, and more memory would be taken. So  I think adding a new config to limit max instances is acceptable. 

And now Doris's query optimizer can't decide when to use broadcast join or shuffle join, we should improve our optimizer. And our optimizer should decide how many scan instances should be allocated according to its data size. Then we can drop this config item. 

Looking forward to your PR

**Comment by kangkaisen** [comment]
@imay Thanks for your reminder.  I will not parallel scan exec instance for  broadcast join inner table and small size table.

As for the  `max instances limit`，I want to do this initially, but I don't find a good way to do this.
If we want to limit the max instances for All BE, different cluster has different BE number，but we don't have cluster level config and only one server level config couldn't do this limit well.
If we want to limit the max instances for one BE, I think we could indirectly do this by `parallel_scan_exec_instance_num` config.

**Comment by chenhao7253886** [comment]
Now we have support parallel execution for query without join, you can set mt_dop to decide start how many threads for one fragment in one host, so i think you need't support this config and i will support parallel join by partiton join later, and your SQL does't contain GroupBy all,  if you query contains Groupby , the computing power of AggregateNode will be matched with the computing power of ScanNode.  I wonder if I understand all your ideas.

**Comment by imay** [comment]
> If we want to limit the max instances for one BE, I think we could indirectly do this by `parallel_scan_exec_instance_num` config.

I think that `parallel_scan_exec_instance_num` default value should be 1 to make no influence when upgrading cluster.

**Comment by kangkaisen** [comment]
> > If we want to limit the max instances for one BE, I think we could indirectly do this by `parallel_scan_exec_instance_num` config.
> 
> I think that `parallel_scan_exec_instance_num` default value should be 1 to make no influence when upgrading cluster.

Yes, I agree with you. set 1 or 0 should both be Ok.
