### ISSUE TITLE
[Bug] doris on es 中 连接es ip问题

### ISSUE THREAD

**Issue by emmataobao** [apache/incubator-doris#8331]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0.14.0

### What's Wrong?

使用doris 连接 docker安装的es时，使用http://宿主机ip：9200/，出现连接拒绝会自动跳向docker ip。异常拒绝的ip也是docker ip
![1646377709(1)](https://user-images.githubusercontent.com/46233536/156716216-e87d1464-9fc1-44d9-98fe-90086e4d4731.png)
我已经使用 "nodes_discovery" = "false"

### What You Expected?

有什么办法可以解决

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dataalive** [comment]
这个报错是refused不是timed out，所以先确认下172.17.0.2上9200是否打开了并且是否防火墙允许访问？

**Comment by emmataobao** [comment]
> 这个报错是refused不是timed out，所以先确认下172.17.0.2上9200是否打开了并且是否防火墙允许访问？

我在配置上的ip是 "hosts" = "http://192.168.5.242:9200" , 但是doris 连接的时候将ip转成docker ip172.17.0.2 ，为什么出现refused，是因为doris测试节点上有其他容器的ip是172.17.0.2，所以出现了refused。我现在的困惑是我的配置esip是192，结果连接转成172，导致连接不上目标es，我的es节点是防火墙端口开放的，我已经配置了 "nodes_discovery" = "false"。

**Comment by emmataobao** [comment]
如果我的es集群部署方式是物理机部署，或者be安装在es部署节点上，则不会出现上述问题。如果我的es集群为docker部署，且宿主机无be部署则会出现上述问题。

**Comment by emmataobao** [comment]
这个问题同样出现使用docker在doris部署上，我使用编译后自己制作镜像进行部署。但是我部署好be和fe，在ALTER SYSTEM ADD BACKEND "host:port"，我的host使用的是宿主机ip的话，SHOW PROC '/backends'; ， isAlive就是false，我不得不使用docker容器和宿主机ip一致才没有出现问题。

**Comment by dataalive** [comment]
> 

设置的时候是否参考了官网这里的说明：

IP 绑定
因为有多网卡的存在，或因为安装过 docker 等环境导致的虚拟网卡的存在，同一个主机可能存在多个不同的 ip。当前 Doris 并不能自动识别可用 IP。所以当遇到部署主机上有多个 IP 时，必须通过 priority_networks 配置项来强制指定正确的 IP。

**Comment by emmataobao** [comment]
> priority_networks
谢谢，我已经知道我部署的问题在哪里，es的问题我也知道了。我配置参数没有问题，主要部署的测试es是单节点版本所以network.host指向的是docker内部ip，doris的运行逻辑是他会先去拿metadata，他通过我配置的ip端口拿metadata，但是后续的请求会使用metadata的ip和端口号，导致我的配置只能获取metadata，所有的请求没有使用。造成了配置和请求的ip地址不一致问题。谢谢
![1646895458(1)](https://user-images.githubusercontent.com/46233536/157606365-de897a7c-6eb3-440a-aa9e-a9a511b2734a.png)

**Comment by doglex** [comment]
一样的问题。 我的机器有多个ip， 填的能连通的ip，结果却走了不能连通的ip，就导致无法连通。
