### ISSUE TITLE
[Bug] ssb load data failed with Missing required fields in request: need_gen_rollup

### ISSUE THREAD

**Issue by HackToday** [apache/incubator-doris#8417]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

latest master branch commit id: f4663ad2eb3fc8ce929304ccdea09d87bb86ec8a

### What's Wrong?

Following https://doris.apache.org/zh-CN/benchmark/star-schema-benchmark.html#%E6%95%B0%E6%8D%AE%E5%87%86%E5%A4%87
to import data, with  `bash load-dimension-data.sh`

run with with following error

```
W0309 17:33:55.149286 765291 stream_load_executor.cpp:80] fragment execute failed, query_id=ed488e005d1adc92-796838cb0f1bd68d, err_msg=NodeChannel[11686-11001], load_id=ed488e005d1adc92-796838cb0f1bd68d, txn_id=1013, node=192.168.42.126:8060, open failed, err: failed to open tablet writer, error=Bad request, error_text=[E1003]Missing required fields in request: need_gen_rollup, hos, id=ed488e005d1adc92-796838cb0f1bd68d, job_id=-1, txn_id=1013, label=74da78b0-5146-4e60-aed7-3f4d0e100f20, elapse(s)=0
W0309 17:33:55.149302 765570 status.h:260] warning: Status msg truncated, OK: cancelled: NodeChannel[11686-11001], load_id=ed488e005d1adc92-796838cb0f1bd68d, txn_id=1013, node=xxxx:8060, open failed, err: failed to open tablet writer, error=Bad request, error_text=[E1003]Missing required fields in request: need_gen_rollup, hos precise_code:1 
```

### What You Expected?

bash load-dimension-data.sh would run success

### How to Reproduce?

Just follow the official build and run and load data guide as following 

https://doris.apache.org/zh-CN/installing/compilation.html#%E4%BD%BF%E7%94%A8-docker-%E5%BC%80%E5%8F%91%E9%95%9C%E5%83%8F%E7%BC%96%E8%AF%91-%E6%8E%A8%E8%8D%90
https://doris.apache.org/zh-CN/benchmark/star-schema-benchmark.html#%E6%95%B0%E6%8D%AE%E5%87%86%E5%A4%87

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by HackToday** [comment]
@morningman  Could someone help check if new code breaks ?

**Comment by HackToday** [comment]
I used commit `b536c1850fc8e29a11130dd4743796eee261f7dc`, it works, so it should be a new bug between such two commits

**Comment by yiguolei** [comment]
@HackToday Sorry, it's my fault. I have fixed this bug in 8420 pr. I have tested it on my local machine. Could you please test it?

**Comment by HackToday** [comment]
@yiguolei  sure. But may be tomorrow. many things today. :0
if your verification works, maybe it is ok for that.
