### ISSUE TITLE
0.15.0 rc4 shutdown

### ISSUE THREAD

**Issue by dp0304** [apache/incubator-doris#8523]
<img width="898" alt="image" src="https://user-images.githubusercontent.com/1586562/158939409-842f37ea-35d2-4ef4-825b-433e075f45cb.png">

*** Aborted at 1647509176 (unix time) try "date -d @1647509176" if you are using GNU date ***
PC: @          0x37c6b9b tcmalloc::ThreadCache::ReleaseToCentralCache()
*** SIGSEGV (@0x0) received by PID 2890 (TID 0x7f92ad3bf700) from PID 0; stack trace: ***
    @          0x214c712 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f92cee6b980 (unknown)
    @          0x37c6b9b tcmalloc::ThreadCache::ReleaseToCentralCache()
    @          0x37c6f25 tcmalloc::ThreadCache::ListTooLong()
    @          0x13a07bb doris::ScalarColumnVectorBatch<>::~ScalarColumnVectorBatch()
    @          0x1478b13 doris::segment_v2::BinaryDictPageDecoder::~BinaryDictPageDecoder()
    @          0x1c22e30 doris::segment_v2::FileColumnIterator::~FileColumnIterator()
    @          0x1c22ff2 doris::segment_v2::FileColumnIterator::~FileColumnIterator()
    @          0x1bfba1e doris::segment_v2::SegmentIterator::~SegmentIterator()
    @          0x1bfbf52 doris::segment_v2::SegmentIterator::~SegmentIterator()
    @          0x1493db9 std::_Sp_counted_ptr<>::_M_dispose()
    @          0x1aa9939 doris::OlapScanner::close()
    @          0x1a65549 doris::OlapScanNode::scanner_thread()
    @          0x14f81ef doris::PriorityThreadPool::work_thread()
    @          0x2118717 thread_proxy
    @     0x7f92cee606db start_thread
    @     0x7f92ce7eb71f clone
    @                0x0 (unknown)
start time: Fri Mar 18 09:35:30 CST 2022

I have deployed 0.15 rc4 cluster, but be nodes are down every day.
Please commit a  0.15 fix

**Comment by xiaokang** [comment]
@dp0304 Can you provide the steps to reproduce the problem? such as cluster configuration, SQL query, table schema and sample data.

**Comment by xiaokang** [comment]
you can follow the instructions in https://github.com/apache/incubator-doris/discussions/8411 .

**Comment by dp0304** [comment]
并没有操作。查看后台日志对应时刻是大量刷屏。  8台BE集群每天都down两三个节点。
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/1586562/158950162-cca95a13-39c1-4bd1-a516-52e27ed2b9bb.png">

**Comment by dp0304** [comment]
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/1586562/158952894-a2d73bab-5acc-46c2-aef4-8932581bcd2f.png">

@xiaokang 对应fe的warning是这样。

**Comment by xiaokang** [comment]
OK. The warning message is not enough to figure out the reason of the crash problem. 

Is there anything happen before be coredump, eg. running some query ? You can provide the whole log file contains the coredump info.

**Comment by dp0304** [comment]
It seems  to happen at consistency  check time, I will enable minidump tonight.  @xiaokang

**Comment by xiaokang** [comment]
OK. More information such as logs and minidump will be helpful.

**Comment by hf200012** [comment]
@dp0304 You add my WeChat: 35926237

**Comment by xiaokang** [comment]
@dp0304 Have you got the minidump and logs for the crash? By the way, it will be more efficient to discuss the details with @hf200012 by WeChat.

**Comment by dp0304** [comment]
@xiaokang @hf200012 I staggered the consistency check time with the stream load time and it won't crash for now. Can you wait for the weekend?

**Comment by xiaokang** [comment]
> @xiaokang @hf200012 I staggered the consistency check time with the stream load time and it won't crash for now. Can you wait for the weekend?

Sure.
