### ISSUE TITLE
[Feature][Vectorized] vectorized table functions support

### ISSUE THREAD

**Issue by BiteTheDDDDt** [apache/incubator-doris#8526]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

We still have some vectorized table functions unimplemented. This issue will tracks their progress. You can also declare in this issue that you will implement which function 

* explode_split #8448
* explode_bitmap #8890
* explode_json_array_int  #8539
* explode_json_array_double #8539
* explode_json_array_string #8539

only supported on vectorized engine:
* explode_numbers #8509
* explode_outer #8766

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Lchangliang** [comment]
I will implement the explode_json_array_int function.

**Comment by Lchangliang** [comment]
I find that the explode_json_array_int implementations the same as the other two (explode_json_array_double, explode_json_array_string)，So I will implement all of them.
