### ISSUE TITLE
canal同步指定字段到doris报错

### ISSUE THREAD

**Issue by yym12** [apache/incubator-doris#8573]
doris表结构
![image](https://user-images.githubusercontent.com/41983444/159391931-03c50b3a-260c-438b-af66-5aa7ffcc533e.png)

源表结构
![image](https://user-images.githubusercontent.com/41983444/159391998-a75c9cbb-6a99-42c9-b8d4-e3c21b196082.png)

同步job
![image](https://user-images.githubusercontent.com/41983444/159392040-b4fcf62d-866c-4096-b0ad-437225d83904.png)

**Comment by morningman** [comment]
Please offer:
1. Doris version
2. Error msg

**Comment by morningman** [comment]
cc @xy720

**Comment by yym12** [comment]
Doris version ： 0.15
Error Msg: 
![image](https://user-images.githubusercontent.com/41983444/159394265-8a07f68c-d342-4417-9e2e-1300dc591c75.png)

**Comment by yym12** [comment]
需要根据binlog里的字段进行dummy_column设空

![Uploading image.png…]()
