### ISSUE TITLE
[Bug] Broker Load 导入Hdfs 10亿量级数据失败

### ISSUE THREAD

**Issue by 666chaoge666** [apache/incubator-doris#8600]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

当前版本：1.0.0-preview

### What's Wrong?

Broker Load 导入Hdfs 10亿量级数据失败
做了以下尝试，没有改善：
1 增加以及减少单个 tablet 最大 version 的数量：max_tablet_version_num
2 增加broker节点导入数据上限：max_bytes_per_broker_scanner
3 增加导入任务的内存：exec_mem_limit
4 修改compaction线程：max_compaction_threads
5 修改BE 上单个 Tablet 的写入速度限制：push_write_mbytes_per_sec

！！！跪求大神帮忙看下！！！

以下为报错信息：
W0321 17:35:01.568506 12540 tablet_sink.cpp:133] index channel has intolerable failure. 192.168.12.218, err: add row failed. NodeChannel[16764-10005], load_id=1906b7af29354e8a-beb34b1b8954ebe8, txn_id=4089, node=10005:8060, add batch req success but status isn't ok, err: tablet writer write failed, tablet_id=16817, txn_id=4089, err=-238; 

### What You Expected?

因为渠道分区数据都在10亿以上，希望成功导入Hdfs中10亿及以上量级数据

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dataalive** [comment]
pls show the table schema , and query sql without sensitive info.

**Comment by 666chaoge666** [comment]
> pls show the table schema , and query sql without sensitive info.

建表及load语句如下：
CREATE TABLE t_user_dau_detail (
    dt varchar(10)  DEFAULT "",
  channel varchar(36)  DEFAULT "",
  uuid varchar(124) DEFAULT ""

)
DISTRIBUTED BY HASH(`dt`) BUCKETS 100
PROPERTIES("replication_num" = "1");


LOAD LABEL example_db.abc
(
DATA INFILE("hdfs://nameservice1/user/hive/warehouse/t_user_detail/dt=20220302/channel=abc/*/*")
INTO TABLE t_user_dau_detail
COLUMNS TERMINATED BY "\\x01"
FORMAT AS "orc"
(uuid)
COLUMNS FROM PATH AS (dt,channel)
SET(
    dt=dt,
    channel=channel,
    uuid=uuid
)
)
WITH BROKER 'broker_hdfs'
PROPERTIES
(
    "max_filter_ratio" = "1",
    "exec_mem_limit" = "3298534883328"
);

**Comment by lide-reed** [comment]
insert into 1亿 条数据的表也会发生同样的问题，我后面找个必现的case
