### ISSUE TITLE
[Bug] compile fe failed on branch 'master'

### ISSUE THREAD

**Issue by Tanya-W** [apache/incubator-doris#8664]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

compile fe failed at latest code

### What You Expected?

fix compile

### How to Reproduce?

It should be introduced by this pr: https://github.com/apache/incubator-doris/pull/8635

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yiguolei** [comment]
Could you provide the error stack or messages?

**Comment by Tanya-W** [comment]
> 

[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] xxx/incubator-doris/fe/fe-core/src/main/java/org/apache/doris/task/AgentClient.java:[60,28] cannot find symbol
  symbol:   method submitEtlTask(org.apache.doris.thrift.TMiniLoadEtlTaskRequest)
  location: variable client of type org.apache.doris.thrift.BackendService.Client
[ERROR] xxx/incubator-doris/fe/fe-core/src/main/java/org/apache/doris/task/AgentClient.java:[126,28] cannot find symbol
  symbol:   method getEtlStatus(org.apache.doris.thrift.TMiniLoadEtlStatusRequest)
  location: variable client of type org.apache.doris.thrift.BackendService.Client
[ERROR] xxx/incubator-doris/fe/fe-core/src/main/java/org/apache/doris/task/AgentClient.java:[177,19] cannot find symbol
  symbol:   method deleteEtlFiles(org.apache.doris.thrift.TDeleteEtlFilesRequest)
  location: variable client of type org.apache.doris.thrift.BackendService.Client

**Comment by yiguolei** [comment]
It's my fault, I will fix it.

**Comment by yiguolei** [comment]
@Tanya-W I‘ve fixed, could you please have a try?

**Comment by Tanya-W** [comment]
> @Tanya-W I‘ve fixed, could you please have a try?

I try again, it's ok, thanks!
