### ISSUE TITLE
[Enhancement] Support DROP USER [IF EXISTS]

### ISSUE THREAD

**Issue by zingdle** [apache/incubator-doris#8715]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

## Enhancement

Currently Doris [doesn't support](https://doris.apache.org/sql-reference/sql-statements/Account%20Management/DROP%20USER.html) `IF EXISTS` option in `DROP USER` statement [like MySQL](https://dev.mysql.com/doc/refman/5.7/en/drop-user.html). It would be great to have this feature.

Silimar statements: `CREATE USER`, `CREATE ROLE`, `DROP ROLE`, etc.

### Solution

I'm kind of busy these days, but I'm willing to walk through the code and submit PR once I'm free.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jackwener** [comment]
> I'm kind of busy these days, but I'm willing to walk through the code and submit PR once I'm free.

It's great, If you have some problem, you can contact maintainers in this issue. like this ` @jackwener `

**Comment by zingdle** [comment]
@jackwener  I've submitted a PR and PTAL at your convenience :)
