### ISSUE TITLE
[Bug] get_hash_value_fvn DCHECK failed

### ISSUE THREAD

**Issue by xinyiZzz** [apache/incubator-doris#8810]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

trunk

### What's Wrong?

![70b08dd19cc73d83fa9b45ef6719c88c](https://user-images.githubusercontent.com/13197424/161287488-659066f3-e741-45a5-96bf-f35baacac9f5.jpg)

<img width="788" alt="image" src="https://user-images.githubusercontent.com/13197424/161287620-e9940483-8e2b-4ee6-9baf-697246457b90.png">

compile failed:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/13197424/161288577-98d7382e-e476-4638-865a-9929bd5ffe68.png">

### What You Expected?

win

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by morningman** [comment]
Better to paste text instead of image.
So that it can be easily searched

**Comment by xinyiZzz** [comment]
> Better to paste text instead of image. So that it can be easily searched

Ok, i got it
