### ISSUE TITLE
[Bug] Failed to execute SparkLoadJob 

### ISSUE THREAD

**Issue by zhengshengjun** [apache/incubator-doris#8819]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master branch

### What's Wrong?

Hi, currently I am trying Spark Load Job，but ended up with error msg like this every time:  txn does not exist. id: 0

+-------+--------------+-----------+-------------------+-------+---------+-------------------------------------------------------+----------------------------------------------------------------------------------+---------------------+--------------+---------------+---------------+---------------------+------+-----------------------------------------------------------------------------------------------------------------------+---------------+--------------+
| JobId | Label        | State     | Progress          | Type  | EtlInfo | TaskInfo                                              | ErrorMsg                                                                         | CreateTime          | EtlStartTime | EtlFinishTime | LoadStartTime | LoadFinishTime      | URL  | JobDetails                                                                                                            | TransactionId | ErrorTablets |
+-------+--------------+-----------+-------------------+-------+---------+-------------------------------------------------------+----------------------------------------------------------------------------------+---------------------+--------------+---------------+---------------+---------------------+------+-----------------------------------------------------------------------------------------------------------------------+---------------+--------------+
| 16006 | doris_goods  | CANCELLED | ETL:N/A; LOAD:N/A | SPARK | NULL    | cluster:spark0; timeout(s):3600; max_filter_ratio:0.0 | type:ETL_SUBMIT_FAIL; msg:errCode = 2, detailMessage = txn does not exist. id: 0 | 2022-04-01 19:41:39 | NULL         | NULL          | NULL          | 2022-04-01 19:41:44 | NULL | {"Unfinished backends":{},"ScannedRows":0,"TaskNumber":0,"LoadBytes":0,"All backends":{},"FileNumber":0,"FileSize":0} | 0             | {}           |

### What You Expected?

After going through the code，the Error generated at the following code inside this fuction SparkLoadPendingTask#createEtlJobConf

`// add table indexes to transaction state`
`TransactionState txnState = Catalog.getCurrentGlobalTransactionMgr()`
                            `.getTransactionState(dbId, transactionId);`
`if (txnState == null) {`
        `throw new LoadException("txn does not exist. id: " + transactionId);`
`}`

Seems that the transaction has not begun（transactionId is 0 as shown in error message). The transaction begins lately when SparkLoadPendingTask start to execute. 

I wonder if there is something wrong in my test procedure, but I did follow the guide in official document. 

Thanks for your help .

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sumtumn** [comment]
I also got this error, but was on dev-1.0.0

**Comment by sumtumn** [comment]
I'm a begginer of doris. But i dug into this issue a bit. I think maybe this problem was caused by this https://github.com/apache/incubator-doris/pull/7371/files 
After this, call of LoadJob.beginTxn was moved from LoadJob.unprotectedExecute to SparkLoadPendingTask.executeTask, which was after the call of SparkLoadPendingTask.createEtlJobConf  and so in createEtlJobConf the transactionId was 0.

**Comment by zhengshengjun** [comment]
hi @sumtumn, thanks for your advice. I have solved this problem by a minor modification, and tested. Could you two help to see whether these changes works fine ?  @wangbo @sumtumn

**Comment by wangbo** [comment]
Please add a PR. @zhengshengjun
