### ISSUE TITLE
[Enhancement] keep `.conf` in `output/` after build `build.sh`

### ISSUE THREAD

**Issue by jackwener** [apache/incubator-doris#8888]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Every time we finish compiling, all files in `output/` will be reset. 

This means that if developers need to modify the files, they need to modify them after each compilation.

I think it's useful to keep `.conf`, `start_fe.sh` ..... those file unchanged for developer.

### Solution

There are some solutions. I think that we should discuss about this solution in this issue.

like, `.conf`, `start_...` aren't put in the `output/`.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by BiteTheDDDDt** [comment]
My solution:
1. edit `doris/conf/be.conf` and `doris/conf/fe.conf`
2. use `git update-index --no-skip-worktree doris/conf/be.conf` `git update-index --no-skip-worktree doris/conf/fe.conf`

**Comment by xinyiZzz** [comment]
+1，It seems more reasonable to regenerate `xxx_conf.templet` like Spark and Hive do,

My solution: move the recompiled /lib to another execution path via script and restart...

**Comment by jackwener** [comment]
> edit doris/conf/be.conf and doris/conf/fe.conf

I find this is right way to setup `be` and `fe` conf.

For `start_fe.sh`, we can set `JAVA_OPTS` in `fe.conf`
