### ISSUE TITLE
[Bug] predicate push down is different than 0.14

### ISSUE THREAD

**Issue by dataroaring** [apache/incubator-doris#8892]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master 1.0.0 1.0.1

### What's Wrong?

push down does not work good enough on left outer join.

### What You Expected?

works good enough.

### How to Reproduce?

`CREATE TABLE left_outer_left_table (
  `k1` varchar(200) NULL COMMENT ""
) ENGINE=OLAP
UNIQUE KEY(`k1`)
COMMENT "olap"
DISTRIBUTED BY HASH(`k1`) BUCKETS 20
PROPERTIES (
"in_memory" = "false",
"storage_format" = "V2",
"replication_num" = "1"
);`

`CREATE TABLE left_outer_right_table (
  `k2` varchar(100) NULL COMMENT ""
) ENGINE=OLAP
UNIQUE KEY(`k2`)
COMMENT "olap"
DISTRIBUTED BY HASH(`k2`) BUCKETS 20
PROPERTIES (
"in_memory" = "false",
"storage_format" = "V2",
"replication_num" = "1"
);`

`explain select k2 from left_outer_left_table a left outer join left_outer_right_table b on b.k2 = a.k1 where a.k1='uuid'`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by morrySnow** [comment]
fixed by #9703
