### ISSUE TITLE
[Bug] No matching function with signature: hex(hll)

### ISSUE THREAD

**Issue by xinyiZzz** [apache/incubator-doris#8928]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

trunk

### What's Wrong?

```
SELECT hex(hll_hash('1990-12-10'));
```

error:
```
No matching function with signature: hex(hll)
```

### What You Expected?

win

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jackwener** [comment]
I think that it's a enhancement instead of bug. 

BTW, I think is a good-first-issue for the newer of Doris, how do you think about this?

**Comment by cambyzju** [comment]
hi xinyiZzz,
The reason is:
1. **hll_hash** function return HLL data type;
2. but **hex** function do not support HLL data type as input;

Could I know which situation you need use sql like: _SELECT hex(hll_hash('1990-12-10'));_

**Comment by HappenLee** [comment]
Now we disable the implicit cast from `hll` and `bitmap` cast to `string`. So it's reasonable to get `No matching function with signature: hex(hll)`.

**Comment by xinyiZzz** [comment]
thanks for answer @jackwener @cambyzju @HappenLee
