### ISSUE TITLE
[Bug] There is no ccache in apache/incubator-doris:build-env-latest by default

### ISSUE THREAD

**Issue by kkfnui** [apache/incubator-doris#8932]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

docker build env: `apache/incubator-doris:build-env-latest`
code tag: 1.0.0-rc3

### What's Wrong?

```
[root@a6445c76a6fa incubator-doris]# sh build.sh clean
Python 2.7.5
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/share/maven
Java version: 11.0.13, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.13.0.8-1.el7_9.x86_64
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.10.0-957.27.2.el7.x86_64", arch: "amd64", family: "unix"
cmake version 3.22.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
1.10.2
/root/incubator-doris/env.sh: line 174: ccache: command not found
Thirdparty libraries need to be build ...
build.sh: line 185: /var/local/thirdparty/build-thirdparty.sh: No such file or directory
```

### What You Expected?

Compile it success by default env.

### How to Reproduce?

Just compile code in a new container of `apache/incubator-doris:build-env-latest`

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kkfnui** [comment]
It has been fixed in the newest version.
But there isn't new build env update for developer.

**Comment by yiguolei** [comment]
Great. I also find this problem....

**Comment by jackwener** [comment]
Great catch

**Comment by kkfnui** [comment]
There should be another problem.
```
build.sh: line 185: /var/local/thirdparty/build-thirdparty.sh: No such file or directory
```

It's because of env setting in docker file. Is it can be remove from docker file?
```
ENV JAVA_HOME="/usr/lib/jvm/java-11" \
    MAVEN_HOME="/usr/share/maven" \
    REPOSITORY_URL="https://doris-thirdparty-repo.bj.bcebos.com/thirdparty" \
    DEFAULT_DIR="/var/local" \
    PATH="/var/local/ldb-toolchain/bin/:/var/local/thirdparty/installed/bin/:$PATH" \
    DORIS_THIRDPARTY="/var/local/thirdparty"
WORKDIR /root
```

**Comment by morningman** [comment]
I think you should use:
`apache/incubator-doris:build-env-ldb-toolchain-latest`
not
`apache/incubator-doris:build-env-latest`

**Comment by kkfnui** [comment]
> I think you should use: `apache/incubator-doris:build-env-ldb-toolchain-latest` not `apache/incubator-doris:build-env-latest`

It build successed!
