### ISSUE TITLE
[Bug] The gcc version in `apache/incubator-doris:build-env-latest` is not meet the required by CMakeLists.txt:92

### ISSUE THREAD

**Issue by kkfnui** [apache/incubator-doris#8934]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

docker build env: apache/incubator-doris:build-env-latest
code tag: 1.0.0-rc3

### What's Wrong?

-- Build type is RELEASE
-- Build target arch is x86_64
-- make test: OFF
CMake Error at CMakeLists.txt:92 (message):
  Need GCC version at least 11.0

-- Configuring incomplete, errors occurred!

### What You Expected?

Build success

### How to Reproduce?

```
unset DORIS_THIRDPARTY
sh build.sh --clean --be --fe --ui
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by morningman** [comment]
try this image:
`apache/incubator-doris:build-env-ldb-toolchain-latest`
