### ISSUE TITLE
[Bug] The is-null predicate in the where statement cannot be pushed down to the storage layer

### ISSUE THREAD

**Issue by qzsee** [apache/incubator-doris#9034]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

#### in version 0.13

```sql
select * from tbla where tbla.k1 is null and tbla.k2 is null and tbla.k3 is null and dt = 20220410
```

query profile displays information about segments

- NumSegmentFiltered: 11
- NumSegmentTotal: 13

Obviously, 11 segments are filtered out by zone map

#### in master version

0 segments are filtered out by zone map

It's not normal！

### What You Expected?

everyting is ok

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by HappenLee** [comment]
Can you please give the create table stmt of `tbla`, Thank you.

**Comment by qzsee** [comment]
> Can you please give the create table stmt of `tbla`, Thank you.

CREATE TABLE `tbla` (
  `dt` int(11) NULL,
  `k1` int(11) NULL,
  `k2` bigint(20) NULL,
  `k3` bigint(20) NULL,
  `k4` bigint(20) NULL,
  `k5` bigint(20) NULL,
  `k6` bigint(20) NULL,
  `k7` bigint(20) NULL,
  `k8` bigint(20) NULL,
  `k9` bigint(20) NULL,
  `k10` bigint(20) NULL,
  `k11` bigint(20) NULL,
  `k12` bigint(20) NULL,
  `k13` bigint(20) NULL,
  `k14` bigint(20) NULL,
  `k15` bigint(20) NULL,
  `k16` varchar(128) NULL
) ENGINE=OLAP
DUPLICATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`, `k6`)
PARTITION BY RANGE(`k1`)
(PARTITION p20220410 VALUES [("20220409"), ("20220410")),
PARTITION p20220411 VALUES [("20220410"), ("20220411")),
PARTITION p20220412 VALUES [("20220411"), ("20220412")))
DISTRIBUTED BY HASH(`k3`) BUCKETS 5
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"storage_format" = "V2"
);
