### ISSUE TITLE
Cannot download thirdparty archives when build

### ISSUE THREAD

**Issue by songzhandong** [apache/incubator-doris#914]
Cannot download thirdparty archives when run build.sh

![image](https://user-images.githubusercontent.com/6280632/56033021-2e7c9d00-5d56-11e9-93ba-8414221ce51e.png)

so,i copy the url from vars.sh and access the ur with chrome.

{"code":"NoSuchKey","message":"The specified key does not exist.","requestId":"f90e4a8e-71bf-4893-87d8-e90e228c628c"}
![image](https://user-images.githubusercontent.com/6280632/56033395-18231100-5d57-11e9-8944-bf2fee7b91d3.png)

what should i do?
can anyone help me ?

Thanks!

**Comment by imay** [comment]
@songzhandong 

This problem has been fixed in #916, you can get and try it. Can you close this issue? if you are not convenient, I will close this issue next week.
