### ISSUE TITLE
[Enhancement] Let "create table as ... select" statement could insert data which query from select statement

### ISSUE THREAD

**Issue by lide-reed** [apache/incubator-doris#9143]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

 Now in  Doris, the statement "create table as ... select" only create table and can not insert data, it is not comply with the statement's real semantic logic.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
Assign it to me. I did `insert into select` before, and I was only halfway done. I will perfect him in the near future

**Comment by long2ice** [comment]
In addition, the columns of created table can be same as origin? Because if I create table with list partition, the error always occur, since the columns of created table are always `null` able
```
[HY000][1105] errCode = 2, detailMessage = Failed to execute CREATE TABLE AS SELECT Reason: errCode = 2, detailMessage = The list partition column must be NOT NULL
```

**Comment by stalary** [comment]
> In addition, the columns of created table can be same as origin? Because if I create table with list partition, the error always occur, since the columns of created table are always `null` able
> 
> ```
> [HY000][1105] errCode = 2, detailMessage = Failed to execute CREATE TABLE AS SELECT Reason: errCode = 2, detailMessage = The list partition column must be NOT NULL
> ```

create table is fully reusable and please post your complete SQL.

**Comment by stalary** [comment]
The field was not copied not null. I will fix it later. @long2ice 
```java
if (!ConnectContext.get().getSessionVariable().isAllowPartitionColumnNullable()
                            && columnDef.isAllowNull()) {
                        throw new AnalysisException("The partition column must be NOT NULL");
                    }
```

**Comment by long2ice** [comment]
OK
