### ISSUE TITLE
[Bug] The geolocation function ST_Distance_Sphere should return 0 and returned null

### ISSUE THREAD

**Issue by hf200012** [apache/incubator-doris#9239]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.0 no-avx2

### What's Wrong?

```
mysql> select ST_Distance_Sphere(150.092265,115.082610,150.092265 , 115.082610);
+------------------------------------------------------------------+
| st_distance_sphere(150.092265, 115.08261, 150.092265, 115.08261) |
+------------------------------------------------------------------+
|                                                             NULL |
+------------------------------------------------------------------+
```

### What You Expected?

ST_Distance_Sphere should return 0 but returned null

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Gabriel39** [comment]
On which engine?

**Comment by THELEMITED** [comment]
- [ tunc]>]

**Comment by Gabriel39** [comment]
This is caused by illegal input (e.g. 115 is out of range [0, 90] for latitude) so Doris just returns NULL for this case. 
Besides, in ANSI mode, a runtime error should be thrown instead of just return NULL. So if we plan to support ANSI mode in future, this behavior should be changed.
