### ISSUE TITLE
Fail to load indices due to balance when adding be

### ISSUE THREAD

**Issue by HangyuanLiu** [apache/incubator-doris#936]
**Describe the bug**
Fail to load indices due to balance when adding be

W0416 17:45:33.461661 652365 olap_table.cpp:379] fail to validate segment_group. [version='0-1' version_hash=0]
F0416 17:45:33.461670 652365 olap_table.cpp:319] fail to load indices. [res=-402 table='27112.1694383780']

**Comment by morningman** [comment]
related to ISSUE #1145
