### ISSUE TITLE
[Bug] create table as select creates a table, cannot create a partition

### ISSUE THREAD

**Issue by hf200012** [apache/incubator-doris#9377]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.0

### What's Wrong?

[Bug] create table as select creates a table, cannot create a partition
![image](https://user-images.githubusercontent.com/820301/166889967-2fb47553-7a93-4d00-a5aa-83ad11cb639e.png)

```
SQL 错误 [5083] [42000]: errCode = 2, detailMessage = data cannot be inserted into table with empty partition. Use `SHOW PARTITIONS FROM test_table_partition__dbt_tmp` to see the currently partitions of this table.
```
SHOW PARTITIONS FROM test_table_partition__dbt_tmp :

![image](https://user-images.githubusercontent.com/820301/166890032-5d63f577-df44-44e8-aca4-07d230a75474.png)

### What You Expected?

Can create partitions

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
I think it need dynamic partition 
https://doris.apache.org/zh-CN/data-table/data-partition.html#%E6%95%B0%E6%8D%AE%E5%88%92%E5%88%86-2
