### ISSUE TITLE
[Bug] group_concat does not support DISTINCT

### ISSUE THREAD

**Issue by Level1Accelerator** [apache/incubator-doris#9407]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris 1.0

### What's Wrong?

group_concat does not support DISTINCT

### What You Expected?

group_concat support DISTINCT

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
I will try to solve the problem, please assign to me.
