### ISSUE TITLE
[Bug] show proc "/cluster_balance/history_tablets" report the error of "Malformed packet"

### ISSUE THREAD

**Issue by lide-reed** [apache/incubator-doris#9444]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

dev 1.0.1

### What's Wrong?

MySQL [(none)]> show proc "/cluster_balance/history_tablets"; 
ERROR 2027 (HY000): Malformed packet

### What You Expected?

MySQL [(none)]> show proc "/cluster_balance/history_tablets";
Empty set (0.04 sec)

or show history for tablets balance.

### How to Reproduce?

show proc "/cluster_balance/history_tablets"; 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
I didn't reproduce it in master, do you have any steps to reproduce it

**Comment by lide-reed** [comment]
https://github.com/apache/incubator-doris/pull/10073

**Comment by lide-reed** [comment]
repeated by https://github.com/apache/incubator-doris/issues/10074
