### ISSUE TITLE
[Feature] Doris data Export

### ISSUE THREAD

**Issue by yym12** [apache/incubator-doris#9504]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Expectation：
1、Generate a link for easy download
2、Export a file with a data title

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
Could you describe your requirements in more detail.
