### ISSUE TITLE
[Bug][Vectorized] fix vcast expr input wrong row number

### ISSUE THREAD

**Issue by BiteTheDDDDt** [apache/incubator-doris#9519]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

`block.rows()` just return the first column's row number, sometime the block‘s column have diffrent row number with other column, then cast expr will get wrong result.

### What You Expected?

fix it

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by HappenLee** [comment]
I think it's important to must keep all column in block have same size().

**Comment by Gabriel39** [comment]
In which case columns will have different sizes? Could you give an example?

**Comment by BiteTheDDDDt** [comment]
> In which case columns will have different sizes? Could you give an example?

At the beginning, I tried to do expression evaluation on some incomplete blocks (specifically, some columns are empty, but the columns involved in the expression are complete), such as `vcast_expr`, pass in `block.rows ()` can not get the correct result.

Later I confirmed that expression evaluation should not be performed on incomplete blocks, so this `pull-request` was changed to resize the `param column` passed in `vcast_expr` to ensure that each column in the block is always the same size.
