### ISSUE TITLE
[Feature] datetime column type support auto-initialized  with default CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by dataalive** [apache/incubator-doris#9570]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

An auto-initialized column is set to the current timestamp for inserted rows that specify no value for the column.

so when we define a column like ```sync_at DateTime  DEFAULT CURRENT_TIMESTAMP COMMENT "sync time"```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by BePPPower** [comment]
I'm willing to develop this feature

**Comment by yiguolei** [comment]
CTAS support
insert into values support
insert into select
stream load
alter table
not care about spark dpp load
