### ISSUE TITLE
[Bug] Some query results from information_schema.columns are incorrect

### ISSUE THREAD

**Issue by lide-reed** [apache/incubator-doris#9597]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

dev 1.0.1

### What's Wrong?

MySQL [testdb]> show databases;
+--------------------+
| Database           |
+--------------------+
| abc                |
| testdb           |
...

MySQL [testdb]> select table_schema,table_name from information_schema.columns where table_schema='abc';
Empty set (0.05 sec)

### What You Expected?

The result of following query is not empty.
select table_schema,table_name from information_schema.columns where table_schema='abc'; 

### How to Reproduce?

Still have not...

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by cambyzju** [comment]
I can not reproduce the problem. Could you give more info to reproduce the problem?

**Comment by lide-reed** [comment]
This is an issue introduced by vectorization,  it just reproduce when  set enable_vectorized_engine=true;

**Comment by cambyzju** [comment]
I have reproduce the problem while `set enable_vectorized_engine=true;`. Thanks~

I will try to fix it. Please assign this issue to me.

**Comment by morningman** [comment]
> I have reproduce the problem while `set enable_vectorized_engine=true;`. Thanks~
> 
> I will try to fix it. Please assign this issue to me.

done

**Comment by cambyzju** [comment]
@lide-reed @nextdreamblue the problem already fixed, please merge the codes and try again.
