### ISSUE TITLE
[Enhancement](Nereids)Add physical plan nodes that needed by SSB

### ISSUE THREAD

**Issue by morrySnow** [apache/incubator-doris#9621]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

In SSB, we need these type nodes:
- Filter
- Aggregate
- Join(Only need inner join, but we should add all join type in these stage)
- Sort(Order By)
- Project

### Solution

We need to check out what attributes we need to add in each node according to PlanNode in Fragment.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Kikyou1997** [comment]
I will do it

**Comment by Kikyou1997** [comment]
Why we need filter as a standalone node rather than just add predicates to the fields of operators?
