### ISSUE TITLE
Avoid compacting tablet if it referenced by some query

### ISSUE THREAD

**Issue by morningman** [apache/incubator-doris#969]
**Describe**
When doing some long time queries, with high frequency load, some tablets may already been compacted before the query arrival. So that the version can not be found, which cause the query failed.

I think we can **mark** the tablets and its version before doing the real scan. The marked version cannot be compacted for a certain time

**Comment by kangkaisen** [comment]
https://github.com/apache/incubator-doris/pull/1400/ has fixed this issue.
