### ISSUE TITLE
ubuntu16.04下编译palo报错

### ISSUE THREAD

**Issue by daiqimeng** [apache/incubator-doris#97]
gcc 5.4编译palo,编译thirdparty阶段顺利通过，palo_be在链接阶段报错，详情信息如下

> 

`[100%] Linking CXX executable palo_be
../../../../thirdparty/installed//lib/libglog.a(libglog_la-utilities.o)：在函数‘google::GetStackTrace(void**, int, int)’中：

/myresearch/palo/thirdparty/src/glog-0.3.3/src/stacktrace_libunwind-inl.h:65：对‘_Ux86_64_getcontext’未定义的引用
/myresearch/palo/thirdparty/src/glog-0.3.3/src/stacktrace_libunwind-inl.h:66：对‘_ULx86_64_init_local’未定义的引用
/myresearch/palo/thirdparty/src/glog-0.3.3/src/stacktrace_libunwind-inl.h:78：对‘_ULx86_64_step’未定义的引用
/myresearch/palo/thirdparty/src/glog-0.3.3/src/stacktrace_libunwind-inl.h:70：对‘_ULx86_64_get_reg’未定义的引用
/myresearch/palo/thirdparty/src/glog-0.3.3/src/stacktrace_libunwind-inl.h:78：对‘_ULx86_64_step’未定义的引用
collect2: error: ld returned 1 exit status
src/service/CMakeFiles/palo_be.dir/build.make:164: recipe for target 'src/service/palo_be' failed
make[2]: *** [src/service/palo_be] Error 1
CMakeFiles/Makefile2:696: recipe for target 'src/service/CMakeFiles/palo_be.dir/all' failed
make[1]: *** [src/service/CMakeFiles/palo_be.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

google找到https://code.google.com/p/google-glog/issues/detail?id=207
修改了glog-0.3.3/libglog.pc.in，增加了一行，重新编译还是报这个错，帮忙看下，谢谢

**Comment by morningman** [comment]
请问这个问题解决了吗？如果还没有，可以加微信私聊下：morningman-cmy

**Comment by chenhuaying** [comment]
这个错误我也遇到过，原因是装了两个libunwind，编译时用的是thirdparty里面的，链接的时候用的是系统apt-get安装的

**Comment by morningman** [comment]
Not a problem anymore, using docker dev environment instead
