### ISSUE TITLE
[Bug] double free on lz4

### ISSUE THREAD

**Issue by dataroaring** [apache/incubator-doris#9706]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master & dev-1.0.1

### What's Wrong?

`==2157863==ERROR: AddressSanitizer: attempting double-free on 0x7f8da194e800 in thread T666:
*** SIGABRT unkown detail explain (@0x20ed27) received by PID 2157863 (TID 0x7f8eabd7b640) from PID 2157863; stack trace: ***
    #0 0x56406110d15f in __interceptor_free (/mnt/hdd01/VEC_ASAN/be/lib/palo_be+0x4dac15f)
    #1 0x564067535ae0 in LZ4F_decompress (/mnt/hdd01/VEC_ASAN/be/lib/palo_be+0xb1d4ae0)
    #2 0x5640623f2034 in doris::Lz4fBlockCompression::_decompress(LZ4F_dctx_s*, doris::Slice const&, doris::Slice*) const /home/zcp/repo_center/doris_dev-1.0.1/doris/be/src/util/block_compression.cpp:174
    #3 0x5640623f0c2c in doris::Lz4fBlockCompression::decompress(doris::Slice const&, doris::Slice*) const /home/zcp/repo_center/doris_dev-1.0.1/doris/be/src/util/block_compression.cpp:130
    #4 0x564061c6cee6 in doris::segment_v2::PageIO::read_and_decompress_page(doris::segment_v2::PageReadOptions const&, doris::segment_v2::PageHandle*, doris::Slice*, doris::segment_v2::PageFooterPB*) /home/zcp/repo_center/doris_dev-1.0.1/doris/be/src/olap/rowset/segment_v2/page_io.cpp:179
    #5 0x564063a0748f in doris::segment_v2::ColumnReader::read_page(doris::segment_v2::ColumnIteratorOptions const&, doris::segment_v2::PagePointer const&, doris::segment_v2::PageHandle*, doris::Slice*, doris::segment_v2::PageFooterPB*) /home/zcp/repo_center/doris_dev-1.0.1/doris/be/src/olap/rowset/segment_v2/column_reader.cpp:156

0x7f8da194e800 is located 0 bytes inside of 262148-byte region [0x7f8da194e800,0x7f8da198e804)
freed by thread T690 here:
    #0 0x56406110d15f in __interceptor_free (/mnt/hdd01/VEC_ASAN/be/lib/palo_be+0x4dac15f)
    #1 0x564067535ae0 in LZ4F_decompress (/mnt/hdd01/VEC_ASAN/be/lib/palo_be+0xb1d4ae0)

previously allocated by thread T653 here:
    #0 0x56406110d4b7 in __interceptor_malloc (/mnt/hdd01/VEC_ASAN/be/lib/palo_be+0x4dac4b7)
    #1 0x564067535aed in LZ4F_decompress (/mnt/hdd01/VEC_ASAN/be/lib/palo_be+0xb1d4aed)

`

### What You Expected?

without double free.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xiaokang** [comment]
It's introduced by https://github.com/apache/incubator-doris/pull/9566 for thread safe problem, I will fix it as soon as possible.
