### ISSUE TITLE
Wrong result for ArithmeticExpr

### ISSUE THREAD

**Issue by kangkaisen** [apache/incubator-doris#975]
**Describe the bug**

```
mysql> select 3074062.5421333313 * (9562325.0921268463 / 3946 - 97281.800003051758 / 384);
+-----------------------------------------------------------------------------+
| 3074062.5421333313 * (9562325.0921268463 / 3946 - 97281.800003051758 / 384) |
+-----------------------------------------------------------------------------+
|                                     6670585822.007877058-.+/.+(*6640070909 |
+-----------------------------------------------------------------------------+
1 row in set (0.05 sec)

```

**Comment by imay** [comment]
It looks like that result string has dirty content

**Comment by chenhao7253886** [comment]
This bug has been fixed in master, it should be Decimal's bug and new Decimal has fixed it.

**Comment by kangkaisen** [comment]
@chenhao7253886 Hi, which PR fix this issue?

**Comment by imay** [comment]
> @chenhao7253886 Hi, which PR fix this issue?

https://github.com/apache/incubator-doris/pull/727 
this patch change our decimal implementation to another. This precision is lower than current one. And has no problem for this case.

And this bug is in the current implementation, we are trying to fix it.

**Comment by kangkaisen** [comment]
@imay OK. Thanks you.

**Comment by imay** [comment]
@kangkaisen 

You can try #980 to see if this will fix your problem

**Comment by kangkaisen** [comment]
https://github.com/apache/incubator-doris/pull/980 has fixed this issue, Thanks!
