### ISSUE TITLE
[Enhancement] Remove the redundant `this.`

### ISSUE THREAD

**Issue by jackwener** [apache/incubator-doris#9775]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Remove uncessary `this.`

Most scenario, it just use in `constructor`.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Vikasss7663** [comment]
Hey @jackwener 
I am a beginner and never contributed to any open source.
I want to work on this, can you help me with this issue.

**Comment by jackwener** [comment]
> Hey @jackwener I am a beginner and never contributed to any open source. I want to work on this, can you help me with this issue.

It's ok😀, let's me explain this issue.

In Java, we can use `this.` to access `class member variables` like `if (this.name == jackwener)`. 

But, in most scenario, it's redundant. just use in constructor like:

```java

class Person {
    public string name;
    
    Person(name) {
        this.name = name;
    }

    boolean isJack() {
         this.name == "jack";  // It's redundant;
    }
}
```

So, we can remove the redundant like `isJack()`.

example in #8862 `fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsJobManager.java`

**Comment by jackwener** [comment]
You can find code in `fe/`.

If there are redundant `this.`, you can remove them.

**Comment by Vikasss7663** [comment]
So should I have to remove this from "fe/fe-core/src/main/java" only?

**Comment by jackwener** [comment]
> So should I have to remove this from "fe/fe-core/src/main/java" only?

Yes, It's enough.

**Comment by Vikasss7663** [comment]
I have removed from these 7 packages, should I create pr now or after doing in all packages because that would be huge.

1. alter
2. analysis
3. backup
4. blockrule
5. catalog
6. task
7. transaction

**Comment by jackwener** [comment]
you can spilt them into multiple PR

VISHAL SINGH ***@***.***> 于 2022年5月27日周五 19:15写道：

**Comment by Vikasss7663** [comment]
can you help me with what should I write in PR?

**Comment by Vikasss7663** [comment]
I don't feel like it's my first pr 🤣

**Comment by Vikasss7663** [comment]
can you check now ?
I have just edited 1 files for now.

**Comment by jackwener** [comment]
This issue isn't necessary, and it will make `cherry-pick` harder.
