### ISSUE TITLE
[Bug] 中文文档bug

### ISSUE THREAD

**Issue by taoshengyijiua** [apache/incubator-doris#9833]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

１.０.０

### What's Wrong?

CREATE TABLE example_db.table_hash
(
    k1 BIGINT,
    k2 LARGEINT,
    v1 VARCHAR(2048) REPLACE,
    v2 SMALLINT SUM DEFAULT "10"
)
UNIQUE KEY(k1, k2)
DISTRIBUTED BY HASH (k1, k2) BUCKETS 32
PROPERTIES(
    "storage_medium" = "SSD",
    "storage_cooldown_time" = "2015-06-04 00:00:00"
);
文档地址：https://doris.apache.org/zh-CN/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-TABLE.html#create-table
该语句创建sql报错，UNIQUE_KEYS table should not specify aggregate type for non-key column
value字段不能指定聚合类型

### What You Expected?

修改建表语句，删除v1REPLACE
并且删除V２的聚合字段
CREATE TABLE table_hash
(
    k1 BIGINT,
    k2 LARGEINT,
    v1 VARCHAR(2048) 
)
UNIQUE KEY(k1, k2)
DISTRIBUTED BY HASH (k1, k2) BUCKETS 32
;

### How to Reproduce?

在１.０.０版本执行以上语句

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hf200012** [comment]
这里应该是聚合模型

**Comment by THELEMITED** [comment]
Hai
