### ISSUE TITLE
[Enhancement] setup config by set `conf/*.conf` instead of generating `output/(be|fe)/conf`.

### ISSUE THREAD

**Issue by jackwener** [apache/incubator-doris#9850]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Now, we setup config in `conf/*.conf`, after `./build.sh`, there will be new config file in `output/(be|fe)/conf`.

config if `output/` is actual effective config file.

I think we don't need to generate config file into `output/`, we can use conf file in `conf/` directly.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yangzhg** [comment]
The `output` directory is the final output directory of the compilation result. It is used to distribute binary files. The output file should be able to run completely, and there should be a conf file in it. You may use the output directory as a test environment. This usage is not Appropriate, it should be copied to another directory to run
