### ISSUE TITLE
关于insert into忽略错误的建议

### ISSUE THREAD

**Issue by songzhandong** [apache/incubator-doris#990]
目前insert into时，在列格式不满足目的表列结构的话，直接会忽略掉当前行的数据；
如果数据类似日志或者精确度不高的情况，这种方式还是可以接受的；
如果涉及到精确的数据，这种方式是致命的；
建议增加一个参数，默认为false，保持现状
当用户设置为true时，遇到错误的数据直接报错，导入失败。

**Comment by imay** [comment]
I will add a `enable_insert_strict` variable. When this variable is true, insert will failed if any data is filtered.
